### ISSUE TITLE
tweaking assembly with bogart options

### ISSUE THREAD

**Issue by MichelMoser** [marbl/canu#10]
Dear Canu developers, 

I would like to test various options of Bogart to eventually get higher continuity of sequences. 
When looking at bogart run by default in the canu pipeline, i see the -repeatdetect option with three integers as parameters. 
Could you tell me more about this option and how it effects the unitig-building? 
Thank you, 
Michel

**Comment by skoren** [comment]
This option controls how aggressively contigs are split due to identified repeats. You would modify the second integer which says how many conflicting reads must pile up for a split to happen. By default, it is set to about your coverage. Setting higher will make longer contigs at the expense of potential mis-assemblies. Setting it lower will make shorter contigs. If you have a heterozygous genome, this splitting can sometimes be too aggressive and increasing it to 2X coverage can significantly improve the assembly. However, I'd caution against modifying it for general runs without validating the resulting contigs for correctness.

**Comment by JohnUrban** [comment]
Is there any chance of implementing an option or options telling canu upfront that you are dealing with a diploid/polyploid/heterozygous genome so it automatically sets the -repeatdetect parameters in Bogart?

**Comment by skoren** [comment]
Yes, we plan to look at improvements for bogart including better handling diploid genomes.

**Comment by skoren** [comment]
Bogart algorithm re-written in 1.3 release. It should be less sensitive to false repeat splitting.
