### ISSUE TITLE
Different contigs between two assembly runs

### ISSUE THREAD

**Issue by csm1209** [marbl/canu#1005]
Hello,

My first time around, I ran Canu on my bacterial nanopore reads filtered by NanoFilt on less stringent parameters (this meant very high coverage). This resulted in a single, circular contig approximately the predicted length of my genome in contigs.fasta.

Unfortunately we had problems with errors in the annotation, so went back and re-did the assembly with even more stringent NanoFilt parameters, so # reads/coverage was not so high this time. This time the result was three linear/noncircular contigs, one almost the length of my genome and two short ones. In the second run I got 40x coverage vs the first 164x.

What is the significance of this? Does it mean I should be worried about gaps in the assembly and dial back the quality/length filtering for reads, or could the shorter contigs be plasmids?

I should note this is completely de novo and I have no reference genome to compare the assembly against.

Thank you,

Carl

**Comment by skoren** [comment]
Filtering isn't really necessary since the correction will filter the data anyway. You can use filtering if you have very high coverage but I'd expect random sampling would work as well. It's likely with the stringent filtering you eliminated some reads necessary to span repeats fragmenting your assembly. Since the higher coverage assembly had a single circular contig I wouldn't expect the short contigs are plasmids but parts of the main chromosome.

Since you already have a circular assembly, I'd stick with that result. The filtering isn't going to fix your annotation issues (which I presume are due to frame shifts). Instead, you can run nanopolish to improve the consensus quality and you'd likely need some Illumina data to get  to a final high-quality consensus.

**Comment by csm1209** [comment]
Thank you. I just wanted to confirm my suspicion that perhaps I filtered out too many reads. I did run annotation on both nanopolished and unpolished versions of the first assembly but was having the same issue with annotation errors, so wanted to test if it was an assembly issue. I re-assembled my reads using a different assembly program and got the same results, so ruled out Canu being the problem and thought maybe coverage was too high or there was a problem with read quality.

I attached a screenshot below to show the problem we're having with annotation duplicating (sometimes triplicating) assigned genes. If you know anything about this please feel free to let me know, otherwise thanks for the suggestions!

Carl

![tsvannotation](https://user-images.githubusercontent.com/40922540/42736456-5a536bc6-8835-11e8-876d-36b2a0334c55.png)

**Comment by skoren** [comment]
I assume you've trimmed the circular bit of the contig off the ends? That would cause duplication if not removed since part of the genome is duplicated.

**Comment by csm1209** [comment]
I don't recall doing any trimming step between the assembly, Nanopolish, and gene calling/annotation. How would you go about this? The only trimming that comes to mind is adapter trimming at the beginning and Canu's trimming.

Can you elaborate a little more about why trimming the ends of the contig is important? (This is my first time). Thanks for the help.

**Comment by skoren** [comment]
Since the genome is circular, the assembler keeps going until it hits an already used sequence. This typically means the ends of your contig have the same sequence in two different reads and thus are an artificial duplication. This is actually how the circularity of the contig is detected to set the flag. To trim, you have lots of options. 

- You can use the GFA which gives you the alignment cigar string indicating the alignment of the ends of the contig.
- Run a self-alignment of the contigs (using MUMmer) and trim off the sequence, something like:
```
nucmer --maxmatch -nosimplify asm.contigs.fasta asm.contigs.fasta 
show-coords -lrcTH out.delta |head -n5
1	4654374	1	4654374	4654374	4654374	100.00	4654374	4654374	100.00	100.00	ctg7180000000002	ctg7180000000002
1	17937	4636402	4654374	17937	17973	99.76	4654374	4654374	0.39	0.39	ctg7180000000002	ctg7180000000002
1	13893	5152	19082	13893	13931	99.71	4654374	30958	0.30	45.00	ctg7180000000002	ctg7180000000003
2335	2500	17501	17666	166	166	92.77	4654374	4654374	0.00	0.00	ctg7180000000002	ctg7180000000002
2335	2500	4653939	4654104	166	166	92.77	4654374	4654374	0.00	0.00	ctg7180000000002	ctg7180000000002
```
Here you can see the first 17,937 bases match the last bases. So you'd trim off either 1-17,937 or 4,636,402-4,654,374.

- Try the circlator (https://sanger-pathogens.github.io/circlator/) tool.

**Comment by skoren** [comment]
Any updates on this, was the redundant sequence and were you able to remove it if so?

**Comment by csm1209** [comment]
Unfortunately the truncated genes are found throughout the entire genome, and even lower coverage assembly which does not produce circular contigs has the same result. I found they were not redundant sequences but caused by internal stop codons splitting up the gene annotation. I'm currently investigating this as an error with homopolymer sequences causing shifts in the reading frame and therefore creating false stop codons. If we can't fix it we'll have to resort to hybrid assembly with Illumina. Once again, if you know anything about this feel free to let me know, otherwise thanks for the help and concern!

**Comment by skoren** [comment]
Ah I had expected duplicated or triplicated genes were further apart but looking at your results again, it seems they are mostly next to each other.  Either way, trimming should be done on a circular genome to remove the redundant sequence.

I guess the annotation is calling each chunk of a single gene as individual genes all next to each other. You need to use Illumina data (either for polishing your current assembly with Pilon or Freebayes or Racon) or in a hybrid assembler. With current error rates, nanopore will definitely leave many frame shifted genes as I mentioned before.
