### ISSUE TITLE
covStat

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#101]
In *contigs.fasta, each contig name line has some sort of stat information there, for example,

>tig00000005 len=24813 reads=16 covStat=10.11 

Does this mean that the contig use 16 reads,? How is the covStat calculated?

Thanks.

**Comment by skoren** [comment]
It's the log of the ratio of the contig being unique vs it being two-copy, based on the number of reads used to form it. http://wgs-assembler.sourceforge.net/wiki/index.php/Celera_Assembler_Theory#Coverage-based_repeat_discrimination

Positive means more likely to be unique, negative means more likely to be repetitive. It is flagging tig102 as having too many reads to be unique, based on the rest of the contigs. Given how large the contig is, this could be caused by a pile up of reads in a few repeats, or it could be indicating that this is a contaminant sequenced at higher coverage than the primary target.

**Comment by JohnUrban** [comment]
Hi Sergey,

Hopefully you see this considering the issue is closed…

Is there something other than covstat that goes into determining if a contig should be suggested as a repeat?

Check out these fasta headers -- all have positive covstats, but are suggested to be repeats:
```
>tig00412383 len=26359 reads=41 covStat=51.38 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412386 len=58839 reads=123 covStat=113.25 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412388 len=38707 reads=148 covStat=10.70 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412390 len=64563 reads=212 covStat=65.88 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412391 len=23359 reads=16 covStat=43.54 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412396 len=16431 reads=23 covStat=29.43 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412398 len=23888 reads=70 covStat=16.85 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412402 len=30078 reads=98 covStat=30.39 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412409 len=21117 reads=80 covStat=8.00 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412411 len=24997 reads=52 covStat=27.63 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412413 len=47352 reads=113 covStat=79.18 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412415 len=22476 reads=11 covStat=34.27 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412421 len=96366 reads=199 covStat=232.17 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412424 len=23859 reads=32 covStat=47.45 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412429 len=39546 reads=44 covStat=101.96 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412431 len=18401 reads=12 covStat=31.46 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412432 len=17766 reads=22 covStat=33.72 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412434 len=39611 reads=134 covStat=31.28 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412435 len=26379 reads=73 covStat=24.46 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412440 len=19017 reads=22 covStat=25.81 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412443 len=17658 reads=47 covStat=14.14 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412447 len=31862 reads=68 covStat=59.35 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412449 len=27851 reads=6 covStat=53.99 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412459 len=24543 reads=93 covStat=4.17 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
```

Is this from the graph-based repeat discrimination discussed below the coverage-based repeat discrimination (where I am guessing covstat comes from) in the link you gave?

John

**Comment by JohnUrban** [comment]
p.s. I also found the opposite issue where covstat is negative but suggestRepeat=no:

```
>tig00412436 len=20600 reads=123 covStat=-18.88 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412439 len=28771 reads=298 covStat=-118.81 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00412442 len=17251 reads=163 covStat=-53.71 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
```

**Comment by JohnUrban** [comment]
Perhaps, if I am to guess:

+ covstat and suggestRepeat=yes
comes from contigs where P(single) > P(two-copy), but that ends in repeat branch patterns anyway.
… if so, could these branches be from heterozygosity?

- covstat and suggestRepeat=no
comes from contigs where P(single) < P(two-copy), but does not end in repeat branch patterns
… if so, might these be good candidates for contamination (e.g. some abundantly present bacteria)?
