### ISSUE TITLE
Error File Size

### ISSUE THREAD

**Issue by bruce-boles** [marbl/canu#1030]
Hello,

I'm not sure if this is relevant, but I was using canu v1.6 and encountered an error. The program kept writing the error code until the computer memory was full. The total file size was something like 1.01 TB. It ended up messing with my operating system, ubuntu 18. I have my input command for this porblem, but the error log had to be deleted to restart the computer and use it again.

```
canu \
-p shew1reassembly \
-d /home/bruceboles/Projects/HybridAssemblyShew/canu_trial \
genomeSize= 45k \
-nanopore-raw /home/bruceboles/Projects/RawData/Nanopore/20170801_1704_Bruce_Shew_1/fastq/pass/*.fastq \
```

**Comment by skoren** [comment]
Nothing in Canu would write that much into an error log. It's possible your system was trying to capture the full memory state at the time of the crash (do you have 1tb of ram?). 

Without details of the Canu error can't help diagnose but I'd start by upgrading to 1.7.1 since 1.6 is relatively old. If you have a short amplicon, see also recent issues about downsampling extremely high coverages (issue #1025 and others).
