### ISSUE TITLE
Error correction with Illumina

### ISSUE THREAD

**Issue by mictadlo** [marbl/canu#1060]
Hi,
New tools have been published for error correcting PacBio reads with Illumina reads:

- HALC (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1610-3 ) 
- FMLRC (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5807796) 

I am just wondering which tool do you think is the best one because currently to error correct our reads with Canu takes a long time.

Thank you in advance,

Best wishes,

Michal

**Comment by skoren** [comment]
We worked with Illumina correction a while back and stopped developing it because it doesn't match the quality you get using long reads alone because of difficulties accurately correcting repeats. I wouldn't use any illumina correction personally so can't give advice on which is best. You're welcome to test of them yourself. I expect they'll all be similar in speed to long read correction. See issue #942 for options to speed up Canu's correction/run.
