### ISSUE TITLE
trioCanu read haplotyper likely to cause false positives [enhancement]

### ISSUE THREAD

**Issue by abardill** [marbl/canu#1083]
trioCanu scales the number of haplotype-specific kmers found in a read by the total number of kmers for that haplotype. Suppose you have two haplotypes, one has 1 billion kmers, the other has 1 billion + 1. As far as I can tell, using a minimum score ratio of 1 (the default), a read which has an exactly equal number of kmer matches for both haplotypes will be classified as the former, just because it has 1 less kmer overall. It would be good to be able to set a higher threshold for the specific case where a read has an equal number of kmer matches to both haplotypes.

**Comment by skoren** [comment]
That's the right behavior since having the same number of kmers from both haplotypes doesn't mean the same thing when one haplotype has more kmers. The binning is meant to classify more reads at the expense of some false positives since a few false positives will get outvoted during assembly. 

However, there is already the parameter which controls the ratio between the best and second best for assignment (set to 1 by default), it's just not exposed through the command line. See the ```-cr  1``` parameter in HaplotypeReads.pm. You can adjust it in the code if you'd like to be more strict.
