### ISSUE TITLE
How to speed up the assembly?

### ISSUE THREAD

**Issue by moontree1985** [marbl/canu#1106]
Hello,

I start an assembly of a highly repetitive plant genome of 2.5Gb. The assembly run on a SLURM cluster since 8 weeks and still in the correction step. I am using Canu 1.6 for the assembly.  

Here is my script:
```
#!/bin/bash
#SBATCH --job-name=Canu_default # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=<>  # Where to send mail     
#SBATCH --mem=128gb                    # Total memory limit
#SBATCH --time=168:00:00              # Time limit hrs:min:sec
#SBATCH --output=errCanu_sweetcorn_default_%j.out     # Standard output and error log
#SBATCH --error=errCanu_sweetcorn_default_%j.err
#SBATCH --account=***
#SBATCH --qos=***

module load ufrc
module load gcc/5.2.0 
module load gnuplot/4.6.0
# changed to canu 1.6
module load canu/1.6
module load java/1.8.0_31


export 
PROJ_ROOT=***

canu -correct \
-p Sweetcorn.default -d SC.default \
genomeSize=2.5g \
-pacbio-raw $PROJ_ROOT/m54115_180303_181556.fastq.gz \
$PROJ_ROOT/m54115_180304_042546.fastq.gz \
$PROJ_ROOT/m54115_180305_191509.fastq.gz \
$PROJ_ROOT/m54115_180306_052143.fastq.gz \
$PROJ_ROOT/m54115_180306_185336.fastq.gz \
$PROJ_ROOT/m54115_180307_050011.fastq.gz \
$PROJ_ROOT/m54115_180307_150939.fastq.gz \
$PROJ_ROOT/m54115_180611_172358.fastq.gz \
$PROJ_ROOT/m54115_180612_133532.fastq.gz \
$PROJ_ROOT/m54115_180701_174243.fastq.gz \
$PROJ_ROOT/m54115_180705_151733.fastq.gz \
$PROJ_ROOT/m54115_180706_113544.fastq.gz \
$PROJ_ROOT/m54115_180707_075551.fastq.gz \
$PROJ_ROOT/m54115_180708_041446.fastq.gz \
$PROJ_ROOT/m54115_180709_172258.fastq.gz \
$PROJ_ROOT/m54115_180710_202320.fastq.gz \
$PROJ_ROOT/m54115_180711_163954.fastq.gz \
$PROJ_ROOT/m54115_180712_125805.fastq.gz \
$PROJ_ROOT/m54115_180721_132449.fastq.gz \
$PROJ_ROOT/m54115_180723_163041.fastq.gz \
$PROJ_ROOT/m54115_180724_124723.fastq.gz \
$PROJ_ROOT/m54115_180725_090235.fastq.gz \
usegrid=1 \
gridOptionsJobName=CANU-default \
gridOptions="--mem=128gb --time=168:00:00"
```
Do I need to increase the memory to speed up the assembly? Or there is some parameters which can accelerate the assembly. 

Thanks,

Ying

**Comment by skoren** [comment]
You can check the FAQ for suggestions to speed up the assembly: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow. 

However, I think part of your issue is your command. You specify grid options to always reserve 128gb of memory and 7 days. I expect most of your jobs aren't using this much so your assembly is probably spending more time waiting to run than actually running. Canu should set the memory resources for you so you can just remove that part. As for time, you can check the last job submitted from canu (in the canu.out file) and see how long they've been taking and set the time to that.

**Comment by moontree1985** [comment]
Hi, skoren,

Thanks for your quick response. 

You said Canu can set the memory resources by itself. I found grid information in canu.out as following:
-- Grid:  meryl    125 GB   32 CPUs  (k-mer counting)
-- Grid:  cormhap   31 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     7 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl     7 GB    4 CPUs  (overlap detection)
-- Grid:  cor       10 GB    4 CPUs  (read correction)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red        7 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      186 GB   32 CPUs  (contig construction)
-- Grid:  cns       65 GB    8 CPUs  (consensus)
-- Grid:  gfa       31 GB    8 CPUs  (GFA alignment and processing)

So for each step, canu set the memory and CPU by itself right?

For the time, you said I need to check the canu.out file to see how long they've been taking. However, how we set up the time before running without canu.out file?

Thanks,

Ying

**Comment by skoren** [comment]
So the longest jobs in correction would be the cormhap step which is only set to use 31GB. For setting the time, we usually run with 72 hours as the default because that is typically enough and if any jobs run out of time, we increase it for that step and re-launch. Canu can resume and re-run only the failed jobs so you won't lose intermediate results. Since you've already been running it, you can set a more explicit time limit based on your observed runtimes.

**Comment by moontree1985** [comment]
Thanks for your help! Really appreciate it!

For speeding up the assembly on high repetitive genome, you suggest to use the following parameters: corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerThreshold=500.

How do those parameters affect the final assembly results? Do you compared the assembly between default setting and the above parameters?

Thanks,

Ying

**Comment by skoren** [comment]
I have run several genomes this way yes, and it typically gives a comparable assembly but is much faster in terms of runtime. T
