### ISSUE TITLE
More and longer pacbio reads got poorer assembly

### ISSUE THREAD

**Issue by sanvva** [marbl/canu#1121]
I successfully assembled one plant genome (genome size =900M) two months ago using canu, raw Pacbio reads 67Gbp （N50=11k,avg=6.8k; libreay size=20k）, and assemly genome size=910M, contigs N50=750kb. 

Then about 21Gb raw Pacbio reads (N50=20k, avg= 12k; library size=30kb) were additionally obtained to get more longer subreads. I re-assembled it using all 88Gb Pacbio reads, but the assembly is much poorer with contigs N50=560kb (assembly genome size=980M). 

Why? Is this possible?

**Comment by skoren** [comment]
Those two assemblies aren't very different, especially if one has a slightly larger genome size the N50 could drop just because of the larger denominator. If you want to compare them, use NG50 with a common genome size (say 900mb).

For improving the assembly, take a look at the FAQ. I presume these are Sequel reads, then you'd want to use ```corMhapSensitivity=normal correctedErrorRate=0.085```.

**Comment by sanvva** [comment]
@skoren Thanks!  I'll have a try.

**Comment by skoren** [comment]
Idle.
