### ISSUE TITLE
heterozygous parameters for large genome with nanopore data

### ISSUE THREAD

**Issue by wingwingWY** [marbl/canu#1127]
I  ran canu v1.7 for an 1G plant genome with 0.8%  heterozygosis by 70X nanopore data.

First time, I ran canu as follows:
canu  -nanopore-raw ./data/*.gz  -d ./output -p Genome genomeSize=1G useGrid=false   ovsMethod=sequential   overlapper=mhap utgReAlign=true  corMhapOptions='--threshold 0.8 --num-hashes 512 --ordered-sketch-size 1000 --ordered-kmer-size 14'
 
It takes one month.  The final  assembly is 1.4G  with  261kb N50  .  I also ran wtdbg2 with canu corrected reads and got an 1G genome with 450Kb N50.

Then I change to the  heterozygosis parameters as follows , the trimming step is extremely slow and still running .
canu  -nanopore-raw ./data/*.gz  -d ./output_t2 -p Genome  genomeSize=1G useGrid=false    corMhapSensitivity=normal corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" ovlMerThreshold=500

For an 0.8%  heterozygous genome,  should I set "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50 " parameters?

In  Canu FAQ,  "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50 "  is used for PacBio data. Can I use these parameters for Nanopore data ?  

Should I  set  "overlapper=mhap utgReAlign=true  corMhapOptions='--threshold 0.8 --num-hashes 512 --ordered-sketch-size 1000 --ordered-kmer-size 14"  to improve the speed ?

**Comment by skoren** [comment]
WTDBG is much more aggressive in collapsing heterozygosity in my experience which is why it's giving you a 1 Gbp assembly but it's a consensus of both haplotypes. You can use purge_haplotigs to see how much of the Canu assembly may be redundant due to haplotype separation, I'd expect this will also increase you N50 since you would decrease the denominator (or use NG50 with the same genome size to compare stats).

You can use the same bat options for PacBio or nanopore data, none of them are specific to a technology. I expect your assembly size will increase further closer to 2 Gbp. You can also add the fast options you have listed to speed up the assembly. The reason the overlapping step is slower is you switched back to the default overlap algorithm which may give you a more continuous assembly but will be slower.
