### ISSUE TITLE
Canu failed in SLRUM system when array ID is larger than 1000

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#114]
Hello,
I am using cormhap to correct Pacbio reads of a large genome and canu automatically assigned 1077 jobs in SLRUM system. However, the default MaxArraySize is 1001 in the SLRUM system and I do not have root permission to modify the config. Is it possible to change canu parameters to avoid this failure?
Any suggestion is appreciate.

**Comment by skoren** [comment]
You can increase the memory used for the overlapping steps. Doubling the limit it picked would work and will end up with half as many jobs. Assuming it picked 18gb, something like:
```
cormhapMemory=36 obtovlMemory=12 utgovlMemory=12g obtOvlHashBlockLength=200000000 utgOvlHashBlockLength=200000000
```
Should decrease the number of overlapping jobs by 2 on all steps, assuming you have more memory per machine.

**Comment by brianwalenz** [comment]
Give the latest a try.  It should be discovering MaxArraySize and respecting it.  You can also force it to use a smaller block size with option gridEngineArrayMaxJobs=<integer>.

**Comment by tangerzhang** [comment]
Thanks so much!
That's very useful!

2016-04-26 15:15 GMT+08:00 brianwalenz <notifications@github.com>:

**Comment by johnomics** [comment]
Thanks for looking into this, but the fix didn't work for me. Canu 1.2 attempted to submit 1013 jobs with MaxArraySize set to 1001, which failed with error "Invalid job array specification", as expected from the above.  Using commit https://github.com/marbl/canu/commit/3b41ff5bd0da19605de15f17819b4af69440da1b canu attempted to submit 1001 jobs. But this still failed with the same error, because the maximum number of submittable jobs is MaxArraySize - 1 (see man sbatch for --array, "the maximum value is one less than the configuration parameter MaxArraySize"). 

I tried setting gridEngineArrayMaxJobs to 1000, which worked for getting the first 1000 jobs running, but then canu attempts to run jobs 1001-1013 separately, which fails with error "Invalid job array specification" as before. Can the jobs in the second array be renumbered?

**Comment by brianwalenz** [comment]
Shucks.  Fixing will take a bit of effort.

What a useless parameter name.  You'd think that 'size' refers to the number of jobs in the array, but nope.  The SLURM docs (http://slurm.schedmd.com/job_array.html) say:

```
Note that the minimum index value is zero and the maximum value is a Slurm configuration parameter (MaxArraySize minus one).
```

Argh.

I'll admit I only tested this on SGE.  Worked great there!

**Comment by brianwalenz** [comment]
Finally resolved.
