### ISSUE TITLE
utgovl for assembly really slow

### ISSUE THREAD

**Issue by moontree1985** [marbl/canu#1171]
I am running the utgovl step for assembly. I am working on maize with 2.5Gb genome size. There are 364 jobs required.
For each job, it picked 8 treads per job. At an average I only see 5-6 jobs being completed per day.

I am curious:

1. Is it really slow for such complex genome?
2. Is that due to the computation resources not enough?
3. Should I change my parameters to speed up the assembly?

Canu command:

canu -assemble \
-p corn.assemble -d corn.assemble \
genomeSize=2.5g \
rawErrorRate=0.300 \
correctedErrorRate=0.045 \
corMhapSensitivity=normal \
corMinCoverage=4 \
corOutCoverage=40 \
minOverlapLength=500 \
minReadLength=1000 \
shell="/bin/bash" \
java="/apps/java/1.8.0_31/bin/java" \
gnuplotTested=true \
gnuplot="/apps/gcc/5.2.0/gnuplot/5.0.3/bin/gnuplot" \
gnuplotImageFormat=svg \
-pacbio-corrected $PROJ_ROOT/corn.trim.trimmedReads.fasta.gz \
usegrid=1 \
gridOptionsJobName=CANU-trim \
gridOptions="--mem=10gb --time=96:00:00 --ntasks=1 --qos=mre" \
1>correct.corn.assemble.log 2>>correct.corn.assemble.log

**Comment by skoren** [comment]
You don't say what version of Canu you're running, but yes, it is affected by the repetitiveness of the genome. The number of jobs completed per day isn't very informative though because that doesn't say if they're spending most of their time running or most of their time waiting to get scheduled by the grid nor how many CPUs are available to canu.

You can see the FAQ for suggested parameters to speed up the run for Canu 1.8 (https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow) but you'd have to restart the run from scratch.

**Comment by skoren** [comment]
You specified --mem=10gb and typically mem is interpreted as a per-machine request not a per-core. Are you sure the jobs are actually requesting 80gb? The actual command canu submitted is in ```1-overlapper/overlap.jobSubmit*.sh```, it explicitly uses mem-per-core. You can let it manage memory itself by not including the gridOptions parameter but you can't adjust the memory for a job once it is in the queue typically so you'd have to kill your run anyway. If you are going to do that, restart with ```merThreshold=500``` or just wait for the current run to finish.

**Comment by moontree1985** [comment]
This is one of my overlap.jobSubmit.sh.
#!/bin/sh

sbatch \
  --mem-per-cpu=3g --cpus-per-task=8 --mem=10gb --time=102:00:00 --ntasks=1 --qos=mresende -o overlap.%A_%a.out \
  -D `pwd` -J "utgovl_corn.assemble_CANU-trim" \
  -a 121-364 \
  ./overlap.sh 0 \
> ./overlap.jobSubmit-21.out 2>&1

I guess each job is using 24gb, right?

**Comment by skoren** [comment]
It's probably 10 since that comes after the mem-per-cpu parameter but since the jobs are only using 9.6, they're probably OK. Either way, this doesn't seem like a super long time (about 30k cpu hours for a repetitive plant genome) so your option is to either let it complete or re-start the assemble command from scratch with 1.8 and the suggested FAQ parameters.

**Comment by moontree1985** [comment]
If I use the suggested FAQ parameters, can I save a lot of time? Is the assembly quality comparable to the assembly using the default parameters?

**Comment by skoren** [comment]
Yes, I expect it will be much faster with a comparable assembly result, even the default 1.8 run would likely be much faster as well.

**Comment by moontree1985** [comment]
Thank you so much for your help!

**Comment by moontree1985** [comment]
Hi, Skoren,

I found Canu v1.8 IS NOT compatible with assemblies started with any previous version. Can I use Canu 1.8 to assemble the corrected and trimmed reads from Canu 1.7? 

Thanks,
Ying

**Comment by skoren** [comment]
That's correct it is not compatible with assemblies started by previous versions due to changes in the binary structures. However, if you run in a new folder with the trimmed reads as the input, you will essentially be starting a new assembly with 1.8 (all the binary structures are rebuilt) so that is fine.

**Comment by moontree1985** [comment]
Hi, Skoren,

I changed canu1.7 to 1.8. However, I always get an error message: "ERROR:  Parameter 'gnuplotTested' is not known."

Here is my code:
module load ufrc
module load gcc/5.2.0 
module load gnuplot/4.6.0
# changed to canu 1.8
module load canu/1.8
module load java/1.8.0_31


export PROJ_ROOT=/ufrc/mre/share/hu/Sequencing_data/Pacbio/03_Canu_trim/Sweet.trim
export _JAVA_OPTIONS="-Xmx16g"

canu -assemble \
-p corn.assemble -d corn.assemble \
genomeSize=2.5g \
rawErrorRate=0.300 \
correctedErrorRate=0.045 \
corMhapSensitivity=normal \
corMinCoverage=4 \
corOutCoverage=40 \
minOverlapLength=500 \
minReadLength=1000 \
corMhapFilterThreshold=0.0000000002 \
corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 \
shell="/bin/bash" \
java="/apps/java/1.8.0_31/bin/java" \
gnuplotTested=true \
gnuplot="/apps/gcc/5.2.0/gnuplot/5.0.3/bin/gnuplot" \
gnuplotImageFormat=svg \
-pacbio-corrected $PROJ_ROOT/Sweetcorn.trim.trimmedReads.fasta.gz \
usegrid=1 \
gridOptionsJobName=CANU-trim \
gridOptions="--mem=200gb --time=102:00:00 --ntasks=1 --qos=mresende" \
1>correct.corn.assemble.log 2>>correct.corn.assemble.log

Thanks for your help!

Ying

**Comment by skoren** [comment]
That option is deprecated in 1.8, no longer needed. You can always get a list of supported options with ```canu -options```

**Comment by moontree1985** [comment]
I removed gnuplotTested=true in my code and it works. Thank you so much for your help!
