### ISSUE TITLE
Updating Canu

### ISSUE THREAD

**Issue by peflanag** [marbl/canu#1181]
Hi All, I’m running Canu 1.7 and wondering, if I want to update can I use a simple command like when I do pip update or brew upgrade? My background isn’t computer science and I’m very new to command line for sequencing. I had issues installing Canu originally because I had no idea how to add it to the home directory. I had to get someone from a different department do it for me. So ideally I don’t want to mess up the update as quite a few in my lab depend on it. 

Or is it a case I can just download the folder and put it in the location of the Canu-1.7 folder? Will that work?

Cheers!

**Comment by skoren** [comment]
You can't upgrade using a single command but you can download the compiled binaries from the releases page and either replace the 1.7 installation location (assuming no one is currently running any assemblies since 1.8 is not backwards compatible) or place it alongside that install. 

Multiple versions of Canu can coexist on a single machine. That is if the current install is /some/path/canu-1.7 add a /some/path/canu-1.8. That way, if anyone wants to keep using the older version for an assembly they already started they can while if you give the path to the 1.8 release, you will run that instead.
