### ISSUE TITLE
merylOperation::reportStatistics failing

### ISSUE THREAD

**Issue by johnomics** [marbl/canu#1182]
Vanilla canu 1.8 assembly in progress on Linux Slurm cluster:
```
canu -p asm -d asm genomeSize=512000000 -nanopore-raw *fastq.gz
```

meryl-process.51017_1.out log file contains this:
```
meryl: meryl/merylOp-histogram.C:107: void merylOperation::reportStatistics(): Assertion `sDistinct == stats->numDistinct()' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
meryl/merylOp-histogram.C::107 in _ZN14merylOperation16reportStatisticsEv()
meryl/meryl.C::774 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
/tmp/slurmd/job51017/slurm_script: line 136: 216273 Aborted                 /opt/apps/easybuild/software/bio/canu/1.8-foss-2018b/bin/meryl threads=1 memory=1 statistics ./asm.ms16 > ./asm.ms16.histogram
```

Then features many identical messages like this:
```
For word-frequency 0.000000, found threshold 5858
```

Then repeats the errors:
```
meryl: meryl/merylOp-histogram.C:107: void merylOperation::reportStatistics(): Assertion `sDistinct == stats->numDistinct()' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
meryl/merylOp-histogram.C::107 in _ZN14merylOperation16reportStatisticsEv()
meryl/meryl.C::774 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```

However, meryl-process.success is produced and canu continues apparently without further issue. The histogram files appear to be created fine; PNG attached:
![asm ms16 histogram](https://user-images.githubusercontent.com/348469/49744851-9f6f5380-fc95-11e8-90ca-7684448096ca.png)

Should I be concerned?

Thanks
John

**Comment by brianwalenz** [comment]
Concerned?  Not much.  This failed at the very end of writing the histogram output (which is used only to make those pretty plots).  I _think_ it failed by omitting an extremely common kmer (or kmers) from the histogram itself, then complaining that the number of kmers in the file is different than the number in the histogram.

You can check this with something like `meryl print greater-than 33554432 asm.ms16`.  I'm kind of interested to see what this prints.

Concerned about the reads?  Maybe a little.  We don't hit this on human assemblies of normal depth.  Maybe you have gobs of depth that inflated kmer counts, or maybe there is lots of low complexity in this genome.  Or maybe base calls fail with all A.

Since we like posting gory details of bugs now:
```
  void      addCount(uint64 count) {
    if (count == 0)
      return;

    if (count == 1)
      _numUnique++;

    _numDistinct += 1;
    _numTotal    += count;

    if (count < _histMax) {
      _hist[count]++;
      return;
    }
  };
```
Looks like I just never implemented anything to catch overflow.  At least I didn't have a comment there "TODO" or "FIXME", but the return kind of hints maybe I was throwing an assert() there.

**Comment by johnomics** [comment]
Thanks - it's just TA dimers:
```
$ meryl print greater-than 33554432 asm.ms16
ATATATATATATATAT	82103878
TATATATATATATATA	82464447
Bye.
```

I'm throwing unfiltered reads at canu as Adam told me previously that canu should filter them out itself, so this could just be nanopore junk. But this is a plant genome, so could be nasty repeats or centromeric sequence.

**Comment by brianwalenz** [comment]
Canu in 'space heater' mode.  I used it to help heat my house when the furnace broke a few weeks ago.

**Comment by brianwalenz** [comment]
Fixed!  It's missing data on disk, so the fixed version will still fail if run on an old database.
