### ISSUE TITLE
Fungal Genome Assembly

### ISSUE THREAD

**Issue by peflanag** [marbl/canu#1185]
Hi, I'm using canu to assemble a fungal (Candida albicans) genome tahts approx 15Mb in size. Unlike when the bacteria guys in my lab us canu to assemble their genomes it seems to be taking far longer. I assume this is due to the genome size. However, Im just wondering is this normal? I've attached a screen shot. The bacteria guys in my lab that run canu said they never see the command window pump out this. I have to point out that I started canu 24hrs ago and about 12 hours ago it started pumping out whats in the screenshot

<img width="1260" alt="screen shot 2018-12-13 at 08 56 52" src="https://user-images.githubusercontent.com/32863969/49927350-9e1c7180-feb5-11e8-9952-e23ef3d46c61.png">

Also, this is a strain where I used CRISPR to delete a gene family. So I have deleted 15 genes from the organism. I'm assuming canu can still assemble and then if I view the assembled file in 3rd party software I should see gaps for where the genes are missing?

Cheers in advance,

Peter

**Comment by peflanag** [comment]
Yea its 1.7. I dont know how to update to 1.8 cause I dont know how to tell the Mac to put it into the path to use the canu command. I had to have a computer guy do it for us originally in the lab! If I could pip install or brew install or conda install that would be great. Our lab is a microbiology lab and none of use have command line skills! We're just shooting in the dark! But I'll try the suggestion you mentioned above. Cheers!

**Comment by peflanag** [comment]
How do i remove the 3-overlapErrorAdjustment?

**Comment by skoren** [comment]
To remove, something like: ```rm -rf unitigging/3-overlapErrorAdjustment``` from inside the assembly folder.

FWIW, you don't need to put it in a special place to run (but if you care about how to do it I'd suggest this tutorial as a starting point: ftp://ftp.wayne.edu/ldp/en/Intro-Linux/Intro-Linux.pdf and the section on PATH on page 35). Download and extract the release following the commands on the release page then give the full path to wherever you put it. So after you extract it, run ```pwd``` and then to run canu put ```whatever that reports/*/bin/canu```. But don't do that now since you're in the middle of an assembly and the new release isn't backwards compatible with a previously started assembly.

**Comment by peflanag** [comment]
Oh cool cheers!
