### ISSUE TITLE
Canu 1.8 Meryl problem

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1199]
Hi,

I am running canu 1.8, downloaded binary from github. I am running Canu at Meryl step without submitting a job. In my command line I used this option:

**useGridMERYL=false** 

I had this error:

Running job 2 based on PBS_ARRAYID=1 and offset=1.
Error: Only 01 jobs, you asked for 2.

Any idea what is wrong? Thanks.

George

**Comment by skoren** [comment]
This seems like a PBS problem, it is setting PBS_ARAYID in your job even though, presumably, it is not an array job. That said, it sounds like you're running parts on the grid and parts off the grid. We don't recommend running a mix of off/on grid, it should either run all on a single node or all on the grid.

How are you requesting the node that Canu is running on? What's the full Canu command?

**Comment by brianwalenz** [comment]
Are you running canu from within a job array?  If so, unset PBS_ARRAYID before running Canu.  This used to be done automagically, but (apparently) stopped working in 1.8.  It's fixed in the tip code.

Turning off grid support for individual components seems to work, but isn't something we test or really even use.  Instead, increase masterMemory and masterThreads (to make the canu executive job allocation larger).  If merylMemory and merylThreads are both smaller, canu will directly run meryl -- giving the same result as you're looking for.

**Comment by woodoo46** [comment]
Nope. I am running canu as a single job. I will try to run canu using your trick. Thanks!

**Comment by brianwalenz** [comment]
If you're submitting that as '-t 1-1' it's technically a job array, which has PBS_ARRAYID set.  Omit the '-t' option, or just let canu submit itself to the grid (just run canu on your head node, and it'll launch itself).

**Comment by skoren** [comment]
Idle
