### ISSUE TITLE
scaffolding with canu assembly

### ISSUE THREAD

**Issue by dtzhu337** [marbl/canu#1216]
Hi, I am running Canu, and it has come to unitigging phase now. I have questions about scaffolding. Which scaffolding software do you recommend with canu assembly. I also have a transcriptome to be included. Will ERANGE work?

And btw, which file in the canu results should I use to estimate genome size (using k-mer analysis)?

Thank you

**Comment by skoren** [comment]
There isn't a single scaffolding tool to recommend, it depends on the data type you will be scaffolding with (HiC, bionano, 10x, etc). You can scaffold with rnaseq, it will probably have limited benefit for a long-read assembly since most genes will be in single contigs already.

You can use the outputs in either ```trimming/0-mercounts/*.histogram``` or ```unitigging/0-mercounts/*.histogram``` for input to genomescope, you just need to reformat them to keep only the first two columns and use spaces as delimiters.
