### ISSUE TITLE
mhap  precompute consumes much more memory than specified

### ISSUE THREAD

**Issue by yunfeiguo** [marbl/canu#1240]
Hi there,

Thanks for making `canu`, it's an awesome assembler.

I ran into an issue where the `precompute` step consumes much more memory (290GB according to `qacct`) than specified (`cormhapMemory=150`).

log
```
-- Finished stage 'meryl-process', reset canuIteration.
--
-- OVERLAPPER (mhap) (correction)
--
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.78
--
-- Given 135 GB, can fit 202500 reads per block.
-- For 3 blocks, set stride to 2 blocks.
-- Logging partitioning to 'correction/1-overlapper/partitioning.log'.
-- Configured 2 mhap precompute jobs.
-- Configured 2 mhap overlap jobs.
-- Finished stage 'cor-mhapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Tue Feb 12 10:47:41 2019 with 17123.554 GB free disk space (2 processes; 2 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
```

relevant settings for canu.
```
opt/canu-1.8/Linux-amd64/bin/canu -d output -p canu useGrid=false stopOnLowCoverage=1 merylThreads=20 hapThreads=20 cormhapThreads=20 corovlThreads=20 obtovlThreads=20 utgovlThreads=20 MhapSensitivity=high minReadLength=250 minOverlapLength=125 stopOnReadQuality=false utgGraphDeviation=6 utgRepeatDeviation=3 ovsMemory=150 merylMemory=150 cormhapMemory=150 corovlMemory=150 obtovlMemory=150 utgovlMemory=150  -nanopore-raw
```
canu version
```
opt/canu-1.8/Linux-amd64/bin/canu -version
Canu 1.8
```
UGE cluster, Linux 3.10.0-327.36.3.el7.x86_64

**Comment by skoren** [comment]
It looks like you're running Canu off the grid (useGrid=false) and so are requesting the node yourself. If you do that you should specify maxMemory and maxThreads to match whatever you requested from your scheduler. Otherwise, Canu will detect the full available resources on the node and fill those resources. This should be listed in the Canu preamble when it first starts running. In this case, it is running 2 precompute jobs concurrently so it's using 150gb each or 300 total that you're seeing.

**Comment by yunfeiguo** [comment]
Thanks! `maxMemory` and `maxThreads` works.
