### ISSUE TITLE
Canu -version doesn't return version number

### ISSUE THREAD

**Issue by ilyavs** [marbl/canu#1241]
Hello,
I need canu -version to return the version number as expected since another software depends on checking this number.
Since I updated to 1.8, canu -version returns:
`Canu snapshot (snapshot)`
Instead of:
`Canu 1.8`

How can I fix this asap?

Thanks,
Ilya.

**Comment by skoren** [comment]
Canu is reporting a version. Snapshot is a version which does not correspond to a release. Any git checkout is reported as a release + some snapshot commits. Your case happens when you download a non-release tarball from the repo. There is no information on the github repo so the commit log isn't available and Canu defaults to naming it snapshot.

How exactly did you download/install Canu? I confirmed if I download and extract the relase source code and build or use the pre-compiled binaries I get the right version reported.

**Comment by ilyavs** [comment]
I updated canu using conda. It is installed in a dedicated virtual environment along with other tools.
I understand that it does return a version. However, I need it to return a number. 
According to `conda list` the installed version is 1.8 from the bioconda channel.

**Comment by skoren** [comment]
The conda install and upgrade is not correct and not recommended. It doesn't clean up a prior install before making a new one. Don't use it, I wouldn't trust the version it reports. Install Canu using the pre-compiled binaries instead.

**Comment by thierryjanssens** [comment]
I can only make use of conda to install packages on our server. 
How can I be sure which version of canu is used?

**Comment by skoren** [comment]
In short, you can't which is why we don't recommend it. We as the canu developers have no control over how conda packages it, there are multiple open issues for the package yet the issue is still not fixed. Thus, you should install Canu from a package we can manage and control and test, e.g. the releases page.

The first time you install canu with conda it will probably be OK but any upgrade will leave you with a corrupted installation. You'd have to make sure you clean up anything conda built for Canu. You would also manually want to make sure the conda build is complete by running a small test assembly.
