### ISSUE TITLE
Range in fraction of a reference genome covered with assembled contigs

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#127]
Hello,

I could generate contigs assembled (by canu) with PacBio sequencing from human samples.
The coverage of my data is low (~7~10X).
Using the assembled contigs, I examined what fraction of the human reference genome (hg19) will be covered with the contigs. I found that the fraction is relatively low. For example, in chr7, only 36% of the chr7 genome has been covered by contigs.
My question is: considering that the coverage of my data is low, is this low fraction normal?

Thank you in advance,

Hoon

**Comment by skoren** [comment]
7-10X is definitely below the coverage were you'd get a good assembly, we recommend at least 20X. On simple genomes (like yeast or arabidopsis) at 10X you'd recover 60-80% of the genome. However, you have a diploid sample and likely a lot of copy-number variation (since I presume not all chromosomes have two copies) so there are likely to be many regions with only 3-5X coverage and others with almost no coverage.

**Comment by wisekh6** [comment]
Thank you so much for your explanation.

HK
