### ISSUE TITLE
mhap: limiting the number of jobs submitted 

### ISSUE THREAD

**Issue by ogrecio** [marbl/canu#1270]
I am running the following command(version 1.8), on a Linux Red Hat system:
`canu -p ONTassembly -d $WDR -fast -minReadLength=1500 -stopOnLowCoverage=0.010 -redMemory=64 -oeaMemory=64 -batMemory=64 -merylMemory=64 -maxMemory=64 -maxThreads=12 -genomeSize=100m -gridEngineArrayMaxJobs=10 gridOptions="--time=4:00:00 --partition=shared --qos=shared --mem=64GB" -nanopore-raw METALGEN_cleaned.fastq

`
Canu is submitting too many jobs to the queue and it stops. I specify -gridEngineArrayMaxJobs=10, but it just send many blocks of 10 jobs, ending up in more than 300 simultaneous jobs.

How can I tell canu not to submit more than 300 simultaneous jobs?

output:

[canu.txt](https://github.com/marbl/canu/files/2918673/canu.txt)

**Comment by skoren** [comment]
There isn't a way to limit the jobs created directly, it is based on the memory size you have configured. Since this is failing on mhap, increase from the default memory to ```mhapMemory=20 mhapThreads=6``` or higher. Doing this will invalidate your run up to now since you're changing the block size so you'd have to re-start the assembly from scratch. 

Alternatively, you can let the jobs that could get submitted finish. Then, re-start Canu and it will only submit the remaining jobs that couldn't be submitted the first time. Assuming you have <600 jobs this will succeed and the assembly will continue.

**Comment by ogrecio** [comment]
I changed these two parameters, and it made my processes to run nicely. After mhap, same problem occurred with one of the next steps, but then I relaunched canu again and it submitted all the remaining jobs (I needed around 500 jobs).

Thanks!
