### ISSUE TITLE
overlapInCore uses only 3 threads even though 8 were requested and available

### ISSUE THREAD

**Issue by ilyavs** [marbl/canu#1274]
Hello,
I am using circlator which in turn uses canu. The canu command ran is:
canu -useGrid=true gridOptions='-V -q himem7.q -S /bin/bash' gridEngineMemoryOption='-l mem_free=MEMORY' java=/etc/alternatives/java gridOptionsJobName=circlator190226-57-3-D3 -assemble genomeSize=0.1m stopOnLowCoverage=false  batMemory=200g onSuccess='canu_onSuccess.sh' -d /net/mraid08/export/genie/long_read_assembly/Runs/190226-57-3-D3/2.circlator/04.merge.merge.iter.2.assembly -p canu -nanopore-corrected /net/mraid08/export/genie/long_read_assembly/Runs/190226-57-3-D3/2.circlator/04.merge.merge.iter.2.reads.fasta

The output of canu -version is: Canu 1.8

I am running this on a linux SGE cluster. For some reason, one of the 13 overlapInCore takes a lot longer than the others which already finished. The cluster node is mostly free and my job is assigned the requested 8 threads. However, the process uses only 3. Could this be the reason for the longer run time? What could cause this behavior?

Thanks,
Ilya.

**Comment by skoren** [comment]
The job sounds like it is running fine, each thread gets batches of reads and takes a new batch as it finishes. If a few batches are taking longer the rest of the threads will run out of reads and be idle leaving you with a subset of cores in use. 

No idea what the input reads are like for this, it doesn't look like canu corrected reads. If there are some very long reads they can take longer to process. If they are higher accuracy, you could also decrease the error rate which would speed up the job but otherwise I'd let it run as it is now.

**Comment by ilyavs** [comment]
I understand. Thank you.
Best,
Ilya.
