### ISSUE TITLE
Slurm limits the number of tasks in the queue

### ISSUE THREAD

**Issue by SixPlusSeven** [marbl/canu#1283]
My job always break off because the number of tasks(**holding + running + ...**) in queue cannot exceed the slurm limit(100).

Here is my canu command:

> canu \
 -p out -d out genomeSize=${size} \
 -pacbio-raw ${data} \
 correctedErrorRate=0.040 \
 corOutCoverage=50 \
 gridOptions=" -p paratera " \
 gridEngine="slurm" \
 gridEngineArrayMaxJobs=98 \
 batThreads=24 cnsThreads=24 corThreads=24 cormhapThreads=24 cormmapThreads=24 corovlThreads=24 gfaThreads=24 maxThreads=24 merylThreads=24 minThreads=24 obtovlThreads=24 oeaThreads=24 ovbThreads=24 ovsThreads=24 redThreads=24 utgovlThreads=24 \
 batMemory=62 \
 useGrid=true \
        > std.log 2> err.log

I used the option "gridEngineArrayMaxJobs=98", but this option cannot solve my problem, it may hold too many tasks, here is my error log:

> -- 'scripts/1-bucketize.jobSubmit-01.sh' -> job 1802987 tasks 99-196.
CRASH:
CRASH: Canu 1.8
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /PARA/pp812/BIGDATA-2/3.software/1.canu/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1233.
CRASH:  canu::Execution::submitOrRunParallelJob("out", "ovB", "correction/out.ovlStore.BUILDING", "scripts/1-bucketize", 99, 100, 101, 102, ...) called at /PARA/pp812/BIGDATA-2/3.software/1.canu/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/OverlapStore.pm line 511
CRASH:  canu::OverlapStore::overlapStoreBucketizerCheck("correction", "out", "cor", 263, 263) called at /PARA/pp812/BIGDATA-2/3.software/1.canu/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/OverlapStore.pm line 820
CRASH:  canu::OverlapStore::createOverlapStore("out", "cor") called at /PARA/pp812/BIGDATA-2/3.software/1.canu/canu-1.8/Linux-amd64/bin/canu line 608
CRASH:  main::overlap("out", "cor") called at /PARA/pp812/BIGDATA-2/3.software/1.canu/canu-1.8/Linux-amd64/bin/canu line 783
CRASH:
CRASH: Last 50 lines of the relevant log file (correction/out.ovlStore.BUILDING/scripts/1-bucketize.jobSubmit-02.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
CRASH:

I tried the option gridEngineArrayOption="-a ARRAY_JOBS%100"， but my slurm cannot identify this command:

> sbatch: error: Batch job submission failed: Invalid job array specification

Thanks
Alex

**Comment by brianwalenz** [comment]
Increasing ovsMemory **_might_** help.  You'll need to remove all `correction/*ovlStore*` files and directories before restarting.

Otherwise, just keep restarting canu when your grid jobs finish.  It'll notice those are done and submit the next batch.

You can also run these jobs manually using the `out.ovlStore.BUILDING/scripts/*jobSubmit*sh` scripts.  These need to be run from within `out.ovlStore.BUILDING`, that is, `sh scripts/1-bucketize.jobSubmit-01.sh`.  Option `useGrid=remote` will configure all jobs to run but not submit them - it will tell you to cd to somewhere and run a set of scripts, then to restart canu when those are done.

**Comment by SixPlusSeven** [comment]
@brianwalenz 
Thanks for your reply!

1.Increasing xxxMemory can reduce the task number, but the total number of tasks is likely to still exceed the limit;
2.Keeping restarting canu when grid jobs finish is exactly the method I am using now, but using this method I can't fully use server resources;
3.Manually run the xxx.jobSubmit-01.sh is useful. And I'm trying to change the jobSubmit shell by modifying canu script(Execution.pm) in order to automatically control the number of tasks in queue, the current shell is as follows:

> #!/bin/sh
grep "jobid -" ./meryl-count.sh | awk '{print $5}' | xargs -L 1 -P 5 -I {} \
  srun\
  --mem-per-cpu=512m --cpus-per-task=24 -p paratera -o meryl-count.%A_%a.out \
  -D \`pwd\` -J "meryl_test" \
  ./meryl-count.sh {} \
  > ./meryl-count.jobSubmit-01.out 2>&1

-P control the number of tasks to be run.
But now I get error log as follows:

> srun: interrupt (one more within 1 sec to abort)
srun: task 0: running

Can you give me some advice about that?

Thank you！

**Comment by skoren** [comment]
1. If you increase the memory sufficiently it should keep the total tasks below the limit, each job just has to be big enough. It is difficult to guess exactly the right size of the job to make and will vary based on genome size so it will take trial and error. However, if you're going to often run similar sized genomes you can figure out the settings that work and save them in a canu.defaults file so they are automatically set for subsequent runs for you.

2. I don't see why it wouldn't use the resources, it will only not be using them between the time the run ends and the time you start it again.

3. What you're trying to do won't work since Canu depends on submitting a job and then holding for them. That means all the jobs have to be submitted at once and so will exceed your queue limit. The only option you could use would be to set ```gridEngineMaxArrayJobs=98 gridOptions="--wait"```. This will mean that every set of jobs will be partitioned into at most 98 job chunks and every ```meryl-count.jobSubmit-*.sh``` would not return until all of those jobs finished at which point the next one would run. Haven't tested this extensively but I think it will work but this kind of hold isn't ideal.

**Comment by SixPlusSeven** [comment]
Thanks,
I am using a script to restart canu automatically.
:)
