### ISSUE TITLE
Using trimmed reads

### ISSUE THREAD

**Issue by StephanHolgerD** [marbl/canu#1297]
I want to use only the assembly step of canu, because I already corrected and trimmed the reads using proovread. Everytime I start canu the following lines are written to the log file:

-- WARNING:  No trimmed reads found for assembly, but untrimmed reads exist.
-- WARNING:  Upgrading untrimmed reads to trimmed reads for assembly.

the point is the reads are already trimmed and I specified only the assembly tag in the starting command. Is there an opportunity to feed the proovread corrected reads to the canu assembly without re-running the trim step ?

**Comment by skoren** [comment]
That's fine, it's not going to trim the reads, it's just changing flags to let them be used as trimmed reads even though trimming wasn't done by canu. That said, I have no idea how good of a job proovread does trimming reads, you might still benefit from Canu's trimming.

**Comment by StephanHolgerD** [comment]
thanks for the quick answer

**Comment by javijevi** [comment]
I've done the trimming with canu, but I'm getting the same warnings when running the assemble step with cano. Is it right?

**Comment by skoren** [comment]
Yes, this is fine. The message means that your reads have no trim points input and the the full input read will be used for assembly. Since they're already trimmed that is OK, you just won't be able to ask what the read looked like before trimming which you would be able to had you run canu as the full pipeline or with -assemble-trim.

**Comment by javijevi** [comment]
OK, I've got it. Congratulations for the great tool and the superb assistance!
