### ISSUE TITLE
How should I set parameters to improve speed？

### ISSUE THREAD

**Issue by crkmary** [marbl/canu#1300]
I am running Canu (version 1.8) using Nanopore reads （a human genome sequenced with Nanopore at 40-50X) on the local machine which has 64-thread AMD Opteron 6380 @2.5GHz CPUs with 512Gbp of memory.
canu -p asm -d asm genomeSize=3.1g -nanopore-raw ../rawdata/Human.filt.fq.gz cor                           MinCoverage=0 corMaxEvidenceErate=0.22 useGrid=false batThreads=60 batMemory=500

 It's the first time I'm running Canu. Canu is in correction/1-overlapper task for more than 50 days. 

But I read in an article that it should run about 62K CPU hours (including 29K to correct, 33K to assemble).
canu -p asm -d asm genomeSize=3.1g gridOptionsJobName=na12878nano "gridOptions=–time 72:00:00–partitionnorm" -nanopore-raw rel3*.fastq.gz corMinCoverage=0 corMaxEvidenceErate=0.22 errorRate=0.045 "corMhapOptions=–threshold 0.8–num-hashes 512–ordered-sketchsize 1000–ordered-kmer-size 14" 
They assembly ran on a cluster comprised of a mix of 48-thread dual-socket Intel E5-2680 v3 @ 2.50GHz CPUs with 128 Gbp of memory and 8-thread dual-socket Intel CPU E5-2698 v4 @ 2.20GHz CPUs with 1,024 Gbp of memory.

Why am I so much slower than in this article?How should I set parameters to improve speed?

Thanks，
Mary

**Comment by skoren** [comment]
There are a couple of reasons you're not going to get the same CPU as the reported one. First, your CPU is much older than the intel CPUs and if you look up benchmarks, score at best half as fast. Second, you have higher coverage than the original run. So at best you should expect it will take >120K cpu hours or longer on your CPU. 50 days at 64 cores is about 75k and I expect your jobs aren't getting the full computer. It looks like you have a grid available based on your command, for a 3gb genome you'll be able to run much faster if you let Canu use the parallel grid resources rather than limiting it to one machine.

That said, you can tweak a few parameters. The biggest would be to use the flip-flop basecaller to call your reads. This will improve quality and speed up the assembly. Second, match the parameters you posted from the paper command, namely remove ```corMinCoverage=0 ``` and add ``` "corMhapOptions=–threshold 0.8–num-hashes 512–ordered-sketchsize 1000–ordered-kmer-size 14"``` and add ``correctedErrorRate=0.105``` (see also FAQ for flip-flop settings). Last you could try adding the ```-fast`` option but that might give you a less continuous assembly.

**Comment by crkmary** [comment]
Thanks. I still have some problems.
1. If  the task is killed and the parameters are readjusted，will Canu run again or continue?
2. I cannot find the flip-flop settings in FAQ( https://canu.readthedocs.io/en/latest/faq.html). 
3. " The newest releases should automatically adjust for this but if you are using Canu 1.6 or older you can try 'corMhapOptions=--threshold 0.8 --ordered-sketch-size 1000 --ordered-kmer-size 14'." I am running Canu (version 1.8). Shouldn't this parameter be automatically adjusted?

**Comment by skoren** [comment]
1. Depends on the parameters and if the step has already completed. If you change parameters for correction but already run correction, it won't matter. In your case, the corMhap parameters are already written so changing them won't affect the run unless you remove the 1-overlapper folder completely but the corMinCoverage=0 parameter isn't used until later so changing it is OK.

2. Not sure why build the docs was not auto-pulling the GitHub repo but it's rebuilt now and they should be there.
