### ISSUE TITLE
Canu 1.7.1 one job of trimming/1-overlapper stop execution

### ISSUE THREAD

**Issue by nishaag** [marbl/canu#1304]
Hi,

I do not know why only the last one job of trimming/1-overlapper hang, it  stop updating the output file 000079.ovb.WORKING after it reaches to the size of 1.1 GB, the job just hang without giving me any error or any message for me to understand what has happened.  I restarted that job 4 times but always the same issue, it is running for more than 15 days. Please help.
This is the command I used-

#!/bin/sh

qsub -j oe -d `pwd` \
  -l mem=16g -l nodes=1:ppn=32 -l walltime=00:08:00:00 -q PRTq -o overlap.\$PBS_ARRAYID.out \
  -N "obtovl_test" \
  -t 79-79 \
  ./overlap.sh -F "0" \
> ./overlap.jobSubmit-01.out 2>&1

**Comment by skoren** [comment]
I think this job is probably running, just slower than the others due to some long reads in that partition, which can happen (see #1222). When you say it is hanging, what do you mean? Is it getting any CPU in top? The wall time in the command is limited to 8 day so it can't run continuously for more than 15 days without getting killed by your grid. There were some fixes for this in Canu 1.8 but you can't switch versions in the middle of the assembly without restarting trimming completely. 

Your options are to switch to Canu 1.8 and re-start from the corrected reads. Alternatively, assuming that the job is getting CPU while "hung", increase the wall time to the maximum allowed by your cluster and let it complete, however slowly. I'd still suggest switching to 1.8 to assemble the trimmed reads.

**Comment by nishaag** [comment]
Hi Skoren,

Thanks for your prompt reply.  we are increasing the walltime at runtime.  Here "hung"  I mean is that it stop updating the  file 000079.ovb.WORKING after it reaches to the size of 1.1 GB and yes it is getting CPU . One thing I was ruuning this job requesting 32 threads but out of these 32 threads only one thread is getting CPU time. 

Please suggest if there is any other way to get ride of this issue  instead of moving to canu-1.8 for at least my  this run as I already spent  months for execution of this.

**Comment by skoren** [comment]
Yes, that sounds like a handful of either very long or very repetitive reads causing one thread to run slowly. Each thread gets a subset of reads and only one has the problematic read so all the rest of the threads have finished and shut down while one thread keeps running. This is why you see only 1 cpu being used. 

This was an issue with 1.7.1 and could be somewhat fixed by filtering repetitive k-mers more aggressively (for example see issue #947 which sets ```ovlmerThreshold=500```). This isn't easy to change on the fly though, the easiest would be to to re-run from the start of trimming. You could also try the following:
```
cd trimming/0-mercounts
mv <your asm prefix supplied via -p to canu>.frequentMers.fasta backup.frequentMers.fasta
sh meryl.sh 1
/path/to/canu/bin/meryl -Dt -n 500 -s *.ms22 > <your asm prefix>.ms22.frequentMers.fasta
```
Then kill/relaunch the job not finishing. I'm guessing this is nanpore data? If so, your other option is to edit the overlapper.sh script to lower the error rate from the default of 0.144 to 0.12. You could try both of the above together. Not much else to suggest but to wait for it to finish. Do stop canu after you have trimmed reads and either add ovlmerthreshold or update to 1.8 before running the assembly step.
