### ISSUE TITLE
splitReads failed

### ISSUE THREAD

**Issue by YuyaKiguchi** [marbl/canu#1310]
Hi,

I assembled metagenomic data from pacbio sequel but splitReads failed.

This is the command of my assemble.
`canu -trim-assemble -p KG-V-spike1-GF.rm_ctrl_hg.1200k.correctedReads.split.th10 -d KG-V-spike1-GF.rm_ctrl_hg.1200k.correctedReads.split.th10.assemble -pacbio-corrected KG-V-spike1-GF.rm_ctrl_hg.1200k.correctedReads.split.th10.fasta genomeSize=10m maxThreads=120 minReadLength=500 minOverlapLength=250 corOutCoverage=500 corMinCoverage=4 corMhapSensitivity=normal corOverlapper=minimap obtOverlapper=minimap  > KG-V-spike1-GF.rm_ctrl_hg.1200k.correctedReads.split.th10.assemble.log 2>&1`

This is the log.
[KG-V-spike1-GF.rm_ctrl_hg.1200k.correctedReads.split.th10.assemble.log](https://github.com/marbl/canu/files/3033284/KG-V-spike1-GF.rm_ctrl_hg.1200k.correctedReads.split.th10.assemble.log)

Could you check the log and tell me the solution?

Best,
Yuya Kiguchi

**Comment by skoren** [comment]
You've got a lot of non-default parameters, including mixing parameters for different overlappers so they won't get used (e.g. corMhapSensivity and corOverlapper=minimap will ignore corMhapSensitivity). You also don't need any correction parameters (all the cor prefixes) since you're running trim and assemble only. What are you trying to accomplish?

Your crash is caused by using minimap for the trimming step without doing the realignment, this isn't really tested/supported. You should either use the default (leave obtOverlapper off) or set it to mhap which is equivalent to the -fast option.

**Comment by YuyaKiguchi** [comment]
Thank you Sergey,

I want to speed up metagenomic assemble. In correction step, `corOverlapper=minimap` is faster than default Overlapper, so I tried it for trimming step.

I rerun the assembly using suggested parameters.

Thank you.
Yuya

**Comment by skoren** [comment]
Minimap isn't really recommended, especially not for metagenomes. It may be faster but ends up with worse assemblies because it aggressively filters repeats which will filter true overlaps in a metagenome with uneven coverage.

**Comment by YuyaKiguchi** [comment]
Okay. I use default Overlapper for metagenomic assembly.
Thanks for you suggestion.
Yuya
