### ISSUE TITLE
correcting input reads versus correcting the final assembly

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#1312]
I am assembling sequel reads which seem quite error rich 7-8% as determined by canu.

Would you advice to correct my error-rich reads using illumina reads prior to canu assembly or rather correct the assembly made with the noisy long reads?

It is clear that the second method is faster because there are less one-to-one comparisons to be done but maybe correcting the source could lead to a nicer outcome. Any tools or idea about this?

Thanks

PS: I am not proposing CCS to clean the reads but using Illumina paired end data from the same genome.

**Comment by skoren** [comment]
No, the illumina data is not recommended, we dropped support for this because it tends to mis-map in repeats and makes the quality of the correction/assembly worse even though the overall base accuracy is higher. Sequel data is noisier than RSII though it seems to be improved with the latest chemistry updates.
