### ISSUE TITLE
Bad results of de novo plant genome assembly with ONT

### ISSUE THREAD

**Issue by pjgmale** [marbl/canu#1324]
Hello all!

Thank you very much for this awesome forum. I managed to navigate my first assemblies without too much difficulty thanks to the community.

I did a first ONT de novo sequencing of a plant genome, and received 5.4Gb. Based on a congeneric plant's c-value, I expect the genome size to be south of 300Mb, leading roughly to a 20x coverage.

Before ordering new Nanopore and/or Illumina runs, I performed a first assembly to confirm my genome size estimation. I used canu 1.8 on a grid.

Since this plant might be polyploid, I ran canu with the following paramaters, in order to collapse the haplotypes (I am not interested in more information than the haploid genome size, for now)

 genomeSize=270m
 correctedErrorRate=0.17
 corOutCoverage=200

First red flag: I was left with only half the amount of data after the trimming step. This is the [report](https://github.com/marbl/canu/files/3068475/report.txt).

Second huge red flag: GenomeScope's estimate is an order of magnitude lower than I expected:
```
 GenomeScope version 1.0
 k = 22
 property                      min               max               
 Heterozygosity                4.03059%          4.53219%          
 Genome Haploid Length         16,509,294 bp     16,932,099 bp     
 Genome Repeat Length          12,665,481 bp     12,989,846 bp     
 Genome Unique Length          3,843,813 bp      3,942,253 bp      
 Model Fit                     79.8841%          92.2906%          
 Read Error Rate               4.9173%           4.9173%           
```
(details here: http://genomescope.org/analysis.php?code=oRTm0Kem2hlznJXQsgxJ)

Third gigantic red flag: BUSCO analyses recognized only 3.5% complete genes.

I am not totally sure of what is really happening here. Could you please help me?
Thank you very much in advance!

**Comment by skoren** [comment]
In short, it doesn't look like you don't have enough data to get a reasonable assembly. You often lose 50% data on trimming because with such low coverage the correction isn't doing any base filtering, only the trimming is. The genome scope results shows essentially no peak, I wouldn't trust any of the predictions it gives. This is confirmed by your report where none of the k-mer histograms show any peaks either. The only small peak I see is at 1000x which is probably common repeats, I think all you're assembling is repetitive sequence in your genome.  You could try running more than one round of correction, following the FAQ, but I'm not sure that would help either if the coverage is as low as it seems.

You say the plant might be polyploid, is 270mb the size assuming it is not? Often polyploids (like wheat or coffee for example) have enough differences between the genomes that they aren't going to collapse no matter what parameters you set due to large structural variation. That would give you a lot less than 20x coverage in reality. I'm not sure why it's not in the report but there should be a ```unitigging/*.ovlStore.summary``` file that might give more details to estimate genome size. Can you post it?

**Comment by pjgmale** [comment]
Hello Sergey,

Thank you very much for your super quick answer.

Your explanation of my weird results makes total sense.
To answer your question regarding the haploid genome size, well... Our 270Mb estimate is only based on c-values of phylogenetically close plants. Whether it's really the haploid genome size or half the polyploid genome size is unclear. Moreover, our plant might have a different ploidy. In short, I should probably not work with non-model species.

I could not find the ```unitigging/*.ovlStore.summary file```. Here is the content of the unitigging folder, including hidden files:
```
.             3-overlapErrorAdjustment  nep.ctgStore.coverageStat.log    nep.ovlStore.config.txt
..            4-unitigger               nep.ctgStore.coverageStat.stats  nep.ovlStore.per-read.log
0-mercounts   5-consensus               nep.ovlStore                     nep.utgStore
1-overlapper  nep.ctgStore              nep.ovlStore.config
```
As you suggest, I will rerun the assembly to save the overlaps and I will keep you posted. If I cannot get more information from the new run, the best will probably be to order Illumina sequences for a 50x approx, and see what happens.

Thank you again.

**Comment by skoren** [comment]
Strange, part of the output is there but not all of it, you could try re-running the summary stats from inside the unitigging folder: ```ovStoreStats -S ../nep.seqStore -O nep.ovlStore -C 10 -o nep.ovlStore``` and see what you get. You can also look at the coverages in the output contigs from ```nep.contigs.layout.tigInfo```, there should a coverage column which you could compute the median of to estimate size as well.

**Comment by pjgmale** [comment]
I did both (while the new assembly is running), and I attached the files.
If I'm not mistaken, the median coverage from ```nep.contigs.layout.tigInfo``` is 1... How can I interpret that?
Thank you again.

[nep.contigs.layout.tigInfo.txt](https://github.com/marbl/canu/files/3069918/nep.contigs.layout.tigInfo.txt)
[nep.ovlStore.summary.txt](https://github.com/marbl/canu/files/3069919/nep.ovlStore.summary.txt)

**Comment by skoren** [comment]
Yeah, it will be 1 if you include all the unassembled sequences reported there. You only want to include contigs which are flagged as "contig" and have > 1 read (the last column). Here is the histogram you get from that
![Screen Shot 2019-04-11 at 1 50 16 PM](https://user-images.githubusercontent.com/923478/55979758-eaf43700-5c60-11e9-95d9-67adce0c4618.png)

This seems to indicate somewhere around 4x coverage. The summary is saying that 10% of the reads have about 7x coverage worth of overlaps and 15% of the reads have 2x coverage, somewhat consistent with the above. This would imply your genome is a bit over 600mb. To confirm, I'd suggest getting illumina to 30x of that genome size and see what you get.

**Comment by pjgmale** [comment]
Sounds like a good plan. Thank you very much.
I will let the current run finish and we will take a decision.
More soon!

**Comment by skoren** [comment]
Closing since initial issue resolved, feel free to post updates on how the current run turns out and/or if you get more info on the genome size.

**Comment by pjgmale** [comment]
Hello Serguey,

The run finished and I got this file: [overlaps.txt](https://github.com/marbl/canu/files/3107029/overlaps.txt)
The mode is 18. Given the original 5.4Gb of data, am I correct to estimate my genome size around 300Mb, or should I use another value for the input data amount?

In the meantime, we placed an order for 20Gb of Illumina data. Let's see what happens!

Thank you very much for your help.

**Comment by skoren** [comment]
Just to make sure I remember correctly, this is the count of overlaps for the raw data? Looking at the histogram there is a peak around 20x but these overlaps are run with very high error rate (30%) so this analysis combined with the corrected read analysis is probably indicating your haploid genome is 300mb and the haplotypes are more than 70% similar but you should expect a larger than 300mb assembly because there is still enough difference to separate much of the genome.
