### ISSUE TITLE
overlap jobs failed

### ISSUE THREAD

**Issue by dopameinfy** [marbl/canu#1339]
I was running canu1.8 and had some overlap-jobs problem:

```
 -- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'utgovl' concurrent execution on Tue Apr 23 10:48:09 2019 with 304283.653 GB free disk space (2 processes; 2 concurrently)

    cd unitigging/1-overlapper
    ./overlap.sh 21 > ./overlap.000021.out 2>&1
    ./overlap.sh 30 > ./overlap.000030.out 2>&1

-- Finished on Tue Apr 23 10:48:09 2019 (lickety-split) with 304283.653 GB free disk space
----------------------------------------
--
-- Overlap jobs failed, retry.
--   job unitigging/1-overlapper/001/000021.ovb FAILED.
--   job unitigging/1-overlapper/001/000030.ovb FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'utgovl' concurrent execution on Tue Apr 23 10:48:09 2019 with 304283.653 GB free disk space (2 processes; 2 concurrently)

    cd unitigging/1-overlapper
    ./overlap.sh 21 > ./overlap.000021.out 2>&1
    ./overlap.sh 30 > ./overlap.000030.out 2>&1

-- Finished on Tue Apr 23 10:48:09 2019 (fast as lightning) with 304283.653 GB free disk space
----------------------------------------
--
-- Overlap jobs failed, tried 2 times, giving up.
--   job unitigging/1-overlapper/001/000021.ovb FAILED.
--   job unitigging/1-overlapper/001/000030.ovb FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
```

and these two jobs have different log files. ./unitigging/1-overlapper/overlap.000030.out is 

```
Found perl:
   /N/soft/rhel7/perl/gnu/5.24.1/bin/perl
   This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_181"

Found canu:
   /gpfs/hps/soft/rhel7/canu/1.8/bin/canu
   Canu 1.8

Running job 31 based on PBS_ARRAYID=1 and offset=30.
Job previously completed successfully.
```

Other overlap jobs seemed to be successful. 

Thanks for your help!

**Comment by skoren** [comment]
Thanks for the detailed logs, it seems the re-run failed due to a PBS bug in Canu (which is likely fixed post 1.8). I'd guess the jobs ran out of memory. You can try to re-run one of them by editing the submit script, what is in ```./unitigging/1-overlapper/overlap.jobSubmit-01.sh```?

**Comment by dopameinfy** [comment]
It is like this:

```
#!/bin/sh

qsub -j oe -d `pwd` \
  -l mem=16g -l nodes=1:ppn=8 -l vmem=72G,walltime=72:0:0,nodes=1:ppn=16 \
  -N "utgovl_pbnano_canu_asmble" \
   \
  ./overlap.sh -F "0" \
> ./overlap.jobSubmit-01.out 2>&1
```

I used "gridOptions="-l vmem=72G,walltime=72:0:0,nodes=1:ppn=16"" in my command.

**Comment by skoren** [comment]
That's fine, I think 72gb is safe for most steps though you might have an issue with unitigging, depending on your genome size. You could leave it off when you restart Canu. You also don't need the ppn since Canu is already requesting cores itself but again you're over-requesting resources so it's not a big issue.

This does look like something fixed since 1.8. Can you get an interactive session with 32 or 64 gb mem free (128 vmem) if you have a node that big? Then try running ```sh overlap.sh 30``` and ```sh overlap.sh 29``` inside the 1-overlapper folder to see what it outputs?

**Comment by dopameinfy** [comment]
Hi skoren,
I tried `sh overlap.sh 30` and `sh overlap.sh 21`, they still generated the same output:
```
Found perl:
   /N/soft/rhel7/perl/gnu/5.24.1/bin/perl
   This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi

Found java:
   /bin/java
   openjdk version "1.8.0_181"

Found canu:
   /gpfs/hps/soft/rhel7/canu/1.8/bin/canu
   Canu 1.8

Running job 22 based on PBS_ARRAYID=1 and offset=21.
Job previously completed successfully
```
When I ran `sh overlap.sh 29` for a successful job, it has very different long output.

**Comment by skoren** [comment]
What was the output from overlap.sh 29? 

The issue is PBS is always defining an array job id of 1 even on non array jobs so when you run overlap.sh 30 you're really running 31. So to run jobs 21 and 30 you need to run ```sh overlap.sh 20``` and ```sh overlap.sh 29```. Assuming you can run those two jobs by hand and they finish, you can resume Canu and it will continue.

**Comment by skoren** [comment]
Any update on this?

**Comment by dopameinfy** [comment]
I tried to run `sh overlap.sh 29/20` for over two weeks with vmem=128G and the jobs exceeded the requested time... Both *.ovb.WORKING files are over 1GB so far... And can I resume these two jobs? Thanks!

**Comment by dopameinfy** [comment]
over *one* week

**Comment by skoren** [comment]
The jobs are atomic, meaning you can't resume in the middle of one. You can try increasing the cores the job uses (in overlap.sh, -t parameter) and increasing the wall time to the max allowed by your system. There are suggestions on the FAQ to speed this up but that would require re-running all your overlap job so it probably isn't worth it since you only have a couple left.

**Comment by dopameinfy** [comment]
Problem solved! The "-t" shortens job time remarkably. canu successfully resumed.
