### ISSUE TITLE
How do I know if Canu finished successfully?

### ISSUE THREAD

**Issue by jessMaia** [marbl/canu#1343]
Hi there,

I have a newbie question: how do I know Canu finished successfully?

I'm running Canu version 1.8 on an Azure virtual machine (Ubuntu 16.04). I'm using the Snakemake workflow to run Canu sequentially on 24 samples. The Canu jobs were running in the background with 'screen'.

My Canu command looks like this:

```
canu -p xxx -d xxx genomeSize=5.8m -nanopore-raw {input.fastq} >> logfile
```
One of my 24 samples (I don't know which one) had this mesage printed on the screen:

```
ABORT: Canu snapshot v1.8 +177 changes (r9387 f103a6d399bf602cdda8e7b79f8331d7d845b4e8)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:   can't open 'correction/2-correction/correctReads.sh' for reading: No such file or directory.
```
So how do I find out which of my 24 samples had this error?

All my samples have  '*.contigs.fasta' and '*unitigs.fasta' files.

I re-ran all my samples on a different VM (same specs as the first VM) to try to duplicate the error with no luck. So now I have duplicate canu assemblies but I'm still not sure where to find the error.

Thanks a lot!

**Comment by skoren** [comment]
If you have a contigs.fasta file in the top-level Canu directory then it finished successfully, otherwise it did not. Your error seems like an intermittent filesystem issue so it's not surprising a re-run didn't hit it. It would have prevented corrected reads from being generated.

As for which sample, Canu logs what prefix/directory it is running with as it goes so you should be able to look at your logs right before the abort message.

**Comment by jessMaia** [comment]
This was very helpful! Thank you!
