### ISSUE TITLE
SGE problems

### ISSUE THREAD

**Issue by robertvi** [marbl/canu#137]
Hi,

I've just git cloned and compiled canu on our computer cluster (commit 29f64e4d90db84b62c503e924f09548f9cbc86b6), and have so far not been able to get the example data to run using:

export PATH=~/programs/canu/Linux-amd64/bin/:${PATH}
canu \
    -p ecoli -d ecoli-auto \
    genomeSize=4.8m \
    -pacbio-raw sample_data/ecoli_p6_25x.filtered.fastq \
    maxMemory=8g maxThreads=16 \
    useGrid=true gridEngine="sge" \
    gridEngineThreadsOption="-pe smp THREADS" \
    gridEngineMemoryOption="-l h_vmem=MEMORY" \
    gridOptions="-S /bin/bash" \
    gridOptions="-l h=blacklace01.blacklace"\
    gridEngineArrayMaxJobs=75000

The first error (from ./ecoli-auto/canu-scripts/canu.04.out) was:

canu failed with 'can't run 'qconf' to get SGE config'.

looking in Grid_SGE.pm it seems that to set gridEngineArrayMaxJobs the script tries to run qconf. On our cluster qconf only works on the head node, but canu seems to want to run it on a worker node? I could see one job was running on a work node before the error happened so I am guessing this is the process which tried to call qconf and then quit?

I removed that part of Grid_SGE.pm and set the value manually (gridEngineArrayMaxJobs=75000). Now it has the following error:

canu failed with 'invalid useGrid (1) and gridEngine (sge); found no execution hosts - is grid available from this host?'.

Looking at the perl code, it was trying to query the number of  available worker nodes and failing, so again I suspect it was trying to do this from a worker node whereas this only works from the head node on our cluster. Any idea what the problem is here? Many thanks.

[FYI I was restricting it to only use one particular node (gridOptions="-l h=blacklace01.blacklace") because this is currently the only node with the correct java version installed, but I'm not sure this has any impact on the my issue, and I can roll it out to every node if required.]

**Comment by brianwalenz** [comment]
A failure of our auto-configure strategy is that it configures on every execution of canu, instead of doing it just once and saving the configuration.  Fixing this will be tedious, but probably should be done at some point.

The pipeline has a couple handfuls of places where it wants to run a set of jobs in parallel, then run one job to merge results and set up the next parallel job.  To do this, the canu process submits itself to the grid, to run after the parallel steps.

You can set useGrid=remote to run the smaller jobs on the head node.  It'll prompt you to submit the parallel jobs to the grid, then restart canu when those have run.

With possibly not that much work, it should be possible to make canu (running on the head node) submit jobs to the grid and wait for completion (I forget the qsub option to do this) instead of exiting or submitting itself.

Its worth asking if the compute nodes can be admin hosts, which seems to be done in the default SGE install.  I assume they're already submit hosts.

**Comment by brianwalenz** [comment]
Moving from active issue to feature request.  https://github.com/marbl/canu/projects/1
