### ISSUE TITLE
Conditions for optimal threading

### ISSUE THREAD

**Issue by joanmarticarreras** [marbl/canu#1388]
First and foremost many thanks for maintaining and actualizing Canu. It's of great use for all our lab members!

After reading the documentation, we still find some difficulties in how to properly maximize parallelization in Canu to use as much of our resources as possible. If some guidance could be provided in which options could be tuned to improve its speed, we would be very grateful.

Currently we work with 96 cpu with 755 Gb of memory. All detected, no grid engine.

Our current default command for Canu 1.8 is:
```
canu -p PREFIX -d FOLDER genomeSize=XXX minReadLength=200 minOverlapLength=100 readSamplingCoverage=100 maxThreads=96 -nanopore-raw READS
```
Resource assignment by Canu is as follows:

![image](https://user-images.githubusercontent.com/15156142/59422143-2a114680-8dd0-11e9-894d-634967e68216.png)

Total number of CPUs used is 55. At any given time we suppose than no more than 30 CPUs are used at the same time. Which processes would benefit more (if any) to increase its CPU assignment? Would increase the available memory be a better solution?

Looking forward to see your suggestions.

 Joan

**Comment by skoren** [comment]
We pretty much always run with defaults that Canu picks. In your case it is trying to use all the cores. However, it is possible due to other limitations, like I/O it can't actually use the full CPU. There are also steps where it won't use all the CPU or run single threaded. How are you measuring used CPU? A good place to check would be the cormhap stage as that typically uses 100% of requested CPU on our systems unless your I/O is limiting it.

**Comment by skoren** [comment]
Idle
