### ISSUE TITLE
details of mhap

### ISSUE THREAD

**Issue by rafauel94** [marbl/canu#1390]
hi @skoren, Thanks for your work about genome assembling and overlapping (MHAP) because after reading that, i interested in this field of bioinformatics. and i want to work on this field in my thesis. but I haven't enough background in the biology field and feel confused. i have some question about your work:
1- As i have understood, in MHAP you try to find the most similar sequences by counting **same k-mers** and you not consider the **same k-mers** is next to each other or not. and in other hands, you not consider the **same k-mers** locate at the head/end of sequence or middle of the sequence as i think most of the sequences join from their head or end to another sequence. if you don't consider these cases, please say why they are not considerable and if you consider them, please say how you consider in your algorithm. (is MHAP an alignment method or overlapping method?)

2- what is your inputs? which type of inputs you use? **SRA** or **filtered subreads**?
i use **yeast filtered subreads** ([downloaded from your dataset repository link](http://gembox.cbcb.umd.edu/mhap/raw/yeast_filtered.fastq.gz) and extracted and converted that to fasta file) then i want applying mhap on that, exactly which sequences that i must do MinHash sketches on that?
for example second sequnce in fasta file was this:
```
>m130605_032054_42207_c100515142550000001823076608221373_s1_p0/109020/0_996
CAGGAGACGAGAGCCTGCTAACTGTACAGAATACGTTTTCTCGCTCTCCTTTCAACCATAATTGCCAACAATATACATTCGCCAATAGCGTTCAACTTGAGATTGTTCTACGCAACTATCCCTGTCTTTGGAGAAGCCAATTATTGAAAATCTTATCCGGATTTAACTGTGAGAAAAGATTCGCCAGCCTTATCAGTCTCCTGTACCCATTTTCCTCCAGCGTTGCATTGGTTAGGCCATTCCTCAAAGTCTCCTTCCCTCAATAACACCACTGCTAGACAACAAGACGGTGGCAATCCTTCTTACGCAATAAAAGTCACGTACGCACACACCGCCCACAGGAGTACCATCCATATTCATATGGTCCAAATTAAGATATTCTAGCGCGTCTCATCTAGTAACGATGATAACTGCTTTCCATCTCCGCCTTTCACCGAACGGCCGTGCGGTGTGCTTACCTACTAACGAAAGCCTAGAGGTATTAGATGCTTTATTGTCGGGAGTCCTGTCCCCGCGAGATGAGAAAAGAGAGGATACGCGCAAGGCGGGACCCACTTGAGATGGTATACCTCGGAAATTAAGTCAGTGGAAGATCAAAATTACAGGATGCCGGAGGAAACAGTACATCATTATCGGCTTAAACAATGGAGCCCCGCCTCGTAACACGTAAAGTGCAATAACTTAAGTAACGATTGAACATGGTCCCTTTGGGAAGGAGCGCGCACAGTTCGGTCCTCCAACTAAATTGGCACCATCCTCCCACTCAACAACATGCCAGTCACAATATCTTTTATTTTGTGGTTTCGCGATTGCATACACGATTGTGAGTACTAAAGTTTTGTGACGAATGTAATAGGCGGACCCAGAACAAGCAGGCTTTTTCTGTACTTCACTGAAAAGTTAGAAGGAGCCGGGCGCGCCCCAGCGTTGCTTCATAATACCAACACACGCCGGCAACCGACCTGTTTTGAGACTCTTCTTTCTTCTTTCTTCTAC
```

which contains about 1000bp, and some of the other sequences are longer than that! and if i use this in minhash sketch then i have 1000/3 (about 300 3-mers!!) then in my mind i have so heavy computations and in other hands, if we use the small number of fingerprints for a large number of k-mers that will affect on the quality (accuracy) of assembly. are you use exactly this sequences and i am under the impression about computations and accuracy?

best regards,
Rafael

**Comment by skoren** [comment]
1. It's not counting all k-mers only those that make it into a read's minimum set of k-mers. Any reads that share enough of those k-mers have a second stage filter which looks at the position of the k-mers in the reads to estimate the overlap bounds. MHAP finds  all partial overlaps, it doesn't care if the match is in the middle of one read to the end of another read. This is because it gets used as input to correct reads so you aren't just trying to build  a tiling of the genome. To understand MHAP and MinHashing better I'd suggest reading the original Broder paper (On the Resemblance and Containment of Documents), the methods and supplement of the MHAP paper which i assume you've read (Assembling large genomes with single-molecule sequencing and locality-sensitive hashing) along with Mash (Mash: fast genome and metagenome distance estimation using MinHash), and canu papers (Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.) which build on the ideas in the MHAP paper.

2. The FASTQ or FASTA file from processing the raw data downloaded from the SRA. Don't download the raw fastq directly from the SRA, their process has previously been broken  and  gave low quality data which doesn't assemble. Any read of length L will have L-k+1 k-mers so keeping all of them will increase as the size of the read increases. That's why you keep a fixed length sketch which gives a bounded estimate  on  similarity between reads. In practice we typically use 500 k-mers in a sketch and k=16.

**Comment by elenamesga** [comment]
Hi,

I am very impressed with your work in the assembly field.

However, I have some questions about the overlap algorithms.

It seems that for the overlap step in the canu software, you use the MHAP
program, which is composed of two stages: Minhash (first filter) and a second
filter.

However, in your repository, you will find a program called MASH, which
implements the algorithm an optimized version of Minhash, and I cannot
understand why don't you use that for the first stage of MHAP.

Also, do you plan replacing the MASH algorithm with the new program RabbitMASH
(https://github.com/ZekunYin/RabbitMash) so it could be used with the canu
program?


Thanks,
