### ISSUE TITLE
How can I better estimate or control the size of Canu's working files? (Hit 16TB and ran out of disk).

### ISSUE THREAD

**Issue by oneillkza** [marbl/canu#1391]
Hi there,

I just tried to run Canu on some human PromethION data (about 230Gbp worth), and it failed on creating the ovstore when it ran out of disk. The prior steps (which I've retained) took up about 4.5TB, while the ovstore got to 12TB before maxing out the disk (at which point I got worried emails from folks who needed that disk to run production jobs).

[canu.10.out.txt](https://github.com/marbl/canu/files/3298216/canu.10.out.txt)

I've attached the last canu.out that I got before it crashed. I was running on a Slurm cluster, with the working directory on a large network-mounted scratch disk.

This is the command I sued to run Canu:

```
canu -p NA19240 \
	-d /projects/trans_scratch/hybrid_assembly/na19240_canu \
	genomeSize=3000m \
	-nanopore-raw \
	ERR3219853.fastq.gz \
	ERR3219854.fastq.gz \
	ERR3219855.fastq.gz \
	ERR3219856.fastq.gz \
	ERR3219857.fastq.gz 
```

My question is: how can I better estimate how much disk Canu will use? The docs say to leave 3TB, but this was an order of magnitude more than that.

And is there a way to control how much disk is needed? If it turns out that assembling a human genome requires 30TB, then it may simply not be feasible to use Canu in our environment.

**Comment by skoren** [comment]
There was a change in 1.8 that wasn't cleaning up files as early as 1.7 so the space usage increased (sorting used to remove files as soon as they were sorted). The space is better managed in the tip, with the purgeOverlap options, setting it to ```purgeOverlaps=aggressive``` will clean up as it goes.

Based on your logs, you're through computing overlaps, bucketizing overlaps, and are in the process of sorting. This means you've essentially got 3 copies of all your overlaps which is using up a lot of space. Since you're through most of the computation and store building, you can manually clean up some intermediate files to mimic the aggressive option. Remove the folder results and blocks under correction/1-overlapper (make sure your store has 1-bucketize.success). Add the option ```-deletelate``` in ```*ovlStore.BUILDING/scripts/2-sort.sh```. That should free up several TB, you should then be able to re-launch Canu and it will run without increasing the space except while a sorting job is running (due to the -deletelate option) .

**Comment by skoren** [comment]
Idle, answered.

**Comment by oneillkza** [comment]
Thanks for your response. 

This was really a test run to evaluate feasibility of using this in production, and the need for manual cleanup suggests that it unfortunately is not.

**Comment by skoren** [comment]
Not in 1.8 but as I said, the cleanup can be automated in tip with the purgeOverlaps option.
