### ISSUE TITLE
PBS issue (maybe NFS-related)

### ISSUE THREAD

**Issue by StefanoLonardi** [marbl/canu#140]
I am running a relatively large assembly (~60x for a 620Mb genome) on a system with torque/PBS and I get occasionally these error messages via email:

```
PBS Job Id: 102349[10].head
Job Name:   ovS_cowpea_c1-10
Exec host:  gpu03.cluster/9
An error has occurred processing your job, see below.
Post job file processing error; job 102349[10].head on host gpu03.cluster/9
Unlink of stage out file /var/spool/torque/spool/102349-10.head.OU failed
```

```
PBS Job Id: 102349[11].head
Job Name:   ovS_cowpea_c1-11
Exec host:  gpu03.cluster/3
An error has occurred processing your job, see below.
Post job file processing error; job 102349[11].head on host gpu03.cluster/3
Unlink of stage out file /var/spool/torque/spool/102349-11.head.OU failed
```

This is the command I am running (canu v1.2)
`canu gridOptionsJobName=c1 gridOptions="-M stelo@cs.ucr.edu" java=/usr/lib/jvm/java-1.8.0/bin/java corMhapSensitivity=fast -correct -p cowpea -d cowpea genomeSize=620m -pacbio-raw ./pacbio/*.fastq
`
Compute node have a shared NFS. Maybe NFS cannot handle the I/O volume generated by CANU?
Please advise if I there is anything we can do from the sysadmin side to avoid these errors. My sysadmin suggested that perhaps I could try to submit the job from one of the compute node’s local file system (/var/tmp/XXXX) or maybe I can just ignore these error messages?

Thanks,
Stefano

**Comment by brianwalenz** [comment]
There's nothing in there that canu needs or uses.  All outputs (stdout, stderr, actual output) should be redirected by the scripts we submit.  Any idea why the unlink fails?  My only guess is that the file doesn't actually exist.

We've also made major improvements to the unitig construction algorithm since v1.2, but we haven't made a new release yet.  I'd suggest updating to the github latest before you get too far along.

**Comment by StefanoLonardi** [comment]
Thanks for the reply. I will ignore these error messages for now.
