### ISSUE TITLE
splithaplotype wants more memory

### ISSUE THREAD

**Issue by yobyte** [marbl/canu#1410]
I am running canu 1.8 to do a Trio assembly on a grid. I was running the binning part using command 'launch-canu-hap.sh' and got the message below in splithaplotype.NNNNN.out.  I need suggestions on what to try to work through this...it seems that it could need an adjustment to the cluster instructions? The spec file contains this for the options and otherwise we are running canu using defaults:
```genomeSize=700m
useGrid=true
gridOptions="--partition=*****nc"
```
The splithaplotype.NNNNN.out file contains the following:
```Found perl:
   /usr/bin/perl
   This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_212"

Found canu:
   /nfs/********ne-data/canu/bin/canu
   Canu snapshot v1.8 +159 changes (r9369 90dd52697dfa4b78f8abe2aa3860aaeead25a59d)

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
slurmstepd: Job 351633 exceeded memory limit (17470196 > 12582912), being killed
slurmstepd: *** JOB 351633 ON pn26 CANCELLED AT 2019-07-08T16:31:57 ***
slurmstepd: Exceeded job memory limit
```

**Comment by skoren** [comment]
You're in the middle of some large changes to the k-mer counter meryl post 1.8 release and it had a bug (since fixed in tip) that it used more memory than it was told to. Here, it was told to use 12g and tried to use 18g. To work around this error, either edit the submit script (splitHaplotype*jobSubmit*) to add a larger memory request (try 40gb) or add ```gridOptionshap=--mem=40g``` to your canu command and re-launch.
