### ISSUE TITLE
simple list of commands to execute (like dry-run)

### ISSUE THREAD

**Issue by lucacozzuto** [marbl/canu#1415]
Dear developers,
I'm wondering if there is a way to get a list of commands to be executed without CANU starts to look at grid engine etc, so I can launch them on the grid / cloud as I prefer. I tried by using 

```
canu useGrid=remote \
 -s spec.txt \
 -p ecoli3 -d ecoli-pacbio3 \
 genomeSize=4.8m \
 -pacbio-raw pacbio.fastq.gz
```

But it starts to look at qconf...

```
ABORT:
ABORT:   can't run 'qconf' to get SGE config.
ABORT:
```

many thanks,

Luca

**Comment by skoren** [comment]
Generally, what you want is ```gridOptions=remote```. This will run Canu up to a compute command, print the command it wants to submit and exit. It will then be up to you to run those commands and re-start Canu when they're done.

However, in either case you need to have qconf available because that is how Canu knows your grid environment and configures its jobs to fit. If you have SGE, qconf should be a standard command, is it disabled by your sysadmin for some reason? If so you'll have to work around it by faking its output (see #392) for some information on how to do that.

**Comment by lucacozzuto** [comment]
Many thanks for your help! Actually I would like CANU to make no assumption on the system it is running so that I can then decide where to run the single step. Is this possible? 

Thanks again,

Luca

**Comment by skoren** [comment]
No that isn't really possible. Canu doesn't make assumptions which is why it needs to know how to request resources and what resources are there, that's why it does the queries. There's lots of different SGE configurations and ways to request memory/cpu, Canu needs to know that a) you have resources that are compatible with it and b) how to request them, otherwise it can't give you a command to run that would be valid on your grid.

**Comment by lucacozzuto** [comment]
Thanks again. However I was thinking to the scale to the cloud where I can specify how much time / memory etc request by myself...

**Comment by lucacozzuto** [comment]
And in our system it is normally the scheduler that decides where to send the job depending on the resources requested...

**Comment by skoren** [comment]
The cloud is a different case, you could easily put Canu on a single node without any cluster and it will work without running qconf, it will again use the available resources. Again, even in this case if you reserve a 128gb machine you need the run to scale to limit itself to that and not try to use 200gb and crash. Scaling to multiple cloud nodes is different and would require code changes as cloud systems don't typically have a shared file system. 

Canu will handle the submission of jobs to your scheduler, the scheduler will decide where jobs actually run.

**Comment by lucacozzuto** [comment]
Thanks again. 
I was thinking to use an orchestrator for handling the in/out transfers and the memory / time/cpus requests. This is why I would like to have a list of command lines without assumption of the system.

**Comment by skoren** [comment]
Fundamentally, I don't understand what you mean "without assumption of the system". How would you request memory/time/cpu to request without running the same process before, you'd have no idea how much the code would use. Just seeing a command isn't going to tell you the resources it will use. 

Canu can already run without a shared file system, that's how it runs on DNA nexus. Rather than writing a whole new wrapper, you'd be better of adjusting the Canu code to work with AWS commands (or whatever cloud you want to use), see #1099 for suggestions. We don't have access to AWS instances to test so can't add that support ourselves. It should still work in exactly the same way as now. Canu can see instances available in the cloud environment, tailor jobs to them, and request cloud instances. As before, with gridOptions=remote you'd get a printout of the submission request it would want to run and could change it however you want before actually launching.

**Comment by lucacozzuto** [comment]
Sorry maybe I'm not explaining myself very well and I apologize for this... 
reading the previous thread I see that I have to fake the results of qhost just to obtain the command lines I needed. I was just wondering if we can have a way to avoid the use of qhost in a future release. 
Many thanks again.

**Comment by skoren** [comment]
You don't need qconf/qhost in 1.8, as long as you define the necessary variables yourself (they're listed in that issue I pointed to). If all the variables are defined, qconf will run.

If you qhost returns an empty list or no valid nodes, canu will default to using limiting to maxThreads/maxMemory you specified for all jobs.

**Comment by lucacozzuto** [comment]
Thanks! I still get some errors and I don't know what I'm doing wrong... My command line is:
```
canu  \
-s spec.txt \
-p ecoli3 -d ecoli-pacbio3 \
genomeSize=4.8m \
-pacbio-raw pacbio.fastq.gz
`
``
my spec.txt file is: 
```
maxMemory = "250" 
maxThreads = "16" 
gridOptions="remote"
gridEngineArrayMaxJobs = "100" 
gridEngineThreadsOption = "-pe smp THREADS" 
gridEngineMemoryOption = "-l h_vmem=MEMORY"

```

I got: 
```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_181' (from '/usr/lib/jvm/java-openjdk/bin/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 94 gigabytes of memory.
-- Limited to 250 gigabytes from maxMemory option.
-- Limited to 16 CPUs from maxThreads option.
-- Detected Sun Grid Engine in '/usr/share/univage/soldierantcluster'.
-- User supplied Grid Engine environment '-pe smp THREADS'.
-- User supplied Grid Engine consumable '-l h_vmem=MEMORY'.
Can't exec "qconf": No such file or directory at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Grid_SGE.pm line 221.
readline() on closed filehandle Q at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Grid_SGE.pm line 222.
Can't exec "qhost": No such file or directory at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Grid_SGE.pm line 283.
readline() on closed filehandle F at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Grid_SGE.pm line 285.
readline() on closed filehandle F at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Grid_SGE.pm line 286.
readline() on closed filehandle F at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Grid_SGE.pm line 298.
--
-- WARNING:  No hosts found in 'qhost' report.
-- WARNING:  Will use maxMemory=250 and maxThreads=16 instead.
-- 
-- Found   1 host  with  16 cores and  250 GB memory under Sun Grid Engine control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     12 GB    4 CPUs  (k-mer counting)
-- Grid:  hap        8 GB    4 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap    6 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        8 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       16 GB    4 CPUs  (contig construction with bogart)
-- Grid:  gfa        8 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'ecoli3.seqStore', found PacBio reads:
--   Raw:        12528
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'ecoli3' in '/nfs/users2/bi/projects/external/Karl_Wotton/sequencing_analysis/Karl_Wotton/2019-02-27-howerfly_assembly/analysis/test/ecoli-pacbio3'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
----------------------------------------
-- Starting command on Tue Jul 16 08:44:38 2019 with 290497.842 GB free disk space

    cd /nfs/users2/bi/projects/external/Karl_Wotton/sequencing_analysis/Karl_Wotton/2019-02-27-howerfly_assembly/analysis/test/ecoli-pacbio3
    qsub \
      -l h_vmem=4g \
      -pe smp 1 remote  \
      -cwd \
      -N 'canu_ecoli3' \
      -j y \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh
sh: qsub: command not found

-- Finished on Tue Jul 16 08:44:38 2019 (like a bat out of hell) with 290497.842 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 127.  (rc=32512)
ERROR:

CRASH:
CRASH: Canu 1.8
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit script.
CRASH:
CRASH: Failed at /project/canu-1.8/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 780.
CRASH: 	canu::Execution::submitScript("ecoli3", undef) called at /usr/local/bin/canu line 771
CRASH: 
CRASH: No log file supplied.
CRASH:
`
``

**Comment by skoren** [comment]
It looks like Canu is doing the right thing, when the query fails it limits itself based on your maxMemory/maxThreads. Your spec looks fine but ```gridOptions=remote``` should be ```useGrid=remote```, I made a mistake in the option above.

However, your grid appears to be completely non-functional. It's identified as SGE (because it has SGE_ROOT environment variables) but then none of the SGE commands work. As I mentioned above, Canu needs to be able to run some parts of the pipeline to calculate job sizes and partitions (for example, assume it takes 1gb of ram to index 20k reads, then the number of index partitions will change with the number of reads you have and can't be computed before the run). What kind of grid engine is this? Is this really SGE or something else? You'll need to either figure out a working way to submit jobs to your grid for Canu to use or you'll have to run the pipeline off grid which will actually run everything and print the commands as they run.

**Comment by lucacozzuto** [comment]
Many thanks for your help. Indeed our system is SGE and the commads like qsub etc are running well. I think the problem is because I'm using a singularity container where the SGE commands are not installed. This is why I would like to launch them by myself to different nodes. 
I see that I have only a single shell script now:
```
correction/0-mercounts/meryl-count.sh
```
is this normal? 
Btw: thanks a lot for your kind answers!

**Comment by skoren** [comment]
I don't recommend running Canu in a container, especially not the executive. The executive is mostly lightweight and runs single-core jobs. You should run Canu itself outside of a contained, it will run the executive to perform the job partitioning/check success/failure/etc and then give you a qsub command with a shell script to run (when you use the remote option), you can then run that shell script in a container if you want.

**Comment by lucacozzuto** [comment]
I agree. But I was thinking to bundle everything in a container so that I can move the whole pipeline easily and in a reproducible way. I'll try to figure out if this is feasible. Thanks.

**Comment by skoren** [comment]
Like I said before, I think bundling in this way with wrappers to move files is not practical. Canu is already doing this for you, it dynamically configures itself to the resources, figures out job sizes, makes standalone shell scripts for jobs, and runs those jobs. You're essentially splitting Canu apart and trying to build it back together.  This is error-prone and will quickly be out of date. For example, what if we change the pipeline in the next release?

If you're trying to move it to a cloud platform you should take a look at the DNANexus support I pointed you to earlier and work on modifying that.
