### ISSUE TITLE
collision rate and k-mer size

### ISSUE THREAD

**Issue by ghandschin** [marbl/canu#1446]
Hi, 
I have a question about the k-mer size used for haplotype k-mer identification in the trio-binning procedure.
In the paper "Complete assembly of parental haplotypes with trio binning"
you used the formula 𝑘=log|4|𝐺(1−𝑝)/𝑝) to determine optimal k-mer size where G = Genom size and p = collision rate.

What did you consider to be a "tolerable collision rate"? why does p for thaliana differ form p in sapiens and taurus? (p=0.027 and p=0.00068) and what would you recommend for a highly heterozygous  2.5 G Genome? 

Thanks,

**Comment by skoren** [comment]
I'm not sure where the numbers you listed come from? The collision rate is fixed in the code as 0.001, the formula gives 19 for a. thaliana and 21 for h. sapiens or b. taurus. This formula is completely independent of heterozygosity, it's based on drawing a random set of k-mers from the space of all k-mers to equal the genome size to see if there is a collision.

In practice, there is a tension between the k-mer size and read error. It would be nice to use a 51-mer and those are more unique than 21-mers, few of those survive in PacBio or OxNan reads. Thus we use the lowest k we can such that you avoid random collisions (thus the formula above).

**Comment by ghandschin** [comment]
Hi,
I was confused as in the publication ( https://www.nature.com/articles/nbt.4277 ) you state that you used k = 16 for a. thaliana.

> "Given a genome size G and tolerable collision rate p, an appropriate k can be computed as k = log4 (G(1−p)/p)52. According to this formula, we used k = 16 for A. thaliana and k = 21 for H. sapiens and B. taurus."

Thank you for clarifying!
