### ISSUE TITLE
Advice of correction parameter for plant genome

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/canu#1449]
Dear community and developer:

I have about 120X coverage Nanopore fastq sequence of plant genome (Nanopore R9 1D; estimated genome size is 580 Mb; self-pollinating species). Below is the sequence summary of Nanopore fastq sequence after trimming adaptor:
```
# contigs (>= 0 bp) | 8913471
# contigs (>= 1000   bp) | 6923179
# contigs (>= 5000   bp) | 3697224
# contigs (>= 10000   bp) | 2325311
# contigs (>= 25000   bp) | 711816
# contigs (>= 50000   bp) | 118431
Total length (>= 0 bp) | 72711798733
Total length (>= 1000   bp) | 71611153733
Total length (>= 5000   bp) | 63414016273
Total length (>= 10000   bp) | 53508770421
Total length (>= 25000 bp) | 27802480179
Total length (>= 50000   bp) | 7776099977
# contigs | 8013521
Largest contig | 315423
Total length | 72411139971
GC (%) | 34.03
N50 | 19403
N75 | 9596
L50 | 1094014
L75 | 2406933
```

After read the Canu v1.8 tutorial, FAQs, and manual, I think changing some parameters below may be useful for better correction. And you are welcome to give me suggestions (e.g. the value of each parameter; other parameter I didn't mentioned also helpful and so on)

1. corMaxEvidenceErate
The default is unset. The description in FAQs said "Setting corMaxEvidenceErate=0.15 is sufficient to correct for the highly repetitive and AT/GC rich genome". The GC (%) above is 34%. I think I don't need to adjust this value?

2. corOutCoverage
The default is 40. From the previous literatures I read, it seems that 30X coverage reads is enough for assembly. In my case, I am curious whether I can obtain better assembly if the coverage of corrected reads increase? Anyone has idea about this?

3. MhapSensitivity
The default is normal. According to the Canu manual, I will set "low" because the read coverage I had is about 120X.

4. minReadLength
The default is 1000. Since I have larger read coverage (120X). I think it's better to set value 3000?

Thus, the command I probably use will be:
genomeSize=580m minReadLength=1000 corOutCoverage=60 MhapSensitivity=low 

Any suggestion and experience are welcome.

And I still have some questions:

Q1: The estimated genome size is usually calculated by k-mer analysis or flow cytometry analysis. I am curious if the actual genome size is 550 Mb but I set estimated genome size is 580 Mb during correction process (or assembly process), whether the quality of assembly will be severely impacted?

Q2: The parameter of "correctedErrorRate" is used in assembly process? (I knew it was classified in all stages. But I don't understand what's the function of correctedErrorRate during correction and assembly process, respectively. 

Q3: Previous literatures discussed the quality of assembly using different assemblers. Briefly, Canu performed very well and it can be used in distinct species (from bacteria to animals). The only main concern is that Canu spends more time and computation resource for assembly.  In my case, I expected the assembly process can be finished within 1 month and obtain high quality of plant assembly. In my above case of plant genome, I will add options below for assembly "corMhapOptions=--threshold 0.8 --ordered-sketch-size 1000 --ordered-kmer-size 14' correctedErrorRate=0.105". These options are referred from FAQs (or Canu manual). I would like to ask your suggestions for assembly process using Canu.

The resource of PBS cluster I use:
 ```
resources_max.nodes = 1
resources_max.pvmem = 25gb
resources_max.vmem = 2048gb
  
Total nodes: 2
Total CPU cores: 160 
```

Thank you for the patience about reading my questions. You can just give suggestions in any part of above questions.

**Comment by skoren** [comment]
1/3. Your parameters look ok, you don't need to set corMaxEvidenceErate and MhapSensitivity will get set to low automatically. 
2. It doesn't help to add coverage to the assembly unless you have a very heterozygous genome, if it is see the FAQ for suggested het parameters, you can estimate heterozygosity from the illumina data.
4. Increasing this to 3kb should be ok but it won't make much difference, Canu will automatically select the longest reads to use preferentially during correction.

Q1 The genome size doesn't have to be precise, better to over than under estimate but 600 vs 550 isn't going to make a difference. 

Q2 CorrectedErrorRate is only used after correction, it is the error rate remaining in the reads post correction. The value of 0.105 is reasonable for recent nanopore data. If you have not yet, I'd suggest running the data through the latest base caller (Guppy with HC) before you start the run.

Q3 Your options are OK, I'd also suggest looking at the FAQ for the parameters for heterozygous genomes (if yours is) and the parameters for repetitive genomes. The repetitive parameters might help you since you don't have a large cluster and it might speed up the run.

**Comment by hungweichen0327** [comment]
Dear Sergey Koren,
Thank you for the kind and fast reply. The suggestions you provide are clear and helpful for me. There is only one questions I just want to confirm. 

Q1 (refer to 2):
About the corOutCoverage issue, do you mean increasing longest read coverage (e.g. set 40X to 60X) will not help to get better assembly? (In my case, the heterozygosity of this genome is low)

Q2 (refer to Q2):
In Canu version v1.8, the default value of CorrectedErrorRate is 0.144 for Nanopore data, is that right? The latest version of base caller for Nanopore (Guppy with HAC option) increase the read accuracy from 92.1% to 95% (provided from to the company). But the base calling speed decreased to 8 fold. Actually I don't know whether it's worth enough to do re-basecalling for better accuracy (increase 2.9%). Because the hardware of computer in our lab can not support GPU mode during basecalling, it may spend >6 months for re-basecalling. (Unless my advisor is willing to replace graphics card compatible for Guppy...XD).

Thanks again and looking forward for the suggestions.

**Comment by skoren** [comment]
Q1, yes in the case of low heterozygosity (what exactly is low? 0.1%, 0.5%?) higher coverage won't help. I'd suggest het parameters over 0.5% heterozygosity.

Q2, Yes in 1.8 it's 0.144 and in the 1.9 branch is 0.12. However, we've been using 0.105 for recently base called data. Switching from 0.144 to 0.105 would likely save a good bit of compute time though I don't think it would save 6 months of time. Perhaps you can look into using a cloud computing GPU instance instead of running on local CPU for base calling?

**Comment by hungweichen0327** [comment]
Dear Sergey Koren,

Q1: I'll check the exact value heterozygosity.

Q2: I remembered that CPU mode is 10 times slower than GPU mode when basecalling. I will seek for cloud computing GPU instance.

Thank you.
