### ISSUE TITLE
How can I run canu on several different files 

### ISSUE THREAD

**Issue by dridk** [marbl/canu#1472]
How can I run canu on differents files with  a slurm grid engine ? 
Each fastq file comes from a different sample. 
Are the following lines the good way ? 
```
for file in *.fastq
 name = `basename $file`
 canu -p assembly -d name genomeSize=4m -nanopore-raw {file}
```
canu snapshot ( 1.8)

**Comment by skoren** [comment]
Yes your command is OK (with the change of `-d name` -> `-d $name`)  Each assembly will be in a different directory, and all will name their outputs e.g. 'assembly.contigs.fasta'.

For maximal performance, add `gridOptionsJobName=$name`.  This will give each Slurm job a unique name.  Otherwise, Canu will wait for _all_ jobs of one stage to finish before starting _any_ jobs of the next stage.

If you have hundreds of samples, it might be better to run each sample _without_ grid support.  Make a batch something like this:
```
#!/usr/bin/env bash
jobid=$SLURM_ARRAY_TASK_ID
cores=$SLURM_CPUS_PER_TASK

if [ x$jobid = x -o x$jobid = xundefined -o x$jobid = x0 ]; then
  jobid=$1
  cores=`grep -c ^processor /proc/cpuinfo`
fi

if test x$jobid = x; then
  echo Error: I need SLURM_ARRAY_TASK_ID set, or a job index on the command line
  exit 1
fi

num=`ls *.fastq |sort |wc -l |awk '{print $1}'`
if [ $jobid -gt $num ]; then
   echo "Error: Maximum job id is $num but you asked for $jobid"
   exit
fi

file=`ls *.fastq |sort |head -n $jobid |tail -n 1`
name=`echo $file |sed s/.fastq//g`
canu -p assembly -d $name genomeSize=4m -nanopore-raw $file useGrid=false maxMemory=16g maxThreads=$cores
```

You can then submit this as an array job as you would for any other SLURM task request 16gb of memory/16 cores per array instance (or whatever number of CPUs and memory you want to use; these are decent values for microbes).

**Comment by dridk** [comment]
Thanks for your help ! I will do that !
