### ISSUE TITLE
CCS low coverage assembly

### ISSUE THREAD

**Issue by LipengKang** [marbl/canu#1473]
Any recommended settings for low coverage HiFi data? With 4x coverage of 12kbp HiFi reads from a repetitive plant genome, the parameters in HiFi NBT paper bring only 19M assembled contigs:

```
canu -assemble -p asm -d asm genomeSize=2135m \
  correctedErrorRate=0.015 ovlMerThreshold=75 batOptions="-eg 0.01 -eM 0.01 -dg 6 -db 6 -dr 1 -ca 50 -cp 5" \ -pacbio-corrected *.fasta
```

no need for a nice assembly. Just want nice contigs as much as possible. WIth this low coverage case, if increase correctedErrorRate is ok, like 0.045 or 0.105?

Thanks in advance!

lipeng

**Comment by skoren** [comment]
You should run both trimming and unitigging (don't specify -assemble) as these reads still have some errors that trimming helps. Since you have low coverage you could keep running w/o trimming but a higher error rate. 

Increasing the error rate would help if your contig breaks are caused by errors. I think at your coverage it is more likely your errors are caused by coverage gaps. I expect if you take everything in ```*unassigned.fasta``` with at least two reads and I expect that plus your contigs will get closer to the genome size. However, you're not going to get a good assembly.  By Lander-Waterman statistics, 4x is not really enough to get large contigs and a good fraction of your genome is not going to be covered.

**Comment by LipengKang** [comment]
Yes, as you would expect, gaps are caused by coverage holes. And also a certain outcrossing rate.
The main trouble is what coverage is cost-effective and cover-effective for me.
The aim is to cover genome as much as possible but no need for very nice contigs. Assembly maybe a way to improve align ability of interspecific  comparison. So  if these  raw contigs can mainly stand for this specie, the result is perfect.
Any advice?

**Comment by skoren** [comment]
I would say you want 10-15x per haplotype or 20-30x total for an assembly. If you just want sequences representing the genome, you can get those from the k-mers in the reads since they're accurate. As I said earlier, I expect the unassembled sequences w/>2 reads will give you a bigger fraction of your genome as well.

**Comment by LipengKang** [comment]
Ok, I have accepted unassembled reads before. Thank you for your attention!
