### ISSUE TITLE
Unitigging resources

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1508]
Hi Sergey

The assembly job is now in the unitigging stage. From the beginning, the assembly is running on batch nodes that are not high memory. each node has 125GB and 24cores. Now I see that the algorithm submitted a job "bat_Spu" requesting 512gb and 32 cores, see belwo:

1649591.sapelo2         malabady    batch    bat_Spu             --      1     32     512gb 720:00:00 Q       --     --
The job is setting in the queue and I don't think it will be dispatched because none of the nodes in this batch queue has these resources. 

I thought that Canu looks up the available resources in the grid and submit the jobs accordingly. Am I wrong? 

What is the best solution in this case? Should I kill this job, change the queue to a one that have the requested resources and restart? Any other solution? 

here are the contents of the "unitigging" folder:
0-mercounts 
1-overlapper  
3-overlapErrorAdjustment  
4-unitigger  
Spu.ovlStore 
 Spu.ovlStore.config  
Spu.ovlStore.config.txt 
 Spu.ovlStore.per-read.log  
Spu.ovlStore.summary

many thanks.

**Comment by skoren** [comment]
Canu isn't aware of partitions when it does the query/submissions. This is because the grid typically reports all nodes available. So if there is a 500gb machine in the grid, Canu will submit jobs to it. 

You have two options to fix it, either way kill both the bat job and the canu job waiting for it. You can either tell this step to use the appropriate queue (```gridOptionsBat="<whatever you need to request the queue>"```) or limit bat to the memory available on the smaller nodes (```batMemory=120```). I expect 120gb will be sufficient for the assembly to run so I would suggest to try this first.

**Comment by skoren** [comment]
It's always defaulted to 40, that is correct. Since the longest 40x of reads are corrected anyway and these are used for consensus. Adding much more coverage gives you diminishing returns for consensus quality so it's set to 40x to decrease memory/cpu usage.
