### ISSUE TITLE
need help regarding canu overlap, correction, trimming parameters

### ISSUE THREAD

**Issue by gauravarai** [marbl/canu#1513]
Sir, 
I have total number of 68 reads to assemble. these reads I got for a virus and are retrieved from virus metagenomic sequence data using graphmap. pictorial representation of graphmap alignment is attached below. as we can see from the image, the alignment covers about 90% of the the genome (the alignment mismatch is 33%)
![bc3gom_virus_align_003 sam-NC_001648_Cassava_vein_mosaic_virus_complete_genome](https://user-images.githubusercontent.com/25291940/66742768-0cdfa800-ee96-11e9-9754-9732d0fc1599.png)
but when I pipelined these reads into canu it gives contig of just 551 nt length with just 3 reads. all other reads are getting filtered out. 
I need help regarding if there is any way possible by which maximum number reads can pipelined into final canu contig assembly. I'm uploading current canu assembly [files](https://drive.google.com/open?id=1IUnsXO_uaPt0pHubmbptm8Zymr1wI6gX) and raw sequence read [files](https://drive.google.com/open?id=1Xpc6kaO-yPTupCivW5zvSxcSVjHI6Q0y) which are used in assembly. title of this file is name and genbank id of the virus to which all 68 reads aligned into graphmap.
canu parameters im using-

```
./Linux-amd64/bin/canu -p canu -d NC_001648_Cassava_vein_mosaic_virus_complete_genome_minovlp50_gs0.008m_cer0.4 genomeSize=0.008m -nanopore-raw NC_001648_Cassava_vein_mosaic_virus_complete_genome.fasta useGrid=false minReadLength=200 minOverlapLength=50 stopOnLowCoverage=0 correctedErrorRate=0.4
```

**Comment by gauravarai** [comment]
Sir,
Further, I did some tweaks about my issue from already reported problems here and based on that I followed this parameter
`canu -p canu -d NC_001648_Cassava_vein_mosaic_virus_complete_genome_minovlp50_gs0.008m_cer0.6_comincov0_coroutcove10000_corfiltnone_cormhapsenhi genomeSize=0.008m -nanopore-raw NC_001648_Cassava_vein_mosaic_virus_complete_genome.fasta useGrid=false minReadLength=200 minOverlapLength=50 stopOnLowCoverage=0 correctedErrorRate=0.6 corMinCoverage=0 corOutCoverage=100000 corFilter=none corMhapSensitivity=high`
With this I'm able to extend contig length upto 4.8 kb with 3 reads. but I'm expecting contig length about  7.5-7.8 kb based on graphmap alignment. the actual genome size of the virus is 8.15kb. is there any way to increase contig length...?

**Comment by skoren** [comment]
Have you tried mapping with anything other than graphmap? Neither minimap2 nor ngmlr find any mappings of these reads. The graph map alignments are around 50% identity, not 70 as you indicated above, which I think are just noise. 

I don't think there is away to assemble the data because I don't think these mappings are very accurate. Essentially the reads aren't really agreeing with each other and so correction and trimming within Canu are going to remove the reads since they don't agree with each other. I can get a larger contig by turning off pretty much all filtering and assembling the raw uncorrected reads:
```
canu -assemble -p asm -d asm useGrid=false -nanopore-corrected NC_001648_Cassava_vein_mosaic_virus_complete_genome.fasta minOverlapLength=100  genomeSize=8k correctedErrorRate=0.25 contigFilter="2 0 1.0 0.5 2" batOptions="-nofilter suspicious,lopsided"
```
but again this doesn't really map to the reference sequence (except with graphmap). I'd go back and try retrieving data a different way instead of assembling this data.
