### ISSUE TITLE
corrected output seqs **id=[num]**?

### ISSUE THREAD

**Issue by Yunxia-li** [marbl/canu#1543]
Hi:
I had a question about the corrected output seqs:            
I am wonder what's the **id=332_1** mean?
why there are duplicate sequence ids but with different id=[num]?
 
```
>3fb4b4d1-75a1-41a4-bc5e-7be5980f8dff id=332_1

>3fb4b4d1-75a1-41a4-bc5e-7be5980f8dff id=332_1
```

Hope for your reply

Yunxia

**Comment by brianwalenz** [comment]
The first part of the 'id' is how canu refers to reads.  We use increasing numbers instead of dealing with text strings (that could be duplicates).  The second part, after the underscore, *was* to indicate that the source read was split into multiple pieces during read correction; '_1' would be the first part of the read, '_2' the second, etc.  We stopped doing this sometime around Canu v1.6, and now create one corrected read for each input raw read.

**Comment by skoren** [comment]
I don't think you posted the right logs, the two lines are identical. What @brianwalenz said is correct, if you get something like <number>_<number>like this:
```
>3fb4b4d1-75a1-41a4-bc5e-7be5980f8dff id=332_1
>3fb4b4d1-75a1-41a4-bc5e-7be5980f8dff id=332_2
```
then this is the behavior for old versions of canu. The original read got split into two or more pieces and it's reporting that back to you. You should update to the 1.8 or soon to come 1.9 release as versions that had this output are more than two years out of date.

If you see something like:
```
>3fb4b4d1-75a1-41a4-bc5e-7be5980f8dff id=332
>3fb4b4d1-75a1-41a4-bc5e-7be5980f8dff id=335
```
That is a problem with your input, canu assigns unique IDs to the reads as they are read in and the above log shows that the same read occurred more than once in the input files.
