### ISSUE TITLE
canu get much smaller genome

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#155]
Hi,
I am using the latest release to assembly a plant genome, whose estimated genome size is 600m.
I got pretty good N50 (2.1 Mb), however a much smaller genome (400 m).
My command line is:
canu -p asm-d asm \
 -pacbio-raw pacbio.raw.fastq \
 genomeSize=600m \
 gridOptions="-t 20000000" \
 minReadLength=500 \
 corOutCoverage=80 \
 useGrid=1

Is there any suggestion to improve this situation?
Thanks!

**Comment by tangerzhang** [comment]
Sorry, I should mention that I have 78X coverage of raw data. That should be sufficient to cover most of genome.

**Comment by skoren** [comment]
This can happen if your genome has lots of simple repeat or heterochromatic sequence which are significantly longer than your reads and are collapsed. If you aren't using a recent checkout from the repository, I'd suggest rerunning with Canu 1.3 (just the unitigging step). You can also look for unassembled tigs in asm.unassembled.fasta with more than 1 read which would likely have the collapsed missing sequence.

**Comment by tangerzhang** [comment]
Hi Skoren,
I got a lot of tigs with more than one reads supported in unassembled fasta file. Attach is a few lines of unassembled.fasta.
Should I extract these tigs and add them into the final assembly?
Thanks!
####################
>tig00000001 len=3357 reads=6 covStat=4.05 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000007 len=4046 reads=10 covStat=6.89 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000012 len=16339 reads=27 covStat=39.73 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000013 len=25813 reads=674 covStat=-337.71 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000015 len=20913 reads=40 covStat=72.56 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000017 len=27626 reads=91 covStat=48.25 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000019 len=23006 reads=30 covStat=74.17 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000028 len=19254 reads=10 covStat=41.95 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000029 len=5571 reads=6 covStat=5.17 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000030 len=31792 reads=47 covStat=119.40 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000031 len=15718 reads=17 covStat=39.53 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000032 len=9063 reads=10 covStat=22.81 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000033 len=6396 reads=10 covStat=14.43 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000035 len=38909 reads=367 covStat=-50.87 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000036 len=22175 reads=27 covStat=78.56 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no
>tig00000037 len=29563 reads=74 covStat=61.81 gappedBases=no class=unassm suggestRepeat=no suggestCircular=no

**Comment by skoren** [comment]
You can see how many bases are in the unassembled tigs with at least a few reads, say 10, and include them in your assembly. Some of them may be redundant and all are unassembled repeat elements from your genome so you can include them in your assembly but they are low confidence because of these reasons.

You can also try adjusting the unassembled filter. See the FAQ on the documentation here:
http://canu.readthedocs.io/en/stable/faq.html#faq
under My asm.contigs.fasta is empty, why?

Increasing the 0.75 to 0.85 or 0.95 would filter less of your tigs. You don't need to re-run the full assembly to test this setting, only unitigging/4-unitigger onward. If you remove the unitigging/4-unitigger, unitigging/5-consensus, unitigging/asm.tigStore*, asm.*.fasta and re-launch with the updated filter setting, Canu will rerun just the last steps.

**Comment by tangerzhang** [comment]
Thanks for your suggestion.
I will try these settings.
