### ISSUE TITLE
Unable to run job: denied: host "nodexxx" is not submit host

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#156]
When trying canu on a new SGE cluster today, I got the error message above.
I know It's the problem of SGE, but no idea what caused this failure.
Running other jobs e.g. FALCON looks good.
Any suggestion?
Thanks!

**Comment by skoren** [comment]
The SGE nodes must be allowed to submit jobs on your cluster to run Canu. Without this option, you would have to run the executive on the head node and manually submit each large compute to the grid when it stops. @brianwalenz can give details on how to run that. Falcon runs because it leaves a job running on the head node which polls the scheduler to see if jobs are done but we've had issues with this on heavily loaded grids which is why Canu uses the submit and wait approach instead.

**Comment by brianwalenz** [comment]
The magic isn't very involved:  canu option useGrid=remote will do small bits of compute on the head node and prompt you to submit jobs to the grid.  When the job finishes execution, you restart the same canu command for the next step.  Repeat until done.

Adding all the compute nodes as submit hosts will solve the problem, but this needs to be done by an SGE admin.

**Comment by tangerzhang** [comment]
Thanks Skoren and Brian!
At least I can use Canu now.
I will report this issue to our SGE admin.

**Comment by wuxiaopei0509** [comment]
Hi，brianwalenz 
We encounter the same issue about Unable to run job: denied: host "nodexxx" is not submit host when running falcon,you have suggested that " Adding all the compute nodes as submit hosts",could you tell me how to use some commands to solve this problem exactly?
Thank you !

**Comment by BioYLiu** [comment]
Hi, wuxiaopei0509
use follow command:
> qconf -as compute_node_name
Example: qconf -as compute-0-0.local
you can find your hosts file in /etc/hosts
