### ISSUE TITLE
PacBio coverage fluctuation & split contigs (maybe?)

### ISSUE THREAD

**Issue by pi3rrr3** [marbl/canu#1571]
Hi, I am using Canu 1.8 to assemble a ~340 Mb genome (estimate based on literature) with >60X coverage of a haploid individual (Sequel v3, subread N50: 11 kb). I am running the assembly on a grid, and so far my best results are obtained through the following command:

`canu -p canu_18_A -d mydir genomeSize=338m -pacbio-raw combined_reads.fa.gz "gridOptions=-t 72:00:00" correctedErrorRate=0.085`

The final assembly is 338Mb long and quite complete (BUSCO output: C:96.7%[S:92.1%,D:4.6%],F:2.2%,M:1.1%,n:4415). However, I am a bit surprised about the continuity: I got 3,633 contigs with a N50 at 261 kb, while I had a decent amount of data from a single, haploid genome. I ran RepeatMasker quickly and got ~14% of overall repeat content, so I don't think TEs are the culprit.

I have also used wtdbg2, after four Racon iterations I got a 270Mb assembly with 3,381 contigs and a N50 of 1.2 Mb. TE content is a tad lower but similar in this assembly, around 11%.

I have aligned contigs between assemblies and have identified contig ends in the Canu assembly which appear resolved in the wtdbg2 assembly (i.e. two Canu contigs are assembled as a single contig in wtdbg2). 
Below is an IGV screenshot of such a breakpoint in the wtdbg2 assembly. The red part indicates the location of the breakpoint in the Canu assembly (in which this contig is split in two), and below are displayed raw reads aligned against the wtdbg2 assembly.

![Screenshot 2019-11-13 at 17 08 34](https://user-images.githubusercontent.com/25509901/69559199-2a825000-0fb2-11ea-98b1-87a0bea488db.png)

I should probably look at corrected reads as well (the report indicates 37.6X of corrected data), but what strikes me is that the breakpoint coincides with a stack of ~20 subreads originating from the same polymerase read (no clipping here). There are ~30 subreads which span the breakpoint itself, suggesting that the wtdbg2 assembly is correct here.   

I have seen almost a dozen cases like this one, where a single wtdbg2 contig is split in two in the Canu assembly, and which co-occurs with stacks of subreads from the same polymerase read.

As the Canu assembly is closer to the expected genome size, I would like to try tweaking parameters to try and improve the continuity in this case. However, I am a bit lost regarding where to start. I guess it lies in the assembly step, but I don't know if it is about overlap quality (`utgGraphDeviation` & `utgRepeatDeviation`) or contig splitting (`utgRepeatConfusedBP`). 

Any input would be appreciated!
And apologies if the problem was already raised, I did not find anything in the resolved issues.

**Comment by skoren** [comment]
I see a coverage drop in the middle of your figure and lots of reads that stop at the boundary. There are in contrast only a couple of reads that cross this. Are all the reads stopping on both sides really all subreads from a single read? It would be surprising that you have so many passed (over 15 by my count) and in the same location in the genome. We don't typically see this many passes in a CLR library. This seems more like a haplotype variation which canu tends to be conservative and split the assembly compared to wtdbg2 which is more aggressive. It's aggressiveness though is likely why your overall assembly is so much smaller too, it may be collapsing true repeats as haplotypes (we've seen this on genomes with whole-genome duplication).

As for stats and improving them, the N50s aren't comparable since the assemblies differ by 25%. You should measure the stats using a consistent genome size (like 340mb) in which case I expect you'll see that the wtdbg2 NG50 is more similar to canu. I wouldn't suggest tweaking parameters to try to increase continuity. If you really do have a lot of 15+ subreads from a read, you could try throwing out all but the median length one since they are effectively redundant observations of the data and re-assembling. You could also rely on scaffolding + gap filling (which arrow does) to improve the continuity. I'd also suggest running a tool like purge_dups on the canu assembly to make sure the larger genome size is not due to alternate haplotype contigs being included.

**Comment by pi3rrr3** [comment]
Hi Sergey,

Many thanks for your answer and apologies for my initial, unclear, post. Below are more information. 

> This seems more like a haplotype variation which canu tends to be conservative and split the assembly compared to wtdbg2 which is more aggressive.

The library was built from a **single haploid individual** (male Hymenoptera). A size selection step (>10kb) was performed prior to library construction. We did not use the Kingan et al. 2019 protocol ([https://doi.org/10.3390/genes10010062](https://doi.org/10.3390/genes10010062)).
As such I don't expect any haplotype variation, and don't think purge_dups would be helpful.

> As for stats and improving them, the N50s aren't comparable since the assemblies differ by 25%. You should measure the stats using a consistent genome size (like 340mb) in which case I expect you'll see that the wtdbg2 NG50 is more similar to canu. 

Absolutely, I should have mentioned that NG50 metrics are 261kb for Canu, and 598kb for wtdbg2 (assuming a genome size of 340Mb).

> Are all the reads stopping on both sides really all subreads from a single read? 

I believe so. Let's go back to the same region (breakpoint at 1 535 kb), where I have indicated in red all subreads (each is ~ 10kb long on average) I was mentioning:

![wtdbg2_canu_breakpoint_raw_corr](https://user-images.githubusercontent.com/25509901/69706747-ff5a4680-1100-11ea-88a6-a43bc99a8a4b.png)

Here are the first fields of the bam file for these 20 subreads highlighted in red, suggesting to me they come from the same read:

`
m54214_190526_013924/54526561/35201_44381	0	ctg1	1532846	60
m54214_190526_013924/54526561/71967_81166	0	ctg1	1532846	60
m54214_190526_013924/54526561/90317_99434	0	ctg1	1532846	60
m54214_190526_013924/54526561/108675_117979	0	ctg1	1532846	60
m54214_190526_013924/54526561/127252_136470	0	ctg1	1532846	60
m54214_190526_013924/54526561/164142_173343	0	ctg1	1532846	60
m54214_190526_013924/54526561/25891_35158	16	ctg1	1532846	60
m54214_190526_013924/54526561/62909_71920	16	ctg1	1532846	60
m54214_190526_013924/54526561/81211_90272	16	ctg1	1532846	60
m54214_190526_013924/54526561/99477_108630	16	ctg1	1532846	60
m54214_190526_013924/54526561/118022_127208	16	ctg1	1532846	60
m54214_190526_013924/54526561/136514_145644	16	ctg1	1532846	60
m54214_190526_013924/54526561/154903_164101	16	ctg1	1532846	60
m54214_190526_013924/54526561/53607_62866	0	ctg1	1532848	60
m54214_190526_013924/54526561/145688_154857	0	ctg1	1532849	60
m54214_190526_013924/54526561/7474_16578	16	ctg1	1532849	60
m54214_190526_013924/54526561/16628_25849	0	ctg1	1532850	60
m54214_190526_013924/54526561/44425_53562	16	ctg1	1532850	60
m54214_190526_013924/54526561/49_7432	0	ctg1	1534604	60
m54214_190526_013924/54526561/173385_178194	16	ctg1	1537248	60
`

On the left side of the IGV screenshot you can see another such stack of subreads in yellow (where each is ~ 12kb long on average).

So all these subreads (50X at breakpoint) are corrected afterwards (lower panel), which would explain the drop in coverage of corrected reads (21X at breakpoint), and in fine the split? At the lowest, in this region the coverage of corrected reads is 10X (at 1 537 kb), which seemed fine by me.

> You could also rely on scaffolding + gap filling (which arrow does) to improve the continuity.

Thanks for the suggestion! I will try that, indeed.

**Comment by skoren** [comment]
I'd still say both the raw and the corrected coverage plots look unhealthy there. The coverage shouldn't be dropping so much randomly in a normal region of the genome. It's possible this is a heterozygous region, which was my original guess, and canu would break to be conservative there. Why aren't there more of these stacked reads starting within the coverage gap? They seem common enough in the data by eye in the plot (perhaps due to the short minimum length selection). What's the overall coverage of the genome in unique regions, 50x?

You could re-assemble by first removing all but one read from a single well. Keep not just the longest but median length one. You could also try turning your data into CCS reads to see how many of them actually convert to high-quality.

**Comment by skoren** [comment]
Idle, some suggestions provided. Canu 2.0 is also less affected by heterozygosity in the genome.
