### ISSUE TITLE
mix pacbio HiFi + CLR + nanopore

### ISSUE THREAD

**Issue by mjfi2sb3** [marbl/canu#1578]
Hello,

Is there a way to use HiFi data along with CLR and ONT nanopore data to assemble a genome?

Regards,
/Salim

**Comment by skoren** [comment]
The optimal way to combine these isn't clear because the HiFi error rate is so much lower than the other two and it would separate many haplotypes the other two techs would collapse. You could make a HiFi assembly and then scaffold/gapfill it with PacBio/Nanopore. If you wanted to use Canu, I'd run correction with the CLR + ONT data together with HiFi data and then run assembly with pacbio parameters on the corrected CLR + ONT data + the original uncorrected HiFi data.

**Comment by mjfi2sb3** [comment]
Hi Sergey,

Thanks for your reply.

>  If you wanted to use Canu, I'd run correction with the CLR + ONT data together with HiFi data and then run assembly with pacbio parameters on the corrected CLR + ONT data + the original uncorrected HiFi data.

That's basically what I have attempted. I corrected the CLR data and the ONT data using Canu and then run Canu on the corrected reads + HiFi reads. I am waiting for Canu to finish to compare with the HiFi only assembly.

>You could make a HiFi assembly and then scaffold/gapfill it with PacBio/Nanopore

I thought about this too. Any tool that you can recommend?

**Comment by gringer** [comment]
Maybe [LR_Gapcloser](https://github.com/CAFS-bioinformatics/LR_Gapcloser)?

**Comment by mjfi2sb3** [comment]
Thanks for sharing, I will check it out.

**Comment by skoren** [comment]
We're thinking about how to combine these data types but  I expect this will take some time. In the meantime, if you find a recipe that worked for you post it here.

**Comment by Adamtaranto** [comment]
Has anyone found a good way to combine HiFi and ONP Ultra-long reads in the one assembly?

**Comment by PanosProv** [comment]
> Hi Sergey,
> 
> Thanks for your reply.
> 
> > If you wanted to use Canu, I'd run correction with the CLR + ONT data together with HiFi data and then run assembly with pacbio parameters on the corrected CLR + ONT data + the original uncorrected HiFi data.
> 
> That's basically what I have attempted. I corrected the CLR data and the ONT data using Canu and then run Canu on the corrected reads + HiFi reads. I am waiting for Canu to finish to compare with the HiFi only assembly.
> 
> > You could make a HiFi assembly and then scaffold/gapfill it with PacBio/Nanopore
> 
> I thought about this too. Any tool that you can recommend?

Hello,

Have you had the chance to compare the HiFi only assembly with the Canu corrected + HiFi?

**Comment by skoren** [comment]
This issue is quite outdated and is before any of our HiFi-specific assembly work. I wouldn't recommend running a mix of HiFi with any other data as it will break assumptions that help HiFi assembly. The best is likely what I originally said, scaffold/gapfill the HiFi assembly with the other datatypes. You could first assemble the ONT data and use the assembly to gap fill the HiFi (so you don't have to worry about polishing as much).

**Comment by PanosProv** [comment]
Thank you Sergey!
