### ISSUE TITLE
Adapter trimming required

### ISSUE THREAD

**Issue by ranitori** [marbl/canu#1583]
Hi,
I have bacterial genome sequence data generated using the ONT Rapid Kit on the MinION (various iterations from 2017, 2018 and early 2019). Before running an assembly on canu do I need to remove the rapid kit sequencing and other adapters (e.g. using porechop)?
Thanks.

**Comment by skoren** [comment]
It probably won't hurt to run the adapter trimming. We generally don't because Canu has a trimming step which looks for sequences with no good support across junctions. There should not be good support for genomic sequence crossing to adapter (since the fragments have random start positions) and so these are typically trimmed away.

**Comment by ranitori** [comment]
Thank you
