### ISSUE TITLE
Why are so many reads discarded before assembly

### ISSUE THREAD

**Issue by SixPlusSeven** [marbl/canu#1590]
I used canu v1.8 for my genome assembly. 
When I mapped the raw pacbio subreads to my genome.fasta, the mapping rate was 88%, but the trimmed reads' mapping rate was 99%. So as we can see, a lots of reads have been discarded by correction or trimming step. Why are so many reads discarded ? Is this normal for canu?

Thanks,
Alex

**Comment by skoren** [comment]
I assume you're talking about pacbio CLR data not hifi data? There are lots of artifacts in the raw reads, including missed adapters, chimeric sequences, and low-quality noise reads. It's not surprising that some raw reads are not mappable to the assembly due to these artifacts. Trimming removes those reads with no support from any other data. The trimmed reads would be corrected as well which would make them easier to map.
