### ISSUE TITLE
Genome duplication(2.4x) when assembling using CCS/Hifi reads

### ISSUE THREAD

**Issue by mbhall88** [marbl/canu#1624]
Moving [this](https://github.com/marbl/canu/issues/1586#issuecomment-587388733) into its own issue.
I am attempting to assemble a *Mycobacterium tuberculosis* sample (which I actually have Illumina, nanopore, and CCS for). My expected genome size is ~4.4Mb, but the assembly I get from Canu ends up with 332 contigs, and a genome size of ~10.7Mb (2.424 duplication). The Canu assembly I get from the nanopore reads is 31 contigs and a genome size ~6Mb (1.36 duplication). 
In contrast, using Flye with the CCS data I get a single contig that is very close to my expected genome size and for ONT data I get 3 contigs slightly bigger than expected genome size.

Mtb has a fairly GC-rich genome (~65%) and has some fairly repetitive regions. Given this, I also tried the assembly with Canu setting `corMaxEvidenceErate=0.15` (as [recommended in the docs](https://canu.readthedocs.io/en/latest/faq.html#my-genome-is-at-or-gc-rich-do-i-need-to-adjust-parameters-what-about-highly-repetitive-genomes)), but it didn't make any noticeable difference.

I am working off https://github.com/marbl/canu/commit/7ae7a097fab4819ab4d29bdcce0f38aa744f571c

_Originally posted by @mbhall88 in https://github.com/marbl/canu/issues/1586#issuecomment-587388733_

**Comment by mbhall88** [comment]
As requested [here](https://github.com/marbl/canu/issues/1586#issuecomment-587522049) by @skoren , this is my log file. If you also want the data, let me know and I am happy to provide that too.

[canu.log](https://github.com/marbl/canu/files/4224277/canu.log)

**Comment by skoren** [comment]
It looks like all the extra sequence is in bubbles, even if the sample is clonal, it can have rare variants at high enough multiplicity to be separated (in hifi mode, canu is sensitive down to 1 SNP every 10kbp). Flye will only be sensitive down to 2 or 3 in 100bp in contrast. The contigs total 4.7mb with a single contig comprising your chromosome at 4.4 mb, the rest may be plasmids, you can check if they're circular or they're so different they didn't get marked as bubbles. Since you're getting larger genome sizes on ONT, I expect there is at least some variability in the sample as ONT data will collapse most variation.

```
-- Found, in version 2, after consensus generation:
--   contigs:      21 sequences, total length 4753054 bp (including 3 repeats of total length 24716 bp).
--   bubbles:      311 sequences, total length 5959191 bp.
--   unassembled:  2405 sequences, total length 10571342 bp.
--
-- Contig sizes based on genome size 4.411532mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     4427553             1     4427553
--     20     4427553             1     4427553
--     30     4427553             1     4427553
--     40     4427553             1     4427553
--     50     4427553             1     4427553
--     60     4427553             1     4427553
--     70     4427553             1     4427553
--     80     4427553             1     4427553
--     90     4427553             1     4427553
--    100     4427553             1     4427553
```

You could randomly downsample your coverage to 30 or 40x, this will likely remove the bubbles or you can just ignore the entries in the fasta file which are marked as suggestBubble=yes.

**Comment by skoren** [comment]
It looks like all the extra sequence is in bubbles, even if the sample is clonal, it can have rare variants at high enough multiplicity to be separated (in hifi mode, canu is sensitive down to 1 SNP every 10kbp). Flye will only be sensitive down to 2 or 3 in 100bp in contrast. The contigs total 4.7mb with a single contig comprising your chromosome at 4.4 mb, the rest may be plasmids, you can check if they're circular or they're so different they didn't get marked as bubbles. Since you're getting larger genome sizes on ONT, I expect there is at least some variability in the sample as ONT data will collapse most variation.

```
-- Found, in version 2, after consensus generation:
--   contigs:      21 sequences, total length 4753054 bp (including 3 repeats of total length 24716 bp).
--   bubbles:      311 sequences, total length 5959191 bp.
--   unassembled:  2405 sequences, total length 10571342 bp.
--
-- Contig sizes based on genome size 4.411532mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     4427553             1     4427553
--     20     4427553             1     4427553
--     30     4427553             1     4427553
--     40     4427553             1     4427553
--     50     4427553             1     4427553
--     60     4427553             1     4427553
--     70     4427553             1     4427553
--     80     4427553             1     4427553
--     90     4427553             1     4427553
--    100     4427553             1     4427553
```

You could randomly downsample your coverage to 30 or 40x, this will likely remove the bubbles or you can just ignore the entries in the fasta file which are marked as suggestBubble=yes.

**Comment by mbhall88** [comment]
Thank you for the thorough support @skoren - I really appreciate it.

Mtb doesn't have any plasmids. However, it has a repertoire of genes call [PE/PPE](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-2467-y):
> Approximately 10 % of the Mycobacterium tuberculosis genome is made up of two families of genes that are poorly characterized due to their high GC content and highly repetitive nature. The PE and PPE families are typified by their highly conserved N-terminal domains that incorporate proline-glutamate (PE) and proline-proline-glutamate (PPE) signature motifs. They are hypothesised to be important virulence factors involved with host-pathogen interactions, but their high genetic variability and complexity of analysis means they are typically disregarded in genome studies.

Some of these genes are very similar so I wonder if maybe they are contributing to this somehow.

I will try rerunning with the suggestedBubbles parameter you suggested. :pray:

**Comment by skoren** [comment]
The bubbles isn't a parameter, it is already annotated in your contigs.fasta file, just look for it in the header line and skip that contig if it is a bubble so no need to re-run.

If you do re-run, you can try randomly downsampling to 30-40x (just take the first few reads from the fastq file) which I expect might help some of these too, this will be the default coverage used soon.
