### ISSUE TITLE
Very Low Coverage Assembly

### ISSUE THREAD

**Issue by chocotwig** [marbl/canu#1630]
Hi, 
I am seeking to perform assembly of very low coverage long nanopore reads. Robustness of assembly is not critical; I am happy with a contig N50 that is ~3-4x of my read N50. I am only looking to see how the reads stack up on one another, so I can get a sense of what the genome looks like.

What options do you recommend?
My genome coverage is ~4x.
Options I Use:
 genomeSize=0.4m \
 stopOnLowCoverage=0 \
 correctedErrorRate=0.170 \
 corMinCoverage=0 \
 contigFilter="2 0 1.0 0.5 0" \

Using canu v1.9

Thanks!

**Comment by skoren** [comment]
Those options seem reasonable but at 4x coverage you're likely not going to get most of your genome represented at all in the assembly. So not only would the contigs be short, they would comprise maybe 25-50% of the genome. Likely, you'll only get the most common repeats assembled and it may run slower because it has to be more sensitive to find more overlaps.
