### ISSUE TITLE
consensus failed with error expected BLOB, got 80 42 17 f8 '<80>B^Wø'

### ISSUE THREAD

**Issue by yaohuFCS** [marbl/canu#1634]
I have been using canu-1.8 release version to run a very large genome about 30G, after months , when it come to consensus , it failed with such error:
```
Index error in read 151055017 mSegm 0 mByte 2967525280 mPart 2 expected BLOB, got 80 42 17 f8 '<80>B^Wø'
utgcns: stores/sqStore.C:447: void sqReadData::sqReadData_loadFromBlob(uint8*): Assertion `blob[0] == 'B'' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/sqStore.C::447 in _ZN10sqReadData23sqReadData_loadFromBlobEPh()
utgcns/libcns/abAbacus-addRead.C::145 in _ZN8abAbacus7addReadEP7sqStorejjjbPSt3mapIjP6sqReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10sqReadDataS6_SaIS7_IS8_SE_EEE()
utgcns/libcns/unitigConsensus.C::1011 in _ZN15unitigConsensus10initializeEPSt3mapIjP6sqReadSt4lessIjESaISt4pairIKjS2_EEEPS0_IjP10sqReadDataS4_SaIS5_IS6_SC_EEE()
utgcns/libcns/unitigConsensus.C::779 in _ZN15unitigConsensus13generatePBDAGEP5tgTigcPSt3mapIjP6sqReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10sqReadDataS6_SaIS7_IS8_SE_EEE()
utgcns/utgcns.C::522 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted
```
Seems like it is the utgStore or ctgStore is corrupted, I removed 4-unitigger, utgStore, ctgStore to go from last step again, but the error still exists, how could I solve this problem? Thanks in advance

**Comment by skoren** [comment]
The corruption is in the sequence store, not in the utg/ctg stores. Does this happen for all jobs for consensus or just one? It may be possible to re-build the seqStore but I'm not sure how/why it was corrupted in the first place. 

Are you able to share the data (we'd need the trimmed reads, seqStore, and utg/ctg store, depending on which is failing). The FAQ has instructions to send the data.

**Comment by yaohuFCS** [comment]
Thanks @skoren, the consensus jobs all failed except the last two which is a small partition, I have checked the seqStore files and the directory is not touched since months ago, I am sorry but the data is just two large to share(several TB). Is it possible that the genome is too large ? maybe I can set cnsPartition to a large number, would this help?

**Comment by yaohuFCS** [comment]
And also I traced the code and found the _blobData which is corrupted was read from the partitionReads.seqStore.

**Comment by skoren** [comment]
The partitionedReads.seqStore is created from the original seqStore but resides within the ctg and tug stores so if you removed those before the restart it should have been re-created. Looking at the code, it is possible the partition files are too big causing an error.

You could try running the consensus script w/o the partitions. Edit the consensus.sh script to point to the full seqStore rather than the partitionedReads store. This will mean more I/O and slower jobs but might run if there's an issue partitioning the data.

**Comment by yaohuFCS** [comment]
You mean all the cns jobs use the full seqStore in the same time?  Thanks, I will have a try !

**Comment by skoren** [comment]
Yes but I'd start by testing it on one partition. You may not be able to run all partitions at once this way, depending on your filesystem.

**Comment by yaohuFCS** [comment]
```
Running job 1 based on command line options.
-- Opening seqStore '../../YS.seqStore' partition 1.
Failed to open '../../YS.seqStore/partitions/map' for reading: No such file or directory
```
seems utgcns still think i am using a partitioned store, did I miss some parameter?

**Comment by brianwalenz** [comment]
When using the whole seqStore at once, each job will make random accesses to retrieve read data.  This puts a large load on your file system.  On my small development cluster, with correspondingly small file system, I can get 10-15 jobs running this way before all my time is spent waiting for the file system to return data.

Any partition file larger than 4 GB will be 'corrupt' this way.  The fix is to increase the number of partitions.   Try setting cnsPartitions equal to the number of 'blobs' files in the store.  Before restarting, remove the 'partitionedReads.seqStore' files and directories from inside both the `ctgStore` and `utgStore`.

If you're paranoid (I suggest it), remove write permissions from the seqStore and ovlStore directories, and make a backup of the ctgStore and utgStore directories (after removing the partitionedReads directories/files).

**Comment by brianwalenz** [comment]
Yes, to run without partitions, there is a slight change needed to tell it to not use partitions.  In the utgcns command, change `-T blah.ctgStore 1 $jobid` to `-T blah.ctgStore 1 .`.  (a single dot instead of a number supplied by a variable)

**Comment by yaohuFCS** [comment]
> Yes, to run without partitions, there is a slight change needed to tell it to not use partitions. In the utgcns command, change `-T blah.ctgStore 1 $jobid` to `-T blah.ctgStore 1 .`. (a single dot instead of a number supplied by a variable)

by this way there would be only one cns job? how could I tell the difference between different jobs?

**Comment by yaohuFCS** [comment]
> When using the whole seqStore at once, each job will make random accesses to retrieve read data. This puts a large load on your file system. On my small development cluster, with correspondingly small file system, I can get 10-15 jobs running this way before all my time is spent waiting for the file system to return data.
> 
> Any partition file larger than 4 GB will be 'corrupt' this way. The fix is to increase the number of partitions. Try setting cnsPartitions equal to the number of 'blobs' files in the store. Before restarting, remove the 'partitionedReads.seqStore' files and directories from inside both the `ctgStore` and `utgStore`.
> 
> If you're paranoid (I suggest it), remove write permissions from the seqStore and ovlStore directories, and make a backup of the ctgStore and utgStore directories (after removing the partitionedReads directories/files).

I checked the partition files to found that except the last partition, all the blobs file are larger than 4GB, I guess this is the cause then, I will change cnsPartition and have a try, thanks !

**Comment by brianwalenz** [comment]
Yup, that's the answer.

(for the record: sadly, it can't do what we want to do.  Consensus can be computed in multiple jobs only if the reads are partitioned.  The assignement of 'tig to job' is stored (implicitly) in partitionedReads.seqStore.  So without that, all it can do is compute consensus for every tig in one job.)

**Comment by yaohuFCS** [comment]
@skoren @brianwalenz Thanks for the help, after increase cnsPartition, it worked, but I am still curious why is there a 4G constraint, I have been reading the code, could you point me where is the trick?

**Comment by brianwalenz** [comment]
It's a long story.  The gist is that to keep read metadata size small (it's stored in-memory) we set "reasonable" limits on various indices (which file a read is in, the position in that file, etc).  Since then, genomes got bigger, contigs got bigger, reads got longer, coverage got higher...all of which resulted in more data per contig, which (silently!) exceeded the limits.

The limit is implicitly set by the type of _mByte at the end of src/stores/sqRead.H.  However, the store was heavily modified in the v1.9 release, which removed the limit.  Well, effectively removed the limit; it's now 1 TB per file.

**Comment by yaohuFCS** [comment]
I see, we will change to v1.9 soon.  Btw, we have finished the whole pipeline after the cnsPartition increase, thanks again for your help!
