### ISSUE TITLE
splitting apart collapsed regions

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#1635]
Hello,
I am dealing with a heterozygous plant genome assembly (2.5 Gb haploid size, ONT reads assembled with Flye to 3.7 Gb) that has ~400 Mb of contigs at 2x coverage as the others.
Being these contigs candidates for being collapsed paralogous/allelic sequences or homozygous regions, I would like to reassemble them locally to try to recover both variants in separate contigs.

I see that the settings for polyploid genomes are helping a bit (we get about 140% of the initial contig length), while default Canu or the --meta option are not giving much increase in sequence length.
Is it worth trying to tweak some of the settings to try to be more stringent in the overlap step?
`corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"`
Which ones would you work on? What do dg, db, dr, ca, and cp stand for?
Thanks,
Dario

**Comment by skoren** [comment]
The fundamental issue with resolving the alleles is that the nanopore data noise overwhelms the true signal from the alleles. The dg/db/dr control the deviation away from median that are used to set an error rate, lower deviation tolerates less errors in the overlaps and can separate some alleles (or shatter your assembly if you exclude useful overlaps). The ca/cp control the aggressiveness of repeat splitting, I wouldn't adjust those. I don't expect you're not going to get below 1-2% divergence with parameter tweaks. 

If you're not already, I suggest using Canu 1.9 and the latest nanopore basecaller to reduce the noise. Other than that, your best option is probably to try to identify variants within the contigs by read mapping and try to bin the reads before assembly by allele rather than trying to get the assembly to separate them.

**Comment by skoren** [comment]
Idle, answered.
