### ISSUE TITLE
file size is very low

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#1637]
Hi,
My ONT nanopore raw data file size is 8.8 GB and correction the file size is 451 MB and after trimming, the file size is 206 MB only.

Expected plant mitochondrial genome size is 1.24 MB (calculated with Illumina pair-end reads using BBMap tools)

I have used the following commands:
Correction:
$./canu -correct -p ont-mt -d plant-mt genomeSize=1.24m -nanopore-raw ./plant-ONT.fastq.gz

Trimming:

$./canu -correct -p Plant -d plant-mt genomeSize=1.24m -nanopore-corrected ./plant-mt/ont-mt-correctedReads.fasta.gz

I would like to know why the file is very small? 

Thank you.

**Comment by skoren** [comment]
What exactly is your input data, the full genome or selected reads for just the mitochondria? As the FAQ says (https://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak), by default canu will only try to correct the longest 40x of data for your genome. Since you specified 1.2mb as the genome, 40x of that is much smaller than your full input of 10gb. Thus the decrease in size. If you are giving all the reads for the genome, you should set the genome size to the full genome size not 1.2mb.

**Comment by bioramg** [comment]
Hi, 
Thank you for your suggestion.
I have submitted full raw read data (8.8 GB) for correction and trimming. 

I don't know my mitochondrial genome size. So, I used pair-end Illumina data and submitted to bbmap tools and suggested that the expected genome size is ~1.24mb. 

If I do not know genome size, can I run this program?

Please suggest to me. 
Thank you.
