### ISSUE TITLE
One of my read is too long for canu

### ISSUE THREAD

**Issue by eugenio** [marbl/canu#164]
the output of the command : 

`canu  -p sd0178 -d sd0178-auto  genomeSize=4.9m -pacbio-raw SD0178_01_a_contigs.fastq
`

```
-- Finished on Wed Jun 15 13:58:47 2016 (lickety-split) with 128.5 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
Gatekeeper detected problems in your input reads.  Please review the logging in files:
  /home/okamotolab/Documents/alkaliphilic_eet_microbe/SD0178/sd0178-auto/correction/sd0178.gkpStore.err
  /home/okamotolab/Documents/alkaliphilic_eet_microbe/SD0178/sd0178-auto/correction/sd0178.gkpStore.errorLog
```

content of 
`/home/okamotolab/Documents/alkaliphilic_eet_microbe/SD0178/sd0178-auto/correction/sd0178.gkpStore.BUILDING/errorLog` 

:

`read 'unitig_0|quiver' is too long; contains 6456813 bases, but we can only handle 2097151.
`

content of 

`/home/okamotolab/Documents/alkaliphilic_eet_microbe/SD0178/sd0178-auto/correction/sd0178.gkpStore.BUILDING.err `

: 

```
Starting file '/home/okamotolab/Documents/alkaliphilic_eet_microbe/SD0178/sd0178-auto/correction/sd0178.gkpStore.gkp'.

  Loading reads from '/home/okamotolab/Documents/alkaliphilic_eet_microbe/SD0178/SD0178_01_a_contigs.fastq'
    Processed 15 lines.
    Loaded 2451846 bp from:
      3 FASTQ format reads (2451846 bp).
    WARNING: 1 reads issued a warning.

Finished with:
  1 warnings (bad base or qv, too short, too long)

Loaded into store:
  2451846 bp.
  3 reads.

Skipped (too short):
  0 bp (0.0000%).
  0 reads (0.0000%).


gatekeeperCreate did NOT finish successfully; too many warnings.  Check your reads.
```

please help me to solve this problem, i checked various pages and serched on gooogle but with no luck....

**Comment by brianwalenz** [comment]
As the error states, there is a limit of 2Mbp on input reads.  You can increase this to 8Mbp by changing AS_MAX_READLEN_BITS from 21 to 23 in file src/stores/gkStore.H.  But this hasn't been tested.

Shredding the contigs to 1Mbp chunks at perfect 2x coverage - so a 500k overlap to the next shred - would work probably just as well.  It's pretty hard to get confused with 500k overlaps.

You probably want to be using -pacbio-corrected instead of -pacbio-raw.  The latter will do an error correction step, and probably do the wrong thing.

Why are you assembling contigs, anyway?

**Comment by eugenio** [comment]
I need to circularize the genome to send it to annotation software, and I thought I needed to assembly it first....
