### ISSUE TITLE
No output even after canu finishes without any error

### ISSUE THREAD

**Issue by BlueGirl15** [marbl/canu#1642]
Hi, I am using canu 1.9 I ran this command:
canu -trim -p K07G -d K07G_canu1 genomeSize=9m -pacbio-corrected filtered_subreads.fastq

However, even after the canu.out says it finished off without any issues, I cannot see trimmed.gz file. It happens also after I run the following command, after which I cannot see the assembled contig file. 
canu -assemble -p K07G -d K07G_canu1 genomeSize=9m -pacbio-corrected filtered_subreads.fastq
I however see no error message but only the message that it finished off. I am running it on slurm. What would be the issue?

**Comment by skoren** [comment]
When Canu runs on the grid, the initial command will submit jobs to the grid and exit (see https://canu.readthedocs.io/en/latest/tutorial.html#execution-configuration). You have to check the slurm job scheduler to see the status of the run after that (or the logs in K07G_canu1/canu-scripts).

If you've launched the same canu more than once, I'd suggest killing all your slurm jobs and removing the work folder as otherwise you mixing multiple runs in one folder will lead to errors. You also shouldn't be providing the original filtered_subreads.fastq as corrected reads, they should go in as -pacbio-raw reads to be corrected first (-correct or just canu as the default will run all three steps for you).
