### ISSUE TITLE
CANU 1.9 disk space

### ISSUE THREAD

**Issue by cement-head** [marbl/canu#1643]
Running CANU 1.9 on a PBS-Torque GRID.

Everything is running along swimmingly with _**one**_ exception; we are already at 12 TB disk storage space and we will likely run out of space.

I see here from [Issue#1588](https://github.com/marbl/canu/issues/1588) that there are a couple of options:

1. Begin by remove the 1-overlapper/blocks folder.
2. As long as a bucketizing step completed (it has a bucket folder and there is no error about being out of space like above in the file), you can remove the corresponding ovb file.

QUESTION:

Can I stop the run, and re-start it with the `purgeOverlaps=aggressive` parameter?  Or do I have to start from the beginning?

Thanks

**Comment by cement-head** [comment]
*BUMP*

**Comment by skoren** [comment]
Not clear from your description what step you're actually on right now. What step is canu on? What is using most of your disk space in the correction folder?

If you haven't started store building then yes, you can re-start with pugeOverlaps=agressive, you could also add the staging options (see https://canu.readthedocs.io/en/latest/parameter-reference.html#file-staging) if you have local scratch space on nodes. This reduces disk usage as large intermediate files are only written locally and discarded.

**Comment by cement-head** [comment]
We are at:
./mhap.sh 168 > ./mhap.000168.out 2>&1

**Comment by skoren** [comment]
Do you know how many partitions it has? None of the purgeOverlaps or the cleanup settings apply to this step as it is not yet building overlaps. Given the partitions done and remaining and the space you have left, you can see if it the compute will fit or not. If it will not, take a look at the FAQ for adjusting parameters to save space.

**Comment by cement-head** [comment]
When you say "partitions", what do you mean, and how would I check that?  And if I wanted to adjust parameters for a highly repetitive genome, would I have to start again, from the beginning?

And would the command be something like:

canu -p wfop -d wfgenomeJM genomeSize=6g -nanopore-raw wf-ont.fastq -pacbio-raw wf-pbs2.fastq corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 purgeOverlaps=aggressive useGrid=remote

**Comment by cement-head** [comment]
In other words, in order to reduce the disk usage for a repetitive geneome (we're on track to use at least 25 TB), would one have to re-start the whole process? with the above recommended command?

**Comment by skoren** [comment]
I didn't realize you have such a large genome, how much input coverage do you have? 

Re partitions, there should be a file in the correction/1-overlapper folder named partitioning.log which says how many jobs will be run. In order to reduce the disk usage in the initial overlap computation step, yes you'd need to re-start from scratch. I'm not sure how many mhap jobs you're running in parallel at the same time but they generate intermediate files that are compressed at the end of a run. So the space usage is larger than it will be at the end.

I think you'll likely need a good bit of space to assemble the genome given the size (and I assume repetitiveness). You can estimate the total size needed by looking at the files you have generated so far (correction/1-overlapper/results) and see what fraction of mhap jobs have completed and use that to compute space. The final store building will require up to 2-fold more than this, that should give you a final estimate.

**Comment by cement-head** [comment]
We didn't either ;-)

We think it's 6.0ish Gbp and it's a diploid frog, so likely there's quite a bit of repetitive regions. 

We have about 30x coverage with very long PBSII reads and some 5x coverage with long/ultra-long ONT reads.

**Comment by skoren** [comment]
I'd just provide all data as raw pacbio (no -nanopore-raw), with an increased corrected error rate (```correctedErrorRate=0.105```) along with the adjusted parameters above to reduce space.

**Comment by cement-head** [comment]
So you wouldn't use the ONT data, or you wouldn't tell CANU that there is ONT data?

**Comment by skoren** [comment]
I wouldn't tell Canu there is ONT data.

**Comment by skoren** [comment]
Idle
