### ISSUE TITLE
What does changing the MhapSensitivity parameter do in practice?

### ISSUE THREAD

**Issue by bio-GNOSNUG** [marbl/canu#1648]
Hi, 

I've been running some test assemblies changing different global parameters as part of an undergraduate project. Unfortunately in your literature and in the Berlin K et al. (2015) paper describing MHAP I have been unable to find information on what altering the MhapSensitivity parameter changes in practice? I had assumed that it might change the size of the k-mer sketch used, however I see that this is also controlled by MhapMerSize? 

It is entirely possible that I may have missed something, any help or guidance would be greatly appreciated!

**Comment by brianwalenz** [comment]
mhapSensitivity is processed at https://github.com/marbl/canu/blob/master/src/pipelines/canu/OverlapMhap.pm#L120.  Just above there are default settings for mhapSensitivity based on read coverage.  These values are then passed to mhap at https://github.com/marbl/canu/blob/master/src/pipelines/canu/OverlapMhap.pm#L367.

I'm not terribly familiar with how mhap works, so that's all I can say.

What data are you using for the test assemblies?

**Comment by bio-GNOSNUG** [comment]
Thank you! That's really helpful! 

I used simulated Nanopore reads generated by BadRead at 20X from a reference of Leishmania infantum, then compared test assemblies back to this reference. Due to limited time, I haven't been able to test parameters using whole genome assemblies so made a 'pseudo-genome' reference of 4 contigs that held chr1, 7, 32 and 35 sequences. It seems this wasn't challenging enough for canu.

**Comment by skoren** [comment]
In practice, the mhap sensitivity changes the size of the sketch and the tolerance for how many hash values from the sketch have to match before a pair of reads are evaluated in more detail. There are also some changes to the secondary comparison parameters but the main changes are the two I listed above.
