### ISSUE TITLE
Produced no assembly - failed. 

### ISSUE THREAD

**Issue by raw937** [marbl/canu#1679]
canu -version
Canu 1.9

Finished on Tue Apr  7 02:29:34 2020 (6 seconds) with 5288.368 GB free disk space

segments   memory batches

01 15.50 GB       1
02 15.00 GB       1
04 14.50 GB       1
06 14.00 GB       1
08 14.00 GB       1
12 13.50 GB       1
16 13.50 GB       1
20 13.00 GB       1
24 12.01 GB       1
32  8.02 GB       1
40  8.00 GB       1
48  7.00 GB       1
56  6.00 GB       1
64  5.00 GB       1
96  3.50 GB       1

For 7259892 reads with 146002442451 bases, limit to 1460 batches.
Will count kmers using 01 jobs, each using 17 GB and 4 threads.

Report changed.
Finished stage 'merylConfigure', reset canuIteration.
No change in report.

Running jobs.  First attempt out of 2.

'meryl-count.jobSubmit-01.sh' -> job 16559720 task 1.

Starting command on Tue Apr  7 02:29:34 2020 with 5288.368 GB free disk space

    cd /data/friesen/UAri/ftp/Trifolium-1_microcephalum_40pM/micro
    sbatch \
      --depend=afterany:16559720 \
      --cpus-per-task=1 \
      --mem-per-cpu=4g   \
      -D `pwd` \
      -J 'canu_micro' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh

Finished on Tue Apr  7 02:29:34 2020 (in the blink of an eye) with 5288.368 GB free disk space

DONT UNDERSTAND WHY IT DIDN'T produce an assembly!
I can give it a ton more memory.

**Comment by skoren** [comment]
This is the correct behavior, see the documentation: https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-support. 

It is likely still running, you can see the jobs in your grid queue. However, if you've run the same command multiple times you may have ended up creating conflicting jobs. I'd suggest removing your run folder, making sure you have no Canu jobs pending in the slurm queue, and re-running the initial command. You can monitor the job your your grid scheduler.

**Comment by raw937** [comment]
um. So, I have different file names on different data with different folders. All failed. I have ran it multiple times. similar results. I can ran one Canu job at a time? In my queue? whaa?

**Comment by skoren** [comment]
I'm not sure what you mean by "all failed". The initial run you posted did not fail, it was in fact still running. If it failed, there would be an error reported in the canu.out log file.

You can run any number of assemblies with different prefixes/folders at the same time. What you cannot do is run the same command while it is still in your queue (with the same -p and -d options). So if you originally ran, say ```canu -p asm -d asm -pacbio-raw data.fasta.gz``` and it exited as in your log since it submitted itself to the grid. If you thought it didn't produce an assembly and ran ```canu -p asm -d asm -pacbio-raw data.fasta.gz``` again, you would end up with two assemblies running with the same input and the same folder, which is bad. That's why I suggested making sure you don't have active jobs so you don't accidentally collide. 

If you don't want Canu to use your grid and just run on the single node you've launched it on, add useGrid=false to your command. It will be slower since it'll use less resources.

**Comment by raw937** [comment]
Sorry mate. I didn't post the canu.out. It failed. I will try it without the grid and see if that works. I don't think the grid will work on my system. 
Thanks for understanding. 
If it doesn't finish. I will post the correct stuff so you can help me debug. 
What do you recommend to polish a draft? Once I get it from Canu to improve the assembly.
