### ISSUE TITLE
Can anyone explain -dove and -cont in read category literally?

### ISSUE THREAD

**Issue by ZhichaoXu** [marbl/canu#168]
Sorry I'm not a native speaker so I cannot understand what -dove and -cont means literally. Especially, what's the difference between repeat-cont and repeat-dove reads? What's the difference between uniq-repeat-cont and uniq-repeat-dove	reads? Why are they hard to assemble or lead to mis-assemblies? 
I tried to read the [MHAP paper](http://www.nature.com/nbt/journal/v33/n6/pdf/nbt.3238.pdf) and canu manual again but didn't find the answer.

**Comment by brianwalenz** [comment]
A decent question.

'Dove' and 'cont' refer to overlap types.  'Dove' is short for dovetail, where the ends of reads align fully.  'Cont' is short for 'contained', where a read aligns fully within some other read.

```
-----====----
     ||||
     ====--------
Partial overlap

-------======
       ||||||
       ======------
Full overlap (dovetail)

-----========----
     ||||||||
     ========
Full overlap (contain)
```

For trimming, all three types are computed.  For assembly, only the dovetail and contain type are computed.  The stats presented in correction/ and trimming/ are somewhat misleading because of this.

This report is trying to assign each read to a category based on the coverage presented in overlaps.  The uniq-repeat category contains reads that have regions at expected coverage (and so look like they should be uniquely placed) but also regions at higher than expected coverage (indicating a repeat).

uniq-repeat-cont reads are fully contained in some other read.  These could potentially be spanning a short repeat.  Since they are contained, they aren't used to form the initial contigs.  The unique portion probably means they will be placed correctly and won't contribute to consensus errors.

uniq-repeat-dove reads are not fully contained in some other read.  These will be used to form initial contigs.  If the repetitive portion is at the end of the read, it is possible the read will cause a contig to end (because there is no clear path to follow).

These 'analysis' results are all based on intuition.  We've never analyzed a final assembly to verify either the classification or the result.

**Comment by ZhichaoXu** [comment]
Thank you brianwalenz, I can understand -dove and -cont now. I have another follow-up question.

As you explained in the 'contain' type:
> - - - ======== - - - -
>        | | | | | | | | |
>        ========
> Full overlap (contain)
If the upper read is a repeat-cont one and bottom one is a repeat read, are those flanking sequences of the upper read unique? If yes, how do you make a distinction between a repeat-cont and a span-repeat read? I guess observed coverage might be one sign. But except for coverage, are there any more aspects? Especially, how long enough should the flanking sequences be to make a read as span-repeat one?

**Comment by brianwalenz** [comment]
At this stage, they're all based on coverage.  There isn't any inherent minimum size of the flanking sequence.

Each read is analyzed in isolation.  For the bottom read, all it will know is that its coverage is more than expected.  For the top read, it will know that there is a portion in the middle of the read at higher than expected coverage, and that the ends are not at higher than expected coverage.

I'm flagging this as a bug because:

1. it is always using 9x to 51x as it's 'normal' coverage level.
2. it probably should enforce some minimum flanking size.

The results of this analysis are only consumed by humans, so neither is really a huge problem.  It was intended to be a quick peek at the overlaps generated, in particular, if there are trimming issues with the reads.

**Comment by ZhichaoXu** [comment]
Thank you brianwalenz, I think we can close this issue.
