### ISSUE TITLE
Could you please help me to check my script for quiver correct? 

### ISSUE THREAD

**Issue by yuanyuan12543** [marbl/canu#1684]
Hi, this is my first time to use quiver to polish my genome, could you please help me to check if my script shown below correct? 
#!/bin/sh
#SBATCH --account=austin
#SBATCH --qos=austin-b
#SBATCH --job-name=junli_quiver
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=zjl1983@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=96:00:00
#SBATCH --output=junli_quiver_%j.out
#SBATCH --error=errCanu_quiver_%j.err
pwd; hostname; date

module load genomicconsensus/2.3.3

quiver m64019_191028_232701.subreads.bam, m64019_191107_090935.subreads.bam -r Mercenaria.assemble.contigs.fasta -o Mercenaria.variants.gff -o Mercenaria.consensus.fasta -o Mercenaria.consensus.fastq 

Thanks!

**Comment by skoren** [comment]
We're not the authors of quiver so this isn't the right place to ask. Quiver has also been deprecated in favor of arrow so you probably want to be using that. Looking at the command, I'm also not sure it supports multiple bam files, I believe they all have to be merged into one. If you have issues running arrow/quiver I suggest contacting PacBio directly since they maintain that softaare.
