### ISSUE TITLE
Making scaffold - Reg.

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#1702]
Hi,
I have used the following commands:
./canu -p ont -d canu genomeSize=1.7g -nanopore-raw ont.fastq.gz batMemory=188

I assembled plant whole genome nanopore sequencing and obtained ~3000 contigs and the longest contig size is 242 Kb.  But, I already had contigs (the longest scaffold is ~500 Kb) which is generated by hybrid assembly of both Illumina and nanopore using spades. Also, I mapped both assembler contigs with reference mitochondrial genes and few contigs contain those genes.  I am having more than ~25 contigs which are having mitochondrial genes. When I tried to make scaffold with ONT contigs, none of the contigs are similar to spades contigs or did not generate scaffold. So, how to improve my assembly and how to make a scaffold? 
Thank you.

**Comment by skoren** [comment]
I don't know what you're asking, or what "make scaffold with ONT contigs" means. Mitochondrial genes aren't restricted to the mitochondria and can occur on the chromosome in NUMT so that may be what you're seeing. It may also be that the mitochondria is very high coverage so multiple contigs represent the variation in the sequenced mitochondria. 

Canu doesn't make scaffolds so there is no way to make scaffolds from just the ONT data. You can scaffold using some other data type like HiC or bionano or 10X, etc. As for improving the assembly, that depends on your data quality and coverage, you can look at the FAQ for some suggested parameters (https://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it). However, given that the max sizes from your assembly are so short, I think you probably have data that is too short/low coverage to assemble well.

**Comment by bioramg** [comment]
Thank you for your suggestion.
I assembled ONT reads with canu but the generated contigs are not similar to spades contigs (Used hybrid assembly with Illumina and ONT). But both contigs are encoded the same set of genes. Also, the total genome size of the plant is 1.7 GB only (nuclear genome size). So, I have given that parameter. My question is that how do I get high-quality contigs/similar like spades contigs.

**Comment by skoren** [comment]
A hybrid assembly will have higher sequence identity than a nanopore assembly without any illumina data. You'd have to polish it to improve base accuracy. Is that what you mean by not similar?

With other details like what your read distribution looks like/how much coverage you had/what base caller you are using/etc and the report from the canu run I don't have anything else to suggest.

**Comment by bioramg** [comment]
Ok thank you for your valuable suggestion.
