### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by davidaray** [marbl/canu#1703]
Canu commands
CANU_PATH=/lustre/work/daray/software/canu-1.8/Linux-amd64/bin

#Export path
export PATH=$PATH:$CANU_PATH:

export CANU_UGE_OPTIONS=( "useGrid=true" "gridEngineThreadsOption=-pe sm THREADS" "gridEngineMemoryOption=-l h_vmem=MEMORY" "gridOptions=-P xlquanah" ) 

#Run Canu, genome size was set up to 3.3GB
canu -d . -p geomys genomeSize=3.3g -nanopore-raw raw_pacbio/*.fastq "${CANU_UGE_OPTIONS[@]}" 

My job has been running for several weeks now. Part of the problem I know is the fact that our cluster has two queues. One has a two day walltime and this doesn't appear to be enough for some subjobs. Thus, I've had to switch to a second queue with a 5 day wall time but fewer processors.

I thought those jobs were finishing but after inspecting the .out files, I'm seeing the following error in many of them:
loadFromFile()-- After loading 11564 out of 23268 'sqStore::sqStore_loadDataFromFile::blob' objects (1 bytes each): Input/output error

This is occurring during overlap jobs. Ex. overlap.82.out.

I can't find any instances of this using a google search. 

How  big of a problem is this and is there something I can do about it?

Thanks

**Comment by skoren** [comment]
This looks like your filesystem is having issues reading from disk. The errors will kill whatever job reported them but Canu is tolerant of intermitted grid/machine failures. So if there aren't too many jobs that report those, they'll just re-run and hopefully not fail again. If too many fail Canu will stop. So not a big worry until canu stops because too many jobs fail. If too many jobs fail, you'll likely have to consult with your IT and perhaps limit the number of concurrent jobs you are running.

**Comment by skoren** [comment]
Idle
