### ISSUE TITLE
HiCanu "Excessive Coverage Detected"

### ISSUE THREAD

**Issue by Sea-bar** [marbl/canu#1707]
Hello,
I'm using HiCanu on Canu2.0. I have 9 million Hifi reads representing 90x coverage. We are attempting a haplotype-resolved assembly on a high-ploidy genome. However, Canu is downsampling the data to 50x coverage prior to assembly. Would you kindly explain the rationale for this, and if this can be avoided? 

For the assembly I am using (batOptions="-dg 3 -db 3 -dr 1 -ca 500 -cp 50"). If you have any other advice I would appreciate it.

Thank you.

**Comment by skoren** [comment]
We typically only have 30-40x coverage of a HiFi dataset. This is sufficient to assemble both haplotypes since the HiFi data needs less coverage per haplotype than regular sequencing. When you have very high coverage, the errors can confirm each other which limits the correction of the reads and thus the ability to resolve repeats. You can remove this limit by setting maxInputCoverage=100 (or something higher than your input). I'd suggest running assemblies both ways, with the defaults and using all data though.

Lastly, I would not provide any bat options, the defaults are tuned for HiFi already and pretty much any genome is going to get separated into two haplotypes (even at human-level diversity) so you don't need any tweaked parameters.

**Comment by Sea-bar** [comment]
Thank you!

**Comment by trn30** [comment]
Good morning, I am making assemblies with HiFi reads and I can't find if indeed the downsampling is being done on my data. I am using version 2.2 and in the output called .seqStore.sh the parameter -coverage is set to 200 and indeed in the .seqStore.err appears the filtering of coverage to 200 but I can't find the filtering to 50X that you are talking about. where can I see the amount of reads remaining after the downsampling to 50X. 

Thank you.

**Comment by skoren** [comment]
There is a bug in the release which only downsamples to 200 not 50x. There's no downsampling past what's done in seqStore. You can randomly downsample before running canu or add maxInputCoverage=50 to your parameters to make it only use 50x.
