### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by raw937** [marbl/canu#1710]
canu -version
Canu 1.9

Command
canu -p micro -d micro genomeSize=500m -pacbio-raw m64041_191111_034310_subreads.fastq.gz

Main error
sh: ./logs/1-bucketize.000136.out: No space left on device

I can't get canu to produce an assembly after a month of trying. I want to use it. I just don't understand why it keeps failing.

**Comment by skoren** [comment]
The error message is that you have run out of space (either quota or actual disk) so that's why it is failing. You can look at the FAQ for parameters to reduce space usage along with some rough guidance on how much space you need to run. There are some suggestions in other issues on intermediate files you can clean up (e.g. #1681). The short answer is you need more space though.

**Comment by raw937** [comment]
wow, okay that is a different issue. Thank you. Most appreciated.

**Comment by skoren** [comment]
Idle
