### ISSUE TITLE
High amount of duplication after purge_dups

### ISSUE THREAD

**Issue by proteinosome** [marbl/canu#1731]
Hi, 

I have recently tried to assemble the human pangenome data freeze HG002 HiFi data set. I assembled all four 15kb libraries of PacBio HiFi  (https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA586863) for HG002 with this command:
`canu -assemble -p hifi_15kb_4cells_34X_hicanu -d hifi_15kb_4cells_34X_hicanu genomeSize=3.1g -pacbio-hifi \
SRR10382246.fastq.gz \
SRR10382247.fastq.gz \
SRR10382248.fastq.gz \
SRR10382249.fastq.gz`

After that, I ran purge_dup by first generating the config
`python ~/softwares/purge_dups/scripts/pd_config.py hifi_15kb_4cells_34X_hicanu/hifi_15kb_4cells_34X_hicanu.contigs.fasta fastq_list_15kb_4cells.fofn -n purge_dups_config -l purge_dups_output`
Then, I added `-x asm20` to the `mnmp_opt` in the config file and ran the pipeline with the following:
`python ~/softwares/purge_dups/scripts/run_purge_dups.py -p bash \
  $(pwd)/purge_dups_config \
  ~softwares/purge_dups/src \
  hg002_hicanu`

The final assembly stats from the purged haplotype:
2082 contigs
3.61 Gb total assembly size
59 Mbp NG50
24.5 Mbp NGA50 and 40 LGA50
BUSCO complete (Mammalia ODB10) is 79% single copy, 9.7% duplicated copy

It appears that the contiguity stats are perfectly fine, but the genome duplication rate is high even after running purge_dups (Larger than expected haploid assembly size and high BUSCO duplication). Is there any parameter that needs to be tuned in purge_dups when we use Canu assembly?

Thank you!

**Comment by skoren** [comment]
Purge_dups often picks incorrect thresholds on HiFi assemblies because everything is already split into haplotypes. Check what thresholds it picked from calcuts. The important values are the first, fourth, and last. The fourth one should probably be around 30 given the coverage. I typically plot the coverage from the stat file and pick a cutoff past the first peak.

**Comment by proteinosome** [comment]
Thanks Sergey! As the primary contig is almost doubled than that of haploid genome size at 5.7Gb, the histogram actually showed a peak at ~ 20X instead of 30X. Should I expect two peaks instead of one? This is what I see:
![PB stat](https://user-images.githubusercontent.com/13174349/84124653-17c2fa80-aa6e-11ea-9e1e-65b78a3d0f45.png)

Anyway, I tried setting manual cutoff to 5, 20 and 70 (for the first, fourth and last value) according to the histogram and the assembly seems much better with ~ 3Gb size and only 400 contigs. NG50 is around 60Mbp (Hifiasm approaches around 90Mbp). Thank you for the suggestion!

**Comment by skoren** [comment]
No you should expect only one peak, purge_dups usually expects two which is why it selects an incorrect threshold by default. We've talked to to the purge_dups developers and perhaps it makes sense to add a hifi option to avoid this in the future.

As for NG50s, those are becoming pretty meaningless because it is limited by the chromosomes and mostly due to differences in how aggressively an assembler traverses the graph (in my limited companions hifiasm prunes more aggressively than than hicanu). Even when it makes an incorrect decision, it would cause a local mis-assembly which would be hard to detect and validate since it will be in regions w/o references (e.g. centromeres, large repeat arrays) but one or two of these changes can drastically change the NG50. I'd use NGx plots instead.

**Comment by proteinosome** [comment]
Thanks Sergey for your help and suggestion. Appreciate it!
