### ISSUE TITLE
How to specify different java/perl/gnuplot versions with SGE?

### ISSUE THREAD

**Issue by polkacode** [marbl/canu#1735]
Dear developers,

I try to get canu running on a Linux SGE cluster.
I'm using canu snapshot v2.0-development +532 changes (r10025 14fca271b783334190fcb54decdfd94f1c2b61e2)

I've specified  gridEngine=sge  gridEngineResourceOption="-pe cores 1" and the
initial job gets submitted:

```
-- Starting command on Thu Jun 11 14:55:47 2020 with 4109.786 GB free disk space

    cd /scratch/test
    qsub \
      -pe cores 1 \
      -S /bin/bash  \
      -cwd \
      -N 'canu_LU_1SMRTcells_Canu_2_0heute3' \
      -j y \
      -o canu-scripts/canu.09.out  canu-scripts/canu.09.sh
Your job 244902 ("canu_LU_1SMRTcells_Canu_2_0heute3") has been submitted
````

But, once the thing runs on one of the compute nodes, it fails because
the wrong java version is used, which is kind of "normal" since there are a few of
them installed which are addressed by the modules environment when one is 
creating its own submit scripts.

From canu.out:

```
-- CONFIGURE CANU
-- Failed Java version check.
--   'java version "1.7.0_79"'
--   'OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)'
--   'OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)'
```

Where would I modify the canu setup, so that I can load different versions of
java/perl/gnuplot on runtime on the compute nodes? I wanted to avoid messing
around in site_perl/*.pm in the first place...

Any help is highly appreciated
Thank you very much
Andreas

**Comment by skoren** [comment]
First, I'd recommend using the release version rather than the development branch it looks like you have.

You can specify a java version with the java parameter (```canu -options |grep -i java```), set it to the full path to your java executable and Canu will use that rather than the default on the system. You can also specify commands for canu to run on startup (if you want to load modules/etc on your system) using the option preExec, you can specify an arbitrary command to run which will get put at the top of all canu scripts (e.g. ```preExec="module load java/1.8; module load gnuplot"``` or whatever you need on your system).

**Comment by polkacode** [comment]
Thank you so much, that's exactly, what I was looking for.

Bests
Andreas
