### ISSUE TITLE
alignment of contigs to a reference

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#177]
Hello,

I could assemble pacbio reads from a human tumor sample.
And then, I tried to align the contigs on a human reference to identify where they would be aligned.
Interestingly, I can see several contigs that consist of the sequence fragments aligned on different strands of the reference chromosome. In other words, such a contig usually consists of, for example, two sequence fragments (contig = A + B ) which are aligned (by, for example, Blat) to different strands (A on + strand and B on - strand) of a reference. I believe this would be due to a structural variation, but I am not fully convinced about it. 
I wonder if you have never seen this pattern in any normal samples you analyzed. Because I don't have pacbio from a normal sample, I can't check it up, and therefore, your comments based on your experience will be highly appreciated.

thank you,

**Comment by skoren** [comment]
I'm not sure I follow your question. You have a contig composed of two reads A and B which occur in the reference in this layout:
```
ctg:-----------------------------
A:   ------------------>
B:                  <-------------
```
What is the mapping of the contig in the reference? Is it something like:
```
ctg:----------------------------->
```
or 
```
ctg:------------> <-----------------
```
It's perfectly valid for a contig to mix forward and reverse strand sequences as long as the contig stays in the same strand it's not a structural variation. The assembler has no idea which strand a read came from so it can use it in either strand arbitrarily and align to the reference in an arbitrary strand as well.

**Comment by wisekh6** [comment]
I am very sorry for confusing you.
What I wanted to ask you was:

an assembled contig: --------------------------------------------------------------->
                             
After aligning the contain on a reference, a part of the contig (i.e. the first half) was aligned on + strand of the reference and the rest was aligned on - strand (with >=99 % identity) like:
on reference: ------------------------------> <-------------------------------

I believe this would represent a structural variation, but I was not sure.
I would appreciate it if you could provide your comment on it.
I wonder if this is clear to you.

Best,

**Comment by skoren** [comment]
Ah, ok I understand, I was confused by fragment meaning substring of contig not a read.  That does seem like a structural variation though you have to be careful because PacBio reads which still have their SMRTbell adapter missed would look exactly like the pattern you have drawn (it should be immediately adjacent to each other on the reference). I would only trust the contig if it is composed of many sequencing reads (e.g. it's not just 1 or 2 reads) and as a final verification I would also map the raw sequences to the region in question and confirm support for the variant.

You can take a look at the assemblytics paper:
http://biorxiv.org/content/early/2016/03/20/044925
which gives nice summaries for variations between your assembly and a  reference.

**Comment by wisekh6** [comment]
Thank you so much for your quick response.
It is a good idea to map the raw sequence reads to the region in question.
I will try, and will let you know.
Once I confirm it, I will close this ticket. is it ok?

Best,

**Comment by wisekh6** [comment]
By the way, is it possible to know which reads (i.e. read ids) were used for generating each contig? Probably, there would be a mapping file, but I could not find one.

Another question is:
Some contigs which were mapped to copy number amplified regions were suggested (by canu) to be 'Repeat'. Because those regions are CNV gain regions, may I assume that that suggestion could be false in this case?

Thank you in advance,

**Comment by skoren** [comment]
There is an asm.layout file which gives the read ID in each contig. However, these are post-correction ids:
```
read      248232 anchor     73186 hang      0      0 position  24897      0
read       54866 anchor         0 hang      0      0 position  17018   3113
read      310873 anchor         0 hang      0      0 position  15857   3181
read       73186 anchor    172032 hang      0      0 position  26919   6387
```
You need to get the original raw ids from the gkpStore folders in trimming and unigging. Using read 248232 an example, we first find it's id in the unitigging/asm.gkpStore:
```
cat unitigging/asm.gkpStore/readNames.txt |grep 248232
248232	249518 clr=27,24924
```
Then we get the raw ID:
```
cat trimming/asm.gkpStore/readNames.txt |grep 249518
249518	m131126_030533_42175_c100583772550000001823087704281444_s1_p0/92998/0_25696 iid=1219482_0
```

As for the contigs marked repeat, this means they have more reads (higher coverage) than expected. If there is a CNV that has amplification and the assembly is collapsed into a single copy it would get marked as a repeat because it has higher coverage than expected (due to the amplification).

**Comment by wisekh6** [comment]
Thank you very much for your comments.
