### ISSUE TITLE
Feature request: output overlap error histogram

### ISSUE THREAD

**Issue by bredeson** [marbl/canu#1770]
Hi Canu Devs,
Thank you for the awesome program! Is there a way to generate a histogram of the overlap error rate between reads? I was actually surprised this is not already plotted for the user by default; I see read trimming metrics histograms and k-mer depth histograms are produced by default.

In the meantime, how would I go about doing this using the tools available with Canu?

Best,
Jessen

**Comment by skoren** [comment]
You can dump this information from the overlap store using ovStoreDump (run it without parameters to get help,  for example you can dump the error rate vs length histogram). However, this type of overlap histogram is not particularly useful because it will report all overlaps found, not necessarily the ones used in an assembly so it will include lots of overlaps between haplotypes and between repeats that may not actually be useful in practice.

You probably want to look at the stats in the untigging folder (```unitigging/4-unitigger/*.001.filterOverlaps.thr000.num000.log```) which will report statistics on overlaps used for the assembly (this will be in the report in the future):
```
                                                 --------threshold------
6695701                      fraction error      fraction        percent
samples                              (1e-5)         error          error
                 --------------------------      --------       --------
command line                                 ->     30.00        0.0300%
mean + std.dev       0.21 +-   4 *     1.81  ->      7.44        0.0074%
median + mad         0.00 +-   4 *     0.00  ->      0.00        0.0000%
90th percentile                              ->      1.00        0.0010%  (enabled)
```

The ```*.best.edges``` file in that same folder reports the actual values for error rate of overlaps if you wanted to plot them or compute other statistics.

**Comment by bredeson** [comment]
Hey @skoren,
Thank you for the response; the `best.edges` file is what I was hoping to see.
