### ISSUE TITLE
worse assembly using canu2.0

### ISSUE THREAD

**Issue by Secretloong** [marbl/canu#1775]
Hi, recently I re-aasembled my Pacbio reads with `Canu 2.0` but get worse assembly contigs. For details:
`Canu snapshot v1.8 +358 changes (r9568 c478f9e441e76326ea1435adedf7f01997bbd32f)`: I got contigs with N50 241K, and total length 360Mb.
```
canu -correct -p my_species -d my_species .out genomeSize=300m -pacbio-raw reads/*fastq.gz -s canu.cfg
canu -trim-assemble -p my_species -d my_species .out genomeSize=300m -pacbio-corrected my_species .out/my_species .correctedReads.fasta.gz -s canu.cfg
```
On the other hand, `Canu 2.0` with the same command as follower: I got contigs with N50 172K, and total length 387Mb.
```
canu -correct -p my_species -d my_species .out genomeSize=300m -pacbio-raw reads/*fastq.gz -s canu.cfg
canu -trim-assemble -p my_species -d my_species .out genomeSize=300m -pacbio-corrected my_species .out/my_species .correctedReads.fasta.gz -s canu.cfg
```

Do you know Why? And how to improve this? Thank you very much!
(I would scaffold with HiC, but the result of  `Canu 2.0`  cannot be connected with any HiC reads by `SALSA2`. I am afraid there is any problem within the result of  `Canu 2.0` .)

**Comment by skoren** [comment]
Those assembly stats are near identical so I wouldn't make any conclusions from the N50, the slight change in genome size may explain the change. 

Have you checked any other statistics to make you think that the Canu 2.0 assembly is worse (identity to a reference, BUSCO completeness, QV, completeness, etc)? If not, I'd expect the reason Salsa is not scaffolding it is because the assembly N50 is quite low. There may not be enough HiC coverage or there are issues mapping your data. If you haven't already you should use purge_dups to remove any duplication in the assembly before scaffolding.

**Comment by Secretloong** [comment]
Thank you for your suggestion. I have no reference, this is a new species. But I will try BUSCO. If anything new, I will tell you or close this issue.

**Comment by skoren** [comment]
Idle, no reply. Relatively minor change in stats and no concrete identified assembly errors in 2.0 reported vs the older version. If there are examples where 2.0 created a validated mis-assembly that the previous version did not, open a new issue.
