### ISSUE TITLE
PBS account error

### ISSUE THREAD

**Issue by onkarnath89** [marbl/canu#1776]
I am getting PBS account error. I suspect that this is due to the account name, which is different to my username.
The Script ends with the following lines:

```
--
-- Report changed.
-- Finished stage 'merylConfigure', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: Canu 2.0
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /gpfs1/homes/s4539277/Softwares/canu-2.0/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1275.
CRASH:  canu::Execution::submitOrRunParallelJob('Canu_LRAssembly', 'meryl', 'correction/0-mercounts', 'meryl-count', 1) called at /gpfs1/homes/s4539277/Softwares/canu-2.0/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 834
CRASH:  canu::Meryl::merylCountCheck('Canu_LRAssembly', 'cor') called at /home/s4539277/Softwares/canu-2.0/Linux-amd64/bin/canu line 989
CRASH:
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl-count.jobSubmit-01.out):
CRASH:
CRASH: qsub: PBS Account Error - account must be specified!
CRASH:
```

I could not find any option to set the PBS parameters. Please suggest me a solution.

**Comment by skoren** [comment]
This looks like your grid requires some extra parameters (like the account name) when submitting jobs. From the FAQ (https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system): "You can supply your own grid options, such as a partition on SLURM, an account code on SGE, and/or time limits with gridOptions="<your options list>" which will passed to every job submitted by Canu. " So add gridOptions="<whatever PBS options your system requires like account code/time limit/partition/etc>"

I'll also caution that PBS support is always a bit limited because we don't have access to a test system and PBS/PBSPro seem to be very different between cluster environments/versions.

**Comment by skoren** [comment]
Idle, missing gridOptions required for grid.
