### ISSUE TITLE
Falconsense very slow

### ISSUE THREAD

**Issue by farhan-phd** [marbl/canu#1784]
Dear Adam, Sergey, et al,

I am assembling a 1 GB fish genome sequenced with PacBIo using canu-1.8 from conda. We have about 170x coverage and I used very standard options:

canu -p Asta-latifasciata -d canu-00-assembly genomeSize=1g -pacbio-raw /storage/maryam/00-raw-data_pacbio/ala-1b-Ge-Mus-M_PacBio.fastq utgOvlErrorRate=0.065 trimReadsCoverage=2 trimReadsOverlap=500 minReadLength=1000 corMinCoverage=4x corOutCoverage=500 gnuplotTested=true maxThreads=60 maxMemory=800g > std.error 2> std.out 

During the correction phase, it splits the data into 473 batches. This process has been running for 1 month now and around 310 batches have been completed (on average taking 10 to 12 batches per 24 hours). In the canu command, I have specified computational resources as maxThreads=60 maxMemory=800g running on Linux HPC with 1 TB RAM and 120 CPUs.

Do you think the high coverage can cause an unusual delay in the correction of reads and it can further slow down the downstream steps such as trimming and assembling? Do you suggest, should I wait until the correction is completed (a total of 163 batches still remaining), or is there any way if I could make it faster?  

In addition, I have found there are several .err files being generated in /correction/2-correction/correction_outputs, please see below. Is this error message going to be a serious issue in assembly? I found certain batches have no .err whereas many batches do have .errr files! 

![image](https://user-images.githubusercontent.com/61362867/91864781-05102a00-ec47-11ea-933e-0ccab6edae30.png)

Thanks in advance
Farhan

**Comment by skoren** [comment]
The error message isn't a concern, as long as the runs complete it is OK. The err files are cleaned up when the job is successful.

This step is depending on random I/O seeks so it can be affected by your file system. If you're on a cluster, you can use the the staging options (assuming your nodes have local space) which can significantly speed this step up (something like `'stageDirectory=/lscratch/$SLURM_JOBID' 'gridEngineStageOption=--gres=lscratch:100'` where the grid engine stage option tells canu to how request local disk resources from your grid). You should be able to kill the current run and then remove the shell scripts in the 2-correction folder and re-run canu after adding the above options. 

The other issue is you're outputting a lot of coverage, by default canu corrects the longest 40x. Correcting with your parameters will correct all 170x of data which is going to be at least 4-fold slower. There isn't much benefit in correcting so much data for assembly.

**Comment by farhan-phd** [comment]
Many thanks for your quick response and advice! 

Sorry to not mention that I am on a local machine, not a cluster and neither on the grid, therefore do you have any specific advice for me to use further options for speeding up this step on the local computer?

For default 40x coverage, in case I kill the ongoing process and restart with the default coverage option, will Canu resume the correction phase from its current batch?
Best regards

**Comment by skoren** [comment]
I/O issues can still be a problem if your filesystem can't keep up with the process on the node. There is less you can do to address it on a single node though. You can check on top if the jobs are waiting on I/O a lot (D state) and if you have faster disks (like SSD) move the seqStore/assembly there. Another option would be to make a memory-mapped file system and put the seqStore there so it's always in cache. You have plenty of ram available and that's probably the best option. You'd want to kill the Canu run, make the memory disk, copy the seqStore there, then symlink to it so the correction script can find it and restart Canu.

To correct 40x, you'd need to re-run the 2-correction step from scratch since you'd change what reads need to be corrected and what reads are in each partition. I wouldn't recommend doing that since you've completed 2/3 of your runs.

**Comment by farhan-phd** [comment]
Hello, I just let the process running despite of being very slow, and today after around two months the correction step has been completed with the error of segmentation fault (see the attached screenshot) and eventually stopping further assembly steps. I have now restarted assembly by the same command parameters, and it is resumed from the correction of the failed 15 batches. I wonder if it's possible to exclude the 15 failed batches and proceed with trimming, how? Or I should start from scratch again with the default coverage option?
 
![image](https://user-images.githubusercontent.com/61362867/93711371-1355b580-fb24-11ea-9fc4-2331551a0843.png)

Many thanks in advance
Best,
Farhan

**Comment by skoren** [comment]
You probably don't want to skip 15 partitions as you'll be throwing away a bunch of your data. Further, we've not seen a segfault in that part of the code for a long time. I didn't realize your installation of canu is from conda. We don't recommend that as conda has been known to completely mess up installs ending up with intermediate or mixed versions of canu. I suspect this is the cause of the crash and if we try to run this locally, it would not fail. In particular, the falcon_sense binary has not existed since Canu 1.7. This makes me think you're not really running Canu 1.8 and I wouldn't trust it for assembly results. 

My suggestion would be to install Canu 2.1 from the GitHub repo not conda and run again using normal output coverage and using either SSD disk or a ram disk for your seqStore folder to speed up the run.
