### ISSUE TITLE
Canu is crashing with no significant errors (v2.0)

### ISSUE THREAD

**Issue by unique379** [marbl/canu#1787]
Hi 
I am trying to assembled reads of pacbio  as well as nanopore reads but its crashing with errors which i dont get it, please find the attached log generated by canu. I tried local (useGrid=false) as well as default but its crashing it always, please take a look.

`Apps/envs/assembly/bin/canu -d  AssemblyReports/canuOut -p pacbio useGrid=false genomeSize=3.3g -pacbio-raw /pacbio/merged_fastq/PACBIO_merged.fastq`

And please tell me how to resume the run if its has been crashed?

**Note: Please download the files as it will be deleted in 1 week.**

[https://filebin.net/ouhv4zuztvfry4tx](url)

**Comment by skoren** [comment]
Your PacBio log has no error, it just ends so nothing to fix there, if you have a full log with an error post that directly in the issue. As for the nanopore, one job had an error post it's log report (`precompute.000126.out`).

**Comment by unique379** [comment]
Hi
I dont find any error log in pacbio or in nanopore analysis, just have precompute.000001.out, precompute.000002.out, precompute.000003.out in both cases. The precompute.000126.out has been "2>&1" so cant get it. 
1. is there way that i can resume the analysis, by just running the same script/commands?
2. do you think, if its memry issue then can be solved by using "maxMemory={130000}M maxThreads={4}"?

Thanks

**Comment by skoren** [comment]
For the pacbio, I meant if there are any errors reported in any of the precompute log files since that's where the log just ends. I'm not sure what you mean by it's been "2>&1"? That just merged stdout and stderr, post the full contents of  precompute.000126.out from the nanopore run.

You can certainly re-launch with the same command but if it failed before it may fail again. You can't change memory in the middle of the step, you'd have to re-start since the partitioning will change as well so I wouldn't do that until you figure out why it stopped.

**Comment by skoren** [comment]
Idle, no reply.
