### ISSUE TITLE
Running Hicanu v2.1 with batMemory=200 ... Getting error

### ISSUE THREAD

**Issue by VManning** [marbl/canu#1811]
Hi!

I had some luck with assembling my metagenome with the older version of canu but wanted to try the new one and compare. Some threads about metagenome assembly with version 2.1 suggested setting the batMemory=200. I am running this on a cluster and have to limit the # of cores I am using or the job will never run. Does the batMemory and the requested memory from the cluster have to match? Also, why is it important to set the batMemory?

Below is the error message. Thanks for any help, I am not very savvy. Viola

```
-- Detected 8 CPUs and 31 gigabytes of memory.
-- Detected Sun Grid Engine in '/local/cluster/sge/default'.
-- Grid engine and staging disabled per useGrid=false option.

--
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 8 cores with 31 GB memory each.
-- ERROR
-- ERROR  Task bat can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    batMemory=200 memory (gigabytes)
-- ERROR    batThreads=2-8 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change batMemory and/or batThreads
-- ERROR
```

**Comment by skoren** [comment]
Yes, if you want to use 200G for bogart, you have to be running on a node with 200G. You don't have to restart from scratch though, you could reserve a larger node and re-run the same Canu command and it will resume where it left off.

The reason to increase batMemory is because Canu estimates how many overlaps to load based on the genome size and coverage but those values will be meaningless in a meta genome so increasing batMemory will force it to always load more overlaps into memory.

**Comment by VManning** [comment]
Great, Thanks! Will do.
