### ISSUE TITLE
hetero/homoxygous boundaries

### ISSUE THREAD

**Issue by acalcino** [marbl/canu#1818]
In the VGP preprint, the authors observed while using FALCON that:

During assembly curation, we discovered that the original version of FALCON software was producing inaccurate breaks in contigs at junctions between stretches of highly homozygous and highly heterozygous sequences of each haplotype (Supplementary Note 1). When we fixed this function in an updated FALCON release (Supplementary Table 2), the NG50  contig continuity nearly tripled to 12.77 Mbp with a concomitant increase in scaffold NG50.

Has a similar issue been observed with canu? Has anyone looked? I'm trying to assemble a super heterozygous genome (>2%) and so I essentially get an assembly which is double the predicted size but I'm worried that regions with high heterozygosity but below that 2% threshold might suffer from erroneous breakages.

**Comment by skoren** [comment]
Since canu uses best edges this shouldn't happen as the longer contig will steal the other haplotype reads. However, there may be over-fragmentation because these regions look like repeats as well. This was improved in recent version (post 1.9) but I expect it still happens. However, these should be relatively easy to resolve via scaffolding and gap filling after the assembly is done.
