### ISSUE TITLE
Controlling min number of reads for unitig construction

### ISSUE THREAD

**Issue by rafalwoycicki** [marbl/canu#182]
Hi All,

How can I tell canu that it should not make the unitig when only two reads overlap - I know that I can filter out unitigs already made, but as I have seen I have several cases when contigs not supported by the reference have the drop of coverage to 2-4 reads exactly at the position where the similarity to reference contigs ends - these positions also does not have coverage with Illumina reads.
Thanks for any thoughts.
Rafal

**Comment by brianwalenz** [comment]
Before I say that it can't be done (except by trimming bases with less than N coverage), this sounds like it might be a trimming problem, or novel sequence.  It's quite possible we're not detecting a hairpin adapter, or generic chimeric read, because it's supported by a duplicate read.  It's a little involved to examine the (assembler) data to determine this, and I'd rather not write up the steps right now.

Have you isolated the reads at the coverage drop?  If mapped to reference, do they map full length, in one piece, etc?  I don't have the time right now, but I would like to examine this data in more detail.

Options:

trimReadCoverage (default 1) will trim reads so that every base is supported by at least this many other reads.

trimReadsOverlap (default 1) requires that the evidence be overlapping by this many bases for the trimming to be contiguous.  Example: a 500bp read with two overlaps covering bases 1-100 and 101-500 will be trimmed to 101-500 because there is not at least a 1bp overlap between the two overlaps.  Increasing this can help in detecting chimeric reads, but can easily over trim.

**Comment by brianwalenz** [comment]
Idle issue, nothing to do.
