### ISSUE TITLE
Assembly using illumina reads

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#1832]
Hi,
I would like to assemble the plant mitochondrial genome using both Illumina and ONT nanopore reads. I have read one recently published article stated that they have used short reads for Canu assembly. Can we use Illumina short reads for Canu assembly? If so, could you please inform me what are the commands are needed to execute? I have read the Canu manual but could not find it anywhere. 
Thank you and looking forward to hearing from you.
With warm regards,
Raman. G

**Comment by skoren** [comment]
No you cannot use any short-read data with Canu. I expect the article you are referring to used the short-read data to polish the consensus of the canu assembly. That would be the recommended strategy not including the short-read data for assembly.

**Comment by bioramg** [comment]
Could you please go through the recently published article in the Journal of BMC Evolutionary Biology?

[Kan2020_Article_TheCompleteMitochondrialGenome.pdf](https://github.com/marbl/canu/files/5448960/Kan2020_Article_TheCompleteMitochondrialGenome.pdf)

**Comment by skoren** [comment]
It seems the main strategy in that article was to assemble short reads with SPAdes and use that to bait long reads which were then assembled with Canu. There is this sentence: "In the second strategy, all short clean reads were assembled de novo by using Canu directly [30]." but as they said the two strategies give similar assembly I would use the first approach. I have no idea what parameters they used for assembly of short-read data with Canu since, as I said before, it's not supported. You can ask the authors of that paper if you really want to do it but I wouldn't recommend it.

**Comment by bioramg** [comment]
Thank you for your prompt response. They bait long reads represent ONT reads??

**Comment by skoren** [comment]
Yes, from the manuscript:

First, the short clean reads were de novo assembled with SPAdes v 3.13.0 [24] using multiple k- mer values [21, 33, 55, 77]. <b>Second, potential mitochon- drial contigs were extracted by aligning against the mito- chondrial protein-coding genes of Cycas taitungensis [3] with BLAST v 2.3.0 [28]. Then, the putative long mito- chondrial reads were baited by mapping the short reads to the plant mitogenome database (ftp://ftp.ncbi.nlm.nih. gov/refseq/release/mitochondrion/) and the potential mitochondrial contigs using BLASR v5.1 [29]. Finally, the putative long mitochondrial reads were assembled by Canu v1.7.1 [30]. </b>In the second strategy, all short clean reads were assembled de novo by using Canu directly [30].
