### ISSUE TITLE
Question about quickstart "Correct, Trim and Assemble, Manually"

### ISSUE THREAD

**Issue by lmtani** [marbl/canu#1834]
Hi! I have a low coverage nanopore sequencing reads (~30x) and would like to perform an experiment trying the following recommendation from your documentation:

"For low coverage datasets (less than 30X), we recommend increasing correctedErrorRate slightly, by 1% or so."

To speed up my process I would like to follow the instructions from [Correct, Trim and Assemble, Manually](https://canu.readthedocs.io/en/latest/quick-start.html#correct-trim-and-assemble-manually), but I'm uncertain about how the correctedErrorRate are used in "correct" and "trim" tasks.

I'm wondering if it will use nanopore default value 0.144. If so, will it have consequences in "assemble" step running with, say correctedErrorRate in range of [0.145, 0.147, 0.149, 0.150, 0.160, 0.170]?

**Comment by skoren** [comment]
correctedErrorRate isn't used at all in the correct step. In the trim task that is the error rate used for overlapping reads. Any reads with no support for its sequence from other reads at correctedErrorRate will be trimmed to the largest supported region. It will affect the assembly step if you trim at a lower error rate since some reads that the assemble step could have used will get trimmed. For that reason, I don't think running the steps manually will speed up the run any over running the full pipeline, they will both do the same work. I'd suggest using ```corMinCoverage=0``` along with an error rate of 0.15 (the default in 2.1 is 0.12 not 0.144). You could try the `-fast` option but it can produce a less continuous assembly but it is faster.

**Comment by lmtani** [comment]
Thanks for your answer and suggestion. I'll try it.
