### ISSUE TITLE
Questions About Consensus vs Haplotype Assembly (Canu v1.5 and v2.1)

### ISSUE THREAD

**Issue by cwarden45** [marbl/canu#1841]
Hi,

I am very grateful for assistance that was provided for an [earlier question](https://github.com/marbl/canu/issues/1797).

We have found Canu to be extremely helpful for assembly troubleshooting.

However, there are some things where I would appreciate it if you could help me understand what is happening with the Canu assembly better.

I would appreciate any feedback that you might have to the [attached PDF summary](https://github.com/marbl/canu/files/5532554/Summary.-.Round56k.pdf), but I believe **slides 17-21** are the most relevant.

Briefly, these are the main questions (reworded from **slide 18**):

**1)** There are 3 separate samples/clones that have similar types of genomic content but also have noticeable differences (**introductory slide 8**).  If I mix the raw subreads for those clones (and sometimes 2 additional ones), then I **_don’t_** believe that I am seeing evidence for the presence of 3 haplotypes (for similar clones with different end sequences that cause divergence from each other).

The goal for the above point was really to test this as a strategy for consensus creation.  However, as I thought about it, I started to wonder if this could also be happening in the **separate assemblies** (when we expect 1 BAC clone, but it is theoretically possible that there could be unexpected variation between clones and/or an unexpected mix of clones in a given sample).

**2)** When I combine subreads from 3-5 samples, the results can be different with different versions of Canu.

I don’t think this is highly surprising, but it is part of the reason why we are currently focusing in starting with a draft created by merging 2 clone sequences (190M+19d16) and then comparing all the separate assemblies to the draft that represents 5 overlapping clones.  If there is a way to define an equally good or better consensus using Canu, then that would be neat.  However, it is OK if that is harder than some might expect.

**3)** For at least 2 assemblies with combined subreads, it looks to me like the resulting assemblies look primarily like one of the 2-5 separate assemblies (**slides 19-21**).  These are BAC assemblies where we ultimately want to provide the original (chicken) linear sequence before BAC creation.  Since the assembly method doesn’t know about the **BAC backbone** sequence, I thought that should be somewhat (but not perfectly) random and therefore helps with visually saying that some assemblies look noticeably similar to each other.

I am guessing this is probably not a huge problem.  Nevertheless, if you can confirm that that things look good and explain what is happening for questions **1)** and **3)**, then that would be very helpful.

Of course, if you do think something needs to be changed for a valid “solution,” then we would also very much appreciate any feedback that would help us gain confidence in our assemblies.

Thank you very much!

Sincerely,
Charles

**Comment by skoren** [comment]
I'm not sure I followed all the slides but I can give some general answers to the questions above. First, the position of the BAC vector will be completely arbitrary between assemblies since the circular BAC will get linearized differently by the assembly depending on which read is picked to start the path. So assemblies can only be compared after trimming off the self-match on the end and rotating them to a common coordinate system.

1. Canu is not going to be sensitive to haplotype differences (essentially what you have when you combine BACs) below about 1-2% divergence. Some large SVs will still be picked up but SNP-level variation will likely get removed during correction and consensus. 

2/3. Canu will arbitrarily pick a winner among haplotypes for the larger SVs and will make no attempt to keep SVs in phase between the haplotypes. So, I would not rely on Canu to identify mixtures during assembly. I'd instead generate an assembly and then do SNP/variant calling to see if there are consistent minority alleles not represented by the assembly but that do not look like random noise. As I said above, the position of the vector isn't important but I'd focus on the alignment similarity between the assemblies after translating to consistent coordinates. 

I hope that helps.

**Comment by cwarden45** [comment]
Hi Sergey,

Thank you very much for your response.  I will close this issue.

I think you are saying that Canu is better for a consensus than defining haplotypes, which was my guess (although I thought that it was better than the Falcon and Flye assemblies that I tested, on *slides 28-29*).

I think you are agreeing that the BAC backbone location should be largely random.  So, when you have a mix of 2 clones and the resulting assembly is **a)** more similar to one of the clones than the other(s) and **b)** the position of the BAC backbone is similar to the separate assembly with the same version of Canu for that clone, then I believe you are saying it is kind of like Canu focused on one of the overlapping assemblies as the main haplotype?

For **b)**, if I wasn't clear, that would be like **slide 20** or the **top of slide 21**.

I think the rule of thumb for Canu not separating <2% divergence is also helpful.

Thank you very much!

Sincerely,
Charles
