### ISSUE TITLE
Failed with code 134

### ISSUE THREAD

**Issue by signor-molevol** [marbl/canu#1855]
Code:
```
./canu -correct -d /storehouse/sarah/piRNA_project -p SZ_232_correct genomeSize=140000000 -nanopore-raw /storehouse/sarah/piRNA_project/SZ_232_all_11_13.fastq useGrid=false maxThreads=20 maxMemory=120
```

```
Error:

ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate correction layouts.
ABORT:
ABORT: Disk space available:  5016.484 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/SZ_232_correct.corStore.err):
ABORT:
ABORT:   ERROR: bogus overlap '         1         25  N       0       2     69       4 4294966326  0.000000'
ABORT:   generateCorrectionLayouts: correction/generateCorrectionLayouts.C:96: void generateLayout(tgTig*, uint16*, uint32, double, double, ovOverlap*, uint32, FILE*): Assertion `ovlLength < (((uint32)1 << 21) - 1)' failed.
ABORT:
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP7siginfoPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   correction/generateCorrectionLayouts.C::96 in generateLayout()
ABORT:   correction/generateCorrectionLayouts.C::330 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   Aborted (core dumped)
```
Keeps coming up after multiple restarts.

**Comment by skoren** [comment]
Usually, this is because your file system failed and left corrupted data or there was more than one assembly running in the same folder (see #773 or #1401). Did you run out of space during this run at some point?

The easiest option is to remove the folders (e.g. 1-overlapper, 2-correction and *corStore and *ovlStore directories from your current assembly and restarting). If you're running on a grid, you can limit the number of concurrent jobs running at once to avoid issues with the filesystem (see https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system which explains how to do it on slurm/sge). If you're not on the grid, reduce maxMemory to limit concurrency. If you're comfortable editing code, you could remove the offending assert and just skip this overlap, change:
```
    if (ovlLength > AS_MAX_READLEN) {
      char ovlString[1024];
      fprintf(stderr, "ERROR: bogus overlap '%s'\n", ovl[oo].toString(ovlString, ovOverlapAsCoords, false));
    }
    assert(ovlLength < AS_MAX_READLEN);
```
to
```
    if (ovlLength > AS_MAX_READLEN) {
      char ovlString[1024];
      fprintf(stderr, "ERROR: bogus overlap '%s'\n", ovl[oo].toString(ovlString, ovOverlapAsCoords, false));
      continue;
    }
#    assert(ovlLength < AS_MAX_READLEN);
```

in src/correction/generateCorrectionLayouts.C. Make sure though that there aren't too many bogus overlaps if you do that.

**Comment by skoren** [comment]
Idle, likely I/O corruption.

**Comment by signor-molevol** [comment]
Apologies, I had already tried something else dumb that didn't work, but having done the assembly over again I am having the same problem. 

I have tried your suggested solution and we'll see if it works. Thank you!
