### ISSUE TITLE
Change "random" downsampling of HiFi data to longest read selection?

### ISSUE THREAD

**Issue by TC-Hewitt** [marbl/canu#1857]
Hello,
according to canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak for high coverage data: For HiFi data, Canu automatically downsamples to a random 50x subset... 
correct me if I'm wrong but I thought Canu normally chooses the longest 50x reads, so why is it random for HiFi data? this seems suboptimal. I know maxInputCovergae can be changed to include all the data but in cases where we want to limit the coverage, is there a way to sample the longest HiFi reads instead of a random subset?
regards,
TCH

**Comment by skoren** [comment]
The downsampling is never purely based on length, when correcting it's based on supported length of the read (e.g. covered by overlaps). You can skew the downsampling to pick longer reads using the readSamplingBias parameter (https://canu.readthedocs.io/en/latest/parameter-reference.html). HiFi libraries are typically tightly size selected and longer reads typically have worse error profiles (since they have fewer passes) so you'd be biasing your data to be higher error when you bias it to be longer. That plus the fact that string graphs have issues for different length means we pretty much never select for longest reads in HiFi data and I don't expect you'd get a better assembly doing that.

**Comment by TC-Hewitt** [comment]
Thanks for the explanation. I'm just wondering if there's a way to optimise the read sampling but as you say biasing for longer reads may sacrifice accuracy. I am concerned that some of my contigs appear chimeric and thought this may be due to suboptimal shorter reads but perhaps it's due to low coverage support in the junction overlap? Is this information in one of the tigStore outputs and is there a parameter you suggest to minimise chimerics?

**Comment by skoren** [comment]
The best way to avoid chimeric contigs is to make sure you're using canu 2.1, it improves the assembly accuracy over 2.0. You could also try turning on trimming in case there was some issue in your data preparation, which is off for HiFi data by default (add `-untrimmed`). 

Beyond that, unless you have a very good reference, it can be hard to know true chimeric errors vs incorrect reference or sample differences. There are certainly some handful of errors on large genomes (we estimated <15 large errors on a human genome) and we typically rely on other datatypes like bionano/hic/etc to identify/fix those during scaffolding.

**Comment by TC-Hewitt** [comment]
Thanks for your suggestions.  I checked the tig info and there appears to be adequate coverage in the questionable contigs. I was using Canu 2.0 but I will try using 2.1 with -untrimmed. Cheers!
