### ISSUE TITLE
genomeSize parameter for HiFi ?

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#1858]
Hi,

From what I understand, the genomeSize parameter is used to downsample the data for the correction step.

However for the HiFi option, how does it affect since there is theoretically no need for correction ?

I am also asking this question because I am not really sure about the genome size of my species.

**Comment by skoren** [comment]
The genome size affects some things in HiFi data as well, it first guides job sizes to avoid over-partitioning on small datasets and there is default downsampling of 50x on HiFi data. The genome size doesn't have to be very precise, as long as you're not many fold off. Err on the side of larger rather than smaller to avoid downsampling too much.
