### ISSUE TITLE
ovStoreIndexer and correction step.

### ISSUE THREAD

**Issue by jlim125** [marbl/canu#1859]
Hello,

I am Jaechul Lim, a postdoc at Yale. We are trying to assemble a large eukaryotic genome with high repeats from raw PacBio reads. We are using Canu 2.1 (a binary package) on AWS (amazon web service). We are using Linux and the FSx lustre file system.

For the correction step, it took a long time and a lot of disk space, but we were able to finish 1-correction and 1-bucketize/2-sort steps in ovlStore.BUILIDING. We have ~1900 buckets and ~30000 slices. We are now in the ovStoreIndexer step. It looks like this step and the next step (2-correction) are single process ('Canu executive'). So I was wondering if there is any way to speed up those processes although it could be currently the fastest step in Canu (according to your Canu Document). Would it be possible to modify Canu in some way?

Please find the parameters for our run below,

```
corMaxEvidenceErate=0.15 corMhapSensitivity="normal" \
correctedErrorRate=0.105 \
purgeOverlaps='aggressive' \
corPartitions=1024 corOutCoverage=99999
```

And any other suggestions are welcome. Thank you!

Best,
Jaechul

**Comment by skoren** [comment]
That is a lot of slices and buckets, or are those file counts? What did canu report for the partitioning and memory of this step, it sounds like it could have benefited from higher memory which may help in trimming/unitigging steps too (`ovsMemory=32 ovbMemory=32` for example).

There's no easy way to modify canu to make those parallel, you'd have to re-write the code. There is not a fundamental reason why they could be parallelized but we haven't prioritized them as they are usually not too long and they are I/O bound as you need a full pass through the ovl store. Running with corOutCoverage= 99999 will slow the step down somewhat since you're going to be trying to correct all the data, something we don't commonly recommend unless you have a metagenomci dataset. Both steps are low memory and should fit in under 8gb so you should be able to use a small instance to run them.

**Comment by jlim125** [comment]
Thanks for your comments!

We actually used ovsMemory=62 and ovbMemory=31 with x1e instances. Our genome looks like to have a lot of repeats which often have very high coverages, so I wanted to include all the data. Would you still recommend to use default (40) for the highly repetitive genome?

Do you think if higher memory would also benefit the ovStoreIndexer or correction step?

Best,
Jaechul

**Comment by skoren** [comment]
The default of 40x is fine for repetitive genomes, the main case when we recommend higher coverage is for very heterozygous genomes where the two haplotypes (or more) are very different, in which case you want enough coverage of all the haplotypes.

More memory wouldn't help these steps, no. It is possible to with some code changes to build the corStore in parallel which I detail below but this is not generally recommended or supported. First make the following code changes:
```
diff --git a/src/stores/tgStoreLoad.C b/src/stores/tgStoreLoad.C
index 4ee195fd9..a80113913 100644
--- a/src/stores/tgStoreLoad.C
+++ b/src/stores/tgStoreLoad.C
@@ -110,7 +110,7 @@ loadTigs(char const            *seqName,
     FILE *TI = AS_UTL_openInputFile(tigInputs[ff]);
 
     while (tig->loadFromStreamOrLayout(TI) == true) {
-      if (tig->numberOfChildren() > 0)                       //  Insert it!
+      if (tig->numberOfChildren() >= 0)                       //  Insert it!
         tigStore->insertTig(tig, false);
 
       else if (tigStore->isDeleted(tig->tigID()) == false)   //  Delete it!
diff --git a/src/stores/tgTig.C b/src/stores/tgTig.C
index cb8d5f0fc..09f202601 100644
--- a/src/stores/tgTig.C
+++ b/src/stores/tgTig.C
@@ -581,6 +581,8 @@ tgTig::loadLayout(FILE *F) {
         _class = tgTig_unassembled;
       else if (strcmp(W[1], "contig") == 0)
         _class = tgTig_contig;
+      else if (strcmp(W[1], "unsetc") == 0)
+        _class = tgTig_noclass;
       else
         fprintf(stderr, "tgTig::loadLayout()-- '%s' line " F_U64 " invalid: '%s'\n", W[0], LINEnum, LINE), exit(1);
```

Then you’d run generateCorrectionLayouts as Canu would (you can let it start and kill it to see the command line but use the -b and -e options):
```
generateCorrectionLayouts -S ../*seqStore/ -O *.ovlStore <whatever other parameters it has> -C part1 -b 1 -e 4000
generateCorrectionLayouts -S ../*seqStore/ -O *.ovlStore <whatever other parameters it has> -C part2 -b 4001 -e 8000
…
generateCorrectionLayouts -S ../*seqStore/ -O *.ovlStore <whatever other parameters it has> -C partN-b X -e <total number of reads>
```
You probably want more than 4000 reads per partition, pick some reasonable value. Then you’d need to dump and add all the partitions to one big store:

```
cp -r part1 <your asm prefix>.corStore
tgStoreDump -layout  -T part2 1 -S ../*seqStore/  |awk -v ID="" '{if (match($0, "tig ")) {if (ID != "") {while ($NF > ID+1) {ID++; print "tig -1\nlen\t0\ncns\nqlt\ntrimBgn\t0\ntrimEnd\t0\nclass\tunsetc\nsuggestRepeat\tF\nsuggestBubble\tF\nsuggestCircular\tF\ncircularLength\t0\nnumChildren\t0\ntigend"; } } ID=$NF; print "tig -1";} else { print $0; }}'  > part2.output
echo “part2.output” > inputList
tgStoreLoad -S ../*.seqStore/ -T <your asm prefix>.corStore 1 -L inputList
tgStoreDump -layout  -T part3 1 -S ../*seqStore/  |awk -v ID="" '{if (match($0, "tig ")) {if (ID != "") {while ($NF > ID+1) {ID++; print "tig -1\nlen\t0\ncns\nqlt\ntrimBgn\t0\ntrimEnd\t0\nclass\tunsetc\nsuggestRepeat\tF\nsuggestBubble\tF\nsuggestCircular\tF\ncircularLength\t0\nnumChildren\t0\ntigend"; } } ID=$NF; print "tig -1";} else { print $0; }}'  > part3.output
echo “part3.output” > inputList
tgStoreLoad -S ../*.seqStore/ -T <your asm prefix>.corStore 1 -L inputList
…
tgStoreDump -layout  -T partN 1 -S ../*seqStore/  |awk -v ID="" '{if (match($0, "tig ")) {if (ID != "") {while ($NF > ID+1) {ID++; print "tig -1\nlen\t0\ncns\nqlt\ntrimBgn\t0\ntrimEnd\t0\nclass\tunsetc\nsuggestRepeat\tF\nsuggestBubble\tF\nsuggestCircular\tF\ncircularLength\t0\nnumChildren\t0\ntigend"; } } ID=$NF; print "tig -1";} else { print $0; }}'  > partN.output
echo “partN.output” > inputList
tgStoreLoad -S ../*.seqStore/ -T <your asm prefix>.corStore 1 -L inputList
```

However, I'd recommend using CCS data instead of CLR data given how large and repetitive this genome is, as I said in my reply to your email.
