### ISSUE TITLE
Canu for bacterial genome assembly

### ISSUE THREAD

**Issue by rthapa1** [marbl/canu#1860]
Hi, I am doing bacterial gennome assembly with default parameters of canu. It seems like the final assembled genome has many misodered alignments. I wonder if tweaking the parameters help to improve the assembly. I would appreciate any suggestions. Thanks

**Comment by skoren** [comment]
Can't give advice without any info on your assembly.

- What version of canu?
- What is the full command line?
- What is your data type?
- How do you know they are mis-ordered?

**Comment by rthapa1** [comment]
Thank you for your reply. I am using canu-2.1.1. The full command is, 
/programs/canu-2.1.1/Linux-amd64/bin/canu useGrid=false -p ea -d ea-oxford genomeSize=3.8m -nanopore-raw long.fastq
The data is generated from nanopore sequencer and is in fastq format. I assembled the genome of a strain with canu for which the refernce genome is available. I checked the assembled genome with the refernce genome of the same strain using mauve and saw inversions which is unlikely to happen because it is the genome assembly of the samme strain from which refernce genome has been sequenced.

**Comment by skoren** [comment]
It is possible to make trimming more aggressive (in case these are chimeric reads) or assembly more conservative but I think you want to first make sure these are not real differences.

Are these large inversions or small (e.g. a few kb or megabases)? I wouldn't be surprised if the same strain had inversions due to repeat elements, even if it was the same source material that was allowed to grow between when the reference was generated and when it was sequenced. Very large inversions would be less expected but still possible, depending on the bacteria. Have you re-mapped the sequencing data to check coverage at the inversion locations? Is the coverage normal or low at those positions.

**Comment by rthapa1** [comment]
<img width="1436" alt="Screen Shot 2020-11-09 at 4 27 22 PM" src="https://user-images.githubusercontent.com/61608522/102152415-f2f77780-3e42-11eb-9af7-73fa5d624a63.png">

The inversions are few Kb but there are many inversions. Could you please check the attached image? Thanks

**Comment by skoren** [comment]
I don't normally use mauve so I'm not sure how to interpret the image, I think the large blocks are not inverted but just in a different order, is that right (I thought inversions appear below the line)? If that's the case and the genome is circular, there's no reason for canu to report it in the same order as the reference.

**Comment by rthapa1** [comment]
Thank you for your response. I wonder if there is a way to identify the origin of replication correctly during assembly of the circular genome by canu. I think the blocks are in different order because the origin of replication was not identified correctly. Do you have any suggestion? My ultimate goal is to identify structural variants after aligning the assembled genome correctly to the reference genome. Thanks

**Comment by skoren** [comment]
There's really no way to identify the origin of replication, unless you look for specific genes. Since the genome is circular there are reads spanning all coordinates equally well so where the assembly choses to start is random and arbitrary. Any rotation is an accurate representation of the genome as sequenced due to this. 

There are post-processing tools (like circlator) which will identify genes and rotate the assembly to a canonical start gene. You can also do it yourself based on alignments. Many SV tools also have support for circular genomes and so can ignore such differences in rotation so I don't see why the assembly you have, even rotated, wouldn't be suitable for SV calling.
