### ISSUE TITLE
Mhap precompute jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by YunxinFan** [marbl/canu#1863]
hello,I used the following command:

`bsub -o bo_canu_bsub_output.err canu -p bo_canu2 -d /gss1/home/yy20200615/bo_canu2 genomeSize=350m maxThreads=40 -pacbio rice.m64048_201207_040454.subreads.fasta.gz`

in a LSF grid,and my canu version is:

```
(base) [yy20200615@login ~/bo_canu_2]$ canu -version
canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)
```

and I met a error like this:

```
BEGIN CORRECTION
--
--
-- OVERLAPPER (mhap) (correction) complete, not rewriting scripts.
--
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000071.dat FAILED.
--

ABORT:
ABORT: canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

how should I resove the problem?? could I delete the 000071.dat and run on ?

**Comment by skoren** [comment]
This is usually an issue with the JVM or the interaction between the JVM and the grid (see #1764 for example). Check the log of the failed job (`correction/1-overlapper/*71*out`) for an error and post it here. You can also use the parameter listed there to increase the memory request for the MHAP job  if it is running out of memory, updating it to whatever is correct on your grid system.

**Comment by skoren** [comment]
Idle, no response, likely a JVM config issue.

**Comment by ardy20** [comment]
Hello Sergey

I faced the same problem using Canu 2.1.1. It might not be from JVM because I finished another assembly exactly with the same HPC system.
I increase the RAM to 350 Gb (for a 550 Mb plant genome) but still the problem persists.

I checked the last correction/1-overlapper/*71*out file. There is no Error.

Please see the logs below:

(base)  user@fl010:~> /scratch/project/qaafi-cnafs/canu-2.1.1-WRB/build/bin/canu -p canu -d /scratch/project/qaafi-cnafs/canu-2.1.1-WRB/outdir_clr_TaxB genomeSize=550m -fast useGrid=remote gridOptions="--mem-per-cpu=13g" -pacbio /scratch/project/qaafi-cnafs/canu-2.1.1-WRB/m64137_201104_025231_sub.fasta.gz
-- canu 2.1.1
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
--
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
--
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
--
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
--
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_101' (from '/usr/java/latest/bin/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 24 CPUs and 504 gigabytes of memory.
-- Detected PBSPro '18.1.2' with 'pbsnodes' binary in /opt/pbs/bin/pbsnodes.
-- Detecting PBSPro resources.
--
-- Found   1 host  with  24 cores and 3976 GB memory under PBSPro control.
-- Found  24 hosts with  24 cores and  503 GB memory under PBSPro control.
-- Found   1 host  with  24 cores and 2478 GB memory under PBSPro control.
-- Found  13 hosts with  24 cores and  500 GB memory under PBSPro control.
-- Found   1 host  with  48 cores and  500 GB memory under PBSPro control.
-- Found   1 host  with  24 cores and  440 GB memory under PBSPro control.
-- Found   1 host  with  24 cores and  956 GB memory under PBSPro control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     24.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       12.000 GB   24 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   32.000 GB   12 CPUs  (overlap detection with mhap)
-- Grid:  obtmhap   32.000 GB   12 CPUs  (overlap detection with mhap)
-- Grid:  utgmhap   32.000 GB   12 CPUs  (overlap detection with mhap)
-- Grid:  cor       16.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
--
-- In 'canu.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Raw:                      1
--   Corrected:                1
--
-- Generating assembly 'canu' in '/scratch/project_mnt/S0030/canu-2.1.1-WRB/outdir_clr_TaxB':
--    - trim corrected reads.
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        550000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN TRIMMING
--
--
-- OVERLAPPER (mhap) (trimming) complete, not rewriting scripts.
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'obtmhap' concurrent execution on Fri Sep 10 17:45:09 2021 with 1019826.421 GB free disk space (1 processes; 1 concurrently)

    cd trimming/1-overlapper
    ./precompute.sh 77 > ./precompute.000077.out 2>&1

-- Finished on Fri Sep 10 17:45:09 2021 (in the blink of an eye) with 1019826.421 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job trimming/1-overlapper/blocks/000077.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'obtmhap' concurrent execution on Fri Sep 10 17:45:09 2021 with 1019826.406 GB free disk space (1 processes; 1 concurrently)

    cd trimming/1-overlapper
    ./precompute.sh 77 > ./precompute.000077.out 2>&1

-- Finished on Fri Sep 10 17:45:09 2021 (like a bat out of hell) with 1019826.406 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job trimming/1-overlapper/blocks/000077.dat FAILED.
--

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

> tail precompute.000083.out
Current # sequences loaded and processed from file: 110000...
Current # sequences loaded and processed from file: 115000...
Current # sequences loaded and processed from file: 120000...
Current # sequences loaded and processed from file: 125000...
Current # sequences loaded and processed from file: 130000...
Current # sequences loaded and processed from file: 135000...
Processed 138566 sequences (fwd and rev).
Read, hashed, and stored file ./000083.input.fasta to ./000083.input.dat.
Time (s): 1417.643140928
Total time (s): 1417.643299021

**Comment by skoren** [comment]
The failing job isn't 83 but 77, post the log from `trimming/1-overlapper/precompute.000077.out`. Also post `trimming/1-overlapper/partitioning.log`

**Comment by ardy20** [comment]
Hello Sergey

Yes, please see below:

 cat precompute.000077.out

Found perl:
   /bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/java/latest/bin/java
   java version "1.8.0_101"

Found canu:
   /scratch/project_mnt/S0030/canu-2.1.1-WRB/build/bin/canu
   canu 2.1.1

Running job 77 based on command line options.
/scratch/project_mnt/S0030/canu-2.1.1-WRB/outdir_clr_TaxB/trimming/1-overlapper
Opened seqStore '../../canu.seqStore' for 'corrected' reads.
Dumping corrected reads from 6566401 to 6652800 (inclusive).
Failed to extract fasta.

> cat partitioning.log
Job 1 computes block 1 vs blocks 2-22 (and self),
Job 2 computes block 1 vs blocks 23-43,
Job 3 computes block 1 vs blocks 44-64,
Job 4 computes block 1 vs blocks 65-84,
Job 5 computes block 2 vs blocks 3-23 (and self),
Job 6 computes block 2 vs blocks 24-44,
Job 7 computes block 2 vs blocks 45-65,
Job 8 computes block 2 vs blocks 66-84,
Job 9 computes block 3 vs blocks 4-24 (and self),
Job 10 computes block 3 vs blocks 25-45,
Job 11 computes block 3 vs blocks 46-66,
Job 12 computes block 3 vs blocks 67-84,
Job 13 computes block 4 vs blocks 5-25 (and self),
Job 14 computes block 4 vs blocks 26-46,
Job 15 computes block 4 vs blocks 47-67,
Job 16 computes block 4 vs blocks 68-84,
Job 17 computes block 5 vs blocks 6-26 (and self),
Job 18 computes block 5 vs blocks 27-47,
Job 19 computes block 5 vs blocks 48-68,
Job 20 computes block 5 vs blocks 69-84,
Job 21 computes block 6 vs blocks 7-27 (and self),
Job 22 computes block 6 vs blocks 28-48,
Job 23 computes block 6 vs blocks 49-69,
Job 24 computes block 6 vs blocks 70-84,
Job 25 computes block 7 vs blocks 8-28 (and self),
Job 26 computes block 7 vs blocks 29-49,
Job 27 computes block 7 vs blocks 50-70,
Job 28 computes block 7 vs blocks 71-84,
Job 29 computes block 8 vs blocks 9-29 (and self),
Job 30 computes block 8 vs blocks 30-50,
Job 31 computes block 8 vs blocks 51-71,
Job 32 computes block 8 vs blocks 72-84,
Job 33 computes block 9 vs blocks 10-30 (and self),
Job 34 computes block 9 vs blocks 31-51,
Job 35 computes block 9 vs blocks 52-72,
Job 36 computes block 9 vs blocks 73-84,
Job 37 computes block 10 vs blocks 11-31 (and self),
Job 38 computes block 10 vs blocks 32-52,
Job 39 computes block 10 vs blocks 53-73,
Job 40 computes block 10 vs blocks 74-84,
Job 41 computes block 11 vs blocks 12-32 (and self),
Job 42 computes block 11 vs blocks 33-53,
Job 43 computes block 11 vs blocks 54-74,
Job 44 computes block 11 vs blocks 75-84,
Job 45 computes block 12 vs blocks 13-33 (and self),
Job 46 computes block 12 vs blocks 34-54,
Job 47 computes block 12 vs blocks 55-75,
Job 48 computes block 12 vs blocks 76-84,
Job 49 computes block 13 vs blocks 14-34 (and self),
Job 50 computes block 13 vs blocks 35-55,
Job 51 computes block 13 vs blocks 56-76,
Job 52 computes block 13 vs blocks 77-84,
Job 53 computes block 14 vs blocks 15-35 (and self),
Job 54 computes block 14 vs blocks 36-56,
Job 55 computes block 14 vs blocks 57-77,
Job 56 computes block 14 vs blocks 78-84,
Job 57 computes block 15 vs blocks 16-36 (and self),
Job 58 computes block 15 vs blocks 37-57,
Job 59 computes block 15 vs blocks 58-78,
Job 60 computes block 15 vs blocks 79-84,
Job 61 computes block 16 vs blocks 17-37 (and self),
Job 62 computes block 16 vs blocks 38-58,
Job 63 computes block 16 vs blocks 59-79,
Job 64 computes block 16 vs blocks 80-84,
Job 65 computes block 17 vs blocks 18-38 (and self),
Job 66 computes block 17 vs blocks 39-59,
Job 67 computes block 17 vs blocks 60-80,
Job 68 computes block 17 vs blocks 81-84,
Job 69 computes block 18 vs blocks 19-39 (and self),
Job 70 computes block 18 vs blocks 40-60,
Job 71 computes block 18 vs blocks 61-81,
Job 72 computes block 18 vs blocks 82-84,
Job 73 computes block 19 vs blocks 20-40 (and self),
Job 74 computes block 19 vs blocks 41-61,
Job 75 computes block 19 vs blocks 62-82,
Job 76 computes block 19 vs blocks 83-84,
Job 77 computes block 20 vs blocks 21-41 (and self),
Job 78 computes block 20 vs blocks 42-62,
Job 79 computes block 20 vs blocks 63-83,
Job 80 computes block 20 vs blocks 84-84,
Job 81 computes block 21 vs blocks 22-42 (and self),
Job 82 computes block 21 vs blocks 43-63,
Job 83 computes block 21 vs blocks 64-84,
Job 84 computes block 22 vs blocks 23-43 (and self),
Job 85 computes block 22 vs blocks 44-64,
Job 86 computes block 22 vs blocks 65-84,
Job 87 computes block 23 vs blocks 24-44 (and self),
Job 88 computes block 23 vs blocks 45-65,
Job 89 computes block 23 vs blocks 66-84,
Job 90 computes block 24 vs blocks 25-45 (and self),
Job 91 computes block 24 vs blocks 46-66,
Job 92 computes block 24 vs blocks 67-84,
Job 93 computes block 25 vs blocks 26-46 (and self),
Job 94 computes block 25 vs blocks 47-67,
Job 95 computes block 25 vs blocks 68-84,
Job 96 computes block 26 vs blocks 27-47 (and self),
Job 97 computes block 26 vs blocks 48-68,
Job 98 computes block 26 vs blocks 69-84,
Job 99 computes block 27 vs blocks 28-48 (and self),
Job 100 computes block 27 vs blocks 49-69,
Job 101 computes block 27 vs blocks 70-84,
Job 102 computes block 28 vs blocks 29-49 (and self),
Job 103 computes block 28 vs blocks 50-70,
Job 104 computes block 28 vs blocks 71-84,
Job 105 computes block 29 vs blocks 30-50 (and self),
Job 106 computes block 29 vs blocks 51-71,
Job 107 computes block 29 vs blocks 72-84,
Job 108 computes block 30 vs blocks 31-51 (and self),
Job 109 computes block 30 vs blocks 52-72,
Job 110 computes block 30 vs blocks 73-84,
Job 111 computes block 31 vs blocks 32-52 (and self),
Job 112 computes block 31 vs blocks 53-73,
Job 113 computes block 31 vs blocks 74-84,
Job 114 computes block 32 vs blocks 33-53 (and self),
Job 115 computes block 32 vs blocks 54-74,
Job 116 computes block 32 vs blocks 75-84,
Job 117 computes block 33 vs blocks 34-54 (and self),
Job 118 computes block 33 vs blocks 55-75,
Job 119 computes block 33 vs blocks 76-84,
Job 120 computes block 34 vs blocks 35-55 (and self),
Job 121 computes block 34 vs blocks 56-76,
Job 122 computes block 34 vs blocks 77-84,
Job 123 computes block 35 vs blocks 36-56 (and self),
Job 124 computes block 35 vs blocks 57-77,
Job 125 computes block 35 vs blocks 78-84,
Job 126 computes block 36 vs blocks 37-57 (and self),
Job 127 computes block 36 vs blocks 58-78,
Job 128 computes block 36 vs blocks 79-84,
Job 129 computes block 37 vs blocks 38-58 (and self),
Job 130 computes block 37 vs blocks 59-79,
Job 131 computes block 37 vs blocks 80-84,
Job 132 computes block 38 vs blocks 39-59 (and self),
Job 133 computes block 38 vs blocks 60-80,
Job 134 computes block 38 vs blocks 81-84,
Job 135 computes block 39 vs blocks 40-60 (and self),
Job 136 computes block 39 vs blocks 61-81,
Job 137 computes block 39 vs blocks 82-84,
Job 138 computes block 40 vs blocks 41-61 (and self),
Job 139 computes block 40 vs blocks 62-82,
Job 140 computes block 40 vs blocks 83-84,
Job 141 computes block 41 vs blocks 42-62 (and self),
Job 142 computes block 41 vs blocks 63-83,
Job 143 computes block 41 vs blocks 84-84,
Job 144 computes block 42 vs blocks 43-63 (and self),
Job 145 computes block 42 vs blocks 64-84,
Job 146 computes block 43 vs blocks 44-64 (and self),
Job 147 computes block 43 vs blocks 65-84,
Job 148 computes block 44 vs blocks 45-65 (and self),
Job 149 computes block 44 vs blocks 66-84,
Job 150 computes block 45 vs blocks 46-66 (and self),
Job 151 computes block 45 vs blocks 67-84,
Job 152 computes block 46 vs blocks 47-67 (and self),
Job 153 computes block 46 vs blocks 68-84,
Job 154 computes block 47 vs blocks 48-68 (and self),
Job 155 computes block 47 vs blocks 69-84,
Job 156 computes block 48 vs blocks 49-69 (and self),
Job 157 computes block 48 vs blocks 70-84,
Job 158 computes block 49 vs blocks 50-70 (and self),
Job 159 computes block 49 vs blocks 71-84,
Job 160 computes block 50 vs blocks 51-71 (and self),
Job 161 computes block 50 vs blocks 72-84,
Job 162 computes block 51 vs blocks 52-72 (and self),
Job 163 computes block 51 vs blocks 73-84,
Job 164 computes block 52 vs blocks 53-73 (and self),
Job 165 computes block 52 vs blocks 74-84,
Job 166 computes block 53 vs blocks 54-74 (and self),
Job 167 computes block 53 vs blocks 75-84,
Job 168 computes block 54 vs blocks 55-75 (and self),
Job 169 computes block 54 vs blocks 76-84,
Job 170 computes block 55 vs blocks 56-76 (and self),
Job 171 computes block 55 vs blocks 77-84,
Job 172 computes block 56 vs blocks 57-77 (and self),
Job 173 computes block 56 vs blocks 78-84,
Job 174 computes block 57 vs blocks 58-78 (and self),
Job 175 computes block 57 vs blocks 79-84,
Job 176 computes block 58 vs blocks 59-79 (and self),
Job 177 computes block 58 vs blocks 80-84,
Job 178 computes block 59 vs blocks 60-80 (and self),
Job 179 computes block 59 vs blocks 81-84,
Job 180 computes block 60 vs blocks 61-81 (and self),
Job 181 computes block 60 vs blocks 82-84,
Job 182 computes block 61 vs blocks 62-82 (and self),
Job 183 computes block 61 vs blocks 83-84,
Job 184 computes block 62 vs blocks 63-83 (and self),
Job 185 computes block 62 vs blocks 84-84,
Job 186 computes block 63 vs blocks 64-84 (and self),
Job 187 computes block 64 vs blocks 65-84 (and self),
Job 188 computes block 65 vs blocks 66-84 (and self),
Job 189 computes block 66 vs blocks 67-84 (and self),
Job 190 computes block 67 vs blocks 68-84 (and self),
Job 191 computes block 68 vs blocks 69-84 (and self),
Job 192 computes block 69 vs blocks 70-84 (and self),
Job 193 computes block 70 vs blocks 71-84 (and self),
Job 194 computes block 71 vs blocks 72-84 (and self),
Job 195 computes block 72 vs blocks 73-84 (and self),
Job 196 computes block 73 vs blocks 74-84 (and self),
Job 197 computes block 74 vs blocks 75-84 (and self),
Job 198 computes block 75 vs blocks 76-84 (and self),
Job 199 computes block 76 vs blocks 77-84 (and self),
Job 200 computes block 77 vs blocks 78-84 (and self),
Job 201 computes block 78 vs blocks 79-84 (and self),
Job 202 computes block 79 vs blocks 80-84 (and self),
Job 203 computes block 80 vs blocks 81-84 (and self),
Job 204 computes block 81 vs blocks 82-84 (and self),
Job 205 computes block 82 vs blocks 83-84 (and self),
Job 206 computes block 83 vs blocks 84-84 (and self),
Job 207 computes block 84 vs itself.

**Comment by skoren** [comment]
That looks like there might be some corruption in the read store. Is this a restart of another assembly or is it possible multiple assemblies ran in this same folder? Try running the dump command manually:
```
sqStoreDumpFASTQ -nolibname -noreadname -fasta -o tmp -r 6566401-6652800 outdir_clr_TaxB/*.sqStore
sqStoreDumpMetaData -reads -r 6566401-6652800 outdir_clr_TaxB/*.sqStore
```
and report any errors. Also post the contents of `outdir_clr_TaxB/*.sqStore`.

**Comment by ardy20** [comment]
Thanks Sergey! This is actually a resumed work but in a separate folder. I will run with the command above and post updates soon.

**Comment by ardy20** [comment]
Sorry, the dump command did not work and I am re-running the assembly.

**Comment by skoren** [comment]
I'd suggest starting after correction since you should have `*.correctedReads.fasta.gz` in your folder rather than starting from scratch. Use something like `canu -p canu -d restart genomeSize=550m -fast useGrid=remote gridOptions="--mem-per-cpu=13g" -corrected -pacbio /scratch/project/qaafi-cnafs/canu-2.1.1-WRB/outdir_clr_TaxB/canu.correctedReads.fasta.gz` (add the -corrected and point to the corrected reads instead of the initial input).
