### ISSUE TITLE
The canu can't make full use of the data

### ISSUE THREAD

**Issue by Olympusmons123** [marbl/canu#1865]
I have a file that includes about 6000 sequencing sequences，and I want to synthesis of a 30000 DNA base. But when I use the canu to synthesize, it only uses part of the date, about 3500. I try to change the data of corOutCoverage, but it doesn't work. 
  this is the 
```
canu -correct \
    -p ecoli -d ecoli-oxford \
    corThreads=32 corOutCoverage=400 corMinCoverage=2 \
    genomeSize=29903 minReadLength=200 minOverlapLength=50 \
    maxMemory=50g maxThreads=16 \
    ovsMemory=1-32G ovsThreads=16 ovsConcurrency=16 \
    ovbMemory=1g ovbConcurrency=16 oeaThreads=16 \
    -nanopore-raw 10.fasta
```
when I change different corOutCoverage, even the same parameters will have different results。

here is the different result, 
```
(1)-- In sequence store './ecoli.seqStore':
--   Found 3554 reads.
--   Found 5982292 bases (200.05 times coverage).
(2)-- In sequence store './ecoli.seqStore':
--   Found 3511 reads.
--   Found 5980825 bases (200 times coverage).
 you can see it only uses part of the data about 3500/6288, I want to make full use of it.
```

[10.zip](https://github.com/marbl/canu/files/5722185/10.zip)

**Comment by skoren** [comment]
Based on your genome size, this looks like an amplicon or small viral genome. There are two parameters that control the data, corOutCoverage controls how much is corrected while readSamplingCoverage/maxInputCoverage control how much total data is input. The default is to downsample to 200x for raw data and 50x for hifi data (https://canu.readthedocs.io/en/latest/faq.html?highlight=readSamplingCoverage#can-i-assemble-amplicon-sequence-data, https://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=readSamplingCoverage#global-options). If you increase readSamplingCoverage the full data will be used. 

However, the reason we downsample is because it is not beneficial to increase coverage over the defaults, you will increase computational time and will likely make your assembly worse not better.
