### ISSUE TITLE
Racon after Canu

### ISSUE THREAD

**Issue by SShivani22** [marbl/canu#1876]
Hi guys... it is my first work with canu, so please excuse my basic questions.
I want to polish canu data using racon. following are my concerns:
- for "overlap sequences" in racon, I should use the canu output "trimmed reads", right?
- the acceptable formats for "overlapped sequences" are MHAP, PAF and SAM. Can anyone suggest how to change canu's FASTA output to any of these formats? 

Thanks so much:)

**Comment by skoren** [comment]
I wouldn't advice polishing Canu with Racon, it's unlikely to yield any benefit since it is using the same input data. Typically we run a technology-specific polishing tool (like Arrow for PacBio or Medaka/Nanopolish for ONT).

If you do run racon, give it the raw reads, not the trimmed reads output. The overlapped sequences wouldn't come from Canu. You would take the Canu contigs.fasta file and align the raw reads to them using minimap2/winnowmap to generate the paf or sam inputs for racon.
