### ISSUE TITLE
Assembling reads without error

### ISSUE THREAD

**Issue by jakewendt** [marbl/canu#1877]
I am developing a script to simulate reads by taking a small (5mb) section of hg38 and randomly selecting regions in length from 1000bp to 15,000bp. Eventually I was going to add random error to these reads, however I wanted to try to reassemble these reads first for comparison. I had hoped that the result would be the initially selected sequence.

I selected 20,000 reads generating a 160mb `nanopore.exact.fasta`

If I run it simply with ...
```
canu -p nano -d nano genomeSize=5m useGrid=false -nanopore nanopore.exact.fasta
```
... it completes in about an hour but many reads are "corrected" and some end up unassembled.

Since I know this data has no errors, I thought that I'd try setting the error rate options to 0.
```
canu -p nano -d nano genomeSize=5m useGrid=false -nanopore nanopore.exact.fasta rawErrorRate=0 correctedErrorRate=0
```
Unfortunately, this creates no "corrected" reads and then no assembly happens.

I've tried to assemble them using the `-assemble` option, but that doesn't work either.

Is there a way to assemble reads without modification with `canu`?

**Comment by skoren** [comment]
I think setting error rate to 0 might not work correctly since canu auto-determines the actual threshold down from the max limit. You should supply these reads as `-corrected -trimmed -nanopore nanopore.extract.fasta`. That will skip the correction and the trimming steps. You can set correctedErrorRate low, maybe 0.01 or so and it will be adjusted down automatically from that.

**Comment by jakewendt** [comment]
Thank you. Trying it now.
