### ISSUE TITLE
High coverage OXN data as input

### ISSUE THREAD

**Issue by YuanwenGuo** [marbl/canu#1885]
Hello,

I am trying to assembly a few plasmids with super high coverage OXN sequence (~3000X). The reason of such high coverage data is these plasmids are pretty similar to each other except for a few hundreds bp of insertion or deletion. I already decreased correctedErrorRate to 0.1, and add -fast option to speed up assembly, but it still takes a lot of time during trimming. Should I adjust Canu parameters further, or do randomly downsampling with readSamplingCoverage? My current commands are as follows:

canu maxMemory=80 redMemory=50 oeaMemory=50 gridOptions="--time=100:00:00 --partition=*** -p $prefix -d $dir genomeSize=320k correctedErrorRate=0.1 gnuplotTested=true -nanopore-raw $OXN_file -fast

Thanks a lot for the help!

Best,
Yuanwen

**Comment by skoren** [comment]
3000x is still going to be slow, even when you use fast because there will be lots of reads to correct and lots of redundant overlaps. Randomly downsampling is a good idea. You could generate a downsampled assembly, map all reads and call variants against this assembly, and then do targeted assembly of reads showing variants to get the lower frequency variations that the downsampling misses.

**Comment by YuanwenGuo** [comment]
Thank you for the suggestion! We will try and see how it turns out.

Best,
Yuanwen
