### ISSUE TITLE
Issue: Task bat can't run on any available machines.

### ISSUE THREAD

**Issue by Stephkoo** [marbl/canu#1893]
I ran on WSL (Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.):

canu -correct -p hla -d GRCh38_latest_genomic.fna genomeSize=3.1g -nanopore-raw consolidated_fastq_pass_copy.fastq
```
And got the following issue:
-- Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.
-- Detected Java(TM) Runtime Environment '1.8.0_92' (from '/home/stephkoo/anaconda3/bin/java').
-- Detected gnuplot version '4.6 patchlevel 0' (from 'gnuplot') and image format 'svg'.
-- Detected 8 CPUs and 25 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Task bat can't run on any available machines.
-- It is requesting 128-512 GB memory and 8-32 threads.
-- See above for hardware limits.
--
Undefined subroutine &canu::Configure::caExit called at /home/stephkoo/anaconda3/libexec/lib/canu/Configure.pm line 316.
```
Would you let me know where it went wrong?

Thanks!

Steph

**Comment by skoren** [comment]
The bat task is trying to use between 128-512 gb of memory given your genome size. However, since you're only running the correction step, you don't need this step. Set `batMemory=25` and it should run. In general, running correction on a 3gb genome with only 8 cpus and 25gb of memory will take a very long time.
