### ISSUE TITLE
canu-2.1.1: This JVM package only includes the '-Xcompressedrefs' configuration.

### ISSUE THREAD

**Issue by mmokrejs** [marbl/canu#1896]
Hi,
  it is difficult to understand the error messages

```
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
...
```

At least it should have pointed out to the relevant error log file, e.g. `correction/1-overlapper/precompute.000001.out`.

From other issues on github #1499 , #1339, #1087 , #1074 , #1043 I learned where to look for the real message.

```
cat correction/1-overlapper/precompute.000001.out

Found java:
   /cvmfs/software.metacentrum.cz/spack1/software/openjdk/linux-debian10-x86_64/1.8.0_222-b10-intel-xc66un/bin/java
   openjdk version "1.8.0_222"

Found canu:
   /auto/plzen1/home/mmokrejs/apps/canu-2.1.1/build/bin/canu
   canu 2.1.1

Running job 1 based on command line options.
/auto/brno1-cerit/nfs4/home/mmokrejs/mygenome/mygenome_canu_2.1.1_correctedErrorRate_0.16_v2/correction/1-overlapper
Opened seqStore '../../mygenome.seqStore' for 'raw' reads.
Dumping raw reads from 1 to 86400 (inclusive).

Starting mhap precompute.

Selected VM [default] does not exist.
This JVM package only includes the '-Xcompressedrefs' configuration. Please run the VM without specifying the '-Xnocompressedrefs' option or by specifying the '-Xcompressedrefs' option.
To compile the other configuration, please run configure with '--with-noncompressedrefs.
Mhap failed.
```

Now my question is. Does this speak about `openjdk` being compiled in a `wrong` way? I assume '-Xcompressedrefs' will use compressed references and ssummingly have smaller memory footprint. What is the recommended approach? How is `canu` calling the java vm?

In other github threads `JAVA_OPTIONS` and `JAVA_OPTS` were pointed out. Why canu does not check for these in the begginnings of it exections and log the settings somewhere in a single place?

Please drop the message:

```
ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

It is just confusing.

**Comment by mmokrejs** [comment]
I see `correction/1-overlapper/mhap.sh` containing:

```
if [ ! -e $outPath/$qry.mhap ] ; then
  /cvmfs/software.metacentrum.cz/spack1/software/openjdk/linux-debian10-x86_64/1.8.0_222-b10-intel-xc66un/bin/java -d64 -XX:ParallelGCThreads=16 -server -Xms58982m -Xmx58982m \
    -jar  $bin/../share/java/classes/mhap-2.1.3.jar  \
    --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 \
    --store-full-id \
    --num-hashes 768 \
    --num-min-matches 2 \
    --threshold 0.73 \
    --filter-threshold 0.0000001 \
    --ordered-sketch-size 1536 \
    --ordered-kmer-size 12 \
    --min-olap-length 500 \
    --num-threads 16 \
    -s  ./blocks/$blk.dat $slf  \
    -q  queries/$qry  \
  > $outPath/$qry.mhap.WORKING \
  && \
  mv -f $outPath/$qry.mhap.WORKING $outPath/$qry.mhap
fi
```

Meanwhile I tried to use openjdk-11 to see if the error is mysteriously avoided.

**Comment by skoren** [comment]
I don't see anything wrong in Canu's command. JAVA_OPTS aren't really relevant, they are only needed if you want to over-write any user specified defaults, which isn't the normal practice. Canu isn't requesting anything related to `-Xcompressedrefs`, so that's coming from your system/JVM configuration. 

If you google the error message from the JVM there is this in the documentation: https://www.eclipse.org/openj9/docs/xcompressedrefs/ and a GitHub issue: https://github.com/eclipse/openj9/issues/479. So your JVM seems to have been built to not allow >57 Gb heap sizes. I've not seen this in any other JMV, this seems specific to certain builds/versions of openJDK. I think lowering how much memory Canu uses for this step with `mhapMemory=48` should work around the JVM or you could see the instructions in the JDK documentation I found which specifies how to build support for both compressed and uncompressed refs.

**Comment by mmokrejs** [comment]
Hi @skoren,
  thank you for your quick answer. I will try to lower the `mhapMemory=48`, thank you for the tip. Meanwhile, switching just to openjdk-11.0.2 did not help, for some reason `-d64` was detected by canu initially but later JVM chokes on this.

```
Found perl:
   /usr/bin/perl
   This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /cvmfs/software.metacentrum.cz/spack1/software/openjdk/linux-centos7-x86_64/11.0.2-gcc-adsf52/bin/java
   openjdk version "11.0.2" 2019-01-15

Found canu:
   /auto/plzen1/home/mmokrejs/apps/canu-2.1.1/build/bin/canu
   canu 2.1.1

Running job 1 based on command line options.
/auto/brno1-cerit/nfs4/home/mmokrejs/mygenome_canu_2.1.1_correctedErrorRate_0.16_v2/correction/1-overlapper
Opened seqStore '../../mygenome.seqStore' for 'raw' reads.
Dumping raw reads from 1 to 86400 (inclusive).

Starting mhap precompute.

Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Mhap failed.
```

I do not understand why 1.8.0_222 is mentioned in the `STDERR` output from `torque` below:

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_222' (from '/cvmfs/software.metacentrum.cz/spack1/software/openjdk/linux-centos7-x86_64/11.0.2-gcc-adsf52/bin/java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 6   ' (from 'gnuplot') and image format 'png'.
-- Detected 128 CPUs and 2004 gigabytes of memory.
-- Detected PBSPro '19.0.0' with 'pbsnodes' binary in /usr/bin/pbsnodes.
-- Grid engine and staging disabled per useGrid=false option.
```

**Comment by skoren** [comment]
Glad that it worked. I checked and Canu is properly using java to check the availability of the `-d64` option (I ran it using OpenJDK 11), I suspect you have both JDK 8 (which supports the option) and JDK 11 (which does not) available and different nodes are defaulting to different versions leading to the flag being included. The best way to avoid that is to explicitly give a path to java to canu using the `java` parameter. Since the original issue was also a build issue with the JDK not Canu I'm closing this issue.
