### ISSUE TITLE
Detected Java(TM) Runtime Environment '1.8.0_281' (from '/data/liqingmei/tools/jdk1.8.0_281/bin/java') without -d64 support.

### ISSUE THREAD

**Issue by li0604** [marbl/canu#1922]
Hi everyone,
When I run the Canu correct, there is an error was given. I have try my best to download the java fit with linux 64bit system, but it did not work. Would you give me some help?

Thanks in advance.

The script and error were showed as following:
![L2~~$Z9W%LBP_I2I_LZS2WY](https://user-images.githubusercontent.com/54136123/112160499-2f4a2900-8c25-11eb-8b6b-07bc9127e51c.png)

![AN}TJ_`T)2D23 }MU$WI5YV](https://user-images.githubusercontent.com/54136123/112160641-5143ab80-8c25-11eb-8de5-2973cc3527f9.png)

**Comment by skoren** [comment]
This doesn't looked related to java, the issue is your PBS node is missing standard programs which Canu uses to query the grid. It's likely your issue is this: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs. 

You should check with your IT if your compute nodes are allowed to submit jobs. If not, you will have to run with either `useGrid=false` or `useGrid=remote` as listed the FAQ.

**Comment by li0604** [comment]
Dear professor,


Thanks for your help. I will have a try according your suggestion and read the likely issue.


Thank you very much.


Yours sincerely,


Qingmei Li













在 2021-03-24 00:39:11，"Sergey Koren" ***@***.***> 写道：

This doesn't looked related to java, the issue is your PBS node is missing standard programs which Canu uses to query the grid. It's likely your issue is this: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs.

You should check with your IT if your compute nodes are allowed to submit jobs. If not, you will have to run with either useGrid=false or useGrid=remote as listed the FAQ.

**Comment by skoren** [comment]
Idle
