### ISSUE TITLE
Low coverage CCS reads

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1926]
Hi,

We have low coverage CCS reads (human) about 16X; we used canu default setting of  '-pacbiohifi' to do the assembling job. It finished, but we have inflated genome size, which is about 5G. Is this because of the low coverage? If so, is there any parameter we can tune up to do the job? Or we do need 20-25X coverage.

Thanks!

George

**Comment by skoren** [comment]
Nothing to do with coverage, this is expected for HiFi data since HiCanu will separate and assemble both haplotypes in the genome.  See: https://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads and https://canu.readthedocs.io/en/latest/faq.html#my-genome-size-and-assembly-size-are-different-help and related issues like #1836 and #1817. Typically, you should run purge_dups on the full output though you may get close to a haploid genome by removing anything marked as a bubble in the fasta defline of the contigs.fasta output.
