### ISSUE TITLE
Parameters for HiFi reads and similar plasmids

### ISSUE THREAD

**Issue by mcombs33** [marbl/canu#1950]
Hello,

I'm using canu v2.1.1 to assemble a bacterial genome with pacbio HiFi reads. This bacteria has quite a few (10-20) plasmids, many of which are short (10-30kb) and very similar to one another (phage derived). I'm wondering what parameter adjustments might be useful to make the assembly more conservative in order to improve confidence that the highly similar plasmids have been correctly assembled? I'm thinking about increasing the minOverlapLength, or adjusting the readSamplingBias. Initially I considered setting corOutCoverage=999, but I don't think this applies for HiFi reads, which are already corrected. Any advice is highly appreciated!

Here is the code used to generate an initial assembly with default parameters using canu v2.1.1:
./canu -d BC19-crct-default genomeSize=1.5m -p BC19-crct-default -pacbio-hifi BC19.filtered.ccs.fastq

I'm running this on a linux Google Cloud Platform VM.

I haven't found many good examples of others dealing with this issuue. Thanks for your help.

**Comment by skoren** [comment]
I'm not sure what you mean have confidence that the plasmids are correctly assembled. With HiFi data, you can separate repeats close to 1 in 10 kbp which is down to just a couple of differences between the plasmids. They're also relatively short in relation to the read lengths and should be spanned by just 1-2 reads assuming a 15kb library. I'd be relatively confident in the default parameters and just validate the results by checking read re-alignments.

You could try increasing ovlSize to 1 or 2 kb, decreasing correctedErrorRate from 0.01 to 0.005 but I don't think these will make much difference since the default is already using perfect or near perfect overlaps (you can confirm this in the report). You can set maxInputCoverage to higher than the default of 50 if you have high coverage but this will likely also mean you'll get some more noise from the errors in HiFi data which will cause these reads to form their own contigs.

**Comment by skoren** [comment]
Idle
