### ISSUE TITLE
I installed Canu 2.1 on Linux, but only get version 1.6, why? and how to fix it?

### ISSUE THREAD

**Issue by Jenny-SRA** [marbl/canu#1954]
Hello Canu community, I installed the latest Canu 2.11 version on my Linux through the recommend binary file download. 
Once downloaded, I run the following commands to install:
$tar -xJf canu-2.1.1.*.tar.xz
$sudo apt install canu

Everything seems ok. then I checked the version by:
$canu -version
It is Canu 1.6, instead of Canu2.1

I tried few version, Canu 1.8, Canu2.0 and tried to install on another Linux computer. all the same, I can only get Canu1.6.

I do need higher version as the correction run failed at last step (Mhap precompute jobs failed). and one of the recommendation is to use higher version of Canu.

what can I do to install Canu2.1? many thanks in advance.

**Comment by skoren** [comment]
The issue is sudo apt install canu isn't related to your download. Instead, give the full path to where you downloaded and extracted the 2.1.1 binary (as listed on the releases page), something like `<full path to where you downloaded tar.gz>/canu-2.1.1/bin/canu -version` and it should report the right version. You can prepend the bin location to your PATH variable so just canu will run the latest version.

```

**Comment by Jenny-SRA** [comment]
Thank you Skoren, I did not realize that there is no need to use the "sudo apt install" function at all. As you mentioned, providing the full path works. may I have one more question regarding the genome size? I sequenced enriched fragment, in a small region. should I use the real genome size or just the enriched region length? I feel the later is more accurate. Thanks.

**Comment by skoren** [comment]
I'd use the enriched fragment size. In general, the genome size doesn't do much, it mainly controls downsampling of very high-coverage datasets and sets some default parameters. The default max coverage is 200x so you will likely get random downsampling of your data (which I recommend because you don't need to assemble very very high coverage). You can adjust this with maxInputCoverage if you wanted to try higher coverage assemblies.
