### ISSUE TITLE
LSF queue dwontime

### ISSUE THREAD

**Issue by Kai-Maker1** [marbl/canu#1962]
Using canu2.1, my script is ‘canu -p test -d test_pacbio_clr1 genomeSize=600m executiveMemory=16 -pacbio test.fasta.gz’，running in LSF job scheduling system。

Hello Canu community，
        The node submitted is a high-memory node, but after canu runs, it automatically adapts to a high-computing and low-memory node. As a result, the low-memory node cannot meet the 16g requirement of running memory, resulting in queue downtime. Is there a global parameter control problem in canu? Does the parameter useGrid=true can control this problem？
         What is the default minimum thread of Canu? Is there a distinction between sub-threads and total threads? Now it is set to execute memory 16g, which always leads to memory overflow and queue downtime. Can I increase the number of threads to reduce the memory requirements and keep Under the premise of executing memory 16g.
Many thanks in advance。

**Comment by Kai-Maker1** [comment]
The default execution memory is 4g, and I set ’executive=16’. It is too small to assemble and has no results, and too big to be too large for my system. For example, my cluster node has three nodes of test1, test2, and test3. How to make canu only run on the test1 node,like‘gridOptions=test1’？

**Comment by brianwalenz** [comment]
Canu wants to run its various components (read correction, overlapping, consensus, etc) as individual grid jobs; technically they're run as job arrays.  The executiveMemory setting is only controlling the size of the component that does job configuration, file management and other minor tasks.  This component analyzes the state of the assembly, figures out what needs to be computed, sets those jobs up, and then submits those jobs to the grid for execution.  Each of those jobs will be sized based on the genome size and available compute nodes -- these sizes are reported in the canu logging.

The other way to run Canu is to tell it to ignore the grid and run all jobs on the current machine without submitting them to the grid.  'useGrid=false' enables this.  Parameters 'maxMemory' and 'maxThreads' are useful here.  Canu will use at most 'maxThreads' CPUs concurrently and will (try to) use no more than 'maxMemory' GB of memory for all processes it runs.  For this way, you'd typically put the canu command in a small shell script and submit that to the grid (and here you can tell LSF to run that job on a specific node or class of nodes -- this is entirely LSF specific and it's been well over 15 years since I've used LSF). 

Note that when letting canu use the grid directly, maxMemory and maxThreads are slightly different; they're the maximum size that a single job can be, but the grid can choose to run as many as it wants to at one time.

Relevant documentation:  https://canu.readthedocs.io/en/latest/tutorial.html and https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-support.

**Comment by skoren** [comment]
This seems to be a continuation of #1955 so I closed that issue. If I understand your question correctly, the issue is when you request 16gb the job ends up waiting in the queue too long? If there are nodes that are too small, they shouldn't ever be used so I'm not sure how limiting yourself to only one node would make it schedule faster. I think you're better off seeing if you can fit into the 4gb limit.

I expect there is only one step in the executive (generateCorrectionLayouts) that is taking more than the default 4gb of memory. Try the following, get an interactive session reserving 16gb node and launch Canu with the original command you used (`canu -p test -d test_pacbio_clr1 genomeSize=600m executiveMemory=4 -pacbio test.fasta.gz`) on the folder where it stopped. It will resume the assembly and run the generateCorrectionLayouts code locally on the larger node then submit itself to use 4gb nodes.

**Comment by Kai-Maker1** [comment]
Thanks for your prompt suggestions，as for the restart option，I found that there is a restart description in the Canu FAQ, so I only need to rerun the previous script in the original stopped folder, and it will automatically recognize and work again?Could you precisely tell me the script or instructions I need to take?
Besides，Can I use the previous version 1.8 of Canu to split a process into three processes. As for (generateCorrectionLayouts) that the step could take more than the default 4gb of memory. Where does this step exist (correction, trimming, or assembly)? Can I only improve the execution memory in one of the steps. so in other processes Compute nodes can be used to increase speed.
Does Canu have a job scheduling system retrieval function? When I ran the test, I found that it would automatically generate a script file for a queue that I had not given before, causing some small memory queues to go down.

**Comment by skoren** [comment]
You can't mix 1.8 and 2.1 so you can't run any steps from 1.8 on an assembly started with 2.1 or vice versa. generateCorrectionLayouts is in the correction step but I wasn't suggesting ever increasing executive memory. As I said, when you restart Canu start it on a interactive node with 16gb reserved rather than on a head node. This will run generateCorrectionLayouts locally using the 16gb reservation and submit Canu to continue using 4gb for subsequent jobs which should be sufficient.

As for queue, canu will use all available queues. If you want to limit it to specific ones, you'd have to specify that in gridOptions.
