### ISSUE TITLE
correctReads runtime 

### ISSUE THREAD

**Issue by fergsc** [marbl/canu#1965]
Hi,

I have a large and long ONT dataset (N50: 39,883, coverage=~75x) that I am currently assemblying with canu 2.1.1 on a PBS system. I have a walltime limit of 48 hours. There is nothing I can do to extend this limit. I am stuck on correctReads (falconsense). 

falconsense runs on a single thread, increasing the number of threads has no impact. I have changed the number of threads for both the PBS submission script and falconsense command.

The only way I can get this assmbly to finish (I think) is to increase the number fo correction jobs running, ie to decrease the block size. Would lowering 'MMapBlockSize' be the best thing to do here? And would overlapping need to be reperformed if making such a change?

thanks.

**Comment by brianwalenz** [comment]
I just started looking at an assembly with the same issue.

The parameters you want to set are `corPartitions` and `corPartitionMin`.  The first controls how many partitions (jobs) to make, and the second one sets a lower limit on the number of reads per job (as a guard against making many many tiny jobs).  Setting `corPartitions=500` and `corPartitionMin=1`, will give you 500 jobs.  There's no real upper limit to how many jobs you can make; you could make thousands of jobs if you wanted to.

There's no need to recompute overlaps.  All the work for this stage is in `correction/2-correction` and simply deleting (or renaming) that directory then restarting canu (with the new parameters) will make it resume with the smaller falconsense jobs (after it repartitions, which can be a bit slow).

I might have a better solution in a few days.  If you're CPU time isn't free, and you can wait a couple of days for a better solution, I'd suggest waiting.

falconsense does use multiple threads, but only for the first half of its work.  You might eke out a bit more effective run time by increasing the number of threads slightly (`corThreads`) from the default of 4 to 6 or 8.

**Comment by fergsc** [comment]
Thanks I just discovered that option and am re-computing the PBS script now (having removed the store and 2-correction directory). Any hints as to what this better solution may be?

Due to the lack of CPU efficiency I have been running falconsense with 1 CPU. Too many genomes to assemble, not enough CPU time. Up until now it hasn't been an issue.

Thanks

**Comment by fergsc** [comment]
Using `corPartitions=XX` and `corPartitionMin=1` solved my problem.

Thanks for the help.

**Comment by fergsc** [comment]
Hi, I succeeded with correction and trimming and now face a similar issue with overlapping during unitigging. Other than reducing coverage is there a way of setting a similar parameter for this stage? I was unable to find anything.

thanks

**Comment by skoren** [comment]
This step (and overlapInCore in general) tends to be slow on the very long reads at high error rates. The trimming is usually the worst step because it has to process very long reads only to realize they aren't good (e.g. chimeric) and throw them away for subsequent steps. 

There are options to create more jobs for this step (see https://canu.readthedocs.io/en/latest/tutorial.html#ovl-overlapper-parameters) but they're a bit difficult to use and I'd recommend not changing the partitioning. Instead, I would suggest increasing the cores for each job (assuming you have more cores available). You can also check the selected k-mer threshold (https://github.com/marbl/canu/issues/1453) and lower and potentially decrease the correctedErrorRate from the default of 12% to 8-10% which is likely sufficient with recent better quality ONT data.

**Comment by fergsc** [comment]
Thanks. The solution was way to simple, increase the core count.

Strange that I got through trimming with this number of cores. I am using the `-fast` parameter so that mhap is used during all stages. Assemblying plant genomes with high repeat content.

**Comment by skoren** [comment]
Resolved, per message above. Please feel free to open a new issue if you encounter another error with the asm.
