### ISSUE TITLE
About overlap implementation

### ISSUE THREAD

**Issue by elenamesga** [marbl/canu#1966]
Hi,
I am very impressed with your work in the assembly field.

However, I have some questions about the overlap algorithms.

It seems that for the overlap step in the canu software, you use the MHAP program, which is composed of two stages: Minhash (first filter) and a second filter.

However, in your repository, you can find a program called MASH, which implements an optimized version of Minhash, and I cannot understand why don't you use that for the first stage of MHAP.

Also, do you plan replacing the MASH algorithm with the new program RabbitMASH (https://github.com/ZekunYin/RabbitMash) so it could be used with the canu program?

Thanks,
Elena E.G

**Comment by skoren** [comment]
Mash isn't an optimized version of MHAP, they're trying to solve quite different problems. They also use different versions of minhashing (multi-hash vs bottom-hash) and we found in early testing with noisy reads that the multi-hash version performed better. MHAP is also looking for partial hits within sequences while mash is comparing entire sequences against a database. Mash would only be part of the first step within MHAP but it's easier to operate in the single program rather than trying to replace half of MHAP with mash. The closest tool to MHAP would be MashMap or Winnowmap which could potentially replace MHAP though we have not done full testing/tuning/evaluation of them for this purpose.
