### ISSUE TITLE
correction-overlapper jobs fail

### ISSUE THREAD

**Issue by meganlsmith** [marbl/canu#1979]
I am running canu to assemble PacBio CLR data. I am using canu v2.1.1, and it is failing at the stage when it is submitting correction/1-overlapper jobs. I have attached the log file. I have tried restarting, as it says it is mostly a harmless error, but the same error occurred again. The log file is attached, and below I have reproduced the command I used to run canu. Thanks for any insight you are able to provide! 

/N/project/Prophysaongenomics/canu-2.1.1/bin/canu -p prophysaon_v3 -d prophysaon_v3  useGrid=false genomeSize=1.54g -pacbio-raw ./fastq/*.fq

[canu.log](https://github.com/marbl/canu/files/6791565/canu.log)

Sincerely,
Megan

**Comment by skoren** [comment]
Given that all the jobs are failing and quickly, I would guess there is an issue with the JVM. Post the log of one of the failing jobs `correction/1-overlapper/*precompute*.out` which will have more details.

**Comment by meganlsmith** [comment]
Hi Sergey,
Thanks, by looking at that file (attached), I can see that it is not finding java. I am running this on an HPC and am loading java prior to running. I tried setting java=java on the command line, since the module is loaded, but I get the same error. Any suggestions, or should I reach out to the HPC? 
Thanks,
Megan
[precompute.000001.out.txt](https://github.com/marbl/canu/files/6801766/precompute.000001.out.txt)

**Comment by skoren** [comment]
It seems the JVM location Canu has set from the head node (`/usr/lib64/jvm/jre-11-openjdk/bin/java`) isn't available on the compute node. I presume the module load is pointing to a different location? Do you know the full path to the JVM that works on the compute nodes? If so you can specify it as the argument to `java="<full path to jvm>"`. Canu also has an option to load modules before running through the preExec parameters (e.g. `preExec="module load java"`) so you could also try that instead of configuring the java path.

**Comment by skoren** [comment]
Idle
