### ISSUE TITLE
Read error detection jobs failed

### ISSUE THREAD

**Issue by shaobinzhong** [marbl/canu#1983]
Hello,

I used the following canu command to assemble a fungal genome with hifi seq data:

canu -p A1_hifi -d A1-pacbio-hifi useGrid=false genomeSize=36m -pacbio-hifi A1.ccs.fastq.gz

But the job failed: 
```
-- Read error detection jobs failed, tried 2 times, giving up.
--   job 00001.red FAILED.
--   job 00022.red FAILED.
--

ABORT:
ABORT: canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
Cgroup mem limit exceeded: Task in /pbspro.service/jobid/835931.bright01-thx killed as a result of limit of /pbspro.service/jobid/835931.bright01-thx
```
See the details on the attached file:
[canu_2.1.1.e.txt](https://github.com/marbl/canu/files/6812697/canu_2.1.1.e.txt)

Please help! Thanks.

**Comment by shaobinzhong** [comment]
I run canu 2.1.1 on linux

**Comment by skoren** [comment]
The error message indicates your job was killed for exceeding memory limits. There's probably a disconnect between how much memory you requested and how much Canu is trying to use, which defaults to the full machine. Make sure you reserve the full machine (126gb in this case) or limit Canu to whatever you requested via maxMemory. I expect the jobs would complete if you restart even without changing memory since there aren't many left but it might help other later steps.

**Comment by shaobinzhong** [comment]
Hi Sergey,

Thanks for your quick reply. The jobs finished well after I changed increased the memory.

Best regards.

Shaobin
________________________________
