### ISSUE TITLE
CANU 2.0 SLURM slurm_script: line 48: 258100 Killed 

### ISSUE THREAD

**Issue by JosephHeras** [marbl/canu#1999]
Hello, 
I'm trying to run canu v2.0 on an HPC3 with the following bash script
```
#!/bin/bash
#SBATCH -p free               
#SBATCH --nodes=1               
#SBATCH --mem=18G
#SBATCH --cpus-per-task=1

module load canu

canu -p Ribbon_two -d Ribbon_output2 -pacbio R251-C01.1-Reads.fastq genomeSize=600M executiveMemory=18 useGrid=true
```

It will run for about 45 minutes and when the script ends there is an output directory with files but it doesn't create an assembly (a fasta file).  I searched around and found in canu.02.out the following error message: 

```
-- Meryl finished successfully.  Kmer frequency histogram:
/export/spool/slurm/slurmd.spool/job7552932/slurm_script: line 48: 258100 Killed                  /usr/bin/env perl $bin/canu -p 'Ribbon_two' -pacbio '/share/crsp/lab/dgerman/share/R251-C01.1-Reads.fastq' 'genomeSize=600M' 'executiveMemory=18' 'useGrid=true' canuIteration=1
slurmstepd: error: Detected 1 oom-kill event(s) in step 7552932.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

I have read the previous postings that sound similar to my issue and I tried adding more memory but I didn't have any luck.  Is there something I'm missing here.  Also, my PacBio fastq file is about 220GB.

**Comment by skoren** [comment]
You can try increasing memory a lot more, like 32 or 64gb and see if that succeeds. Version 2.0 is quite old and this issue was fixed since that release (see #1757). All this step is doing is creating a histogram for you to view and you can just skip this since this is just for display if you touch the file */0-*/meryl-process.success file and then re-start. I'd still recommend updating to Canu 2.1.1 (or 2.2 which should be released soon) rather than using v2.0.
