### ISSUE TITLE
The latest version 2.2 failed to compile

### ISSUE THREAD

**Issue by simon28li** [marbl/canu#2016]
Hi，The latest version 2.2 failed to compile.
This is an error message.
```
  >> 104    utility/src/parasail/cpuid.c:31:5: error: impossible constraint in 'asm'
     105         __asm__ ( "cpuid" : "+b" (ebx),
     106         ^~~~~~~
     107    utility/src/parasail/cpuid.c: In function 'check_xcr0_ymm':
  >> 108    utility/src/parasail/cpuid.c:79:5: error: unknown register name '%edx' in 'asm'
     109         __asm__ ("xgetbv" : "=a" (xcr0) : "c" (0) : "%edx" );
     110         ^~~~~~~
     111    utility/src/parasail/cpuid.c: In function 'check_xcr0_zmm':
  >> 112    utility/src/parasail/cpuid.c:95:5: error: unknown register name '%edx' in 'asm'
     113         __asm__ ("xgetbv" : "=a" (xcr0) : "c" (0) : "%edx" );
     114         ^~~~~~~

```
my system information is as follows.
```
> uname -a

Linux simon28li 4.18.0-193.el8.aarch64 #1 SMP Fri May 8 11:05:12 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

> cat /etc/os-release

NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
```
Is the error reported because arm is not supported? Because I've seen similar speeches.[#1804](https://github.com/marbl/canu/issues/1804)

**Comment by skoren** [comment]
Yes, this is an issue with ARM compilation, from a third-party library canu uses. It looks like that library does have ARM support so it could be updated but you'd likely encounter other errors because we've never compiled on an ARM processor and don't have access to one to test.

I'm going to close this issue since it's redundant with the other ARM support request. If we do get access to a test machine, that issue would get updated.
