### ISSUE TITLE
No record of assembly, trimmed, or corrected reads 

### ISSUE THREAD

**Issue by JosephHeras** [marbl/canu#2019]
Hello I am trying to run canu on a genome ~800mb and I can't get an assembly out of it.  Here is the command that I used. 

```
canu -p Ribbon_two -d Ribbon_test2 genomeSize=600m correctedErrorRate=0.035 -trimmed -pacbio-raw R251-C01.1-Reads.fastq.gz useGrid=false &
```

Here is the version that I'm using. 
```
canu snapshot v2.3-development +2 changes (r10273 f265325f29d94649dfa9cefe08f4aede581666cd)
```

When I check inside the directory (-d) there's no assembly file but I do see that it recognized the pacbio reads (CLR).  I don't see any indication of trimmed or corrected reads. Any suggestions would be helpful.  Also, I noticed that in my directory there are 4096 files and I saw in a previous thread this was an issue too.  I don't know if this is a bug issue or something else.   Thanks in advance! 

<img width="1227" alt="Screen Shot 2021-09-03 at 12 24 38 PM" src="https://user-images.githubusercontent.com/12835257/132057525-847b7e92-592e-4a58-aba1-2a80dceb0a7a.png">

**Comment by brianwalenz** [comment]
It looks like you've got two assemblies running in the same directory - Ribbon_two and Ribbon_three.  This will greatly confuse canu.  Each assembly needs to be in a different `-d` directory.

**Comment by JosephHeras** [comment]
My apologies, I tried redoing the same command and sent it to a different directory.  However, I'm still having the same issue.

**Comment by skoren** [comment]
I think another issue is your command. You're specifying both `-trimmed` and `-pacbio-raw`. Trimmed reads should also be corrected which is in conflict with the `pacbio-raw` designation. You should not include -trimmed unless you're using hifi reads in which case you just need `-pacbio-hifi` not `-pacbio-raw`.

If you still have an error, post the full output of your canu launch and the contents of the `*.seqStore.err` file.

**Comment by JosephHeras** [comment]
Thank you.  I tried running it again this is what came up.  It seems that it has loaded the reads, but I don't see trimmed reads, corrected reads, or an assembly. 


![Screen Shot 2021-09-04 at 11 43 27 AM](https://user-images.githubusercontent.com/12835257/132104922-1359e273-cab6-40c2-b710-9fe63257c86e.png)
![Screen Shot 2021-09-04 at 11 43 50 AM](https://user-images.githubusercontent.com/12835257/132104925-535c45b9-4e82-4047-9662-d0a03124a941.png)

**Comment by skoren** [comment]
What's the Canu command you're using and what is the full output of the canu command?

**Comment by JosephHeras** [comment]
Here are the following items.  Below is the command that I used.  
<img width="1420" alt="Screen Shot 2021-09-05 at 10 41 12 AM" src="https://user-images.githubusercontent.com/12835257/132136347-e2060cfa-f085-422d-8037-a395b393387e.png">
Next is what is inside the output directory (-d).  
<img width="910" alt="Screen Shot 2021-09-05 at 10 42 48 AM" src="https://user-images.githubusercontent.com/12835257/132136365-f8d5fbe5-efe1-46f2-91ff-dd4e67ea0308.png">
This is where I executed my command.  
<img width="894" alt="Screen Shot 2021-09-05 at 10 45 57 AM" src="https://user-images.githubusercontent.com/12835257/132136427-08c05f5e-fb4a-45ad-8cde-03e50b03c331.png">
If you have any questions, please let me know. Thanks!

**Comment by skoren** [comment]
That's not the output I was looking for. I mean whatever is printed to screen when you run the command. Since you're running with `&` that will put the canu job in the background so it will keep running and you may not get the full output. Run without the `&` and post the full log from start to any error.

**Comment by JosephHeras** [comment]
Usually it run for a bit and then it will stop.
<img width="1429" alt="Screen Shot 2021-09-07 at 9 49 43 PM" src="https://user-images.githubusercontent.com/12835257/132448376-d24dc5c9-73e8-462d-ac66-382b936af52e.png">

**Comment by skoren** [comment]
If that's the end of the log, there's no error. It looks like this is resuming a previous assembly which had finished 32/47 jobs (presumably you stopped it because it wasn't writing to screen?) and it is now continuing onto the rest. As long as it isn't reporting an error or exiting the process, you should let it run.

**Comment by JosephHeras** [comment]
Sounds good and thanks!  I'll leave it running and see what happens.

**Comment by JosephHeras** [comment]
I'm still using the same command as above and now I'm getting this error.  I tried to rerun the command, but I keep getting this error.  Any insight would be greatly appreciated. 

![Screenshot from 2021-09-21 10-20-49](https://user-images.githubusercontent.com/12835257/134221559-436bbdca-2978-46d6-b9b9-47cde8feb5fb.png)

**Comment by JosephHeras** [comment]
Here is a log from mhap.000186.out.

![Screenshot from 2021-09-21 11-09-47](https://user-images.githubusercontent.com/12835257/134226374-003d5872-3fc1-4030-b5e2-6f98da139869.png
![Screenshot from 2021-09-21 11-09-17](https://user-images.githubusercontent.com/12835257/134226384-e167f187-8df3-4994-b4ee-bf1e1dc301d3.png)
)

**Comment by skoren** [comment]
That doesn't look like it has any error. What's the contents of your correction/1-overlapper/results and the correction/1-overlapper folders

**Comment by JosephHeras** [comment]
Here is what I see in the correction/1-overlapper/results and the correction/1-overlapper folders.  
<img width="683" alt="Screen Shot 2021-09-24 at 3 14 39 PM" src="https://user-images.githubusercontent.com/12835257/134744981-b74e7f7a-79a1-4380-8f98-8e637264fd21.png">
<img width="529" alt="Screen Shot 2021-09-24 at 3 14 12 PM" src="https://user-images.githubusercontent.com/12835257/134744984-a2c70b1e-c663-42ad-ad29-ac66d40bbc79.png">

**Comment by skoren** [comment]
It might have run out of time while converting the output. Try removing all the results files for one failed job, (e.g. `correction/1-overlapper/results/000186.*`) and running the job by hand (on a compute node like where you ran canu originally with at least a 24 hr time limit) by running `sh mhap.sh 186` in the 1-overlapper folder and report what it runs.

**Comment by brianwalenz** [comment]
While I ponder what could be going on here, try running with option `mhapPipe=false`.  This modifies the way this step runs so it uses files (warning: LARGE!) for inter-process communication.  To be safe, remove `mhap.sh` before restarting.  Don't forget to remove the outputs of the failed jobs.

The file listing shows that the failed jobs successfully complete the first part of the compute (`######.mhap.success`) but the second part, that is creating the `*.WORKING` files, is not completing.  The second part will make a file `######.mcvt.success` when it completes successfully.  Check for errors near the start of the log file, too.

With option `mhapPipe` disabled the first step will instead write output to `######.mhap` and then the second step will read those and create `######.ovb`.

**Comment by mariasilviamorlino** [comment]
Hi,

I am chiming in because I faced very similar issues to those mentioned in this thread recently.
In short, I used Canu to assemble a cyanobacterial genome from Nanopore reads. The program ran for quite a while before aborting with the message “Don't panic, but a mostly harmless error occurred and Canu stopped.”, and I was able to see from the report file (attached) that it was able to run until unitigging.

Canu version:
canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)

Command line:
canu -p cyano05 -d larocca_assembly_Canu/cyano05 genomeSize=7.7m correctedErrorRate=0.188 minInputCoverage=3 minReadLength=600 minOverlapLength=300 maxThreads=5 -nanopore ../basecall/fastq/barcode05.fq.gz

Attached (file cyano_05_canu_abort.txt) is what is printed to screen when I relaunch the exact same command line to attempt to resume the work.
On the basis of this, and thanks to the comments in this issue, I tracked down the job that failed. Here are the contents of the folder unitigging/5-consensus/ ...

![Schermata a 2021-11-22 09-43-33](https://user-images.githubusercontent.com/45208965/142843753-9ee480cf-5792-4b12-a227-13c33816b9f0.png)

and unitigging/5-consensus/ctgcns/

![Schermata a 2021-11-22 09-43-54](https://user-images.githubusercontent.com/45208965/142843821-7c244bfb-98e7-4e8c-839f-3eeb5c406a71.png)

I tried manually launching consensus.sh on the job that failed (command: sh consensus.sh 3), after removing either consensus.000003.out, or ctgcns/0003.cns.WORKING, or both. In all cases, the job kept failing (see file cyano_05_consensus_sh_fail.txt).

Is there anything else I could check or test to try resume the job?
Thank you!

--- attachments ---

[cyano05.report.txt](https://github.com/marbl/canu/files/7580104/cyano05.report.txt)
[cyano_05_canu_abort.txt](https://github.com/marbl/canu/files/7580105/cyano_05_canu_abort.txt)
[cyano_05_consensus_sh_fail.txt](https://github.com/marbl/canu/files/7580106/cyano_05_consensus_sh_fail.txt)

**Comment by skoren** [comment]
@mariasilviamorlino this is not really similar, the error is reported at a different stage and is due to the outdated release version you're using (v2.1.1). See issue #2048 or #1964. Update to v2.2 and re-launch with the same command. It should recompute just the failed consensus job.

**Comment by skoren** [comment]
Idle, original issue likely fixed by `mhapPipe=false`, there have been some more recent issues on Windows Linux emulation and other systems where named pipes don't work properly.
