### ISSUE TITLE
Canu crashed already at the first step

### ISSUE THREAD

**Issue by xiwang2405** [marbl/canu#202]
Hi,

My Canu run crashed already after the gatekeeperCreate step. I think it is due to the memory issue. However I am not sure which "prefix"+Memory I should set in order to increase memory requirement for this step? Is it "master", which I tried but it is an unknown parameter. Any suggestion?

Here is my command:
canu -correct \
     -p canu_correct \
     -d ../tmp/Strategy3/Canu1/canu_correction \
     -pacbio-raw /data/raw/Projects/Wheat/BIO1-326/FVEx_PacBio_gDNA_Fielder/filtered_subreads.fasta \
     genomeSize=15g \
     useGrid=1 \
     gridOptionsJobName=canu1 \
     gridEngineMemoryOption="-l vf=MEMORY,h_vmem=MEMORY" \
     gridOptions="-V -q main,main2,main3 -M geycu" \
     corMinCoverage=0

Attached is the canu-scripts output:
[canu.01.txt](https://github.com/marbl/canu/files/371663/canu.01.txt)

Many thanks in advance!
Xi

**Comment by skoren** [comment]
The gatekeeper step uses almost no memory (it streams the reads and writes to disk). Why do you think it crashed? There is no error reported in your attached log.

**Comment by xiwang2405** [comment]
Thanks for the quick reply!

I assumed this because the run was terminated and the message sent from grid looked like this, which usually indicates memory issue:

Job 8691188 (canu_canu_correct_canu1) Aborted
 Exit Status      = 137
 Signal           = KILL
 User             = geycu
 Start Time       = 07/19/2016 14:17:44.193
 End Time         = 07/19/2016 16:15:05.064
 CPU              = 01:55:28
 Max vmem         = 96.617G
 Max rss          = 32.312G
failed assumedly after job because:
job 8691188.1 died through signal KILL (9)

Also I didn't see anywhere of the disk the reads were written to....

FYI, in total 49 million PacBio reads (~365G) in fasta format are used as input. 

Thanks,
Xi

**Comment by xiwang2405** [comment]
According to the attached gkpStore.err file, I think the gatekeeperCreate has been successfully done. So the problem is from the next step?

[canu_correct.gkpStore.err.txt](https://github.com/marbl/canu/files/372003/canu_correct.gkpStore.err.txt)

**Comment by brianwalenz** [comment]
Most pieces of the assembler memory map the *gkpStore/blobs file instead of reading it block by block.  This greatly inflates the virtual memory size of the processes.  The log is showing yours got up to 96gb, but with only 32g in core.  We haven't had issues with this before, in fact, it seems that most grids that track memory don't care about virtual size.

Are you required to use h_vmem?  That's (I think) what triggered the kill.

**Comment by xiwang2405** [comment]
Indeed I see the blobs file is exactly 96G. And yes, I used h_vmem:
gridEngineMemoryOption="-l vf=MEMORY,h_vmem=MEMORY"

Any suggestions that I can discuss with our HPC support team? Thanks!

**Comment by brianwalenz** [comment]
Yeah, leaving out h_vmem.  ;-)

Memory mapped files should behave just like paging space.  The OS will load what is needed on (program) demand, and release the memory when something else needs the memory.

Canu will replace MEMORY in those options with the amount of memory, excluding this blobs file, each program needs.  I suppose, for this particular assembly, you could try hard-coding h_vmem to 128gb or there about.  Check the start of the canu output for maximum sizes of any program.  The unitigger (bogart) will probably be the largest, by far, so that will also need special care.

**Comment by xiwang2405** [comment]
Great!  Thanks for the tip! I'll try this out.

**Comment by xiwang2405** [comment]
I tried using gridEngineMemoryOption="-l vf=128G,h_vmem=128G" and got error:

Stack trace:

 at /gpfs/bayergpfs1/biogrid/tools/bioinfo/app/canu-20160714/Linux-amd64/bin/lib/canu/Defaults.pm line 234.
        canu::Defaults::caFailure("Couldn't parse gridEngineMemoryOption='-l vf=100g,h_vmem=100g'", undef) called at /gpfs/bayergpfs1/biogrid/tools/bioinfo/app/canu-20160714/Linux-amd64/bin/lib/canu/Grid_SGE.pm line 204
        canu::Grid_SGE::configureSGE() called at /tools/bioinfo/app/canu-20160714/Linux-amd64/bin/canu line 309

canu failed with 'Couldn't parse gridEngineMemoryOption='-l vf=100g,h_vmem=100g''.

I guess I set it in a wrong way, right?

**Comment by skoren** [comment]
Yes, ``gridEngineMemoryOption``` is the flag to specify memory only so you should leave it as ``gridEngineMemoryOption="-l vf=MEMORY"````. To always request h_vmem for all jobs add ```gridOptions="-l h_vmem=128G"```

**Comment by xiwang2405** [comment]
Yeah, it works!  Thanks!
