### ISSUE TITLE
How to set genome size in the "genomeSize" parameter?

### ISSUE THREAD

**Issue by mathavanpu** [marbl/canu#2023]
Hello there,
I am new to genome assembly work. Currently I am doing genome assembly of safflower genome using the PacBio CCS Hifi reads. The genome size of the this plant is 1.4GB. What value has to set thegenomeSize parameter in the case of safflower genome. 

The command I have used
nohup /opt/canu-2.0/Linux-amd64/bin/canu -p asm -d . genomeSize=700m -pacbio-hifi  1172_ccs.fastq.gz corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 stopOnLowCoverage=0.1 minInputCoverage=0.1 useGrid=false maxThreads=40 &

Please guide me!

Reference https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0211985

**Comment by brianwalenz** [comment]
`genomeSize` is not a critical parameter.  We will discard short reads to limit input coverage to 50x for hifi data (maxInputCoverage parameter), and so genomeSize is used for this.  Otherwise, it affects nanopore read correction (in a similar way) and logging.

I strongly suggest installing Canu v2.2 (https://github.com/marbl/canu/releases/tag/v2.2) which has some important bug fixes, especially for hifi reads.

You can remove most of those options, as they aren't used for hifi reads:
```
canu -p asm -d . \
  genomeSize=1.4g \
  useGrid=false maxThreads=40 \
  -pacbio-hifi 1172_ccs.fastq.gz
```
Note that using `-d .` will put a lot of files in the current directory.  I'd suggest using `-d safflower` to isolate the canu files to their own directory.

**Comment by skoren** [comment]
Idle
