### ISSUE TITLE
why use 22-mer ?

### ISSUE THREAD

**Issue by 123long123** [marbl/canu#2054]
Hi,

    I am using Canu 2.1.1 to do a genome assembly. I am confused why canu used 22-mer. Is it suitable for a large genome, like 10-15G genome (diploid with heterozygosity) ?  How can I modify the parameter if I need change this ? Thank you very much. Looking forward to your reply.

long

**Comment by skoren** [comment]
First, I'd suggest updating to v2.2 before starting. The k-mer size is a compromise between picking a unique enough k-mer given a random genome and not picking one too large to seed overlaps due to errors. Picking one that is too small will generally increase runtime but not lead to missed overlaps while too large can lead to missed overlaps. 

The parameters for overlapping are described here: https://canu.readthedocs.io/en/latest/parameter-reference.html#overlapper-configuration-ovl-algorithm. If you have recent recent Nanopore data or HiFi data, you can probably increase it up to 31. Something like `ovlMerSize=31 ovlMerDistinct=0.975`

**Comment by 123long123** [comment]
Thank for your quick reply. I will try to modify the parameters as suggested.
