### ISSUE TITLE
question: contig trim coordinates 0- or 1-based?

### ISSUE THREAD

**Issue by alimayy** [marbl/canu#2059]
Hi, many thanks for developing Canu.

My question is related to the contig nucleotide positions suggested by Canu for non-redunant trimming of circular contigs: are these positions suggested by "trim=" 0- or 1-based? I'm asking because different tools and formats are based on different starting positions, e.g. bedtools is 0-based for instance, while gff is 1-based.
 
Thanks,
Ali

**Comment by skoren** [comment]
The coordinates are 0-based.

**Comment by pjm43** [comment]
So just to make sure I understand - if canu suggests trim=3283-154459 (i.e., >tig00000001 len=157502 reads=1710 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=3283-154459), then my simple bed file (to trim the file so that it represents a circular molecule) should be (since both are 0-based):

chrName     3283     154459

Can you verify?

Thanks - sorry in advance for the basic question.
Jeff
