### ISSUE TITLE
Canu  overlapper jobs failed

### ISSUE THREAD

**Issue by Modupeh** [marbl/canu#2075]
Hi,

I am using Canu (v2.2)to assemble a bacterial genome with high-genome coverage (~900) of PacBio data (Sequell II). The initial script was running okay but ran out of wall-clock time which killed the process after 36hrs. I reran the script but had the error "_canu failed with 'failed to overlap.  Made 2 attempts, jobs still failed'_ ". I have attached the error output and my script for the second run. Can you please advised how to resume the assembly process from where it stopped. thanks
[canu-error.txt](https://github.com/marbl/canu/files/7825233/canu-error.txt)

**Comment by skoren** [comment]
The detailed error should be in the log file from the overlap job: `/tmpdir/job/9913002.undefined/sero6B-canuAssembly-correct-output/trimming/1-overlapper/overlap.000001.out`. It seems like the temp dir is preserved between restarts so you should be able to check that file. You can also try running the shell script `overlap.sh 1` from the 1-overlapper folder and post the log of it.

**Comment by Modupeh** [comment]
Hi Skoren,
Thanks for the response. The log of the output is posted below.

Running job 1 based on command line options.
mkdir: cannot create directory ‘/tmpdir/job/9889623.undefined/sero6B-canuAssembly-correct-output/trimming/1-overlapper/001’: No such file or directory
ERROR: Failed to open -k '/tmpdir/job/9889623.undefined/sero6B-canuAssembly-correct-output/trimming/0-mercounts/serotype-6B.ms22.frequentMers.fasta': No such file or directory

**Comment by skoren** [comment]
This looks like an issue with your folders being missing. I think because you ran in the temporary space, when the original job timed out the temporary folder was removed. The restart then failed because it couldn't access the files from the previous run. Do you have the output results so far saved anywhere besides the temporary space? If not, I don't think you can restart this run because of the use of temporary space. I'd restart from scratch and give a longer time and/or not use temporary storage space to avoid this issue in the future.

**Comment by Modupeh** [comment]
Thanks again. I will restart the run. which is more important to speed up the process in Canu ? increase my RAM request or number of cores?

**Comment by skoren** [comment]
Cores over memory for sure. Restarting is generally OK as long as you don't use temporary space that's erased after the job runs.
