### ISSUE TITLE
Bogart failed

### ISSUE THREAD

**Issue by kangxiongbin** [marbl/canu#2082]
Hi,
I encounter some problem, if someone know how to address? Thank you very much!

First I ran canu-2.1 in linux in a virtual machine :
```
canu-2.1 -assemble -p low -d medium_complex -corrected genomeSize=300M stopOnLowCoverage=3  minInputCoverage=3  useGrid=false  -pacbio long_reads.fa

Error: 
--
-- Bogart failed, tried 2 times, giving up.
--
ABORT:
ABORT: canu 2.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT: Disk space available:  1742.359 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.err):
bogart: bogart/AS_BAT_OverlapCache.C:218: void OverlapCache::computeOverlapLimit(ovStore*, uint64): Assertion `totalOlaps > 0' failed.
```
Later I used canu-2.2 and canu-2.3:
```
canu -assemble -p low -d medium_complex2 -corrected genomeSize=300m merylMemory=4 merylThreads=4 hapThreads=4 batMemory=4  stopOnLowCoverage=5  minInputCoverage=5  useGrid=false  -pacbio long_reads.fa

Error:
-- Detected Sun Grid Engine in '/vol/codine-8.3/default'.
--          Sun Grid Engine disabled by useGrid=false
--
-- Local machine mode enabled; grid support not detected or not allowed.
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 1 cores with 2016 GB memory each.
-- ERROR
-- ERROR  Task meryl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    merylMemory=8 gigabytes
-- ERROR    merylThreads=4 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change maxMemory or maxThreads
-- ERROR    Change merylMemory and/or merylThreads
```
The setting of my sever:
cat /proc/cpuinfo| grep "cpu cores"| uniq
cpu cores	: 10
cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l
8

**Comment by skoren** [comment]
The first error indicates no overlaps found. You're specifying `-corrected` but providing PacBio reads. Unless you've somehow corrected the CLR data before putting it into Canu that won't work. 

The second error is because you've asked it to use 4 cores but your machine is reporting itself as 1 core. Canu uses getconf (`getconf _NPROCESSORS_ONLN`) but also respects grid requests so if you submitted a slurm job and only asked for 1 core, Canu will only see 1 core.

So, don't specify corrected if you're using CLR data and haven't corrected reads and make sure the getconf is working properly on your system and that you're actually requesting the right number of cores.

**Comment by skoren** [comment]
Idle
