### ISSUE TITLE
Bogart options 

### ISSUE THREAD

**Issue by CIWa** [marbl/canu#2090]
Hi,

I successfully ran Canu version 2.0 on a Linux server. 

My call was:
`canu -p er2 genomeSize=2g -pacbio reads.fa corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" saveReads=true 
`
I used the 200x coverage limit and the options for Bogart to avoid collapsing of haplotypes (genome is diploid). Now I would like to know, what precisely do these parameters tweak? Therefore, what do these options mean:
```
-dg 3 
-db 3 
-dr 1 
-ca 500 
-cp 50
```

Thanks for providing us with this great assembler, it worked very well!

Best wishes,
Isabel

**Comment by skoren** [comment]
The first 3 parameters control the error rate MAD used for assembly. The default is 6 in your canu version. So this means the error rate used is lower for assembly than it would have been, allowing between-haplotypes to be filtered out. The second parameter decreases sensitivity of the repeat detection. This is because haplotypes can look like repeats and so the default parameters would fragment the assembly every time there is an alt contig.

**Comment by CIWa** [comment]
Hi Both, 
thanks a lot for the super fast help!
