### ISSUE TITLE
More unassembled bases than contigs

### ISSUE THREAD

**Issue by Duannai** [marbl/canu#2100]
Hello, after running the command `canu -d I1-canu/ -p I1-long genomeSize=3m minReadLength=1000 minOverlapLength=500 -nanopore-raw I-1-clean.fastq.gz corMinCoverage=0 corOutCoverage=all corMhapSensitivity=high correctedErrorRate=0.16 corMaxEvidenceCoverageLocal=10 corMaxEvidenceCoverageGlobal=10  maxThreads=10 maxInputCoverage=10000 obtMhapSensitivity=high utgMhapSensitivity=high utgOverlapper=mhap obtOverlapper=mhap corOverlapper=mhap batMemory=500` for metagenome, the report shows the following information.

> [UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      3577 sequences, total length 270982318 bp (including 277 repeats of total length 8730408 bp).
--   bubbles:      346 sequences, total length 10966309 bp.
--   unassembled:  194278 sequences, total length 1092940911 bp.

The bases in unassembled reads are more than those in contigs, is this situation normal? Or how can it be improved?

The second quetion is about  `277 repeats of total length 8730408 bp`. Do these repeats mean the same length, or the same sequence composition?

If the repeats mean the same composition, should I remove the duplicated sequences from the contigs.fasta before doing binning?

Thanks in advance!

**Comment by skoren** [comment]
It's common that the unassembled is larger than the contigs. This is because single reads can end up in the unassembled sequences so they have much more redundancy than the contigs. If this is a metagenome, you could consider adjusting the parameters for what constitutes an unassembled sequence (see the FAQ). As for the repeats, it doesn't mean anything about their size or composition. The bases reported is the total length but it doesn't mean all 277 sequence are the same size or the same repeat.

Last comment regarding your parameters, you're using the mhap overlapper for all steps without alignment. This is not the default and is not recommended. I'd suggest using the -fast option instead which is not equivalent to your parameters and computes alignments. Without this, you'll likely get a much less continuous assembly.

**Comment by Duannai** [comment]
Thanks for your prompt and clear answer!

Could you please explain what does `repeat` refer to?

The other question is about parameter `trimReadsOverlap` whose default is 500. Therefore, if I set it as 250, will the trimming be more strict or loose?

Thanks!

**Comment by Duannai** [comment]
Thanks very much. 

I just want to make a final comfirmation in this issue. 

> Last comment regarding your parameters, you're using the mhap overlapper for all steps without alignment. This is not the default and is not recommended. I'd suggest using the -fast option instead which is not equivalent to your parameters and computes alignments. Without this, you'll likely get a much less continuous assembly.

If I set `-fast`, can I still set `obtMhapSensitivity=high utgMhapSensitivity=high corMhapSensitivity=high`, will these be conflict?

**Comment by skoren** [comment]
Yes, you can, they won't be in conflict.
