### ISSUE TITLE
CANU contigs name

### ISSUE THREAD

**Issue by aureliendejode** [marbl/canu#2120]
Hi,

I have a simple question: Is there a logic about how CANU names the contigs or is it completely random ?

Thanks

**Comment by skoren** [comment]
Not really, the contigs are named in order of creation. However, when contigs are split due to error, they will get IDs later than the current max. So say, initially you got tigs 1-10 and tig 5 gets split into 3 pieces you'd have 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13. There are also some which are filtered as low-coverage/unassembled which further creates gaps in the numbering.
