### ISSUE TITLE
Metagenomics cDNA assembly

### ISSUE THREAD

**Issue by BertVanm** [marbl/canu#2122]
Hi,

I was redirected here by the people from ONT.
I'm trying to assemble metagenomic cDNA datasets, meaning I have short reads (<750 bp) from mixed origin, with my targets usually being <1% of the data.

I've found that subsetting the data into the different target organisms and assembling separately works quite well with Canu, but this is not always possible. I was wondering if you think it's feasible to feed all data at once into Canu, and if so, which settings I would need to modify to allow such assemblies to finish in a reasonable time frame.

All suggestions are welcome!
Bert

**Comment by skoren** [comment]
Canu isn't designed to handle transcript assembly and I wouldn't recommend it for this purpose. I assume you're primarily using it for read correction? I'm not sure what you're after, it sounds like canu runs and you want to reduce runtime but I don't know what commands you're running now or what time you're trying to run it in. 

You can start with the parameters for metagenomic datasets on the FAQ and potentially try other overlappers for correction (like minimap2) instead of mhap.

**Comment by skoren** [comment]
Idle
