### ISSUE TITLE
Interpret corMhapOptions="--min-olap-length" vs minOverlapLength=2000 when the latter errors

### ISSUE THREAD

**Issue by JamesHowie14** [marbl/canu#2127]
Dear Canu Team, I have a quick-ish question. I hope this is the right place for it, if not, my apologies. 
I am trying to optimise to assemble faster, without loosing accuracy.

For Nanopore, SUP mode,  I have coverages of 37 and 58, with loaded coverages of 29 and 38 for reads longer than 1000 bp. 
This is for two separate species. 

However, each assembly draft takes > 1-3 weeks, even using suggested speed modifications such as:
```
  corMhapFilterThreshold=0.0000000002 \
  corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
  mhapMemory=60g \
  mhapBlockSize=500 \
```
I used these for speed, and because the genome is expected to be repetitive. 

To further speed up, especialy for the 58 starting coverage example, I thought I could try using only longer reads, e.g. by setting 
```
  minReadLength=1750 \
```
, loading fewer reads, but longer, reads, for faster read correction. 

I then thought I could modify the length of overlaps at all phases of Canu, using:

```
   minOverlapLength=2000 \
```

When I do this, Canu understandably throws the error: 

```
## ERROR:  minReadLength=1750 must be at least minOverlapLength=2000
```

This got me thinking. 
As you see above, in a full command I had used the line:
```
corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
```
However, this contains the option:
```
corMhapOptions="--min-olap-length 2000"
```

From the Canu guide, I interpret the command above to mean we will limit the overlap to 2000 or more just the Canu phase when we use the mhap for read correction, while the first example that threw the error means use overlaps of 2000 at all Canu phases. 

In any case, I was wondereing:

1 - why does this _corMhapOptions="--min-olap-length 2000"_  *not* throw an error, when paired with minReadLength=1750 \
2 - is there any point using reads shorter than 2000 in runs where I have specified _corMhapOptions="--min-olap-length 2000"_; like, will all  reads < 2000 bp just be thrown away in the end, but slow down correction meanwhile?
3 - do you have any further suggestions on ways to speed up, taking advantage of this extra coverage, other than what I tried above?
*4 - a related mini question about suppression of repetitive regions: I did it for speed so far, but actually I want to assemble thee repetitive parts of the genome too, as far as possible; would you recommend that I just take the longer time, not suppressing, if I want these regions? It for some reason just dawned on me that by suppressing repeats maybe I am thus not assembling them, and I wanted to check if this is the case or not. 

Thanks for any help!

**Comment by skoren** [comment]
1. Since it's passed a string to the MHAP step, it bypasses the check you are hitting when specifying the minOverlapLength directly. Essentially, if you explicitly specify string parameters to a step they're not separately checked for correctness (including syntax).
2. The reads <2kb will generally be thrown away, yes. You can filter them to speed up the assembly, but I wouldn't go much higher than 2kb since you don't have that much coverage to begin with.
3. Not much beyond what you are already doing. You could try the uncorrected assembly as documented on the quick start: https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files. You could also use a grid engine if you have one available and aren't using it
4. Canu has no way to filter the repetitive regions, suppressing just means you really prefer not to use repetitive k-mers as seeds. The changed parameters bias the k-mer selection away from repeat k-mers even more aggressively. However, if there's no other k-mers to use for seeding, then repetitive ones are used so even reads within repeats will have overlaps and correction.

**Comment by JamesHowie14** [comment]
Dear Skoren, thanks for your rapid and very helpful answers. For 1 - great, thanks. For 2 - Yes, I agree, not throwing out >> 2000 bp reads makes sense given our start coverage, but I'll try removing at least up to the overlap limit. For 3 - thanks. I'll take a look at the uncorrected assembly options as you suggest. For 4 - ah OK thanks, I didn't realise that ;) Good to know. Again, thanks, much appreciated :)
