### ISSUE TITLE
Error upon limiting number of jobs in array

### ISSUE THREAD

**Issue by wbrewer5** [marbl/canu#2130]
```
#!/bin/bash
#SBATCH -J canu_pandora
#SBATCH --account ACF-UTK0011
#SBATCH --time 1-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=campus
#SBATCH --output=log/pandora_canu.o%j
#SBATCH --error=error/pandora_canu.e%j
#SBATCH --qos=campus

set -x

module load canu/2.0
#module load gnuplot

canu \
-d /lustre/isaac/scratch/wbrewer5/pandora/assembly/canu/output \
-p pandora_canu \
genomeSize=700m \
-nanopore /lustre/isaac/scratch/wbrewer5/pandora/assembly/fastq/pandora_nanopore.fastq \
gridEngineResourceOption="--mem-per-cpu=3800 --nodes=1 --ntasks=12  --partition=campus --qos=campus --time=24:00:00 --account ACF-UTK0011" \
gridEngineArrayOption="-a=ARRAY_JOBS%20" \
merylThreads=1
```
Canu 2.0 running on a linux compute cluster

Removing the line `gridEngineArrayOption="-a=ARRAY_JOBS%20"` allows the code to run just fine. I can replicate the error and show full error output if necessary, but for now I still have this line copied from the error. `sqStoreCreate failed; no info file.` The error also points me the`seqstore.err` file, which is empty.

I am trying to limit the number of jobs because users are limited to 288 threads simultaneously and I still need to run other tasks on short notice.

**Comment by skoren** [comment]
You shouldn't be using the resource option like you are, canu will fill in memory and threads by itself and it cannot do that with your command. If you want to request options like qos or partition use gridOptions, see https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-options. Otherwise, multiple steps will fail with out of memory/etc. Since you're trying to limit to a specific number of threads, you should also specify maxThreads so that the number of array jobs * maxThreads is under your limit. 

SeqStore doesn't use any array options so I don't think that error is related to limiting array options. Usually this is an issue with bad input reads or concurrent assemblies in the same folder. Make sure you have no other canu assemblies running on your cluster, remove the output folder completely, and re-launch after updating the command as above. Post the full log of canu.out of that run.

**Comment by skoren** [comment]
You can't set a mem per cpu because the memory per cpu varies between jobs in Canu, it's not fixed. It will request memory as appropriate. If you had issues before it may not occur again because your previous command using gridEngineResourceOption would have prevented canu from properly requesting those resources and could have overloaded nodes.

**Comment by wbrewer5** [comment]
I really appreciate the help on a saturday. So, is the `cpu-per-mem` the only string I should remove for gridOptions to be correct?

**Comment by skoren** [comment]
Yes, and your use of ArrayOptions was correct. So you want: `gridEngineArrayOption="-a=ARRAY_JOBS%20" gridOptions="--partition=campus --qos=campus --time=24:00:00 --account ACF-UTK0011"`

**Comment by wbrewer5** [comment]
[pandora_canu.e73688.txt](https://github.com/marbl/canu/files/8838614/pandora_canu.e73688.txt)
[meryl-count.jobSubmit-01.sh.txt](https://github.com/marbl/canu/files/8838615/meryl-count.jobSubmit-01.sh.txt)
Still getting an error having to do with the job array. Could it be due to there on;y being 2 jobs in the first array, so setting 20 as a max is causing error?

**Comment by skoren** [comment]
No, the issue isn't that, it's the `-a=ARRAY_JOBS%20`, you have to use either `-a ARRAY_JOBS%20` or `--array=ARRAY_JOBS%20`, sorry I didn't notice that in your command before.

**Comment by wbrewer5** [comment]
No need to apologize at all. I only recently started using SLURM, so it will be a learning process for a bit. Thank you so much for the help. I will close the issue if the script works as intended overnight.
