### ISSUE TITLE
contigFilter seemingly not working?

### ISSUE THREAD

**Issue by alimayy** [marbl/canu#2136]
Hi there, thanks for developing Canu.

I'm using Canu 2.2 with nanopore data generated from a bacteria with certain contig filtering options (below). According to the documentation of `contigFilter`:

_A contig that needs any of the following conditions is flagged as ‘unassembled’ and removed from further consideration:_

Maybe I am overlooking something, but I am wondering why I get contigs with <150 reads when I use the below Canu command

`/canu-2.2/bin/canu 
  -p TS-651
  -d canu_assembly 
  useGrid=false 
  stopOnLowCoverage=30.0 
  minInputCoverage=30.0 
  genomeSize=1.8m 
  minReadLength=1000 
  contigFilter="150 1000 1.0 0.8 30" 
  -nanopore-raw <samplename>.fastq.gz`

such as 

`>tig00000005 len=7207 reads=98 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-7207`
and in another sample

`>tig00000003 len=7007 reads=64 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-7007`

Any idea why these contigs with <150 reads aren't removed from the final output (<prefix>.contigs.fasta)?

```
root@2d028e7189ca:/# /canu-2.2/bin/canu --version
canu 2.2
```

**Comment by skoren** [comment]
The filter only removes singleton contigs, those which are part of the graph don't get demoted/removed (e.g. to avoid throwing away small bubbles for example). So, in your case, the contigs are suggestRepeat=true which means they were part of a contig that was split by the repeat detection step and so aren't removed since they are part of that original contig path.

**Comment by alimayy** [comment]
Thanks @skoren , clear! Closing the ticket.
