### ISSUE TITLE
Unable to get canu to run on compute cluster

### ISSUE THREAD

**Issue by 9315808** [marbl/canu#2148]
Hi,

I've been trying to get canu to run on my university's compute cluster as part of a larger genome assembly pipeline but have been hitting some roadblocks when it comes to making it run on our system. Largely, it seems to not like how it is configured. Regardless of how many cores I request for canu and what grid mode I put canu in, it can only ever identify one cpu core. Attached you'll find the error files for different runs and their corresponding stdout files (which have the submission script and statistics about the run appended to the bottom). Ignoring me struggling with getting the input file formatting correct, what could be going on here? If you'd like to look more into our cluster, there's a [website](https://hpc.ncsu.edu) dedicated to it with plenty of rabbit holes to dive down.

[canu_out.286840.txt](https://github.com/marbl/canu/files/9173049/canu_out.286840.txt)
[canu_out.286839.txt](https://github.com/marbl/canu/files/9173050/canu_out.286839.txt)
[canu_out.286838.txt](https://github.com/marbl/canu/files/9173051/canu_out.286838.txt)
[canu_out.286836.txt](https://github.com/marbl/canu/files/9173052/canu_out.286836.txt)
[canu_err.286840.txt](https://github.com/marbl/canu/files/9173053/canu_err.286840.txt)
[canu_err.286839.txt](https://github.com/marbl/canu/files/9173054/canu_err.286839.txt)
[canu_err.286838.txt](https://github.com/marbl/canu/files/9173055/canu_err.286838.txt)
[canu_err.286836.txt](https://github.com/marbl/canu/files/9173056/canu_err.286836.txt)

**Comment by skoren** [comment]
There are several issues in your command. First, you don't want to simultaneously launch correct and trim steps since canu will launch sub-jobs so the trim will start running before correction is done (see first paragraph at https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system). Second, provide a full path to the input fastq, it seems your launch location where you submit canu from != where canu actually starts running on the grid so it can't find the input files. Lastly, you shouldn't submit the canu command itself, launch it on the head node and it will submit jobs for you.

Now as for the actual run errors, your cluster documents say it's LSF but then it has an sinfo (slurm) script which seems to be incompletely or incorrectly faking slurm. You want to explicitly set it to use LSF so it doesn't try to guess. You might need to add more grid options depending on what your cluster requires (e.g. time or partition or account type). Add `useGrid=true gridEngine=lsf` to your command and run canu on the head node and see what happens then.

**Comment by 9315808** [comment]
Excellent, thank you! Your solutions have helped a lot. Unfortunately, a new problem has arisen. As canu tries to submit jobs, it uses the wrong formatting to submit them on our cluster - canu uses `-w` to specify wall clock time, while our cluster requires `-W` to do so and errors out upon canu attempting to submit the job. The command to request memory also is incorrect, as on our system we must use `-R "rusage[mem=x]"` instead of what canu uses, `-M 4096`, which our system will simply ignore.

Also, I am aware that the data I am running canu on has barely any coverage and will not produce good results. I am working with a Nanopore run that got interrupted but I do have more data on the way, so at this time I am just trying to get canu functioning before using it with my additional runs.

[canu_err.287380.txt](https://github.com/marbl/canu/files/9174979/canu_err.287380.txt)

[canu_out.287380.txt](https://github.com/marbl/canu/files/9174978/canu_out.287380.txt)
.

**Comment by skoren** [comment]
Canu doesn't specify wall-clock time at all, the -w option is wait not time and doesn't look like it's causing an issue for the commands being submitted. If there was a submit error, it'd be reported in your canu log and it is not. The jobs (287381 and canu waiting for that job) look like they were submitted without issue. You can use `gridOptions="-W <3-4 days or other time>"` to make canu request a time.

As for -M, that's a standard LSF option: https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=o-m. If your cluster has a custom setup, you can overwrite the default resource request: https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-configuration. The default for LSF is `gridEngineResourceOption="-R span[hosts=1] -n THREADS -M MEMORY"`. If you want to change it update it to `gridEngineResourceOption="-R span[hosts=1] rusage[mem=MEMORY]-n THREADS" assuming you don't need to modify the thread request format.

**Comment by 9315808** [comment]
Lovely, it's all working now! Thank you for your help.
