### ISSUE TITLE
Tweaking the right parameters for de novo assembly of PCR products

### ISSUE THREAD

**Issue by olu2016** [marbl/canu#2175]
Hi,
I'm working on de novo assembly of a pool of 2 PCR products with the expectation that between 1 - 3 contigs will be generated. I have carried out a parameter sweep for two canu (canu 2.2 on linux) parameters (minReadLength and minOverlapLength), and the expected contigs (each of the contigs is ~600bp) were best with these two parameter values: -minReadLength=125 -minOverlapLength=85 as carried out using the canu command below:

`canu -batMemory=120 -maxInputCoverage=1000000 -contigFilter="2 0 1.0 0.5 0" -minReadLength=125 -minOverlapLength=85 -genomeSize=2.0k readSamplingCoverage=300 -nanopore -trimmed fastqfile`

However, a repeat of the above run yielded different and unexpected number of contigs on the same samples used for the parameter investigations above. I noticed that the coverage in the canu output file (*.report) vary between 6x and 300X. 

I'm guessing that because of the random sampling nature of ` readSamplingCoverage` , results from repeated runs may be different.

Are there any suggested values for the parameters in my command that will ensure that I obtain consistently good assembly of the small contigs?

**Comment by skoren** [comment]
I wouldn't rely on random read sampling if you want consistency. In PCR products you don't want to select for very long reads since those are more likely to be artifacts, especially when they're longer than your targets. The read sampling by default is biased to select longer reads. I would suggest downsampling before running, removing very long reads as well as lowering coverage to 100-200x. There is the readSamplingBias option (https://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=sampling#global-options) that you could experiment with to prefer the shorter reads.

**Comment by olu2016** [comment]
Thanks @skoren I will try out your recommendations.
