### ISSUE TITLE
slow speed in overlapping step 

### ISSUE THREAD

**Issue by scintilla9** [marbl/canu#2188]
Hi,

I am working on a Linux server with Ubuntu 16.04, and trying to use HiCanu to assemble a genome with about 1.2G.
I have hifi reads that is about 28X coverage of the genome, therefore, I tried the following command with canu v2.2:

`canu -p DDA_canu_hifi -d . genomeSize=1.2G -pacbio-hifi cell2.hifi_reads.fasta cell3.hifi_reads.fasta cell4.hifi_reads.fastq.gz > canu_hifi.out &`

However, the process stuck at overlapping step (keep running but in a slow way). It have been run for 10 days with 48 CPUs. I think I have enough memory and disk space for the assembly work, but cannot figure out what's going on here.
I attached the canu.report file and the log file as below, could you kindly give me some suggestion?

[canu_hifi.out.txt](https://github.com/marbl/canu/files/10293394/canu_hifi.out.txt)
[DDA_canu_hifi.report.txt](https://github.com/marbl/canu/files/10293395/DDA_canu_hifi.report.txt)

**Comment by skoren** [comment]
I think part of the issue is just the relatively low number of cores, and that it's only running 3 jobs at a time. You're about halfway through the run right now. 

It's also possible that the filtering threshold for repetitive k-mers is set too high. You can check for this by looking for the minimum count value in `0-mercounts/asm.ms*dump`. If it's very high, you could add `ovlMerDistinct=0.975` or `ovlMerThreshold=300` (10* your coverage). This would require you to restart the run from scratch though.

**Comment by scintilla9** [comment]
Indeed, the minimum count in `0-mercounts/asm.ms*dump` seems to be too high, it's 612.
I restarted the pipeline and followed your suggestion by adding the command with `ovlMerDistinct=0.975`.

Thanks for your help, I will come back to update the outcome.

**Comment by scintilla9** [comment]
Hi Koren,

After adding `ovlMerDistinct=0.975`, the minimum k-mers frqeuency reduce to 75.

However, the overlapping process seems to be slow still, it is now working on 14th job (14/106). The resource that taken by overlapping is the same as pervious run (3 concurrent  job, with each job took 16 CPUs), The memory is still plenty, this step only took 3% of the memory in our linux.

In my pervious experience, with the same input HiFi reads, the Canu (not HiCanu) can finished within 5 days. Is there any factors I may ignore?

**Comment by skoren** [comment]
Were you using -fast for your canu run, otherwise, there's no reason for HiCanu to be slower since it runs identical code to Canu except with a lower error tolerance, which would make it faster not slower.

The resources per job wouldn't change but with the lower mer threshold each job should take less time. The only other factor is that the partitioning is sometimes off and so the reads have to get loaded twice, doubling each job's runtime. The parameters to control the partitioning aren't very intuitive so I wouldn't try to adjust it. The only other options to speed up the overlapping would be to increase the k-mer size or the minimum overlap length but that might affect your assembly adversely so my advice would be to let it run and see how long it takes.

**Comment by scintilla9** [comment]
Thanks for the info. 

No, I didn't add `-fast` in the pervious Canu run. The different between my Canu and HiCanu runs is the input data option, from `--pacbio` to `-pacbio-hifi`.  I also add linux build-in `time` to estimate the run time in the HiCanu run, I didn't mention this before because I think this should not affect HiCanu.

I will lower the job priority of HiCanu run, and just left it there, since there's other works wait for analyzing. Will update if I got some results. Thanks!

**Comment by skoren** [comment]
We found recently that there is a sweet spot in k-mer filtering for the overlapping step which may be causing your slowdown. Filtering too few k-mers is bad (expected) but filtering too many is also bad and leads to a slowdown (somewhat unexpected). We've found 0.995 is a good general setting for human HiFI datasets at least. You can try a couple of values for ovlMerDistinct, say 0.985, 0.995 and see if one runs faster than the other.
