### ISSUE TITLE
Enhanced parameters for gene dense and heterozygous genomes

### ISSUE THREAD

**Issue by RxLoutre** [marbl/canu#221]
Hi everyone !

I'm trying to use Canu in order to assemble the D. suzukii genome. As flies genome are genes dense (genes are very close to each others), and as the D. suzukii species contains a lot of polymorphism, I think that my Canu result contains a lot of duplication.

Indeed, I estimate that my genome size for D. suzukii is about 220M bp, but my canu result find almost 300M. I tried the software BUSCO, that find single copy genes (strongly conserved in arthropods), and I found 22% of theses single copy genes are duplicated inside my assembly ( against 5% for the closely related species D.melanogaster, which genome is highly contiguous).

I was looking for some parameters that can fit better to my particular cases. Here the parameters I used last time : 

canu -p suzukii -d /media/loutre/SUZUKII/canu_assembly genomeSize=220000000 -pacbio-raw /media/DATAPART1/Documents/suzukii_assembly/pacbio_reads/filtered_subreads.fastq -minReadLength=7000 -stopOnReadQuality=0 -minOverlapLength=1000

Thanks for your advices !

Cheers,

Roxane

**Comment by aphillippy** [comment]
Hi Roxane,
Rather than smash heterozygous alleles together into a consensus representation, Canu attempts to split them into separate contigs where possible. We are working on flagging such contigs as alternatives, but currently most of them end up in the full output. To identify and remove them you could try aligning the contigs against themselves using a tool like Nucmer. If you prefer to smash things together more aggressively, @skoren or @brianwalenz might have some parameter advice.

Best,
-Adam

**Comment by RxLoutre** [comment]
Hi Adam, thanks for your answers, well, I don't really know if I want to keep them or remove them, but I think that for now, as diploid assembly isn't ready yet, I'm trying to have a "correct" result that is a bit closer to my estimated genome size (220M).

What I tried : I identified where the duplicated Busco genes were one my contigs, and then I compared two by two contigs containing theses duplications. I throwed away the shortest contig used for the comparison when blast result show more than 90% homology and when the shortest contig was shorter than 200Kb. All this "short" contigs were then removed from the fasta file, and I re-runned Busco on this "hand cleaned" file.

The result gets better, both when I'm watching it with Quast or Busco. I've loosed 10% of the complete but duplicated Busco genes (and then gained 10% of complete and single copy genes), my N50 improved, I removed approximatively 130 contigs, and the largest contig is still the same.

For now, I'm satisfied with this result, it's slightly better, but still a bit large ( 281M instead of 220M genome size).

So if you have any suggestions I'm in !

**Comment by brianwalenz** [comment]
There is one parameter, not exposed in the canu interface, that will change how aggressive it will be at assembling reads.

1) In canu_assembly/unitigging, make a new directory 4-unitigger-aggressive
2) Copy unitigger.sh from 4-unitigger to the new directory
3) Modify the script to increase the '-dg' and/or '-db' values from '6' to ... ?
4) Modify the script to change the -o parameter to the new directory (this is the name of the logging and etc outputs)
5) Modify the script to change the -T parameter to the new directory (this is the name of the actual outputs)
6) Run unitigger.sh

The two parameters control how similar reads need to be for them to be initially assembled (-dg) or to be merged as bubbles (-db).  (The -dr parameter is for detecting repeats; you probably don't want to modify it.)  The value is essentially the number of standard deviations allowed in percent error.  The actual values are reported in the first *log file in that directory.  For e.coli, I see:

mean   0.00115480 stddev 0.00257802 -> 0.01662293 fraction error =   1.662293% error
median 0.00040000 mad    0.00040000 -> 0.00395824 fraction error =   0.395824% error

We're using median absolute deviation here, and picked 0.4% error as a cutoff.

When the run finishes, you can check the last of the *sizes files for the assembly size.

If you get a better result, we can work on generating consensus sequences.  I think I'd rather add support for this to canu instead of giving directions.

**Comment by RxLoutre** [comment]
Thanks for the tip ! I'm going to play with those parameters and see.

I modified the -T option but not sure if it's correct : 

`-T /media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive/suzukii-agressive.tigStore.WORKING \`

Before to start, should I also modify the mv command ?
`mv /media/loutre/SUZUKII/canu_assembly3/unitigging/suzukii.tigStore.WORKING /media/loutre/SUZUKII/canu_assembly3/unitigging/suzukii.tigStore.FINISHED
`
I don't want to erase any previous result

I also modified this line : 

`> /media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive/unitigger.err 2>&1 \`

I don't know if it's important but as I saw the "unitigger 4 " directory, I thought it will be safer to add the -agressive.

So, as I understand, I have to slightly raise the -db value and slightly decrease the -dg value, so the structural variant will be considered as "bubble" more as a part of the assembly, I'm I right ?

**Comment by brianwalenz** [comment]
Yes, change any reference to 4-unitigger to 4-unitigger-aggressive.  Your -T change looks good - you can remove the '.WORKING' from it, and also remove the mv command.  Both of those are to detect if the command fails, but since you're running manually, you can check easier.

Increase both -dg (which will try to build unitigs more aggressively) and -db (to try to merge bubbles more aggressively).  Most of the work will be done by -dg however.

**Comment by RxLoutre** [comment]
Hmm, guess something went wrong : 

```
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ls
unitigger.sh  unitigger.sh~
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ./unitigger.sh
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ls
unitigger.sh  unitigger.sh~
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ 
```
Here the script : 

```
#!/bin/sh

if [ -e /media/loutre/SUZUKII/canu_assembly3/unitigging/suzukii.tigStore/seqDB.v001.tig ] ; then
  exit 0
fi

syst=`uname -s`
arch=`uname -m`
name=`uname -n`

if [ "$arch" = "x86_64" ] ; then
  arch="amd64"
fi
if [ "$arch" = "Power Macintosh" ] ; then
  arch="ppc"
fi

bin="/home/loutre/canu-1.3/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/home/loutre/canu-1.3"
fi

$bin/bogart \
 -G /media/loutre/SUZUKII/canu_assembly3/unitigging/suzukii.gkpStore \
 -O /media/loutre/SUZUKII/canu_assembly3/unitigging/suzukii.ovlStore \
 -T /media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive/suzukii-agressive.tigStore \
 -o /media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive/suzukii \
 -B 6619 \
 -gs 220000000 \
 -eg 0.075 \
 -eM 0.075 \
 -el 1000 \
 -dg 10 \
 -db 10 \
 -dr 3 \
 -ca 5000 \
 -cp 500 \
 -threads 20 \
 -M 31 \
 -unassembled 2 1000 0.75 0.75 2 \
 > /media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive/unitigger.err 2>&1

exit 0
```

It seems that I have the rights : 
```

Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ls -l
total 8
-rwxrwxr-x 1 loutre loutre 1017 août  11 11:28 unitigger.sh
-rwxrwxr-x 1 loutre loutre 1016 août  11 11:28 unitigger.sh~
```

I expected the results to be in the same directory than the script... Did I made something wrong ?

**Comment by RxLoutre** [comment]
I allowed myself to modify the threads number (I have 32 CPU so I guess using 20 is okay)

**Comment by brianwalenz** [comment]
Ah, remove the test at the very top - it is checking for an output file (which exists) and will just exit the script if it is found.  The rest of it looks fine.

Remove this:
```
if [ -e /media/loutre/SUZUKII/canu_assembly3/unitigging/suzukii.tigStore/seqDB.v001.tig ] ; then
  exit 0
fi
```

**Comment by RxLoutre** [comment]
Great ! It worked, now I have plenty of files produces but not sure of how I'm supposed to use them.

```
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ls
unitigger.sh  unitigger.sh~
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ./unitigger.sh
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ./unitigger.sh
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ls
suzukii.002.bestOverlapGraph.thr000.num000.log  suzukii.best.edges
suzukii.005.buildUnitigs.thr000.num000.log      suzukii.best.edges.gfa
suzukii.006.placeContains.thr000.num000.log     suzukii.best.edges.histogram
suzukii.007.popBubbles.thr000.num000.log        suzukii.best.edges.suspicious
suzukii.008.markRepeatReads.thr000.num000.log   suzukii.best.singletons
suzukii.009.cleanup.thr000.num000.log           suzukii.fragmentInfo
suzukii-agressive.tigStore                      suzukii.iidmap
suzukii.arrivalRate.1.dat                       suzukii.partitioning
suzukii.arrivalRate.2.dat                       suzukii.partitioningInfo
suzukii.arrivalRate.3.dat                       suzukii.unused.edges
suzukii.arrivalRate.4.dat                       unitigger.err
suzukii.arrivalRate.5.dat                       unitigger.sh
suzukii.best.contains.histogram                 unitigger.sh~
Loutre:/media/loutre/SUZUKII/canu_assembly3/unitigging/4-unitigger-agressive$ ls suzukii-agressive.tigStore/
seqDB.v001.dat  seqDB.v001.tig

```

**Comment by brianwalenz** [comment]
Dang, you're using the 1.3 release, right?  I had improved logging since then.  :-(

First, look in `suzukii.002.bestOverlapGraph.thr000.num000.log` to find what error rates are being allowed.

Then, look at the sizes reported in `suzukii.009.cleanup.thr000.num000.log`, near the end of the file.

You can keep turning up the dg/db parameters until the error rate exceeds 7.5%.  Overlaps were only computed to that limit (I think).

**Comment by brianwalenz** [comment]
Error rates:  The important lines are (first from aggressive, second from normal):
```
removeHighErrorBestEdges()-- with 830169 points - median 0.002400 mad 0.001700 - would use overlaps below 0.027604 fraction error
removeHighErrorBestEdges()-- with 830169 points - median 0.002400 mad 0.001700 - would use overlaps below 0.017523 fraction error
```
So you increased the error rate from 1.75% to 2.76% with your parameter change.

In the cleanup files, the last lines (from normal) are:

```
BUBBLE (16 tigs) (556136 length) (34758 average) (0.00x coverage)
REPEAT (240 tigs) (9239834 length) (38499 average) (0.04x coverage)
CONTIGS (1262 tigs) (283674665 length) (224781 average) (1.29x coverage)
ng010  24239212   lg010        1   sum    24239212  (CONTIGS)
ng020  13747766   lg020        3   sum    52809168  (CONTIGS)
ng030   6696881   lg030        5   sum    68625413  (CONTIGS)
ng040   3169837   lg040       10   sum    90378131  (CONTIGS)
ng050   1103934   lg050       23   sum   110929479  (CONTIGS)
ng060    765932   lg060       48   sum   132690971  (CONTIGS)
ng070    524188   lg070       83   sum   154344580  (CONTIGS)
ng080    381335   lg080      132   sum   176021042  (CONTIGS)
ng090    271311   lg090      201   sum   198060356  (CONTIGS)
ng100    181065   lg100      303   sum   220128311  (CONTIGS)
ng110    111872   lg110      459   sum   242035134  (CONTIGS)
ng120     58577   lg120      727   sum   264058260  (CONTIGS)
```
Or, 1262 contigs with 283Mbp.  From 'aggressive', there are 1223 contigs with total length 280Mbp.  Slightly better.  N50 got slightly better, too.

So, keep turning dg/db up.  Try increasing dr too - with higher dg values, the chance of a misassembly at a repeat increases, so we need to increase the repeat detection threshold too.

Right now, we're probably fine looking at sizes and not sequences.  Once we find parameters that seem to work, we can cleanup the old result to let canu generate consensus sequences.

**Comment by RxLoutre** [comment]
I think that I found some good parameters, here what I get with -db = -dg = 28, -dr=5 : 

suzukii.002.bestOverlapGraph.thr000.num000.log : 
```
removeHighErrorBestEdges()-- with 830169 points - mean 0.007028 stddev 0.012939 -- would use overlaps below 0.369318 fraction error
removeHighErrorBestEdges()-- with 830169 points - median 0.002400 mad 0.001700 - would use overlaps below 0.072972 fraction error
removeHighErrorBestEdges()-- 17085 ends have no best edge; 0 ends are suspiciously high error; 830169 ends are acceptable.
```
suzukii.009.cleanup.thr000.num000.log

```
UNASSEMBLED (31789 tigs) (407198192 length) (12809 average) (1.85x coverage)
ng010     21792   lg010      883   sum    22001515  (UNASSEMBLED)
ng020     19214   lg020     1965   sum    44001820  (UNASSEMBLED)
ng030     17752   lg030     3160   sum    66012327  (UNASSEMBLED)
ng040     16703   lg040     4439   sum    88008191  (UNASSEMBLED)
(...)
BUBBLE (16 tigs) (445873 length) (27867 average) (0.00x coverage)
REPEAT (237 tigs) (9498465 length) (40077 average) (0.04x coverage)
CONTIGS (1189 tigs) (260141344 length) (218790 average) (1.18x coverage)
ng010  22993157   lg010        1   sum    22993157  (CONTIGS)
ng020  22867642   lg020        2   sum    45860799  (CONTIGS)
ng030  10999519   lg030        4   sum    71499587  (CONTIGS)
(...)
```
Don't know if it's normal, but there is a high level of unassembled contigs here. I mean, it was higher in the normal version (1.95x coverage in normal, 1.85 coverage in agressive), but I think it is still very high, but I guess that this problem couldn't be solved easily

**Comment by RxLoutre** [comment]
Are you still available ? I still need help to obtain the corresponding fasta please

**Comment by brianwalenz** [comment]
Thanks for the reminder.

The easiest method will be to make a new assembly directory, and move or copy the old data to it.

```
mkdir -p newAsm/unitigging
mv oldAsm/unitigging/suzukii.gkpStore newAsm/unitigging/
mv oldAsm/unitigging/suzukii.ovlStore newAsm/unitigging/
mv oldAsm/unitigging/[0123]* newAsm/unitigging/
chmod -R -w newAsm/unitigging/*
```

The chmod might cause problems, but I don't think so.  It's there just so we don't accidentally mess up the reads or overlaps.  If the stores are not huge, I'd suggest copying all the above files instead of moving.

Then restart canu, using `-d newAsm` and `-assemble` and `errorRate=0.025`.  It should start running bogart.

Option `utgGraphDeviation` will set the -dg and -db parameters.
Option `utgRepeatDeviation` will set the -dr parameter.

**Comment by RxLoutre** [comment]
Thanks for your answers !
I'm not really sure about the canu command I should launch, and where I have to launch it.
For an obscure reason, I can't find the 2- something directory in my first assembly try...

**Comment by brianwalenz** [comment]
Launch it from the same place that you created 'newAsm'.

Command will be:

canu -p suzukii -d newAsm -assemble utgGraphDeviation=28 utgRepeatDeviation=5 errorRate=0.0.25 genomeSize=220000000  minReadLength=7000 stopOnReadQuality=0 minOverlapLength=1000 -pacbio-raw /media/DATAPART1/Documents/suzukii_assembly/pacbio_reads/filtered_subreads.fastq

I just added my suggestions to your original command.

The '-d newAsm' says to compute the assembly in 'newAsm'.  When you copied files over, you made this look like it had just computed everything up to creating unitigs.  And now you're starting canu up again to do that, build consensus fasta, and finish the assembly.

If you made copies of the gkpStore and ovlStore, there isn't much danger of a catastrophe that would need lots of compute to recover from (e.g., restarting).

**Comment by RxLoutre** [comment]
Okay thanks for the advices !
So you thinks that's not a big deal if the 2-directory is not present..?

**Comment by brianwalenz** [comment]
Not a problem.  There isn't a 2-directory in the assembly stage!  The hole is either a historical accident, or was left for future expansion.

In general, canu uses the files it finds to figure out where it is.  So if it thinks it is missing a 2-something directory, it would happily compute it for you.

**Comment by RxLoutre** [comment]
Haha no thank you, that's kind but I don't think it need one, I was just wondering if I made a mistake by accidentally deleting something !

**Comment by bostanict** [comment]
Hi,

I am following exactly the same steps. The unitigger.sh finishes successfully for the aggressive version but I do not have the logfile No.2 and No.9 in the folder. Here is my folder content list:

![image](https://cloud.githubusercontent.com/assets/18707274/18351566/b1509602-75a8-11e6-93ad-c5b40d4518be.png)


fodler old is not included since contain some old data. Can you please tell me if there is an error? otherwise where I can get the bestOverlapGraph.thr000.num000.log  and check the bg and db tunning?

thanks

**Comment by brianwalenz** [comment]
Blueberries!  Yummy!  I've only assembled deadly, yucky or things we probably should be eating (like humans).

Most of the 'interesting' numbers are now in unitigger.err, leaving only the gory details in the *.log files.

**Comment by kgun12** [comment]
This is what I was witnessing in issue #93 

I have since assembled several genomes using PB RSII data, and had others send me assemblies that used canu and/or SMRTmake, and all with a very large amounts of assembly duplication.  All-vs-all self blasts return thousands of self-hits of 5kb-50kb in length at 99-100% similarity.  I'm thinking it is either an issue with heterozygosity, as these are non-clonal multiiisolates of algae and protists, or there is some other large-scale systemic problem with chimerism or template switching in the subread->consensus process.  I haven't tried a recent version of canu, though, and the above may help.
