### ISSUE TITLE
Which part of over 200 X Hifi reads is selected ?

### ISSUE THREAD

**Issue by sunriseTM** [marbl/canu#2241]
Hi, I am assembling a microorgaism genome with over 200X Hifi reads, but canu told be that only 200X was selected for assembling, do you have any ideas on which part of it was selected?

Canu says this:

For genome size of     28000000 bases,
            retain   5600000000 bases (200.00X coverage).

Found      1106878 reads with  20999061795 bases (749.97X coverage).
Dropped     811663 reads with  15399054876 bases (549.97X coverage).
Retained    295215 reads with   5600006919 bases (200.00X coverage).

**Comment by brianwalenz** [comment]
At that point in the process it is picking random reads.  Parameter readSamplingCoverage controls this behavior: https://canu.readthedocs.io/en/latest/parameter-reference.html#readsamplingcoverage.    Increasing the coverage here will greatly slow down correction and the only real benefit is if there are sequences (e.g., plasmids) in the input.

After correction, reads are further down-sampled to (roughly) 40x, but this does take into account 'rare' sequence.  This is done because overlap-layout-consensus methods seem to suffer with excessive coverage.  This particular parameter is corOutCoverage: https://canu.readthedocs.io/en/latest/faq.html?highlight=coroutcoverage#why-is-my-assembly-is-missing-my-favorite-short-plasmid

**Comment by sunriseTM** [comment]
Thanks for your in-time reply! I know Canu will only output 40X corrected reads when I was assembling with PacBio CLR reads. is there also a 'correction' process for Hifi reads？I have been supposing Hicanu will assemble Hifi reads directly.

**Comment by brianwalenz** [comment]
Oops, I missed that you had HiFi data!  Sorry for the confusion.  There is no correction phase for HiFi reads; they're also assumed to be pre-trimmed.

**Comment by skoren** [comment]
There was a bug introduced in v2.2 that was setting the hifi subsampling to 200x as well instead of 50x. I suggest using maxInputCoverage=50 for hifi data until the next release.
