### ISSUE TITLE
exceeded memory allocation

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [marbl/canu#2243]
Running on local machine, I always get memory allocation errors. My understanding is this should be automatic? It seems to be the meryl step that is the problem so far. The node I am using should have plenty of resource for this genome (3.2Gbp).

Thanks for any help.

job script:

```
#PBS -P dy44
#PBS -q normalsr
#PBS -l walltime=48:00:00
#PBS -l ncpus=416
#PBS -l mem=500GB
#PBS -l jobfs=400GB
#PBS -l wd
#PBS -l storage=gdata/nm31+scratch/nm31+gdata/if89+scratch/dy44+gdata/dy44

cd $PBS_JOBFS

label=doryanthes
saveLocation="/g/data/dy44/r12.1_doryanthes/canu/"
reads="/g/data/dy44/r12.1_doryanthes/q15_10k.fastq"
stageDirectory="./"
genomeSize=3200m
correctCoverage=35
correctedErrorRate=0.105
corMaxEvidenceErate=0.15

/g/data/nm31/bin/canu-2.2/bin/canu \
        -p $label \
        -d ${saveLocation}/canu_${label} \
        -nanopore $reads \
        genomeSize=${genomeSize} \
        stageDirectory=${stageDirectory} \
        corOutCoverage=${correctCoverage} \
        "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
        useGrid=false \
        correctedErrorRate=${correctedErrorRate} \
        corMaxEvidenceErate=${corMaxEvidenceErate} \
        -fast

```
[canu.sh.e90273386.txt](https://github.com/marbl/canu/files/12034400/canu.sh.e90273386.txt)

**Comment by brianwalenz** [comment]
I agree, the node should have plenty of resources.  Looking at the first of the meryl "exceeded memory allocation" reports, I don't understand why it is claiming out of memory - the RSS (amount of memory actually in use) sums to 124 GB and VMEM (amount requested from the OS) is 129 GB.

Looking at what the normalsr queue supplies (https://opus.nci.org.au/display/Help/Queue+Limits) and the 'more information' link (https://opus.nci.org.au/x/SwGRAQ) I suspect what happened is that your CPU request of 416 resulted in the job being assigned to 416 / 104 = 4 nodes with each node limited to 500 / 4 = 125 GB memory.  When run with `useGrid=false` canu can make use of exactly one node - and this agrees with the out of memory kill at just more than 125 GB.  :-(

Canu can use multiple nodes, but it needs to do the scheduling itself with `useGrid=true`.  In this mode, run 'canu' on the head node; it will analyze the resources supplied by the grid, then it will submit itself to the grid and take care of the cpu/memory requests for all the subjobs.  See https://canu.readthedocs.io/en/latest/tutorial.html#execution and https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-config for (not much more) documentation.  (Instead of experimenting with your big assembly, use the ecoli dataset at https://canu.readthedocs.io/en/latest/quick-start.html to get a feel for how `useGrid=true` works and what logging it creates.)

Alternatively, reduce your ncpus to 104 (one node) and leave memory the same.  I strongly suggest getting `useGrid=true` to work though.

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks, that makes sense, however, when I tried grid=true on the test data, it looks like canu erroneously detects all grid resources, not just the current normalsr node.. the job scripts then fail. This also happened on my first attempt, which is why I then tried grid=false above. I suspect 104 cpus and only 128Gb of ram will make it very slow... and the walltime is limited to 48 hrs.

```
#PBS -P dy44
#PBS -q normalsr
#PBS -l walltime=4:00:00
#PBS -l ncpus=208
#PBS -l mem=500GB
#PBS -l jobfs=400GB
#PBS -l wd
#PBS -l storage=gdata/nm31+scratch/nm31+gdata/if89+scratch/dy44+gdata/dy44

cd $PBS_JOBFS

label=test
saveLocation="/g/data/dy44/r12.1_doryanthes/canu-test/"
reads="/g/data/dy44/r12.1_doryanthes/ont.fastq"
stageDirectory="./"
genomeSize=5m
correctCoverage=35
correctedErrorRate=0.105
corMaxEvidenceErate=0.15

/g/data/nm31/bin/canu-2.2/bin/canu \
		-p $label \
		-d ${saveLocation}/${label} \
		-nanopore $reads \
		genomeSize=${genomeSize} \
		stageDirectory=${stageDirectory} \
		corOutCoverage=${correctCoverage} \
		useGrid=true \
		maxInputCoverage=100 \
		correctedErrorRate=${correctedErrorRate} \
		corMaxEvidenceErate=${corMaxEvidenceErate} \
		#"batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
		#-fast
```


[canu-test.sh.e90409240.txt](https://github.com/marbl/canu/files/12045403/canu-test.sh.e90409240.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
The '-l select' is also giving a pbs error.

**Comment by theo-allnutt-bioinformatics** [comment]
I just found this.. seems a saint has already been through this. Will try their method.

https://github.com/AustralianBioCommons/Canu/blob/master/NCI_optimisation.md

**Comment by theo-allnutt-bioinformatics** [comment]
My 3.2 GBp genome made 11TB of temp files and so went over quota. Looks like even Canu is a no-go. :(

**Comment by skoren** [comment]
There are some suggestions on the FAQ on how to reduce disk usage: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow but it sounds like you're able to run on the grid so I'll close this issue.
