### ISSUE TITLE
ovlStore building failed

### ISSUE THREAD

**Issue by kevlim83** [marbl/canu#235]
Hi,

I am at this stage of canu where it is building the ovlStore. Some of the jobs exited with the following error:

`Removing incomplete bucket 
...ovlStore.BUILDING/create0455
Max processes per user limited to 1032395, no increase possible.

Max open files limited to 65536, no increase possible.

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ...correction/1-overlapper/results/000455.ovb.gz
Marking fragments to skip overlap based trimming.
LIB 1 - dup=1 trim=1 spur=1 chimera=1 subreads=1
Marked 0 reads so skip OBT, 0 reads to skip dedupe.
ERROR:  Failed to open output file '...correction/d1.ovlStore.BUILDING/create0455/slice7102.gz': Too many open files in system`

It seems that there are too many open files, I checked "ulimit -a", and found 65536, it seems like it can not be increased further with "ulimit -Sn".

Is there an alternative solution?

Thanks.

Regards,
K

**Comment by kevlim83** [comment]
I forgot to mention, I am running on Grid: PBS

Thanks.

**Comment by brianwalenz** [comment]
The error message sounds like the system limit, instead of the per user limit, is being hit.  Off the top of my head, I don't know how to query that number.  Our error message isn't telling how many files the process has open, either.

Two options:

1) Increase ovsMemory.  The default depends on your genome size, but it is reported at the start of the canu screen output.  If you change ovsMemory, delete all of d1.ovlStore.BUILDING before restarting.

2) Limit the number of jobs that PBS will run at any one time, but you'll need to submit the jobs by hand.  The qsub command will be listed in one of the *.out files in the canu-scripts directory.  To do this, add "%N" (where N is how many jobs to run at one time) to the -t option.  http://arc-ts.umich.edu/software/torque/job-arrays/ describes this.

**Comment by kevlim83** [comment]
Indeed, this problem was resolved by manual job submission. I will bear in mind the ovsMemory option in future. Thanks!
