### ISSUE TITLE
problem of java

### ISSUE THREAD

**Issue by sysu515** [marbl/canu#2356]
Regarding the bug that Jave cannot specify, I don’t know if it is a software bug or a server problem. I hope the author can help solve it.
the code i run is as folows
#linux 
canu -p fp_canu -d san_fp_canu genomeSize=10m -pacbio-raw unmapped.fastq

error is as follows
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from '').
ERROR:  ' -Xmx1g -showversion' reports:

but i already add  java to the PATH
nano ~/.bashrc
the last  two rows is as follows:
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH

I guess canu only can use java 8,can't use java 11,so what cause this error?
thanks author

**Comment by sejmodha** [comment]
I get the same error with the latest version when `canu` is installed a in a conda environment that have `gnuplot` and java available. I have tried installing compatible `openjdk` versions `21.0.2` and `23.0.1` - they both throw the same error. 

I have another environment with `canu` version `2.2` along side `openjdk `version `20.0.0` and `canu` does not throw any java related error in that env.

**Comment by skoren** [comment]
Canu can use java 11 or similar recent version of openjdk, here's an example from my laptop: `-- Detected Java(TM) Runtime Environment '23.0.1' (from '/software/homebrew/opt/openjdk/bin/java') without -d64 support.`. 

The error is indicating that ```java --version``` is not found, you can see this from the message: `you have unknown (from '').` That means `which java` isn't reporting a path to java so your PATH configuration isn't applying to the env you have canu in. This is a system issue not a canu issue. 

You can provide a java executable to canu directly by adding
```
java=/path/to/your/jvm/bin/java
```
to ignore the env and use that binary directly.

**Comment by sejmodha** [comment]
Hi Sergey,

Thanks for the clarification. 

This makes sense but I must say that I was under the impression that installing canu using conda/mamba should ensure that all relevant dependencies are taken care of automatically. I found this to be true for the previous version of canu which as I mentioned, works as expected in the conda/mamba env without need of any additional dependencies. 

For canu v2.3, the Mamba environment automatically had OpenJDK (v23.0.1) installed, which I assumed would suffice for canu v2.3's installation requirements. However, I’m unsure whether the issue lies with the OpenJDK versioning or something else, as it seems to cause problems for canu despite Java being available in the environment.  

Any help/pointers will be appreciated.

**Comment by skoren** [comment]
We didn't make the 2.3 conda recipe so it's possible something was broken with it when it was updated though I see it still clearly lists openjdk and it worked on the test system w/v23: https://github.com/bioconda/bioconda-recipes/actions/runs/12382822885/job/34564417067. So I still suspect the issue is on your conda env/install. I'd maybe try a new clean environment.
