### ISSUE TITLE
Can't find the best minReadLength value

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#236]
After your guys' work with Chandler to run Canu on a PBSPRO cluster, we are finally able to have it running.
I started assembling 2 genomes (~400 and ~500 Mb), that I was able to assemble successfully with Falcon (CtgN50 8.1 and 1.5 Mb). The 500 Mb genome is now running, for the other I get an error linked to too many bases skipped or too many short reads.
For example:
minReadLength=6000: to many short reads
minReadLength=10000: to many short reads
minReadLength=12000: too many bases skipped
minReadLength=15000: too many bases skipped
I am now trying with 11 kb, but I don't think this will fix it.
The command is:
`/rsgrps/rwing/bin/canu -d /../6kb -p cuc_6 genomeSize=400m minReadLength=6000 minOverlapLength=300 corMinCoverage=4 gridOptions="-W group_list=oge -q standard -l jobtype=large_mpi -l select=12:ncpus=12:mem=23GB -l walltime=240:00:00" -pacbio-raw /../subreads_input.fa`
What is causing this issue? With Falcon, I was able to assemble it in a range from 8 to 20 kb of read cutoff.
Thanks

**Comment by skoren** [comment]
The minReadLength parameter is not the same as Falcon's read cutoff. 

In Falcon that means load all sequences and only map all reads to those over the cutoff (so you're trying to correct reads over 8k if that's your cutoff). In Canu, this means do not load reads under 8kb so the assembler never sees them. Since this is eliminating a large fraction of your input data you are getting a warning. You should leave minReadLength as default for Canu, it will always compute all-vs-all overlaps and select the longest read length cutoff automatically based on the genome size and computed overlaps.

**Comment by dcopetti** [comment]
Thanks for the clarification, I restarted it without the length parameter.
In the same cluster I was running another Canu job, and once this above started, the old one went on hold. Here is how qstat looks like:
                                                            Req'd  Req'd   Elap
Job ID          Username Queue    Jobname    SessID NDS TSK Memory Time  S Time
--------------- -------- -------- ---------- ------ --- --- ------ ----- - -----
812371.service0 dcopetti clu_wind canu_hazel  20179   8  96  184gb 1536: H   -- 
812472.service0 dcopetti clu_stan canu_cuc11   9392  12 144  276gb 1536: R 146:2

The HTC support person has these questions:
_$ \qstat -f 812371 | grep comment
    comment = job held, too many failed attempts to run
Looking at the mom logs, it looks like it's starting up and dying shortly after.  Do you know how canu is spawning its remote tasks?  Or possibly that the windfall job was preempted at some point and didn't recover cleanly?  Also, are there any issues with running multiple canu instances out of the same working directory?_
Do you think it is due to the concurrent canu jobs? Shall I kill the old one and restart it? Or wait for one to finish maybe?
Thanks

**Comment by skoren** [comment]
The way it is supposed to run is by submitting tasks and holding for those to complete. There will be logs in canu-scripts/canu.\.*.out which will have any error messages. What exactly is in the mom logs?

What do you mean same directory? You should specify different -d parameters to each assembly or it will not work. However, everything is contained within the -d folder so you can launch multiple assemblies with different -d in the same folder. You should also specify gridOptionsJobName with a unique name for each assembly or they will synchronize between all your running jobs.

**Comment by dcopetti** [comment]
The canu.02.sh file is attached here, we had to rename the folder based on the canu.01.out
```
  mv /.../hazel_10.gkpStore.BUILDING \
     /.../hazel_10.gkpStore.ACCEPTED
```
and then the run restarted, until it went on hold. Interestingly, in the second run we did not need to do this renaming (yet?).
I always change the working dir and the run prefix, I don't think that will be causing the problem at all. I will kill the job on hold and restart it with the additional parameter.



[canu.02.sh.txt](https://github.com/marbl/canu/files/425551/canu.02.sh.txt)

**Comment by skoren** [comment]
You don't want to mv the gatekeeper store since, as I explained, the minReadLength parameter, will completely throw out all your data <10kb from the assembly, dropping your . You should restart with a clean directory without that parameter.

**Comment by dcopetti** [comment]
I run it without the min read length parameter and it completed. (this is on a different cluster than the issue #239)
I am surprised of the large difference in assembly metrics between the Falcon and Canu assemblies - see image attached. Total size is quite comparable, but N50 is >4 times smaller with Canu, as well as the amount of allelic contigs (are the bubble sequences equivalent to Falcon's associated contigs?) Especially, there are less large contigs (see histogram on left and detail of larger ctgs on the right) and many more short ones. What parameters can I tweak to improve Canu's performance? Do you think this difference is due to the algorithms or to the structure of the genome?
Thanks
![screenshot from 2016-08-20 18-18-16](https://cloud.githubusercontent.com/assets/13842014/17834783/e46463e6-6704-11e6-9910-af8f3f30e5b5.png)

**Comment by skoren** [comment]
Canu tries to keep haplotypes separate from the start but currently doesn't flag bubbles very well (see issue #188) which is causing it to keep both the haplotypes in your contigs file. You'd need to compute the NG50 rather than N50 to get a comparison of the assembly continuities (otherwise the denominator for the Canu assembly is >60mb bigger). 

You can also increase the tolerance to haplotypes and let canu smash them together (issue #221). Are you running Canu 1.3 or latest in the repo? If the latest you can run a tail on the sizes files in the unitigging/4-unitigger folder to get an idea of which parameters you could adjust to improve the assembly.
