### ISSUE TITLE
Why hierarchical  approach is better?

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#247]
@skoren Hi!

I had found a similar topic (https://github.com/marbl/canu/issues/172), and I think I would want to know more. 

I had simulate reads from one chromosome (pbsim with --accuracy-min 0.8 --accuracy-mean 0.85). Suppose I would sequencing 100X data, so I have two strategies: one with 100X CLR reads  (mean: 15K), and another is 30X CLR reads and 17.5X CCS (mean: 4K). Then I found 30XCLR17.5XCCS using PBcR would be better than 100XCLR with CANU. 

Except stat in https://github.com/marbl/canu/issues/172, I also hear about that only using long reads would be better. Considering that we would use 20X~30X data to assembly genome, then the quality of final assembly depend on the quality of the correct data. So in my simulation, it means using 17.5X CCS give a better correct result than using 70X CLR (100XCLR=30XCLR+70XCLR). 

Although there are 15% error in pacbio read, I think the long read would still make it suit for correction than the short reads, so I feel confused with my result. Then I re-do the analysis with another chromosome, the hybird way is still better. 

So I want to know: 1) Whether you are saing hierarchical approach better than pacbio+illumina,  but with long CCS reads, the hybird way would be better? 2) Or there are some problem in my simulation and it's just exception?

**Comment by skoren** [comment]
When we talk about hierarchical assembly, I'm generally talking about the approaches that build a de bruijn graph and use long reads to walk the graph. Generally, long-read only assembly improves more at higher coverage than those approaches with complex genomes.

Hybrid correction like done by PBcR benefits from long reads, the longest reads being CLR. CCS would give the best/closest correction to using only long reads, we evaluated these various combinations in our 2013 paper: https://genomebiology.biomedcentral.com/articles/10.1186/gb-2013-14-9-r101

Fundamentally, the assembly is most improved by having more long reads to resolve more repeats and having more coverage would give you that. That is why 100X long reads should be better than 30X+CCS. When you say better result, do you mean accuracy of the corrected reads, length of the corrected reads, continuity of an assembly, or base accuracy of an assembly? Longer/higher accuracy corrected reads don't always mean a better assembly because the aggregate stats don't reflect how the correction is doing in complex regions of the genome which likely affects the assembly. If you're seeing worse correction from 100X I would guess the simulated data isn't accurately modeling current sequencing data (we did design the hybrid method for C1 chemistry when non-hybrid wasn't going to work well due to the short reads/high error) so I'd suggest using a small genome with real data and downsampling it instead as a test.

**Comment by lamz138138** [comment]
Hi, thanks for your reply!

The paper is exactly what I try to do, except the genome size is small, the coverage is too high for complex genome, and maybe the pacbio read length is shorter. With longer reads, and lower sequencing data (100X), do you think it is better assembly with long reads only for species like human? In fact, I want to design my project, and I may only get 100X data (maybe using sequel, with mean 8K read length).

I didn't stat clearly before. When comparing assembly, I use the number of contigs, N50, Genome fractions calculated by quast, and manually check the consistency with reference using numcer and mummerplot. I feel the hybrid approach is better, then I think  it result from the better correction reads. Besides, the distribution of canu corrected reads is a little strange, with bimodal read length in 2.5K and 18K, few reads between 10K~15K, I try to find the problem.

**Comment by skoren** [comment]
I would expect 100X for human to be better yes, because again you'd have more long reads than in 30X of data. I think your simulated data is probably not reflecting true sequencing so the default parameters aren't working as well on that data. The CCS data works better in this case because aligning it to a raw read has half the error rate compared to aligning two raw reads.

I did a test where I ran pbsim with default parameters, with ```--accuracy-min 0.8 --accuracy-mean 0.85``` and aligned to reference comparing to real P6-C4 data aligned to the reference (attached, y=% of reads, x = identity). You can see the distributions in the plot, the default pbsim parameters are shifted down compared to real data. The adjusted pbsim parameters reflect the real data better so I'd suggest using those if you want to see what you'd get from a recent run. 

![screen shot 2016-09-02 at 12 00 17 pm](https://cloud.githubusercontent.com/assets/923478/18210084/e66459bc-7104-11e6-8c99-1d677fe48493.png)

**Comment by lamz138138** [comment]
Hi, thank you for so detail reply, it dose help me a lot in my project, thanks very much again！
Best wishes!
