### ISSUE TITLE
bogart parameter sweeping

### ISSUE THREAD

**Issue by kevlim83** [marbl/canu#249]
Hi,

I was trying to sweep the parameters following the post #88.

However, I encountered some inconsistencies. In the new unitigger folder, there is a generateOutputs.sizes file with an ng50 of about 400kb and total length about 800mb. Next, I proceeded with the consensus step and load the resulting tigs back into the tgStore but when I tried to dump the fasta using tgStoreDump, the contigs total length was only 400mb.

Did I miss something here?

Thanks.

**Comment by brianwalenz** [comment]
I suspect that the problem is in partitioning the reads for efficient loading in each consensus job.  This partitioning was probably done based on the initial contigs, and so when consensus processed the new contigs, it failed to find many reads.

Rather than try to figure out what the problem _actually_ is (and how to correct it), it'll be easier set the bogart options you picked in your parameter sweep in the batOptions canu option, clean up the old contigs, and let canu finish as normal.

You'll need to remove (or move aside) these directories in the unitigging/ directory:

4-unitigger
5-consensus
*.tigStore
*.gkpStore/partitions

You'll probably also need to clean up the output files in the root assembly directory (e.g., *.contigs.fasta), otherwise you won't get updated results.

**Comment by brianwalenz** [comment]
The latest version (as of a week or so ago) fixes the partitioning problem.  The *.gkpStore/partitions directory no longer exists.
