### ISSUE TITLE
unassembled read ID

### ISSUE THREAD

**Issue by bostanict** [marbl/canu#255]
Hi,

I am wondering if there is a way that I can have or extract the actual read IDs that were not assembled. I see the file unassembled.fasta but the read IDs are changed. Even looking at the readtotig file, I was not able to extract them.

Is there anyway that we cna have the read ID of the raw pocbio sequence that was not assembled?

Thanks

**Comment by brianwalenz** [comment]
Finding _all_ reads not assembled will be hard.  Some reads are dropped because they don't generate usable corrected reads.  Some are dropped because they get trimmed to something too short.

So we need to work backwards from the reads that assembled.  Find the assembled contig IDs in the contigs.fasta.  Use readToTig to find the reads in those tigs - the readID here is the internal canu ID.  This can be mapped to the original name using unitigging/*gkpStore/readNames.txt.

Note 1 - I don't know if this will work with the 1.3 release.  If you're getting bizarre results or some of the files (readNames in particular) look truncated or incomplete, upgrade to the lastest code and rerun (you only need to rerun the 'assembly' stage, not correction and trimming).

Note 2 - a read being assembled into a contig just means that _some_ of the read was assembled, correction and trimming can (dramatically) chop the read up.

**Comment by brianwalenz** [comment]
Moving from active issue to feature request. https://github.com/marbl/canu/projects/1
