### ISSUE TITLE
Failed with signal HUP(1)

### ISSUE THREAD

**Issue by russellj7** [marbl/canu#27]
Using nanopore raw data input and the following command I receive a "failed with signal HUP(1) error" between correcting and trimming the reads (illegal division by 0 since the corrected reads are not written to the corrected reads file). I thought this might be because of low coverage but it also happens after applying the low coverage options. 

CANU command:
![image](https://cloud.githubusercontent.com/assets/16675995/12281107/4db22fce-b961-11e5-903c-fe2c4ed03dbd.png)

Output error:
![image](https://cloud.githubusercontent.com/assets/16675995/12281200/101efec0-b962-11e5-8f55-b1f79c62fd4f.png)

**Comment by brianwalenz** [comment]
This does look like it failed to generate any corrected reads, and not a coding error.

Can you provide a link to the data (and directions on how to construct a similar set of fastq, if needed)?

The full output of canu (text file!) would help too.

Also, what version of canu - if not the latest, please use that with option saveReadCorrections=true.  This will save the intermediate files and any problems.

**Comment by russellj7** [comment]
FASTQ read files were taken from the ENU at the EMBL-EBI website. This data comes from a de novo E. coli sequencing project published in Nature and I am trying to use their dataset to test out the code. I am running the program on a local machine. 

The data is located here by these links as separate FASTQ files that I merged into one master read file:
http://www.ebi.ac.uk/ena/data/view/ERX708228
http://www.ebi.ac.uk/ena/data/view/ERX708229
http://www.ebi.ac.uk/ena/data/view/ERX708230
http://www.ebi.ac.uk/ena/data/view/ERX708231

Full output:
[Canu_output_local.txt](https://github.com/marbl/canu/files/90772/Canu_output_local.txt)

Running the command on a cluster environment has given me other issues. Apparently there is an issue with resource allocation and conflicts between qsub scripts (the one I produce to submit the job to the cluster and internal scripts in the program). 

Below is the full output for when run on the cluster:
[Canu_output_cluster.txt](https://github.com/marbl/canu/files/90771/Canu_output_cluster.txt)

My qsub script to submit the job to the cluster:
[Canu_qsub.txt](https://github.com/marbl/canu/files/90778/Canu_qsub.txt)



I believe I am using the latest version unpacked from the zip file located here.

**Comment by brianwalenz** [comment]
This is, I think, the same data we're using in our quick start:

http://canu.readthedocs.org/en/latest/quick-start.html#assembling-oxford-nanopore-data

In your run, no overlaps were found (line 187 in Canu_output_local.txt has a table describing the overlaps found).  I wonder if this is because our example is using only the 2D reads, or because it is using a subset of the reads?

I have reproduced the problem here.

**Comment by aphillippy** [comment]
This is an issue for @skoren when he returns. I'm fairly certain this dataset is in his automated test set.

**Comment by brianwalenz** [comment]
At the default k=16, nearly all of the kmers are single copy.  At k=14, the number of single copy kmers is significantly lower.  I don't know what to expect.

**Comment by skoren** [comment]
I suspect the EBI fastq files are broken, I don't see overlap in the read lengths between the poretools extracted reads from the raw fast5 files and the EBI fastq files, the longest reads in the EBI download:

```
ERR764955.4076 34034
ERR764954.2197 34561
ERR764954.928 37020
ERR764954.762 37113
ERR764955.4076 37115
ERR764953.2862 38395
ERR764954.273 39202
ERR764955.2242 40488
ERR764954.273 40873
ERR764955.2242 43624
```

versus longest 2D reads

```
channel_510_read_204_twodirections:flowcell_32/downloads/pass/LomanLabz_K12_His_tag_1738_1_ch510_file209_strand.fast5 34983
channel_433_read_133_twodirections:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1736_1_ch433_file134_strand.fast5 35776
channel_398_read_102_twodirections:flowcell_32/downloads/pass/LomanLabz_K12_His_tag_1738_1_ch398_file102_strand.fast5 35923
channel_411_read_90_twodirections:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1736_1_ch411_file90_strand.fast5 36018
channel_120_read_114_twodirections:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1736_1_ch120_file118_strand.fast5 37202
channel_402_read_7_twodirections:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_5925_1_ch402_file8_strand.fast5 37402
channel_170_read_52_twodirections:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_5925_1_ch170_file54_strand.fast5 38750
channel_271_read_77_twodirections:flowcell_32/downloads/pass/LomanLabz_K12_His_tag_1738_1_ch271_file78_strand.fast5 42474
channel_251_read_12_twodirections:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1036_1_ch251_file13_strand.fast5 43274
channel_433_read_79_twodirections:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_2004_1_ch433_file81_strand.fast5 47133
```

and only 1d reads

```
channel_170_read_52_template:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_5925_1_ch170_file54_strand.fast5	34034
channel_411_read_90_complement:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1736_1_ch411_file90_strand.fast5	34561
channel_120_read_114_complement:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1736_1_ch120_file118_strand.fast5	37020
channel_475_read_100_template:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1036_1_ch475_file100_strand.fast5	37113
channel_170_read_52_complement:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_5925_1_ch170_file54_strand.fast5	37115
channel_271_read_77_complement:flowcell_32/downloads/pass/LomanLabz_K12_His_tag_1738_1_ch271_file78_strand.fast5	38395
channel_251_read_12_template:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1036_1_ch251_file13_strand.fast5	39202
channel_433_read_79_template:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_2004_1_ch433_file81_strand.fast5	40488
channel_251_read_12_complement:flowcell_33/downloads/pass/LomanLabz_PC_K12_0.4SPRI_1036_1_ch251_file13_strand.fast5	40873
channel_433_read_79_complement:flowcell_39_K12_Histag/downloads/pass/LomanLabz_PC_K12_0.4SPRI_Histag_2004_1_ch433_file81_strand.fast5	43624
```

so I suspect the EBI fastq is only the 1D reads, which are higher error and would not assemble with the default parameters. We have assembled 1D data and a combination of 1D+2D data but that requires alternate parameters and sometimes multiple rounds of correction. I would suggest downloading the raw fast5 files from EBI and extracting the 2D reads (or you can download them http://www.cbcb.umd.edu/software/PBcR/data/sampleDataOxford.tar.gz). All the work in the paper you mentioned only used 2D reads.

As for the qsub error, how do you normally submit jobs? It looks like the Canu job was rejected because it didn't specify a queue or other required parameter which is likely specific to your system:

```

```

You can tell Canu to always pass a parameter to the grid submission by setting gridOptions=XXX.

**Comment by JohnUrban** [comment]
Is it in the plans to be able to specify --nanopore-raw-1d vs --nanopore-raw-2d, so that canu will treat them separately/accordingly?

**Comment by skoren** [comment]
It is generally OK to mix 1D+2D with the --nanopore-raw parameter since most of the corrected reads would come from 2D reads but some 1D reads may get corrected as well and help the assembly. I think the 1D reads have improved since this run but we didn't have access to it for testing. Hopefully we can support either 1D or 2D data with the same parameter.

**Comment by russellj7** [comment]
Skoren, I tried running the dataset you provided in your response and had success with it. You must be right about the reads available at EBI. Hopefully I will have the same success with data I generate myself.

On the qsub issue, I don't think I will be able to run Canu on the cluster because my HPC provider does not allow batch jobs:
<img width="1002" alt="screen shot 2016-01-15 at 7 12 51 pm" src="https://cloud.githubusercontent.com/assets/16675995/12381608/7914cba6-bd5b-11e5-90e1-cc221281a042.png">

**Comment by brianwalenz** [comment]
The qsub 'directives' are those lines with "#PBS" in them.  The highlighted text just says that you can have only one 'block' of these.  We don't make use of these blocks.

**Comment by Blueblo** [comment]
Using pacbio data "ecoli_p6_25x.filtered.fastq" that download from the page http://canu.readthedocs.org/en/latest/quick-start.html recevice the same error ,"ERROR: Failed with signal HUP (1)" as russellj7 mentioned.
Is it also because the fastq file?

thanks

**Comment by skoren** [comment]
No, that file should be fine. Could you open a new issue with the log of your run.
