### ISSUE TITLE
sequence outputs

### ISSUE THREAD

**Issue by brianwalenz** [marbl/canu#28]
(From issue #19)

Break the consensus outputs into three categories:

1. Unassembled crud (singletons and low-coverage near-singletons)
2. Secondary unitigs (unpopped bubbles)
3. Unitigs

Filtering is done (consensusFilter() in Consensus.pm), and should be updated in tigStore, but the tgStoreDump (outputSequence() in Output.pm) doesn't know how to obey the markings.

**Comment by aphillippy** [comment]
Outstanding questions to consider:
A. File name suggestions: 1) unassembled (uns), 2) bubbles (bub), 3) contigs (ctg)?
B. These files are disjoint. Combining them recovers all unitigs. Should this combined file also be ouput as unitigs (utg)? or suppressed since it is redundant?
C. Always output bubbles file, or only when user specifies input is a diploid/polyploid/meta?

**Comment by pb-jchin** [comment]
Hi, Adam and Brian: 

I am curious about whether it is possible have some common naming scheme even between different assemblers related to these bubbles.  It may or may not possible as it really depends on the underlying algorithms which can be different.  However, if there is some opportunity to get a more consistent naming scheme across assemblers, it will help the community.  (I am open to change the naming scheme in the FALCON code too.)

**Comment by brianwalenz** [comment]
A.  I added a 'repeat' category.  We know which reads/unitigs came from detected repeats.  These shouldn't be put in 'unassembled'.
B.  There was some confusion when CA output non-disjoint sets and full sets.  CA's output was utg == ctg+deg.  I vote for disjoint with no combined file.
C.  Always.  They should all be somewhat redundant with the primary output, and we can even point to exactly where it should go.  If it goes in multiple places, it should have been demoted to repeat (or caused the repeat it is pointing at to be split out).

Jason, are you thinking of names of names in (A) or names of types of bubbles?

**Comment by aphillippy** [comment]
I believe he's referring to standardized names for the bubbles (aka alternate alleles, secondary contigs, etc.) I fully agree common language would be very useful. Any suggestions, Jason? You've talked to a lot of people about this. "Bubbles" are the long-time CA lingo, but other words may be more meaningful/descriptive to users.

**Comment by pb-jchin** [comment]
For A, some reads that has highly repetitive regions at the both ends that can be detected by overlap statistic. I will output these reads.  Conceptually, these are more like to be "unassembled reads" or "repetitive reads".  

The other thing I was thinking about is the extra sequence from resolving bubbles. I call some extra contig from different branch of a bubble which is not the primary output "associated contigs" (it can also stands for "alternative contigs".) Sometimes I just call then a-tigs or a-contigs.  Any better suggestions welcome.

**Comment by pb-jchin** [comment]
@aphillippy I think "bubbles" is good. We are writing it up. Some bubbles have more than two main branches.  There could be some cross-over edges between two main branches. In some set-dup regions where the multiplicity is higher than 2, the bubbles can be complicated.  Since I do bubble finding first, I define a "compound edge" as the collection of the edges inside a bubble.  The name "compound edge" is more algorithm specific. I think "bubble" is already good for general term.

**Comment by brianwalenz** [comment]
Since the purpose of this issue was to get sequence outputs in canu, and since that has been accomplished (a long time ago, but in this galaxy)....

I'll leave the larger problem of standardizing terminology for twitter.
