### ISSUE TITLE
Running Canu Separately (-correct, -trim and -assembly)

### ISSUE THREAD

**Issue by MehmetGoktay** [marbl/canu#303]
I run canu separately for each stage (correction, trimming and assembly). My question is: Do I need to set errorRate for each stage? or Do I just need to set errorRate for -assembly step?

Because in the this example errorRate was set just for the assembly part. 

canu -correct \
  -p ecoli -d ecoli \
  genomeSize=4.8m \
  -pacbio-raw  p6.25x.fastq

Then, trim the output of the correction:

canu -trim \
  -p ecoli -d ecoli \
  genomeSize=4.8m \
  -pacbio-corrected ecoli/correction/ecoli.correctedReads.fasta.gz

And finally, assemble the output of trimming, twice:

canu -assemble \
  -p ecoli -d ecoli-erate-0.013 \
  genomeSize=4.8m \
  errorRate=0.013 \
  -pacbio-corrected ecoli/trimming/ecoli.trimmedReads.fasta.gz

**Comment by skoren** [comment]
It should be OK to specify the error rate just for assembly. You may also want to specify it for the trimming step so sequences are trimmed at the same error rate as they are assembled. Generally, it is easiest to run Canu as one command in which case you can specify the errorRate once for the full run.

**Comment by jaworskicoline** [comment]
Hello, so now I am lost about how exactly to run the three different steps manually: here are my questions:
1/ As written in the Quickstart guide, I understood that the -assemble step had to be run twice, once with correctedErrorRate=0.039 and once with correctedErrorRate=0.075. Is that true ? Or should it be run twice but with the same correctedErrorRate and if so, why do we need that, and what should be the command, the outputs and how to interpret it and what does it really do?
2/ In that case, does the second step uses outputs from the first steps to create a consensus assembly ? What do those two steps do ? Why are they necessary ?
3/ I have run the first step, and have a bunch of files as outputs, including *.contigs.fasta and many others, but How can I know that it successfully completed this step ? I mean, treated all the trimmed reads for instance? Which file to look at for error and progress report?
4/ Is this step supposed to be the most resource consuming ? What resources would it need for these two -assemble steps, for a drosophila sized genome ? Or, does it parameterize its own resources anyway ? My first step apparently ran in ~03:30:00 walltime on 16cpus with 60gb (16cpus and 60gb are the parameters I had passed, not sure what it used exactly). Is that surprising, or is it possible that it finished ? how to assess the quality of the first -assemble step ?
5/ What should be the output of the second -assemble step ? If it creates a new directory with another set of output files, are those files a consensus assembly with the first -assemble step ? Id kind of independent, which files should we consider as the best assembly ?
Thanks for answering my lots of questions !

**Comment by skoren** [comment]
Please open a new issue in future.

1. Canu has three steps, correct assemble and trim as documented here:
http://canu.readthedocs.io/en/latest/pipeline.html

which each run once. The quick start gives an example of running the assemble step twice with different parameters to generate two independent assemblies which you can compare and select one to use for your downstream analysis. You don't have to run it twice unless you want multiple assemblies. In general you should run Canu as a pipeline and let it run all steps by itself on your first assembly unless you are tuning/testing some parameter changes.

2. The two steps are unrelated, both use the output of the trimming step.

3. As long as you have an asm.contigs.fasta then it has completed. Canu logs progress to stdout/stderr if running on a single machine and will say something like:
```
-- Finished stage 'generateOutputs', reset canuIteration.
--
-- Assembly 'asm' finished in asm'.
--
-- Summary saved in 'unitigging.html'.
--
-- Sequences saved:
--   Contigs       -> 'asm.contigs.fasta'
--   Unassembled   -> 'asm.unassembled.fasta'
--   Unitigs       -> 'asm.unitigs.fasta'
--
-- Read layouts saved:
--   Contigs       -> 'asm.contigs.layout'.
--   Unitigs       -> 'asm.unitigs.layout'.
--
-- Graphs saved:
--   Contigs       -> 'asm.contigs.gfa'.
--   Unitigs       -> 'asm.unitigs.gfa'.
--
-- Bye.
-- Finished stage 'outputSequence', reset canuIteration.
```

or save in ```canu-scripts``` if running on the grid.

4. The fastest step is typically correction and trimming/unitigging are slower and about equal to each other. Each step will parameterize itself to your system/grid. If it generated the outputs it finished.

5. Same output of second as first since they're completely independent. The prefix is set with the -p option to Canu.

**Comment by jaworskicoline** [comment]
Thanks for your fast and detailed answer, that makes it much clearer !
So from what I can read in my output files, I conclude that the assembly was successful.

I chose to test running the three steps separately because at least it does output something, while we cannot have the canu pipeline work, as discussed there (http://canu.readthedocs.io/en/latest/quick-start.html#quickstart). I am using the same HPC. What are the differences and possible issues when running the three steps manually as compared to the whole pipeline at once ?

**Comment by skoren** [comment]
Running the three steps with default parameters should be identical to running the full pipeline as long as you feed the output of each step into the next.

I'm not sure what you mean by "you cannot have the canu pipeline work", if you have an error running on your HPC, open a new issue with the detailed output from the run.

**Comment by jaworskicoline** [comment]
Thanks !
Best regards,
Coline
