### ISSUE TITLE
Lots of mis-assemblies in Drosophila genome

### ISSUE THREAD

**Issue by biorover** [marbl/canu#304]
Hello, I was testing canu on about 20x and 90x of the Drosophila data from PacBio using default parameters and got some serious mis-assemblies (~50% and >90%, respectively). Attached are alignments of each ("dmelTwenty" and "dmelAll") to chromosome 3 of the reference sequence produced by quast. I also got a middling assembly compared to that achieved in the canu paper (N50 of 5Mb). Any ideas on what settings could improve this? My own data for a Drosophila-like genome (~100x coverage of a ~215Mb genome, diploid but with low heterozygousity, 2n=28) will get in this week and I'd like to be ready.

Thanks!

![capture](https://cloud.githubusercontent.com/assets/7397693/20738901/95a33db6-b684-11e6-9f40-0afdb2d5cbcc.PNG)

**Comment by skoren** [comment]
Hi,

I tested subsets of drosophila with the latest Canu from the repo and did not see significant errors. Below are the mummerplot alignments of the 20x:
![20](https://cloud.githubusercontent.com/assets/923478/20802557/63f0b668-b7ba-11e6-8d75-f6b8173ff379.png)
and 90x assemblies to the reference:
![90](https://cloud.githubusercontent.com/assets/923478/20802576/723897ae-b7ba-11e6-9059-35107357cb6f.png)
generated with
```
nucmer -l 100 -c 1000 ref.fna asm.contigs.fasta
dnadiff -d out.delta
mummerplot --large --fat out.1delta
```

You can see they agree with the reference well. I ran canu as:
```canu -p asm -d dmel_20 genomeSize=160m -pacbio-raw dmel_filtered.20.u.fastq.gz errorRate=0.035```
on 20X and
```canu -p asm -d dmel_50 genomeSize=160m -pacbio-raw dmel_filtered.50.u.fastq.gz```
 on 50 and 90X.

I'm not sure what the percent numbers indicate, are those % of contigs with an error? It depends on what Quast measures as errors, there are many short breaks in the assembly compared to the reference due to several factors, including that the assembly is not polished by Quiver and has indels, the reference has differences in copy number in some places from the assembly, and there may be gaps in the reference filled by the assembly.

As for the N50, the Canu paper measures NG50 statistics based on the reference v6 size of 143Mb. Using that as the genome size, the stats for my subsets were:
```
Processing file dmel_20/asm.contigs.fasta
GenomeSize: 143726002
Total units: 564
BasesInFasta: 140440270
Min: 5,183
Max: 12,388,248
NG25: 8,085,940 COUNT: 4
NG50: 4,808,093 COUNT: 9
NG75: 300,906 COUNT: 45

Processing file dmel_50/asm.contigs.fasta
GenomeSize: 143726002
Total units: 334
BasesInFasta: 151717198
Min: 7,221
Max: 27,927,179
NG25: 18,153,322 COUNT: 2
NG50: 14,216,805 COUNT: 4
NG75: 1,448,846 COUNT: 12

Processing file dmel_90/asm.contigs.fasta
GenomeSize: 143726002
Total units: 319
BasesInFasta: 155272170
Min: 13,602
Max: 24,411,604
NG25: 21,700,684 COUNT: 2
NG50: 6,435,144 COUNT: 5
NG75: 2,166,039 COUNT: 12
```
There is some variation but the max is usually over 25mb and NG50 is above 10 though it varies based on what long reads are picked in the random subset. You could try adding ```corMhapSensitivity=normal``` for the 90x set to see if the asm improves.

**Comment by biorover** [comment]
Thanks! As far as the mis-assemblies, I've gone back through and figured out that it's mostly incorrectly resolved repeats and numbers-wise it's similar to what you reported in the canu paper (~1,000 various errors total). It looked so bad just because Quast puts all nucleotides in any contig with an error into the "mis-assembled" category. Re contig size, it's quite possible I just got an unlucky subset of reads. Just out of curiosity, though, how did you extract and filter the reads for your assemblies? I noticed the "filtered" extension on your read files in your command. All I did for filtering was remove reads <1kbp.

**Comment by skoren** [comment]
The file includes filtered in the name just because the reads were extracted/filtered from the h5 files using `` filter_plsh5.py --debug --filter='MinReadScore=0.7500,MinRL=50'```. I generated subsets of the reads using the fastqSample available in Canu.

**Comment by skoren** [comment]
Closing, file a new issue if you encounter other problems with the assemblies
