### ISSUE TITLE
Canu v1.4 (Linux binary) -- unitig store retrieval failure (works on v1.3)

### ISSUE THREAD

**Issue by gringer** [marbl/canu#312]
I'm trying to assemble long reads from a long-read dataset. I subset these reads to identify ones that had a high likelihood of matching the TCR-alpha and TCR-beta regions, then attempted an assembly on the result. This assembly produced output (unassembled contigs) for v1.3, but not for v1.4.

**Comment by brianwalenz** [comment]
I guess we need to add a set of reads that don't assemble to our test cases!

The problem is that there are no contigs assembled - everything ends up as 'unassembled' left over crud - and so no unitigs are generated.  The pipeline fails when it tries to call consensus on the nonexistent unitigs.  Oops.

A workaround is to replace the unitigs with the contigs.  This will at least get the pipeline to finish.  Just remember that the outputs that refer to unitigs aren't correct.

Something like the following should work:
```
rm -r unitigging/*utgStore/*
cp -r unitigging/*ctgStore/* unitigging/*utgStore/
```
then just restart canu.

Should these reads be assembling?

**Comment by gringer** [comment]
Sorry, I made an error in releasing those reads; I don't have permission to publish those reads, as they are a redistribution of Clive Brown's genome.

**Comment by gringer** [comment]
Those reads probably shouldn't be assembling, as I think they mostly contain transposon sequences with no consistent common sequence apart from the transposon. I can give you similar reads from a parasite genome I'm working on, if that would be helpful.

**Comment by brianwalenz** [comment]
We had those reads too, so you just gave us IDs.  :-)  The crash is fixed.

Some comments:

Corrected reads are being generated, so there is similarity in here.  After correction, there are overlaps between reads, but at 4% error.

Looking at the overlap graph, it seems like everything is contained, but nothing is able to seed a contig, so everything ends up unassembled.  Spot checking, I see about 200 overlaps per read.
