### ISSUE TITLE
The algorithm detail of consensus?

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#316]
Hi!

I had run canu several times, and I tried to understand how consensus work, would you give me more detail? 1) According to the tutorial, the corConsensus could be "falcon" or "falconpip", what the different between them, and how is the consensus process (any paper suggested)? 2) Is these two methods same as "PBDAGCon" and "FalconSense" mentioned in PBcR?
Any suggestion would be grateful!

Best wishes!

**Comment by skoren** [comment]
Essentially, the core of the algorithms are the same as those in PBcR though they have been modified in Canu to be faster and remove some limitations on sequence lengths. The details of how Canu generates consensus for both corrected reads and the final assembly are in the preprint:
http://biorxiv.org/content/early/2016/08/24/071282

The original PBDAGcon algorithm (which is used for contig consensus) was described in the HGAP manuscript:
http://www.nature.com/nmeth/journal/v10/n6/full/nmeth.2474.html
In Canu, the primary modification is the use of an O(ND) alignment algorithm to align to a template.

The falcon_sense algorithm (used to generate corrected reads) was originally described in the MHAP paper:
http://www.nature.com/nbt/journal/v33/n6/abs/nbt.3238.html
It used a simple majority vote with the O(ND) algorithm to align to the template (which in this case is the read to correct). It was since modified to use a DAG-based algorithm, similar to PBDAGcon and those updates were described in the Falcon-unzip paper:
http://www.nature.com/nmeth/journal/v13/n12/full/nmeth.4035.html

The Canu version is updated from that described to remove a limit on read length maximum and switched to be fully in C/C++ rather than a mix of python/C.

**Comment by lamz138138** [comment]
Hi, skoren, thanks for your reply!

In fact, I had go through the above paper except the preprint of Canu, and I am in reading it now. In my opinion, PBDAGCon align all reads-to-reads. Considering this would result in a long running time, so FALCON revised the code by aligning reads to seed reads, then revised seed reads with DAG-based algorithm.  In PBcR, "PBDAGCon" would align all reads-to-reads, while “FalconSense” is same with FALCON by using some seed reads. Am I right? If I am right, "falcon" and "falconpip" would correspond to "PBDAGCon" and "FalconSense", but which one is relate to "FalconSense"?

**Comment by lamz138138** [comment]
OK, after a quick review of Canu paper, I think you didn't support select some reads as seed reads. This paper is very good, I need read carefully!

**Comment by lamz138138** [comment]
Hi, @skoren !

Am I right above?

**Comment by skoren** [comment]
Canu does try to correct the longest reads but it is not based on a seed read cutoff. It always computes all-pairs overlaps and uses the overlaps to estimate corrected read lengths. Then, the longest 40X (by default, controlled by the corOutCoverage parameter which can be set arbitrarily high) are selected based on their corrected read lengths. This is different than picking an initial seed length before overlapping because you are assuming a 30Kb raw read will be 30Kb after correction which isn't always the case. This is described in the Canu preprint as well.

**Comment by lamz138138** [comment]
Hi, thanks for reply!

As I don't familiar with the algorithm, so I want to know whether I am right about the different of PBDAGCon and FalconSense that one use all-to-all alignment, while the other use the alignment of seed reads. According to the reply, I confirm I didn't mistake these.

Thanks again.
Best wishes!

**Comment by skoren** [comment]
I though you were asking about seed reads in the sense of Canu not the algorithms.

Neither falcon_sense nor PBDAGcon uses all-vs-all alignments. Both align to a template (a raw read in the case of falcon_sense and a stitched together consensus in the case of PBDAGcon) to build a DAG and call consensus from a DAG. Originally, the difference between falcon_sense and PBDAGcon was that falcon_sense used a plurality vote but it is now using a DAG as well. PBDAGcon also used a different alignment algorithm than falcon_sense but in Canu they share the same O(ND) alignment algorithm.

**Comment by lamz138138** [comment]
Hi, I feel confuse now.

First, I want to know how Canu, Falcon and PBcR select template? According to above, Canu use the longest 40X data. In my opinion,  with Falcon we can defined a length, reads longer than the defined length would be template (seed reads). In PBcR, if one use PBDAGcon, then all reads would be template (so I say all-to-all above), while use falcon_sense one need to defined a length as Falcon, am I right?

Second, according to the supplemental of http://www.nature.com/nmeth/journal/v10/n6/full/nmeth.2474.html, I think Falcon use DAG to get consensus, so what do you mean about it using plurality vote, is this the previously version? And what is plurality vote, is it the same algorithm as http://bioinformatics.oxfordjournals.org/content/30/21/3004.long? I don't read O(ND) yet, it would be grateful if you can explain to me, but it may take too much time, maybe I read it later would be better.

**Comment by skoren** [comment]
```
First, I want to know how Canu, Falcon and PBcR select template? According to above, Canu use the longest 40X data. In my opinion, with Falcon we can defined a length, reads longer than the defined length would be template (seed reads). In PBcR, if one use PBDAGcon, then all reads would be template (so I say all-to-all above), while use falcon_sense one need to defined a length as Falcon, am I right?
```

Falcon requires a pre-defined seed length. It will then only compute overlaps between reads longer than this seed length and every other read. It will also only call consensus for the reads longer than the seed length. For each read > seed length it will compute a pairwise alignment of a read to it based on the overlaps computed before and generate a consensus. Originally falcon_sense as described in the MHAP paper, it used plurality, the supplement describes the algorithm. Later it was upgraded to use a DAG, as I said above.

PBcR works similarly to Falcon, except rather than defining a fixed seed length, it computes the seed length based on your genome size and desired coverage in corrected reads (40X by default). This gives you how many bases you have to correct so you take the longest reads such that you have >= desired bases in reads longer than this. This becomes your seed length. The overlaps are computed between the reads longer than this and all reads and consensus is computed similarly. In either case with falcon_sense or PBDAGcon, all-pair overlaps are not computed in PBcR. PBcR only used the plurality version of falcon_sense.

Canu has more efficient overlapping so it can compute all-pair overlaps faster than either Falcon or PBcR. It therefore doesn't need to define a seed read length. It computes all pairs overlaps and uses these to estimate the corrected length of a read (so a 30kb raw read with no overlaps will have a corrected length of 0). It then selects enough reads to get the desired bases based on their estimated corrected size. Again, the default is 40X as in PBcR and is controlled by the ```corOutCoverage``` parameter. Canu only uses the DAG version of falcon_sense for generating corrected reads, it does not use PBDAGcon to generate corrected reads. PBDAGcon is only used for a final unitig consensus in Canu. This is because the DAG version of falcon_sense performs better than the plurality version and so there isn't a need to support multiple algorithms here as PBcR did.

In all cases overlapping is not the same as correction of the reads. Falcon uses DALIGNER for overlapping, Canu and PBcR use MHAP. Those do not make corrected reads, just identify which reads could be used to correct other reads.

The plurality algorithm is described in the supplement of the MHAP paper. The paper you link to (http://www.nature.com/nmeth/journal/v10/n6/full/nmeth.2474.html) described PBDAGcon and HGAP, it has nothing to do with Falcon or falcon_sense. The O(ND) algorithm is from the 80s (http://link.springer.com/article/10.1007/BF01840446).

**Comment by lamz138138** [comment]
Hi, thank you for so detail information, I understand very well now, and I think following would be my last question.

I can't understand "PBDAGcon also used a different alignment algorithm than falcon_sense but in Canu they share the same O(ND) alignment algorithm" you mentioned above. Suppose we one reads that would be corrected, Falcon use DALIGNER to find reads that could be used to correct it, while PBcR and Canu use MHAP. Then falcon_sense use plurality or DAG algorithm to correct the reads, and PDBDAGcon use DAG algorithm to correct reads. So what's the function of O(ND)? Did it means  after finding overlap of two reads with DALIGNEN or MHAP, then when performing correction, we re-find how the two reads align, and falcon_sense use a algorithm to re-align while PBDAGcon use another, but in CANU, they all use O(ND) to re-align two reads? Or when you say this sentence, you means falcon_sense is Falcon that use DALIGNER, while PBDAGcon is PBcR that use MHAP?

**Comment by skoren** [comment]
"Did it means after finding overlap of two reads with DALIGNEN or MHAP, then when performing correction, we re-align the two reads, and falcon_sense use one algorithm to re-align while PBDAGcon use another, but in CANU, they all use O(ND) to re-align two reads?"
This is correct. The reads are re-aligned in both falcon_sense and PBDAGcon and added to the DAG.

MHAP does not compute alignments which is part of why it is fast, it can still accurately identify the positions and identity of the alignments. DALIGNER does but Falcon does not save/use those alignments.

**Comment by lamz138138** [comment]
I understand the correction process now, it salve me a lot of time in struggling with the algorithm, thanks you very much!

**Comment by lamz138138** [comment]
Hi, skoren!

I am in reading the paper of MHAP and CANU, and finding you had write so many assembly tools, it's so fantastic. I had tired to understand the theory and detail algorithm of genome assembly, could you suggest any paper, video or seminar major in this?  I had read some material, but sometimes feel the more I read, the more I feel confused. 

Any suggestion would be grateful!
Best wishes!

**Comment by skoren** [comment]
Thats a broad question, there's lots of papers in genome assembly. As a start here are a few of the early papers like:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC327874/
http://online.liebertpub.com/doi/abs/10.1089/gst.1995.1.9
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC55524/
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.52.6330&rep=rep1&type=pdf
http://bioinformatics.oxfordjournals.org/content/21/suppl_2/ii79.abstract
http://science.sciencemag.org/content/287/5461/2196

A few years ago we had a review as well as a more recent review about long-read assembly:
http://www.sciencedirect.com/science/article/pii/S0888754310000492
http://www.sciencedirect.com/science/article/pii/S1369527414001817

That is by far not the complete list but a start and then you can read papers these cite.

**Comment by lamz138138** [comment]
Hi, thanks very much!

**Comment by lamz138138** [comment]
Hi, @skoren !

I have to look for your help again as I still feel knowing a little after doing some investigation. Sorry for interruption!

My question is how can we get assembly in chromosome level? After running with CANU, we can get contigs. Then, I think we can use mate-pair reads, HiC data or BioNano data to link these contigs to scaffold level, and construct APG file, load it to NCBI. Althogh finished above work is grate work, I think assembly in chromosome level would be more useful, since we won't use scaffold assembly when there are chromosome version exists. To reach chromosome, I only know we have to use genetics map, or mapping the scaffold to previously reference like this paper http://www.nature.com/nbt/journal/v29/n11/full/nbt.1992.html. Can you give me some suggestion after running with HiC data.

Any suggestion would be grateful!

Best wishes!

**Comment by skoren** [comment]
HiC (native HiC from live cells) is really the only way to get de novo chromosome assembly but it has higher error rates than other scaffolding technologies. See the goat paper for an example of using BioNano + HiC (http://biorxiv.org/content/early/2016/07/18/064352). There are multiple companies which provide HiC sequencing including Phase (http://phasegenomics.com) and Dovetail (https://dovetailgenomics.com/services/hic/).

**Comment by lamz138138** [comment]
Hi， thanks for your reply, I had miss this previously.
