### ISSUE TITLE
Reads of insert vs subreads usage with canu

### ISSUE THREAD

**Issue by MehmetGoktay** [marbl/canu#320]
Hi Everyone,

I have a general question which is a big questionmark in my mind. It is not directly related with Canu so I hope it is not a big problem.

I want to reproduce same results as they did in this publication. (http://www.nature.com/nmeth/journal/v13/n12/full/nmeth.4035.html)

But they did not published subreads instead (as far as  understand) they published reads of insert which is consensus of subreads from each polymeraese reads. (Data was published on ncbi : https://www.ncbi.nlm.nih.gov/sra?term=SRS1404679)

Is there anyone who could give me an advice how to reproduce same results with reads of insert not directly with subreads. Because I have tried running directly but results were funny.

**Comment by skoren** [comment]
The reads they published are subreads (split at the circularization sequence) but they are not consensus reads. Generally, the SRA formatted reads are different from what you get when you run the PacBio utilities so I recommend downloading the raw h5 files and converting them to fastq. 

For running Canu, since this is essentially two genomes, you should increase the corOutCoverage form the default (so you don't end up with low coverage of both genomes), in the paper they did this by adjusting the seed read length for Falcon. You can set it arbitrarily high. I was also able to get a good assembly of both haplotypes by adjusting some of the Canu parameter for heterozygous genomes (issue #210 and #201). Essentially you want to decrease the -dg and -db parameters as well as the -ca/-cp parameters.

**Comment by MehmetGoktay** [comment]
Thank you very much for your detailed answer!

Yes I m interested in cvi-0. (But thank you for your advices. I will definitely keep in mind if we go for other heterozygous genomes)

I have performed several assemblies with my data (cvi-0 again) using falcon and canu. So far canu gave more continous and high n50 value than falcon runs. It might be because of parameters that I used to run either falcon or canu. But I will figure out it.

That is why I wanted to reproduce their cvi-0 assembly using canu and falcon with their data. (May be canu works better with better chemistry like I have right now, comparatively falcon)
