### ISSUE TITLE
question about *.layout format

### ISSUE THREAD

**Issue by indapa** [marbl/canu#324]
I'm new to de-novo assembly and appreciate the detailed docs on Canu.

I have a simple question about the *.layout file regarding how to figure out which read ended up in the final assembly. Below is some information about where the reads ended up in the assembled unitig. The first two columns refer to the read number. What does anchor and hang mean? I'm guessing the last two columns indicate the start and end of where the read was placed in the unitig. 

`read          81 anchor         0 hang       0       0 position         0      6089`
`read          37 anchor        81 hang       0       0 position       260     33566`
`read         102 anchor        37 hang       0       0 position      4729     41731`
`read          88 anchor         0 hang       0       0 position     35787     18823`

Thank you for your help!

**Comment by skoren** [comment]
The anchor and hang can be safely ignored. It gives information on which read overlap (if one is available) recruited the read into the contig and how much they overlap. Hang is no longer used so it's always 0. They were originally used to help generate a consensus sequence but aren't used by the assembler anymore.

The last two columns are the positions of the read, if start is > begin then the read is reverse complemented. Currently these positions aren't precise because we don't recompute them after calling consensus so they may be off by a few bases. This will get fixed in a future commit.

The read id is the internal number (starting from 1 to # of reads). You can use the asm.gkpStore/readNames.txt file to translate them back to raw IDs:
```
1	c84f390a-ba28-4952-91c1-0673dba68f3e_Basecall_Alignment_template llssbzms2p35x_20161128_FNFAB45271_MN17073_sequencing_run_Hu_Bir_R94_1Dlig_fc5_92573_ch103_read1243_strand id=4_0 id=4 clr=4306,8695
```
For example, the example above shows that read 1 was named ```c84f390a-ba28-4952-91c1-0673dba68f3e_Basecall_Alignment_template llssbzms2p35x_20161128_FNFAB45271_MN17073_sequencing_run_Hu_Bir_R94_1Dlig_fc5_92573_ch103_read1243_strand``` in the input and it was eventually trimmed to bases 4,306-8695. There may be duplicate raw IDs in case the correction split a raw read into more than a single piece.

**Comment by brianwalenz** [comment]
And if the correction split a raw read into multiple pieces, the coordinates in readNames.txt are relative to the split read, not the original read.

Reopen if needed.
