### ISSUE TITLE
unassembled vs unused reads

### ISSUE THREAD

**Issue by indapa** [marbl/canu#332]
Dear Canu Team

I'm a newbie to assembly and have another simple question. My input fastq file when I ran my canu command with PacBio reads had ~47,000 reads in it:

`canu -p asm -d asm-auto-20170110 genomeSize=195000 -pacbio-raw reads.20170110.fastq`

However, the *.correctedReads.fasta.gz and *.trimmedReads.fasta.gz had ~200 reads. I was then expecting the file *.unassembled.fasta file to list the remaining reads not used, but this file has ~100 records. 

It seems that in my analysis, Canu is unable use the vast majority of the original fastq reads given as input. Is the software unable to find any overlaps with these reads? If not, are they logged somewhere I am not looking? The gkpStore/readNames.txt lists all my original read names. I can't figure out based on the docs why most of them are not being used.

**Comment by skoren** [comment]
Canu will only try to use the longest 40x of data for correction/assembly. Since your genome is only 200Kbp, I presume most of the reads are thrown out as "too short". Canu should print the input read length histogram and coverage for the raw and corrected data, you can check that to confirm you do have over 20x coverage in corrected reads.

The IDs in correctedReads and trimmedReads are tracked back to the raw input so you can tell which reads were used and if they are not in the correctedReads file it is because they were too short to be corrected. If you do want to correct all your data you can set ```corOutCoverage=1000``` or some arbitrarily large number higher than your input coverage.

**Comment by indapa** [comment]
Ah ok, got it. I restricted input  read lengths to be at least 1000bp. But if it's only using the longest 40x for correction/trim/assembly, that explains why most of them are not used. I will try and adjust the corOutCoverage value.  

Thanks for your help!
