### ISSUE TITLE
[Question] Corrected file from Canu

### ISSUE THREAD

**Issue by RxLoutre** [marbl/canu#341]
Hi everyone !

I already have used Canu in order to produce a draft of the _D.suzukii_ genome with my PacBio long reads, with a large coverage (> 75x) . I'm quiet satisfied with it, but I still need to polish it. In order to do so, I want to use Pilon, as the pacbio tools (quiver and arrow) do not work for me (it's a long story).

Pilon is not aware of the high error rate of PacBio reads, but it's not excluded to use long reads either.
I was wondering if using corrected PacBio reads will not solve this problem.

What do you guys think about it ? Can I find somewhere in my results a kind of my_reads_corrected.fastq file somewhere in the Correction or Trimming subdirectory ? Should I try something more subtle from your point of view ?

Thanks for your help !

Cheers,

Roxane

**Comment by skoren** [comment]
You don't want to use the corrected reads for polishing in case there were any mistakes in repeats or homopolymers. The final consensus is probably already as good as the corrected reads can do.

Quiver/Arrow rely on the quality from the signal information to fix the errors so the corrected reads would not have any of this information and Pilon isn't designed to use it. You can use Pilon with Illumina data though it will have trouble polishing in repetitive regions where the Illumina data won't map uniquely. This is why Arrow/Quiver first helps because they can use the long reads to place them uniquely in the correct repeat copy. You can try the Arrow pipeline: https://github.com/skoren/ArrowGrid, as long as you have the arrow/blasr binaries from SMRTportal, and SGE, it will run outside of the UI.

**Comment by brianwalenz** [comment]
Hi, Roxane-

Your consensus sequences are the contigs.  Since the corrected reads were used to make those sequences, polishing with the corrected reads will do nothing useful -- there is no additional information added to the computation.  I.e., polishing with raw reads adds the raw signal information; polishing with Illumina adds new (and more correct) base calls.

**Comment by RxLoutre** [comment]
Okay, thanks for your explanations, I think I understand now. But, as Illumina reads are significally shorter, I'm afraid that using them to polish my data won't be that effective on my PacBio-Canu assembly... As skoren said.

Do you think that polish it with Pilon+Illumina reads will lead to a more accurate assembly ?

**Comment by skoren** [comment]
Polishing with Illumina will give you accurate results except in large repeat regions where the Illumina data can't be uniquely mapped. Polishing with raw signal info with Quiver/Arrow would fix those errors.

**Comment by RxLoutre** [comment]
Okay, I've installed SMRT Portal,I want to try the ArrowGrid pipeline you gave me. What are the configurations step (which tools are used that I must precise paths ?)

Thanks again for your help and patience !

Cheers,

Roxane

**Comment by skoren** [comment]
The smrtportal binary folder must be in your path (like pbalign,bamtools, bax2bam, dataset, and variantCaller). If you have SGE it can run on your grid but you will need to edit arrow.sh to have the right submit commands for your system. You can edit the CONFIG file to run locally instead of on the grid.

**Comment by RxLoutre** [comment]
Okay, so as I installed SMRT Analysis yesterday, I can tell you that I don't have SGE or any job managment system (I chose NONE during the installation process).

Also, I'm not really sure that I understand what you mean by "grid"... Sorry this might sound like a stupid question

**Comment by skoren** [comment]
Since you have no SGE, you don't have any grid system so you can edit the CONFIG file that comes with ArrowGrid to be:
```
USEGRID 0
```
you won't get much speedup this way but you can still use the scripts. I'm closing this issue since your recent questions haven't been about Canu, open an issue on the ArrowGrid page if you have followup issues/questions.

**Comment by chenyufanxin** [comment]
Hello, RxLoutre. I want to know whether you havu run ArrowGrid successfully to polish your canu assembly?

**Comment by RxLoutre** [comment]
Hello there !

I indeed managed to use arrow, but I used a different way without ArrowGrid.

I redirect you on that Biostar tutorial that I recently wrote, maybe that may help you.

https://www.biostars.org/p/273447/

I hope it will help !

Cheers,

Roxane

**Comment by skoren** [comment]
Thanks for posting the tutorial. It looks good. The one caveat is that the merging step won't scale to very large genomes (>1g) because the merged file will be multiple TB in size. You can use the dataset tool from SMRTportal to avoid this step.
