### ISSUE TITLE
Couldn't parse gridEngine options 

### ISSUE THREAD

**Issue by ltaulell** [marbl/canu#345]
I'm trying to install Canu for our NGS users on our multi scientific compute center.

I'm using a canu.defaults:
```
maxMemory = 250
maxThreads = 16
useGrid = remote
```
(using "remote" as our compute nodes are not allowed to submit jobs... yet, possible only on front nodes)

First run:
`canu -correct -trim -assemble -pacbio-raw PacBio/concat.fastq -p local_assembly -d temp/ -genomeSize=1000000000 -errorRate=0.05`

failed with:
```
-- Canu v1.4 (+0 commits) r7995 7b04cd09002d6b865ca05f4a3f53edb936b5c925.
-- Detected Java(TM) Runtime Environment '1.8.0_77' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 0' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 252 gigabytes of memory.
-- Detected Sun Grid Engine in '/gridware/sge/default'.
--
-- WARNING:  Couldn't determine the SGE parallel environment to run multi-threaded codes.
-- WARNING:  No valid choices found!  Find an appropriate Parallel Environment name (qconf -spl) and set:
-- WARNING:    gridEngineThreadsOption="-pe <name> THREADS"
--
--
-- WARNING:  Couldn't determine the SGE resource to request memory.
-- WARNING:  No valid choices found!  Find an appropriate complex name (qconf -sc) and set:
-- WARNING:    gridEngineMemoryOption="-l <name>=MEMORY"
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'can't configure for SGE'.
```

Fixing it in canu.defaults failed as well:
canu.defaults:
```
maxMemory = 250
maxThreads = 16
useGrid = remote
gridEngine = sge
gridEngineArrayMaxJobs = 7500
gridEngineThreadsOption = "-pe openmp16 16"
gridEngineMemoryOption = "-l h_vmem=250"
```

Second try failed:

```
-- Canu v1.4 (+0 commits) r7995 7b04cd09002d6b865ca05f4a3f53edb936b5c925.
-- Detected Java(TM) Runtime Environment '1.8.0_77' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 0' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 252 gigabytes of memory.
================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /applis/PSMN/generic/Canu/1.4/Linux-amd64/bin/lib/canu/Execution.pm line 1305
        canu::Execution::caFailure('Couldn\'t parse gridEngineThreadsOption=\'"-pe openmp16 16"\'', undef) called at /applis/PSMN/generic/Canu/1.4/Linux-amd64/bin/lib/canu/Grid_SGE.pm line 155
        canu::Grid_SGE::configureSGE() called at /applis/PSMN/generic/Canu/1.4/Linux-amd64/bin/canu line 331


canu failed with 'Couldn't parse gridEngineThreadsOption='"-pe openmp16 16"''.
```

What am I doing wrong ?

**Comment by brianwalenz** [comment]
Replace 16 with THREADS and 250 with MEMORY - canu will fill in what it thinks the job will need.
```
gridEngineThreadsOption = "-pe openmp16 THREADS"
gridEngineMemoryOption = "-l h_vmem=MEMORY"
```
Longer answer:

It is looking for the PE that reports (qconf -sp) `allocation_rule=pe_slots` and `job_is_first_task=TRUE`.  The allocation_rule says that all slots need to be on a single node.  This is probably needed for multithreaded jobs to be scheduled properly.  The job_is_first_task says that the first slot actually does work (opposed to launching the other slots).  This might not be necessary.  I haven't tested.

For memory, it is looking for a consumable memory resource (qconf -sc).  On the SGE's I have access to, h_vmem isn't consumable; it's really just saying 'kill the job if it exceeds this size'.  I had to add a new consumable to track memory requested by each job -- it isn't the same as memory actually free/used on the host, but an artificial accounting of expected memory usage.  The size of this consumable is specified for each host.  Each job requests some amount of this resource.  SGE will schedule a job to a host only if there is sufficient resource on the host, and then decrease the resource available.  In isolation, Canu might work without a consumable memory resource, because it will size jobs appropriately -- however, it has no way of knowing what else is running on a particular node and there could end up being two 250gb jobs, one from Canu and one from something else, on a single node.

**Comment by ltaulell** [comment]
Thanks for your answer.

It work only without the quotes (in canu.defaults):
```
gridEngineThreadsOption = -pe openmp16 THREADS
gridEngineMemoryOption = -l h_vmem=MEMORY
```

We plan to dedicate nodes for canu sub-jobs. As for us, "-pe openmp16 16" is already a whole single node (with 128 or 256GB ram). h_vmem isn't consumable on our SGE config.
