### ISSUE TITLE
Canu 1.4 failed with a "max processes" and "max open files" error

### ISSUE THREAD

**Issue by kfriesen2** [marbl/canu#353]
Canu 1.4 failed with a "max processes" and "max open files" error, on slurm. I've attached the most recent output file.
[canu.03.out.txt](https://github.com/marbl/canu/files/733945/canu.03.out.txt)

**Comment by brianwalenz** [comment]
For searching, it is reporting
```
ERROR: more reads in histogram than available for output?  oprOutLen=4154742  _oprLen=4154942
```
Which means there are more reads in the overlap output than are known to the assembler.

I just added a bit of debug code to more completely log what is going wrong.  Grab the latest code from github (the green 'clone or download' button) and restart the same command.  When it fails again, the 'lgb_canu2b/correction/lgb_canu2b.ovlStore.BUILDING/config.err' file should report which overlap jobs look broken.

It might be possible to fix without recomputing overlaps (because that will be a *huge* pain).  Try something like (from within the 1-overlapper/results/ directory):
```
ovelrapConvert -G ../../*gkpStore -raw <file>.ovb | overlapImport -G ../../*gkpStore -raw -o <fixed>.ovb -
```
Where <file> is the name of the file config.err says is bad, and <fixed> is some other name.  This will make two new files, <fixed>.ovb and <fixed>.counts.    If the 'counts' file for the original and the new are now different, I suspect the problem is fixed.  Replace the old counts file with the new counts file (and restart).

If they're the same....write back and we'll figure out how to rebuild overlaps without starting from scratch.
