### ISSUE TITLE
Failed with exit code 1.  (rc=256). ulimit: Illegal option -u

### ISSUE THREAD

**Issue by filip-husnik** [marbl/canu#381]
Hi,

My Canu version is v1.4 (+98 commits) r8093 and the test E. coli assembly finishes with no errors. However, with my own data (~400 Mb genome, ~150x coverage), cor.ovlStore.BUILDING fails with this error (copied from the config.err file) during the correction step.

```
./cor.ovlStore.BUILDING/scripts/0-config.sh: 1: ulimit: Illegal option -u
./cor.ovlStore.BUILDING/scripts/0-config.sh: 1: ulimit: Illegal option -u
./cor.ovlStore.BUILDING/scripts/0-config.sh: 7: ulimit: Illegal option -u
./cor.ovlStore.BUILDING/scripts/0-config.sh: 1: ulimit: Illegal option -u
Changed max processes per user from  to  (max ).

Max open files limited to 165535, no increase possible.

gkStore()--  failed to open './cor.gkpStore' for read-only access: store doesn't exist.
```

I guess it is related to hard limits  of my system and settings of the 0-config.sh script. I've already increased hard limits for both open files (165535) and max user processes (1655350), but it does not seem to help. Is there any way how to estimate how high these numbers have to be? Using ovsMemory=400g did not help as well.

Below is the command I run CANU with. I used corOutCoverage=500 to correct as many reads as possible because the assembly is a simple metagenome including the host genome with several symbiotic bacteria and binning works much better with error-corrected/trimmed reads.

```
canu -p P_48 -d P_48_assembly genomeSize=400m maxMemory=480g maxThreads=22 -pacbio-raw pb_339_filtered_subreads_48cells.fastq corOutCoverage=500 gnuplotTested=true useGrid=false
```

**Comment by brianwalenz** [comment]
Dang, someone found it.  The 'failed to open' issue has been fixed in the latest code.  Remove 'correction/*.ovlStore.BUILDING' before restarting.  There's nothing of value in there, so no work is lost.

The ulimit issue is probably harmless.  All we're trying to do is max out the limits.  It might be [this problem](http://askubuntu.com/questions/97257/ulimit-u-gives-illegal-option-error-when-running-from-a-script-but-not-when-fro).  If so, you can supply `shell=/bin/bash` to canu (or set it in `~/.canu` so it is used every time).

**Comment by filip-husnik** [comment]
Thanks Brian! It works like a charm with Canu v1.4 (+112 commits) r8107. Filip

**Comment by mdkeehan** [comment]
Thanks Brian,

I'll use the shell=/bin/bash next time I run canu.
