### ISSUE TITLE
Location of split reads in raw or corrected reads

### ISSUE THREAD

**Issue by johnomics** [marbl/canu#382]
Related to https://github.com/marbl/canu/issues/257 and https://github.com/marbl/canu/issues/324

If I understand correctly, the clear ranges (clr) in unitigging/asm.gkpStore/readNames.txt refer to regions in the split reads output by trimming, not the raw or corrected reads.

Is it possible to get the regions of the raw or corrected reads included in the assembly, either directly from the layouts, or by inferring them via other files?

I can see that the ID of the raw read is reported, and any split parts are reported too (e.g. the raw ids will be 123456_0, 123456_1, 123456_2 etc).

But I can't see any file that reports the location of the split reads within the raw or corrected reads. I have searched for several raw and trimmed IDs in all the files in the trimming folder and none of them seem to contain these details.

Is this information stored anywhere?

(I'm asking because I am trying to confirm that canu has done such an excellent job that it has assembled right to the end of chromosomes - I want to show that the reads incorporated into the assembly do not have substantial overhangs that have been chopped off, which would probably indicate a repeat. But that means I need to know where the split reads have come from in the raw reads, and would prefer not to do new alignments because the sequence is highly repetitive.)

**Comment by skoren** [comment]
Unfortunately, the position in the original raw read isn't preserved. The consensus can add/remove bases in the middle of the read (unlike trimming which can split a read or trim the ends but can't insert in the middle) so it is much harder to find the correspondence between the original positions and the corrected read. It would be possible to get the position of the corrected split part within the full corrected read but again, that wouldn't translate to the raw read so it isn't implemented.

Your best option would probably be to align each corrected split part of the read to its original raw sequence using something like edlib (https://github.com/Martinsos/edlib) in ends-free mode for the raw read to the split corrected part can be aligned to its best location. It isn't guaranteed to be where it came from due to repeats but hopefully the split parts are long enough that they can be uniquely assigned within the raw read. It should be relatively fast to compute these alignments and you can restrict yourself to the reads at the ends of contigs (which are listed in the layout files albeit with internal IDs which can be translated using the gkpStore/readNames.txt file).

**Comment by johnomics** [comment]
Thanks - OK, I'll look into using alignments, and thanks for the edlib suggestion. I realise it's tricky to find the positions in the raw read, but I think reporting the positions of the split reads in the corrected reads could be a useful feature.
