### ISSUE TITLE
canu failed at overlap stage

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#403]
Hi,

Please help me to resolve this error. I was running canu, and was successful to get reads corrected and trimmed. I asked your advice if i can delete files generated during correction and trimming, and was advised that while i can delete the big files, i should still keep the directories, so that canu will assume that that process is over. I did that, and my unitiging step was running smoothly despite of deleting files. But i got error at overlap stage. Please see the attached error report. Please advice me how to proceed.

thank you so much,
[canu_error_report.txt](https://github.com/marbl/canu/files/835770/canu_error_report.txt)

**Comment by amit4mchiba** [comment]
I am sorry that i have not added the command that i used for running canu. Here it is-
/home/amit-rai8chiba/canu-1.4/Linux-amd64/bin/canu -p G_glabra_med-sensitive -d ./G_glabra-assembly_sensitive genomeSize=400m -pacbio-raw /home/amit-rai8chiba/G_glabra_pcdata/data/G_glabra_all_cat.fastq.gz useGrid=0 maxMemory=100 maxThreads=$NSLOTS minThreads=22 corMhapSensitivity=high errorRate=0.05 corMinCoverage=0 corOutCoverage=100 corErrorRate=0.105 minReadLength=200 minOverlapLength=100 utgGraphDeviation=50 corMaxEvidenceErate=0.15

I am now not sure why it failed at this stage. Is it because i deleted huges files for correction and overlap?

**Comment by brianwalenz** [comment]
At the end of that log are a list of 27 jobs that fail.  What kinds of errors are reported in the *.out files for these (e.g., 'unitigging/3-overlapErrorAdjustment/oea.000007.out')?  They're all probably the same, please do check all 27 files.

What `canu -version`?  It looks somewhat old; newer versions report this in the log.  I recall an issue in this stage a few months ago.

**Comment by amit4mchiba** [comment]
Yeah. You are right. This was a older version of canu. 
error message for oea.000007.out is-
/home/amit-rai8chiba/G_glabra_pcdata/./G_glabra-assembly_sensitive/unitigging/3-overlapErrorAdjustment/oea.sh: line 573: 126337 Segmentation fault      (core dumped) $bin/correctOverlaps -G /home/amit-rai8chiba/G_glabra_pcdata/./G_glabra-assembly_sensitive/unitigging/G_glabra_med-sensitive.gkpStore -O /home/amit-rai8chiba/G_glabra_pcdata/./G_glabra-assembly_sensitive/unitigging/G_glabra_med-sensitive.ovlStore -R $minid $maxid -e 0.15 -l 100 -c /home/amit-rai8chiba/G_glabra_pcdata/./G_glabra-assembly_sensitive/unitigging/3-overlapErrorAdjustment/red.red -o /home/amit-rai8chiba/G_glabra_pcdata/./G_glabra-assembly_sensitive/unitigging/3-overlapErrorAdjustment/$jobid.oea.WORKING

So, segmentation fault means memory issues. 

I just updated canu from the git-hub. So, what shall i do. Do i need to rerun the entire process, or shall i take the trimmed seq. data and run assembly again. Can i start from where the error begin. Also, shall i use new version of canu or i should use the version that i used i used for this assembly.

I am sorry for asking so many questions, but i have been waiting for results since long, and i really want to save my time if possible while re-running this.

thank you so much

**Comment by brianwalenz** [comment]
Options:

1)  With latest canu, restart unitigging phase using corrected reads (canu ... -assemble -pacbio-corrected trimmedReads.fasta.gz).  This is the safest, but does require recomputing overlaps.

2)  Depending on which specific version you have (the git hash, please, and/or the canu 'r' number), it might be possible to update only a few versions to get the bug fix I'm thinking of.  I think this still would need to recompute all of the 3-overlapErrorAdjustment phase.

3)  Restarting with the latest code probably won't work, again based on the specific version you have, either from file formats changing or file locations changing.  There was a big pipeline change about a month ago, and I've had no luck restarting old assemblies after that.  But you can try; at worst, you fall back to option 1.  If you try this, give canu the -assemble switch so that it skips correction and trimming.  There's a good chance it'll recompute the mer counts in 0-mercounts (meryl process), but it should skip overlaps.

I'd do option 1, since it has the highest chance of working, and I'm patient.  Option 2 should work (unless it's a different bug than I'm thinking of), but does need another round or two of emails to figure out what to do.
