### ISSUE TITLE
Use GFA to trim and merge contigs

### ISSUE THREAD

**Issue by gringer** [marbl/canu#409]
Canu seems to like assembling the same thing multiple times, ending up with multiple assembled contigs that have similar sequences. The GFA v1 specification has two contig join categories that would be useful to collapse the assembly to remove these duplications:

Link (L): If the link from the end of one contig is unique (i.e. there is only one join), then the two contigs should be merged as a single contig. Potential option: minContigOverlap=500 [if two contigs uniquely overlap at their ends by at least 500bp, then merge into a single contig]

Containment (C): [not currently generated by Canu] If a contig is almost entirely captured by another contig, then the smaller contig should be discarded (because it is represented by the larger contig). Potential options: minContainmentFraction=0.9 [containment removal is triggered if at least 90% of the contig is captured by another contig]; minParentContainmentSizeFactor=2 [Parent must be at least twice the size of the contained subsequence]

**Comment by skoren** [comment]
Canu is designed to keep haplotypes separate throughout the assembly so they will end up being assembled into two contigs, duplicating the genome sequence. The link edges should be captured in the current output. I'm not sure the containment operations would work. Most Canu contigs aren't fully contained in another one but have some unique sequence on their ends. This relationship isn't captured by GFA v1 very well (there is no relationship for a partial overlap between contigs) which is why Canu outputs a separate unitigs GFA that breaks contigs at junctions so all unitigs have a dovetail relationship in GFA v1 (so a contig is a path of unitigs where the assembler may have switched haplotypes). As for the link edge, if Canu didn't join contigs then it had ambiguous evidence and joining them based on the overlap would potentially introduce errors. When contigs are split due to repeats, some of the repeat is left in both bordering contigs (reaching into the repeat by at most a single read) so if you find overlaps between two contigs that doesn't mean they can be unambiguously joined, they just end in the same repeat but there could be multiple copies of the repeat between them not just one.

So it should be possible to use the current unitig and contig gfa output to join contigs based on edges (whose overlap size is included in the link edge) as long as there is outside evidence that joining is correct. For contains, it would require traversing the graph to identify paralogous unitigs (e.g. bubbles in the unitig graph) and you could then arbitrarily pick one traversal of the bubble. Phasing and de-duplicating the Canu graph is ongoing development so at some point this will probably be automated and built into the assembler.

**Comment by gringer** [comment]
Here is a LAST plot for two sequences that Bandage will join, because they have an unambiguous link in the contig GFA:

![shouldbejoined](https://cloud.githubusercontent.com/assets/856314/24128266/a08e1d82-0e3f-11e7-8c51-95f0c9548679.png)

When I map the reads to each other, the mapping extends right to the end of the reads. The match region is not perfect (96.19% identity over 5.6kb according to LAST), but that should be within the error expectation for the assembly. There are no internal repeats in these contigs, 

Here are the sequences, together with the readToTig information, what I think are the component reads, and an additional mapping of these contigs back to the other contigs in the genome (with LAST):

[shouldBeJoined.zip](https://github.com/marbl/canu/files/856872/shouldBeJoined.zip)

Reads were extracted from the unitig store with the following command:

`(for id in $(cat shouldBeJoined.contigs.layout.readToTig | tail -n +2 | awk '{print $1}'); do ~/install/canu/canu-1.4/Linux-amd64/bin/gatekeeperDumpFASTQ -G unitigging/NbL5_ONTDECAF_t1.gkpStore -fasta -o - -r ${id}; done) > shouldBeJoined.reads.fasta
`

I notice that there is a ~1.5kb region in 'tig00003015' that maps to lots of other contigs, but this is in the middle of the contig, rather than at the end.

Are you able to look at these and explain to me why Canu has decided that they shouldn't be joined, and why the link exists in the GFA for these contigs if they shouldn't be joined? I expect that answers to these questions will help me understand if/why doing the contig collapsing in Bandage is a bad idea, and help me with working out what more (if anything) I can do with regards to finishing the genome with the reads that I have.

**Comment by skoren** [comment]
Is this a nanopore or a pacbio assembly? If it is pacbio, 4% is a pretty high error rate, overlaps are only computed out to 4.5% and typically only about 1-2% error is accepted for the contig construction. If it's nanopore, then yes 4% isn't that high. It may be safe to merge contigs as long as the ends are not repetitive in that case.

As for why they weren't merged it could be that they were merged and split due to repeat identification or the overlap was filtered out during construction. If you want to explore this, you could check if the overlap store has the overlap between the reads at the ends of the contigs (```ovStoreDump -q a b``` usage) as well as what error rate is actually being used for overlaps (the output in ```unitigging/4-unitigger/*001.filterOverlaps.thr000.num000.log```):
```
ERROR RATES (626131 samples)
-----------
mean   0.00634727 stddev 0.00686929 -> 0.04756303 fraction error =   4.756303% error
median 0.00410000 mad    0.00170000 -> 0.01922252 fraction error =   1.922252% error
```
Here, overlaps up to 1.9% error would be used. You can also look at the ```unitigging/*.best.edges``` file for the reads in question to see what their best overlap was to.

**Comment by gringer** [comment]
Okay, so what it sounds like is that different thresholds are being used for the actual contig assembly and what goes into the GFA file, is that correct?

These are contigs from nanopore assemblies, with very low coverage. Here's the overlap error threshold:

```
ERROR RATES (1312496 samples)
-----------
mean   0.06149784 stddev 0.03053073 -> 0.24468220 fraction error =  24.468220% error
median 0.05300000 mad    0.01740000 -> 0.20778344 fraction error =  20.778344% error

```

I can't find the overlap in the store, but perhaps the command I am using is incorrect:

```
$ ~/install/canu/canu-1.4/Linux-amd64/bin/ovStoreDump -G NbL5_ONTDECAF_t1.gkpStore -O NbL5_ONTDECAF_t1.ovlStore -q 3015 19494
[no output]
```

It is in the GFA output though:

```
$ grep 'tig000\(03015\|19494\)' NbL5_ONTDECAF_t1.contigs.gfa
S       tig00003015     *       LN:i:16586
S       tig00019494     *       LN:i:20821
L       tig00003015     +       tig00019494     -       5458M   cv:A:F
L       tig00019494     +       tig00003015     -       5434M   cv:A:F

```

**Comment by skoren** [comment]
Right what gets computed and used for the assembly is not the same. There are various filters (like only best edges are used, chimera filters, etc) that can eliminate overlaps from building contigs. However, the GFA tries to report links, including those that didn't go into the assembly.  The idea is to capture everything the assembler saw but didn't use.

To check for the existence of the overlap you'd have to find the reads in question at the ends of the tigs that could have been joined (listed in ```*.contigs.layout```) and then check for overlaps between those reads. The overlap should be there if it's in the GFA (otherwise the GFA wouldn't have found it).

**Comment by gringer** [comment]
I think I'll close this issue; you've demonstrated that Canu does things that are not obvious from the GFA, and there are good reasons why the graphs are not collapsed as much as possible based on the overlap graph (e.g. evidence from mapped reads).
