### ISSUE TITLE
gridOptions can't work.

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#431]
Dear developers,

I have run canu successfully. It's really a great work.

But there is still some problems. Here is one of them.

When I start canu with this command:
`canu -p nott -d 20170329 genomeSize=100m -pacbio-raw file2.fasta merylMemory=60 gridOptions="--cpus-per-task=24 --mem=60g"`

It passes my setting about grid to the program, but:

Each time there will be a default grid setting following my setting like this:
`    sbatch \`

>       --mem=4g \
>       --cpus-per-task=1 \
>       --cpus-per-task=24 \
>       --mem=60g  \

`     --depend=afterany:5151562 \
      -D `pwd` \
      -J "canu_nott" \
      -o /HOME/path/to/canu-scripts/canu.04.out /HOME/path/to/canu-scripts/canu.04.sh
`
Please notice the quoted words.
Not only my setting "`--cpus-per-task=24 --mem=60g`" but also the default setting "`--cpus-per-task=1 --mem=4g`" are passed to canu.
Sometimes my setting is behind the default setting, it will work.
But sometimes my setting is in front of the default setting, the default setting will override my setting.
Just like this:
`      sbatch \`

>         --cpus-per-task=24 --mem=60g  --mem=2g --cpus-per-task=1 \

`       -D `pwd` -J "ovB_nott" \
        -a 1-81 \
        -o /HOME/path/to/correction/xiyu.ovlStore.BUILDING/logs/1-bucketize.%A_%a.out \
        /HOME/path/to/correction/xiyu.ovlStore.BUILDING/scripts/1-bucketize.sh
`

How to solve it?
Wait for your help!

**Comment by skoren** [comment]
The specific issue with overwriting the user parameter was fixed in commit 552ab30cd17da6684a6b156344c2ef2196f9aed9. However, you shouldn't need to request memory explicitly. Canu will manage the memory for you. The memory requirements vary by step so requesting 24 cores/60g memory for the driver process is overkill since it just checks existence of files and submits subsequent jobs. That's why Canu is only requesting 2g for it and 1 core.

If you want to control how much memory a given step uses, you can see the memory options with:
```
canu -options |grep Mem
```
These will automatically request the appropriate amount of memory from your grid as well. The only time you may need to request memory manually is if a job fails due to exceeding a memory limit, otherwise, don't specify memory and let Canu do it.
