### ISSUE TITLE
obtovl takes days to deal with R9.4 nanopore data

### ISSUE THREAD

**Issue by bioprojects** [marbl/canu#437]
Dear developers, 

Thank you for developing this great software.
I'm using canu to assemble R9.4 nanopore data in which 
total read length is approximately 1.4Gb

The default parameter of canu succeeded in obtaining
complete assembly.

But it took about 5 days to finish.
What is particularly slow seemed to be "obtovl".

In order to try to make the computation faster,
I tried to set errorRate=0.025, but it failed to obtain
complete assembly.

Is there any other good way to reduce the time for assembly 
by canu?

Thanks a lot in advance.

Best wishes,

Koji 

###
Koji Yahara
Senior Research Fellow
Antimicrobial Resistance Research Center
National Institute of Infectious Diseases
Aoba-cho 4-2-1, Higashimurayama-shi, Tokyo 
189-0002 Japan
Tel: +81-42-561-0771 (Ex. 3539)
Fax: +81-42-561-7173

**Comment by brianwalenz** [comment]
See issue #414 too.

Using the absolute latest code, not just the latest released version, you can set `overlapper=mhap utgReAlign=true`.  This will use the mhap overlapper for all overlap stages.  In limited testing, it seems to work reasonably well.  We're planning on making this the default for the 1.6 release - but that's a few months away.

You can also try ovlErrorRate=0.12 (the default is 0.144).  Again, I would use the latest code because the 1.4 release handled error rates differently.

The latest code can be downloaded from github using the green 'clone or download' button.

**Comment by bioprojects** [comment]
Thank you very much!  The latest code and the option (overlapper=mhap utgReAlign=true) worked and yielded complete assembly within a day.  I'll continue to try it in other data sets.

**Comment by skoren** [comment]
Glad that worked for you, closing the issue.
