### ISSUE TITLE
The algorithm of mhap, thanks!

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#452]
Hi, @skoren !

Thanks for all help previously. Now, I try to understand the overlap algorithm, but after reading related paper, I still feel confused. For one hand, my English is not very well. For the other hand, I had a little knowledge of algorithm about alignment. All these make me crazy in reading  paper, so I had to look for help here. Any suggestion would be grateful!

1) Suppose we have three reads: s1, s2 and s3 (s1 and s2 were same as in MHAP paper, and s3 is same as s1):
s1: CATGGACCGACCAG s2: GCAGTACCGATCGT.

2) Changing them to sketch: s1, s3 is (5,1,2,15) and s2 is (5,1,6,6).

3) How to get overlap reads before second-stage filter? According to equation 6, it seemed the Jaccard similarity of s1 and s2 should be 2/(2*4-2)=2/6, but in figure 1 it is 2/4. Even though this is right:
a) How can I say s1 and s2 is overlapped? According to figure 1, it seemed 0.22 was calculated with 2/4 using the equation 8 and 9, then 0.22 was used to deduce whether these two reads are overlapped, but how?
b) In equation 9, we try to get the number of shared min-mers x, but in equation it have "x-1", should this be "H-1"?
c) How to deduce the overlap of above three reads? In fact, I can't understand following paragraph:

> The hth min-mer for each read is hashed into the hth hash table, which is shared between all reads. The hash tables are maintained in memory, unless there are too many reads. In that case, the computation is treated as a parallel all-to-all computation, where only a subset of reads are hashed and compared to all reads streamed directly from the drie. This subset-to-all comparison is repeated for all nonintersecting subsets, either in parallel or serially, depending on the computation resources available.
> For each read we find all the reads that are similar by looking up the H min-mers in the hash tables. The hth min-mer is looked for in the hth hash table, and the counts are aggregated into one list. Any read that has at least x min-mers in common with the lookup read is propagated to the secondstage filter. 

```
Is hash table like these:
5={s1, s2, s3}; 1={s1, s2, s3}; 2={s1, s3}; 15={s1, s3}; 6={s2}
Then for s1: 
    count(s1,s2)=0; 
    count(s1,s3)=0
    for each min-mer of s1:
      first 5, we found s2 and s3, so count(s1,s2)++; 
                                      count(s1,s3)++;
      then for 1,  count(s1,s2)++;
                   count(s1,s3)++;
      until the last 15 of s1. At last, 
                          count(s1,s2)=2;
                          count(s1,s3)=4?
```

**Comment by skoren** [comment]
a) you're confusing Jaccard and the minhash estimate of Jaccard. For s1 and s2 there are 4 shared 3-mers:
```
ACC
CAG
CCG
CGA
```
and a total of 18 3-mers in the union of s1 and s2 (Jaccard works on sets so redundant k-mers are ignored). 4/18 = 0.22. That is the true Jaccard. Figure 1 shows the Jaccard estimate which is 2/4 (since there are two equal hash values 5 and 1) and the denominator is always 4 (the sketch size). The estimate of Jaccard here is 0.5 (it's an estimate so it can be wrong but the sketch size controls the bound on how wrong, a sketch of 4 has a poor bound).

b) no equation 9 is correct. You want to compute the probability that you have less than x matches which is the sum of probability you have 0, 1, 2, ..., x-1 matches (https://en.wikipedia.org/wiki/Binomial_distribution).

c) Ignore the part about breaking the computation up, that has no impact on the algorithm, it's just a memory optimization. 

There are different ways to implement MinHash but MHAP uses the multi-hash function/multi-table approach. There is one hash table for each hash function, so Table 1: {5=>s1,s2,s3}, Table 2: {1=>s1,s2,s3}, Table 3: {2=>s1,s3;6=>s2}, Table 4: {6=s2; 15=s1,s3}. What the paragraph says is you sum up the counts for all other sequences in all the H tables. So if you want to find all overlapping sequences for s1, you'd get the value in table 1 at 5 and have the counts {s2=1, s3=1}, then get the value in table 2 at 1 and have the counts {s2=2, s3=2}, then get the value in table 3 at 2 and have the counts {s2=2, s3=3} and finally the value in table 4 at 15 and have the counts {s2=2, s3=4}. So now you can say the estimated Jaccard between s1 and s2 = 2/4 and between s1 and s3 = 4/4. MHAP just sets a threshold for minimum count for shared k-mers in the first-pass filter to get sequences which likely overlap. The second stage filter examines the pairwise matches and eliminates those which are false.

**Comment by lamz138138** [comment]
Hi, thanks for reply. I had understand the algorithm more better, but I still don't know how MHAP set the threshold. I would read paper again a few hours later as it is now 3 am, and post new questions later.  

Thanks again!

**Comment by lamz138138** [comment]
Hi! 

After review the paper, I have following new question:
1. How to set the threshold? I think using equation 9, if we defined f(x;H;p) as 0.05, then x could be calculated for each comparing reads. However, it seemed MAHP use x=3 in either fast or sensitive model. Is these because the two model give a good result according to simulation and compare with BLASR and so on?

2. In CANU, Wq was defined to modify k-mer. Since idf in the range [1,idfmax], is this means a higher value get less integer value after MurmurHash3? Otherwise, there would be more repeat k-mers in sketch set.

3. Whether I have to set mhap parameters in CANU? It seemed different parameter would give different result, change the parameter may give a better assembly.

4. Could you show me how second stage filter work with above three reads? In fact, I don't know how sort-merge algorithm work. Take s1 as example, is it result in ACC (index is 6), ATG (2)...GAC (5), but how to compare it to other reads? I couldn't understand this paragraph, and failed to find any tale in youtube..... I think this question would be very difficult to explain, I would tried to find other way if you think it too hard to give me detail information.

> In order to compute the overlap score and region, we modify the basic sort-merge algorithm by also storing the indices of the k-mer position along with the k-mer fingerprint. In case a k-mer in S1 matches multiple k-mers in S2, we store only the match with the earliest position in the read, thus guaranteeing O(L) operations. The relative offset of the sequences S1 and S2 is estimated by the median difference in the positions of matching k-mers. The k-mer counting algorithm is then run again, constrained to the overlapping region, in order to get the final k-mer count, and the bounds of the overlap are computed from the positions of matching k-mers by taking a uniformly minimum-variance unbiased (UMVU) estimator assuming k-mer matches come from a continuous uniform distribution with unknown start and end points65. 

Best wishes!

**Comment by skoren** [comment]
1. The point of the first-stage filter is to eliminate obviously false matches so you can set a low threshold. The threshold of 3 is set based on empirical tests and simulations, yes.

2. The idf controls how many times a k-mer is hashed. A higher idf value means it is hashed multiple times. Being hashed multiple times increases its probability to be a minimum. Thus k-mers with higher idf values (the unique ones) are more likely to become minimums.

3. No, canu sets reasonable defaults that work well for most datasets and provides a few presets that are automatically selected based on your coverage.

4. The basic idea is composed of two steps, first you figure out the likely shift between the reads then you figure out where they overlap (based on the k-mers that are shared). The merge sort of the positions of the minimums lets you find a median of two sorted arrays. In the case of s1 and s2 that offset is 0 (the minimums are at k-mers 5,6 in both reads). Then the bound is based on k-mers 5-6 in the reads (ACCG). That's essentially it, this is the overlap you would report. The UMVU adjusts for the fact that you may have missed a matching k-mer due to error.

**Comment by lamz138138** [comment]
Hi!

Thanks for your detail reply, but I failed to understand some detail. I make a little change of reads S1, S2, and these two reads overlap as follow:
```
S1:      ACCTCCGATCGTGCAGT
         ||| ||||  
S2: CATGGACCGCCGACCAG
```
After decomposing these two reads to sketch, we find three shared min-mers. Then, the indices of the k-mer position along with the k-mer fingerprint were sorted as follow (* denote shared min-mers):
```
k-m index (S1)    k-m index (S2) 
ACC 0 (*)         ACC 5 (*)
AGT 14            ATG 1    
ATC 7             CAG 10
CAG 13            CAT 0 
CCG 4 (*)         CCG 6 (*) 
CCT 1             CGA 9 (*)  
CGA 5 (*)         CGC 7 
CGT 9             GAC 4 
CTC 2             GCC 8 
GAT 6             GGA 3  
GCA 12            TGG 2
GTG 10
TCC 3
TCG 8
TGC 11
```
1. For ACC of S1, it matchs S2 in index 5 and 12, we only recode ACC match S2 at 5, am I right? That is  "In case a k-mer in S1 matches multiple k-mers in S2, we store only the match with the earliest position in the read".
2. How to calculate the relative offset of the S1 and S2? The minimums of share k-mer of S1 is 0, while S2 is 5, so offest is 5 (5-0). That is, base 1 (0+1) of S1 is aligned to base 6 (5+1) of S2. Am I right? 
3. How to find bound before UMVU? For S1, the overlap region is from minimum index to maximum index (0 to 5), that is ACCTCCGA, while for S2, from 5 to 9 (ACCGCCGA). We then extend the region by overlap length multiply 30% (8*0.3=2), so final bounder of S1 is ACCTCCGATC and S2 is GGACCGCCGACC, am I right?
4. How UMVU work after finding bound? I felt the paper is difficult for me, maybe I don't need to konw how it work. This question could be omited if you think it is difficult to answer.
5. We then calculated the similarity of overlap, but I couldn't find a threshold that was used to filter lower similarity, what had I missed?

Also, I have some questions about DALIGNER:

6. As DALIGNER find diagonal edge longer than a threshold, so there maybe more than one local alignemnt between two reads, while MHAP only output one local alignment?
7. How does DALIGNER work? First, it constructure edit graph for every two reads. Second, it find diagonals edge called seed that have more than X k-mers, overlap more than h bases and less than Y width. Finally, it extend the seed to find local alignment. Am I right?
