### ISSUE TITLE
How to improve the contig length?

### ISSUE THREAD

**Issue by RobertoRun** [marbl/canu#455]
I have another project! The genome size is about 1.7Gb. We have sequenced it about 60X with RSII. The L50 with default parameters is about 300Kb. I don't satisfy it! Someone achieved the L50 of 1Mb. So would like to give me some idea to adjust the parameter? Thanks!

**Comment by skoren** [comment]
Someone sequencing the same genome with the same data had an NG50 of 1mb? The genome repeat content and your read length distribution will determine quality (along with heterozygosity). See the FAQ for your question:
http://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it

You can try either heterozygous parameters (if the genome is heterozygous) or you can try the low coverage parameters to see if it improves your results.

**Comment by skoren** [comment]
Also is this a different dataset than #420?

**Comment by RobertoRun** [comment]
Thank you very much! Yes, the high heterozygosity is different project, different species! 

Yes, some group also sequence the same species, but they achieve the L50 of 1Mb.  They sequenced about 80X, we sequence 60X. But i think the coverage is enough!

**Comment by RobertoRun** [comment]
So sorry, this is not the same with the previous one! We have many projects! Now, three or four are on going!

**Comment by skoren** [comment]
There is too much variability to be comparing a completely different sequencing run to your project. I presume you're not using the same tissue so they could have picked a more inbred strain, done some inbreeding before sequencing, or there could be other strain-specific differences. Higher coverage does help, especially on repetitive or heterozygous genomes because you have more long reads and a higher chance of spanning long repeats. If you have 60x of the haploid genome size on a heterozygous genome you have close to 30x in reality which is not very high. The read length distribution is also going to have a large impact on the assembly quality, so if your average/N50 read length is shorter the assembly will be less contiguous. Even the N50 metric is not reliable. If you assemble a heterozygous genome and Canu splits the haplotypes giving you double the genome size and you measure N50 that will be much lower than an N50 of a collapsed assembly. You would need to use NG50 with the same genome size denominator. So in short, just because some other project has 1mb N50 doesn't mean you should be aiming for that or can get that on your sequencing set. For context, there are several PacBio human genomes, both haploid and diploid. The contig NG50 (same denominator) ranges from 1mb to over 20mb depending on coverage and read lengths. 

I would suggest trying the heterozygous settings which are already documented (```corOutCoverage=200 correctedErrorRate=0.040 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"```). You could combine them with the low-coverage settings as well if you wanted to (```corMhapSensitivity=high corMinCoverage=0```). I am going to close this issue because I don't see anything for us to answer. From the initial description it doesn't sound like you have tried the heterozygous or low coverage settings yet so try those and see if the assembly improves. If you encounter errors in those assemblies open a new issue. However, it doesn't make sense to try to make an assembly of one dataset match the N50 of a completely different dataset.
