### ISSUE TITLE
looking for markRepeatUnique replacement and a way to identify alternate contigs

### ISSUE THREAD

**Issue by mscampbell** [marbl/canu#457]
Hello,

I'm assembling a highly heterozygous plant genome. I ran canu with default parameters and ended up with a 702MB assembly. I am expecting 450MB. I reran the assembly using corMaxEvidenceErate=0.15 as recommended for plant genomes and I got a more reasonable but still larger than expected 593MB. I speculated that the extra sequence was because of high heterozygosity and the maternal and paternal haplotypes were being assembled individually. I used BUSCO as a quick way to identify duplicated genes. I used the plant BUSCOs for the analysis. The 702MB assembly contained 93.8% of the 1440 busco genes as full length 74% as single copy and 19% as duplicated. the 593MB assembly has 89% full length, 80% single copy and 9% duplicated. It doesn't look like the extra assembled sequence is simply individually assembled halotypes. My next guess is that there is something going on with the assembly of repeats. I talked to a lab mate that used PBcR to assemble the maize B73 genome and she suggested that I use a script called markRepeatUnique. It looks like that script did not make the cut for incorporation into canu. Is there a analogous utility available?

Also, I read that the contigs file contains alternate path contigs. Is there an easy way to identify the alternate contigs so I can flag them as alternates for downstream analysis? Does the suggestRepeat flag in the fasta output mark alternates or transposon sequence?

Thanks,
Mike

**Comment by skoren** [comment]
First for the easy answer, markRepeatUnique is automatically incorporated into Canu so it should have already been run/filtered contigs on your assembly (it's the contigFilter parameter described on the FAQ: http://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why. So I don't think you should need to run it on your assembly, the repetitive bits that couldn't be assembled are in ```asm.unassembled.fasta``` already.

As for the harder question, I expect most of your extra sequence is due to the uncollapsed heterozygosity but it's not across the whole genome just 20-30% that is most diverged. I'd suggest trying the heterozygous parameters as those should try to separate more of the haplotypes from the FAQ:
http://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it
```
corOutCoverage=200 correctedErrorRate=0.040 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"
```

This will probably increase the assembly size not decrease it. Unfortunately there isn't an easy way to identify which paths are the alternates at present. We've done filtering before using self-matches with MUMmer or BUSCO genes using this code (https://github.com/skingan/HomolContigsByAnnotation) where you'd remove the secondary contigs in the list. That might get you down or close to the expected genome size.

An alternative option, depending on the type of heterozygosity you have (large structural differences like inversions/etc several hundred kb in length or more) or small localized differences you can try to collapse the assembly with the parameters suggested there too:
```
corOutCoverage=200 ovlErrorRate=0.15 obtErrorRate=0.15
```
However, large structural variation will remain uncollapsed or differences >5% error.
