### ISSUE TITLE
Canu submitting job arrays that are too large for queue

### ISSUE THREAD

**Issue by jehalter** [marbl/canu#461]
We're using Torque/Moab. The administrators have limited the max job array size to 1000. Likewise, max user queuable is also set to 1000:

```
$ qmgr -c 'p s' | grep max_job_array_size
set server max_job_array_size = 1000
```
```
$ qmgr -c 'p s' | grep max_user_queuable
set queue bsl_cpu max_user_queuable = 1000
set queue boomslang max_user_queuable = 1000
```
My Canu job failed when it got to the 1-overlapper stage, when Canu tried to submit an array size of over 4200 elements:
```
-- BEGIN TRIMMING
--
-- overlapInCore attempt 1 begins with 73 finished, and 4200 to compute.
----------------------------------------
-- Starting command on Wed Apr 19 06:21:51 2017 with 115518.461 GB free disk space

      qsub \
        -q boomslang -l walltime=8:00:00 -l prologue=/users/urctest2/torque/prologue.sh,epilogue=/users/urctest2/torque/epilogue.sh  -l mem=16g -l nodes=1:ppn=6 \
        -d `pwd` -N "obtovl_oat4" \
        -t 74-4273 \
        -j oe -o /scratch/urctest2/work/canu-1.4/oat_test/oat4/trimming/1-overlapper/overlap.\$PBS_ARRAYID.out \
        /scratch/urctest2/work/canu-1.4/oat_test/oat4/trimming/1-overlapper/overlap.sh

qsub: submit error (Maximum number of jobs already in queue for user MSG=total number of current user's jobs exceeds the queue limit: user urctest2@bsl-c1.uncc.edu, queue boomslang)

-- Finished on Wed Apr 19 06:21:51 2017 (lickety-split) with 115518.461 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 228.  (rc=58368)
ERROR:
================================================================================
Please panic.  canu failed, and it shouldn't have.
```

Should Canu be able to detect such job limits by querying the queue manager? Or is there a command line option that I've overlooked to tell Canu to limit the job array size, or the max number of jobs to queue at one time?

**Comment by skoren** [comment]
Canu does auto detect the limit on some systems, but not torque, you can explicitly set it with
```gridEngineArrayMaxJobs=1000```
We can update the code using your qmgr command to auto-set it like it does on SLURM/SGE.

The second issues, not being allowed to submit jobs because you have too many queued is harder to solve, there currently isn't any workaround (that is if you cannot submit a total of 4000 jobs even split into 4 arrays). The best workaround for that would be to increase the memory of overlap in core (```obtovlMemory``` and ```utgovlMemory```), doubling it should half the number of jobs/etc.

**Comment by brianwalenz** [comment]
Support for setting gridEngineArrayMaxJobs based on qmgr output has been added, but not tested _at all_.

It might be possible to hack around the limit on number of jobs queued by keeping track of the number of tasks submitted and stopping submission at the limit, then increasing canuIterations so that canu will loop over submissions.  The flow would be:

1. the canu process submits first batch of 1000 jobs, and another canu process holding on the array.
2. the array runs, and the grid starts up the second canu job.
3. the second canu job finds the first 1000 jobs finished, but complains the remaining N thousand are missing.  It submits another batch of 1000 jobs, and another canu process.
4. goto 2.

Usually, canuIterations is 2, which lets canu try running jobs twice.  A downside to this is that if a job _does_ fail, it'll get retried a whole bunch of times before canu gives up.

Have you checked with the sysadmins to see if the limit can be increased?

**Comment by TinaH10** [comment]
Having this problem right now:
gwdu103:12 15:35:48 ~/NANOPORE_READS/FASTQ/CANU_ASSEMBLY_NEW_BASECALL_MAN_ERR_RATE_PASS/unitigging/3-overlapErrorAdjustment > ls
red.jobSubmit-01.out  red.jobSubmit-01.sh  red.sh
gwdu103:12 15:35:49 ~/NANOPORE_READS/FASTQ/CANU_ASSEMBLY_NEW_BASECALL_MAN_ERR_RATE_PASS/unitigging/3-overlapErrorAdjustment > cat red.jobSubmit-01.sh


#!/bin/sh

bsub \
  -M 4096 -R span[hosts=1] -W 24:00 -q mpi -n 4 -o red.%I.out \
  -J "red_WARBLER_MAN_ErrRate_PASS[1-3820]" \
   \
  ./red.sh 0 \
> ./red.jobSubmit-01.out 2>&1


gwdu103:12 15:36:00 ~/NANOPORE_READS/FASTQ/CANU_ASSEMBLY_NEW_BASECALL_MAN_ERR_RATE_PASS/unitigging/3-overlapErrorAdjustment > cat red.jobSubmit-01.out
Job array index too large. Job not submitted.


It is the final step. Can I recover the run from there, or do I need to restart the whole run?

Thanks!
