### ISSUE TITLE
Can't locate Filesys/Df.pm in @INC

### ISSUE THREAD

**Issue by e-sevin** [marbl/canu#47]
Hi there,

Just wanted to know whether I was the only one bumping into this error when trying to use the binary release for Linux:
```
Can't locate Filesys/Df.pm in @INC (@INC contains: /root/mydisk/canu-1.0/Linux-amd64/bin/lib/canu/lib64/perl5 /root/mydisk/canu-1.0/Linux-amd64/bin/lib/canu/lib/perl5 /root/mydisk/canu-1.0/Linux-amd64/bin/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /root/mydisk/canu-1.0/Linux-amd64/bin/lib/canu/Defaults.pm line 45.
BEGIN failed--compilation aborted at /root/mydisk/canu-1.0/Linux-amd64/bin/lib/canu/Defaults.pm line 45.
Compilation failed in require at canu-1.0/Linux-amd64/bin/canu line 48.
BEGIN failed--compilation aborted at canu-1.0/Linux-amd64/bin/canu line 48.
```
The module does exist in your tar ball (In /module/apps/canu/1.0/Linux-amd64/bin/lib/canu/lib/perl5/x86_64-linux-thread-multi-ld/Filesys/Df.pm and /module/apps/canu/1.0/Linux-amd64/bin/lib/canu/lib64/perl5/5.8.8/x86_64-linux-thread-multi/Filesys/Df.pm ), but those directories don't seem to be added to @INC upon execution. Now if I modify the $PERL5LIB to hold those 2 dirs, I get the error:

`perl: symbol lookup error: /root/mydisk/canu-1.0/Linux-amd64/bin/lib/canu/lib64/perl5/5.8.8/x86_64-linux-thread-multi/auto/Filesys/Df/Df.so: undefined symbol: Perl_Tstack_sp_ptr
`

Do I really need to install the module via cpan -i? It works, but I'm trying to allow the use of Canu in VMs created on the fly, and having to set up the cpan environment every time (or even once and for all) feels somewhat overkill.

Thanks for your help
Em

**Comment by skoren** [comment]
I think this is a perl version issue. Your perl version doesn't match our perl version and so the Df.pm file and module is not in the expected path. Your best bet would be to try compiling from source rather than using the binary. It should have the Df package as part of the source and install what it needs when you compile.

**Comment by e-sevin** [comment]
Compilation did produce the binaries (quite a few warnings though), which I'm testing at the moment. Thanks for your input, thanks for the tool!

**Comment by colindaven** [comment]
Another alternative if using the binaries on Ubuntu 14.04, not installing from source:

sudo cpanm Filesys/Df.pm

Might be useful to add to the docs

**Comment by clementfkent** [comment]
Thanks to colindaven! I'm on Ubuntu 15.04 and was getting e-sevin's error. Installing cpanminus and then
sudo cpanm Filesys/Df.pm
solved the problem with the binaries, no compilation from source done.

**Comment by bibilujan** [comment]
Hi!
I am getting the same error... I tried downloading and installing the module but I still get errors during the installation. Do you know of any fix without sudo? I dont have sudo rights on the computer cluster.

**Comment by skoren** [comment]
The module is included in the Canu source so if you build from source it will automatically be included.

**Comment by mav1234** [comment]
Hello,

I built from source using make instructions on the Release page but still receive the error:

Can't locate Filesys/Df.pm in @INC (you may need to install the Filesys::Df module) (@INC contains: /mnt/c/Users/John/Documents/genome/canu-1.3/Linux-amd64/bin/lib/canu/lib64/perl5 /mnt/c/Users/John/Documents/genome/canu-1.3/Linux-amd64/bin/lib/canu/lib/perl5 /mnt/c/Users/John/Documents/genome/canu-1.3/Linux-amd64/bin/lib /home/mav1234/perl5/lib/perl5/5.18.2/x86_64-linux-gnu-thread-multi /home/mav1234/perl5/lib/perl5/5.18.2 /home/mav1234/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/mav1234/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /home/mav1234/perl5/lib/perl5/5.18.1 /usr/local/lib/site_perl .) at /mnt/c/Users/John/Documents/genome/canu-1.3/Linux-amd64/bin/lib/canu/Defaults.pm line 50.
BEGIN failed--compilation aborted at /mnt/c/Users/John/Documents/genome/canu-1.3/Linux-amd64/bin/lib/canu/Defaults.pm line 50.

I did try using the binaries, which resulted in this error:
tar: canu-1.3/Linux-amd64/bin/lib/canu/share/man/man3/File\:\:Path.3pm: Cannot open: Invalid argument
tar: canu-1.3/Linux-amd64/bin/lib/canu/share/man/man3/Filesys\:\:Df.3pm: Cannot open: Invalid argument
tar: Exiting with failure status due to previous errors

But the contents did appear to be extracted and there was a Filesys directory created with Df.pm; however it is not in the INC, so I copied the Filesys directory into canu-1.3/Linux-amd64/bin/lib/canu/lib/perl5 and the error message changed to 

Can't locate loadable object for module Filesys::Df in @INC (with the same above afterwards).

Note I am running Ubuntu Bash in Windows (https://msdn.microsoft.com/en-us/commandline/wsl/about), and am a novice user, so of course it is possible that 1) I made a very dumb mistake (other than using Windows ;) ), 2) the issue lies with Ubuntu on Windows
