### ISSUE TITLE
how to wait for canu in grid to finish?

### ISSUE THREAD

**Issue by wangyugui** [marbl/canu#471]
Hi.

When I run canu in SGE grid,  the canu process will exit after qsub to SGE.
And the 'qstat' result is changing when running, so the option 'qsub -sync y[es]|n[o]' can not be used?

How to wait for canu in grid to finish in a script? We need to start other jobs after canu is finished.

**Comment by brianwalenz** [comment]
Look at options `onSuccess` and `onFailure`.  http://canu.readthedocs.io/en/latest/parameter-reference.html#global-options

**Comment by wangyugui** [comment]
Thanks a lot.

**Comment by mchaisso** [comment]
Finally came across this while setting up canu in a snakefile. Now that assembly is super robust (great work!!), I can foresee this working it's way into more pipelines, and having the canu call wait until the entire process terminates will be useful. For now I'll have onSuccess/onFailure write a checkpoint file that is looked for in a sleep loop.

**Comment by lucyintheskyzzz** [comment]
Sorry I am not that great at coding. How can I update my bash script to include the onSuccess/onFailure? I am trying to run all my barcodes so that after barcode01 completes the other one starts etc. 

#!/bin/bash

# Source directory containing barcode files
source_dir="/lustre/project/taw/kvigil/ONR/sandiago/mussel/ONR122123.121923.combined/fastq_pass/concatenate"

# Destination directory for Canu results
canu_output_dir="/lustre/project/taw/kvigil/ONR/sandiago/mussel/ONR122123.121923.combined/fastq_pass/concatenate/canu"

# Log file
log_file="$canu_output_dir/canu_log.txt"

# Function to log messages
log() {
    echo "$(date +'%Y-%m-%d %H:%M:%S') - $1" >> "$log_file"
}

# Create log file
echo "Canu processing started." > "$log_file"

# Load the required module
module load anaconda3/2020.07

# Activate the Conda environment
source activate ONRviral

# Change to the destination directory
cd "$canu_output_dir"

# Iterate through all files in the concatenate directory
for fastq_file in "$source_dir"/*.fastq.gz; do
    if [ -e "$fastq_file" ]; then
        # Extract barcode from file name
        barcode=$(basename "$fastq_file" | grep -oP "barcode\d+")

        # Create output directory for the current barcode
        output_dir="$canu_output_dir/$barcode"
        mkdir -p "$output_dir"

        # Run Canu for the current barcode
        log "Running Canu for $barcode"
        canu genomeSize=2m maxinputCoverage=10000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=3 -p "$barcode" -d "$output_dir" -nanopore "$fastq_file"
    else
        log "Error: Fastq file not found."
    fi
done

**Comment by skoren** [comment]
See the Canu regression repo: https://github.com/marbl/canu-regression/blob/master/recipes/ecoli-hifi-1/submit.sh for some examples.

**Comment by lucyintheskyzzz** [comment]
Would I just write:

canu genomeSize=2m maxinputCoverage=10000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=3 -p "$barcode" -d "$output_dir" onSuccess=unset onFailure=unset -nanopore "$fastq_file"
