### ISSUE TITLE
Visualizing contig providence from contributing reads.

### ISSUE THREAD

**Issue by mdkeehan** [marbl/canu#474]
Hello, 
Canu is wonderful.

We are investigating a gene on the Bovine Y chromosome and are currently focussing on a single contig from a 60x pacbio assembly.

The contig is a repeat and we would like to see the evidence for the contig i.e. the graph layout for the reads that contribute to the contig as we would like to understand the repeat structure so we can design primers for it.

Is there a recommended way, file to examine or a handy command to say generate a nice  plot
so we can understand the contig ?

This is probably a feature request but just a comment pointing me at the right files would be helpful and might also be useful to others. 

Thanks
Mike

**Comment by brianwalenz** [comment]
Awesome question.

You can use the `layout` files in the output to figure out which reads are contained in the contig.  These are created with the `tgStoreDump` command operating on either ctgStore or utgStore.  With a read ID, the ovStoreDump command will show read-to-read overlaps.  Both have reasonable command line help.

In the unitigging/4-unitigger/ directory (where the 'assembly' part is run) are some more detailed GFA outputs, showing read level structure.  `asm.best.edges.gfa` shows only the best overlaps for each read.  This forms the backbone of the assembly.

The other two GFA's, asm.initial.assembly.gfa and asm.final.assembly.gfa, show _ALL_ overlaps used in constructing contigs, even the non-best and containment relationships.  'initial' is before any overlap filtering occurs, 'final' is after filtering.  The filtering removes overlaps/reads that look like they are biologically incorrect or to bogus reads.  These two are probably not terribly useful for an initial exploration.

Note that the three GFA's do _NOT_ have correct CIGAR strings; the CIGAR is showing just the length of the overlap, not the actual alignment.

Starting with your contig ID, you can use the layout files to find the list of reads in the contig, then filter best.edges.gfa to include only those reads (maybe adding in reads a few hops away).

The same type of processing using unitigs instead of reads.  If the repeat is worth its name though, the unitigs will be not much better than the reads.  It will, at least, be easy to tell when you've come out of the repeat into unique sequence - perhaps useful to generate a graph of all the repeat elements, but this could end up being just an enormous tangle.  The unitig <-> contig association isn't readily available, as it is buried in a log file.

**Comment by fmdom** [comment]
Hi all,
I think there is a possible feature request in this thread:
First, I would like to know what are the specifications of the .layout, .gfa, or .readtotig files ? Are they wig format? If not, could they be easily converted?
The typical next step following de novo assembly (+ qc) is gene annotation and curation. It would be nice to be able to use the information contained in the layout file in genome browsers like Jbrowse and Apollo.

**Comment by skoren** [comment]
The gfa file follows the (https://github.com/GFA-spec/GFA-spec)[GFA] spec so it should be parseable by any tool that reads this format, like (https://rrwick.github.io/Bandage/)[Bandage] for example. 

The layout.tigInfo and layout.readToTig are both tab-delimited and provide a header line to define their columns. I don't think converting them to wig format makes sense since they are showing pileups of reads (readToTig) or tig statistics (tigInfo), neither of which are a 'track'. The readToTig could be converted to a coverage track wig format but it probably makes more sense to convert the readToTig file to a bam output so it could be loaded by IGV or similar tools which we plan to do at some point in the future.
