### ISSUE TITLE
Standardize output of --version 

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#481]
```
# current

% canu --version
Canu release v1.5

# preferred standard

% canu --version
canu 1.5
```

**Comment by skoren** [comment]
We want to distinguish the releases from the unreleased code that people pull of github (versioned by commit). How about
```
canu 1.5
```
vs 
```
canu unreleased 1.5+12 edits (commit XX).
```

**Comment by tseemann** [comment]
It's not parseable by a generic `-v` `-version` `--version` loop attempt.

Maybe `canu 1.5+12-ffffff`  where ffff is your commit?

**Comment by skoren** [comment]
We had that before and users were treating it as version 1.5, ignoring the trailing stuff so I want to clearly indicate it is not a release. 

I'll argue 99% of uses of the version command are by a person and not a parsing script so it's not worth making it confusing for a human to make it understandable by a computer. Also, automated parsing should fail on an un-versioned release (it has no version essentially) so as long as that fails gracefully and returns unknown or unversioned, that is OK. We will update the release version to be parseable.

**Comment by brianwalenz** [comment]
For releases, this is fixed.
```
../Linux-amd64/bin/gatekeeperCreate --version
Canu 1.5
```
You can simulate a release by building without a .git directory.  If it's built in directory 'canu-X.Y/src', the version is set the X.Y, otherwise, it defaults to hardcoded values in canu_version_update.pl which are updated just before a release is built.

For git clones, I'm leaving this as is.
