### ISSUE TITLE
alignGFA stage failing 

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#485]
I am testing canu using ecoli and it is failing on our PBSpro cluster doing the alignGFA. The error in canu.out is;
```
    cd unitigging/4-unitigger
    ./alignGFA.sh
GFA alignments failed.
```
buildtest.contigs.aligned.gfa.err gontains the following;
```
-- Opening tigStore '../buildtest.ctgStore' version 2.
tgStore::loadMASR()-- Failed to find any tigs in store '../buildtest.ctgStore'.
```

The store exists and when I go to unitigging/4-unitigger and run ./alignGFA.sh manually it completes 'GFA alignments updated.' Running canu again lets it continue to completion.

Any idea why it should be failing every time at the same point? I am also including alignGFA.sh for reference;
```
#!/bin/sh

syst=`uname -s`
arch=`uname -m`
name=`uname -n`

if [ "$arch" = "x86_64" ] ; then
  arch="amd64"
fi
if [ "$arch" = "Power Macintosh" ] ; then
  arch="ppc"
fi

bin="/pkg/suse12/software2/ctcb/canu/1.5.20170418/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/pkg/suse12/software2/ctcb/canu/1.5.20170418"
fi


if [ z$PBS_O_WORKDIR != z ] ; then
  cd $PBS_O_WORKDIR
fi

#  File must exist: seqDB.v001.dat
#  File must exist: seqDB.v001.tig

#  File must exist: seqDB.v002.dat
#  File must exist: seqDB.v002.tig

#  File must exist: seqDB.v001.dat
#  File must exist: seqDB.v001.tig

#  File must exist: seqDB.v002.dat
#  File must exist: seqDB.v002.tig


if [ ! -e ./buildtest.unitigs.aligned.gfa ] ; then
  $bin/alignGFA \
    -T ../buildtest.utgStore 2 \
    -i ./buildtest.unitigs.gfa \
    -o ./buildtest.unitigs.aligned.gfa \
    -t 1 \
  > ./buildtest.unitigs.aligned.gfa.err 2>&1
#  File is important: buildtest.unitigs.aligned.gfa
fi


if [ ! -e ./buildtest.contigs.aligned.gfa ] ; then
  $bin/alignGFA \
    -T ../buildtest.ctgStore 2 \
    -i ./buildtest.contigs.gfa \
    -o ./buildtest.contigs.aligned.gfa \
    -t 1 \
  > ./buildtest.contigs.aligned.gfa.err 2>&1
#  File is important: buildtest.contigs.aligned.gfa
fi


if [ -e ./buildtest.unitigs.aligned.gfa -a \
     -e ./buildtest.contigs.aligned.gfa ] ; then
  echo GFA alignments updated.
  exit 0
else
  echo GFA alignments failed.
  exit 1
fi
```

**Comment by hodgett** [comment]
A little more info; the file buildtest.contigs.aligned.gfa.err is in the same folder as canu.sh (root folder) and not in unitigging/4-unitigger where I would expect it and the *_alignGFA log files are showing the current work directory as being the parent, so it appears the cd to unitigging/4-unitigger for PBSpro is not working in this one case.

**Comment by brianwalenz** [comment]
Cute, but fixed.

Details you probably won't care about:  I made an optimization to not run this as an individual grid job for small genomes.  When running jobs, Canu first cd's to the subdirectory (4-unitigger here) then runs the command.  However, for PBS, the command script has boilerplate to 'cd' to wherever the PBS job was submitted from - because these scripts are usually run as standalone grid jobs.  So, when the script ran, it went back to the top-level assembly directory (where 'canu' runs from), then tried to run the command.

Obviously not tested under PBS, so close if it works.  The cutoff between 'small' and 'big' is hardcoded to 400Mbp.  If you lower that to, say, 1bp, you can test running the alignGFA as a grid job too.

**Comment by hodgett** [comment]
Ok, the ecoli worked just fine. I'm running a larger sample set now before I let loose on our complete sequence
