### ISSUE TITLE
Assembling novel 780 MB genome, CANU aborted

### ISSUE THREAD

**Issue by csgasser** [marbl/canu#497]
[canu.16.out.txt](https://github.com/marbl/canu/files/998916/canu.16.out.txt)
I am trying to assemble a novel 780 MB genome from PacBio reads (a combination of RSII and Sequel reads catenated into one .fq file).

Running CANU 1.5  on a small cluster under slum

My .sh file is:
#!/bin/bash -l

#SBATCH -J AsCanuDefMay
#SBATCH -o AsCanuDefMay.output
#SBATCH -e AsCanuDefMay.error
#SBATCH --mail-type=END
#SBATCH --mail-user=csgasser@ucdavis.edu

module load java
module load canu
canu \
 -p AsCanu15May -d AsCanu15May-auto \
 genomeSize=780.0m \
 -pacbio-raw maypacbiotot.fq

It runs for about 36 hours and gets up to generating the file "canu.16.out" then ends, with an error message in this .out file.  I attach canu.16.out.txt.  This file has the error message at the end.

I hope that someone can tell me what to do to make the process continue.  Also, if I am provided with a way to get this to continue, do I have to start again, or can I jump in at the point where it stopped and continue.  I can do it either way.

Another question:  It turns out that the Sequel runs don't include useable quality data in the output (every base has a quality score of "!").  But the RSII sequences do have useable qualities.  Will this affect assembly from a combination of the two kinds of runs.  I am surprised at how much of my data is discarded.  I input about 37 X coverage and by the time it has reached the fail point it appears to be using just over 20X coverage of the data.  But my data my be poor because it is hard to get good DNA out of this plant.

Thanks for any info you can provide,
Chuck Gasser

**Comment by skoren** [comment]
It looks like Canu failed to submit the bogart step command. This typically has the highest memory usage so my guess is it tried to request a machine in a different partition than the default. Based on the Canu preamble it looks like you have two types of machines:
```
-- Found   2 hosts with  64 cores and  500 GB memory under Slurm control.
-- Found  15 hosts with  24 cores and   62 GB memory under Slurm control.
```
Do the 2 hosts with 500gb ram require a special partition/parameters to run on? You can edit ```/group/gasserlab/annona/pacbio/wgcanu/AsCanu15May-auto/unitigging/4-unitigger/unitigger.jobSubmit.sh``` to add the required fields to allow it to run on the 500gb machines. Alternatively, you can decrease the memory request so it fits on the 62gb systems. Once it is edited you can run that script, wait for the job to complete, and then re-run the original Canu command from ```/group/gasserlab/annona/pacbio/wgcanu``` which will resume the run.

As for discarding data, you can try the low-coverage parameters ```corMhapSensitivity=high corMinCoverage=0```. However, since this run is almost done, I would finish this one to see what kind of assembly you get and you can try the above parameters in another run.

**Comment by csgasser** [comment]
This sounds great.  I see that the file you direct me to is as follows:
#!/bin/sh

sbatch \
  --mem-per-cpu=3968m --cpus-per-task=16 -o unitigger.%A_%a.out \
  -D `pwd` -J "bat_AsCanu15May" \
  -a 1-1 \
  ./unitigger.sh 0 \
> ./unitigger.jobSubmit.out 2>&1


When I submit batch jobs to our cluster, I do have to specify "bigmemh" as the host to use the higher memory machines.  So I will add that to the first line in this file.

From my reading of your suggestion, I can then just rerun my original submission job and CANU will skip all the steps it has already done and go right to submitting that job.  Is that correct?  It will recognize that work has been done and will jump to the correct step?

**Comment by csgasser** [comment]
Oh I misread!  I have to run the script directly first.  Now I am doing that and it is running on our bigmem machine.

That worked!  It finshed the unitigging job and I restarted CANU and it is now spawning  "cns" jobs on my server.  Thanks a lot for the help!

Chuck

**Comment by brianwalenz** [comment]
You can set gridOptionsBAT to the magic needed to run these jobs, and canu will include these parameters in the submission command for just this job.

http://canu.readthedocs.io/en/latest/parameter-reference.html#grid-options
