### ISSUE TITLE
20x pacbio + 2x ultra-long nanopore?

### ISSUE THREAD

**Issue by dvera** [marbl/canu#498]
Sorry in advance if this is not the appropriate place to ask a question, let me know if I should post this elsewhere.

Can canu effectively use low-coverage ultra-long nanopore data (2x) with moderate-coverage pacbio data (20x)? Does correction occur on the individual data sets or in combination?

**Comment by skoren** [comment]
Canu will correct both datasets together. However, it's unlikely 2x will help very much since the chance of having a read land in the right place on the genome is low (it has to be before a repeat but close enough to span the repeat). In the GM12878 project, adding 5x of ultra-long reads did increase the NG50 about 2-fold but that's double the coverage you have. Definitely run with the low coverage parameters (```corMhapSensitivity=high corMinCoverage=0```)

**Comment by dvera** [comment]
Great, thanks.
