### ISSUE TITLE
Removing Vector/Cosmid/Fosmid Backbones During Trimming

### ISSUE THREAD

**Issue by zachcp** [marbl/canu#540]
Hi Team Canu,

Thank you for your excellent software.  I was hoping to get your advice on the removal of cosmid/fosmid vector sequences from long-read genome assemblies where the genome is sequenced from pool of cosmid/fosmid clones.  Most vector removal tools cater to short reads and I wonder if you have some advice on vector-removal from long sequences;  perhaps there is already a way to filter/trim sequences during the trim phase of canu that I am unaware of.

Thank You,
zach cp

**Comment by skoren** [comment]
Canu won't trim the vector because it will be valid sequence confirmed by multiple sequencing reads. Typically when we assemble BAC clones, the vector ends up somewhere in the middle of the contig (since the BAC is circular the assembly will start at an arbitrary point) and you can use this to rotate/trim the contig to the origin to start at the vector. You would then end up with a contig per fosmid. If you are trying to assemble the fosmids together and remove vector, you could try to try pore chop: https://github.com/rrwick/Porechop. It is designed for adapters but could probably be modified to identify vectors though we haven't tried it.

**Comment by zachcp** [comment]
thank you @skoren - Porechop looks like a great tool that may be perfect for my needs.

**Comment by zachcp** [comment]
FYI, I ended up using Blasr to identify vector  sequences and removed them before assembly.
