### ISSUE TITLE
Overlap Bucketizing Error

### ISSUE THREAD

**Issue by RyanBio** [marbl/canu#543]
Hi,
Canu returned a failure when bucketizing the overlaps.The 1-bucketize.000152.out is:
```
Running job 152 based on command line options.
Removing incomplete bucket create0152
Changed max processes per user from 1024 to 6204211 (max 6204211).

Changed max open files from 1024 to 4096 (max 4096).

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/001/000152.ovb
Overlap has IDs out of range (maxID 1926921), possibly corrupt input data.
  coords --          0          0  N       0       0      0       0      0  0.000000
  hangs  --          0          0  N       0      0      0  0.000000
Failure.
```
My canu version is:
```
Canu snapshot v1.5
```
The error overlap IDs out of range seems special. There are total 156 bucketize jobs, all succeded expect the 152. Any helps for this?

Thanks!

**Comment by skoren** [comment]
This looks like disk corruption or an error in the previous step. Is this the correction step of the pipeline? Can you post the output of the precompute and mhap outputs if so. What is the full Canu version you are using, it should specify the commit it is on if it is a snapshot and not a release.

**Comment by RyanBio** [comment]
Hi, Sergey
Thanks for your reply.
My Canu is from the release. I had different projects. One returned a failure when the pipeline step was trimming and another returned a failure when the pipeline step was unitigging.

**Comment by skoren** [comment]
The reason I was asking about the full version is because Canu releases report version like this:
```Canu release v1.5```
while code checked out from github reports like this:
```Canu snapshot v1.5 +115 changes (r8315 738e6cbb6b5e7aa4803322bde157143d66d89c12)
```
So if it reporting snapshot in the name, it's not a release but a checkout of the repository code. There have been a lot of changes to part of the assembler recently which could have caused your error in unitigging (see issue #546). However, the above error is probably not related to the changes but more likely a disk issue. Do you have the output from the previous step (```1-overlapper/overlap.*.out```) since I presume this is failing in the trimming stage?

**Comment by RyanBio** [comment]
Hi Sergey,
The reason of Canu version is "Canu snapshot v1.5" maybe I downloaded the release version through git clone. 
The previous step overlap.000152.out looks like successful. 
[1-bucketize.000152.out.txt](https://github.com/marbl/canu/files/1134247/1-bucketize.000152.out.txt)
[overlap.000152.out.txt](https://github.com/marbl/canu/files/1134248/overlap.000152.out.txt)

And i will download the lastest version and rerun.

**Comment by brianwalenz** [comment]
Any update?
