### ISSUE TITLE
About genomeSize and heterozygosity parameters

### ISSUE THREAD

**Issue by uceleste** [marbl/canu#558]
Dear All,

I'm going to do my first test with canu and I have a couple of questions:
1) I'm going to assemble a diploid plant genome of about 400Mb. My question is about the parameter "genomeSize" in the command line. Canu is expecting the diploid size (400M) or the haploid size (200M)?
2) I know that the genome of this species is quite heterozygous, so I think I will use the parameters indicated for "Smash haplotypes together". I know that an high level of heterozygosity "decreases" the effective level of coverage available for the assembly. Considering that I own about 70x of PacBio reads (which in the worst cases will become 35x because of heterozygosity), is it reasonable to add the parameters "CorMinCoverage=0" and "corMhapSensitivity=high"?

Best regards

**Comment by skoren** [comment]
I typically set the genome size to the haploid size and increase the corOutCoverage (which is listed on the recommended parameters). One caveat with the smash parameters is that some difference will not be smashed even with this setting. Typically large structural variants, like inversions, will still end up uncollapsed because there is no good way to represent a "consensus" for them. Smaller variants will get folded together.

It should be fine to run with corMinCoverage=0 corMhapSensitivity=high, that is it won't hurt assembly but it will increase runtime and disk usage so maybe start with the defaults parameters for smash haplotypes together and see how the assembly looks before running the sensitive parameters.

**Comment by uceleste** [comment]
Dear Sergey, thank you so much for your answer and explanations. I will do some tests following your advice!
