### ISSUE TITLE
mhap correction time of large genomes

### ISSUE THREAD

**Issue by albodrug** [marbl/canu#56]
Hi everyone,

I'm assembling a large genome of 1.5Gb with canu. While the assembly part works fine if I feed it corrected data, the -correct portion is slow, slow, slow. 
I want to run in on a sigle machine of 1TB with 22 cores. My question is to know how to best optimise the memory, threads and concurrency. The data is a coverage of ~55x, so a ~150Gb fastq file of raw pacbio. 

So far I have tried:
1) - high memory: This results in over 150 precompute jobs and over 300 mhap jobs

2) - high memory: corMemory=900, cormhapMemory=900
- max threads: corThreads=22, cormhapThreads=22
- low concurrency: corConcurrency=4, cormhapConcurrency=4

3) Same as previous but with concurrencies at 16:
Both result in a 6 precompute jobs that are relatively fast (~ 24h) and 10 mhap jobs that are too long. My mhap job looks like this, and is stuck at first 1/10 of the reads since 2 days:
`
java -server -Xmx900g -jar /software/canu/canu-1.0.local/Linux-amd64/bin/mhap-1.5b1.jar --weighted -k 16 --num-hashes 512 --num-min-matches 3 --threshold 0.04 --filter-threshold 0.000005 --min-store-length 10611 --num-threads 22 -f /project/project1/abodrug/assembly_canu/refQ2-correction3/correction/0-mercounts/refQ2-raw.ms16.frequentMers.ignore -s /project/project1/abodrug/assembly_canu/refQ2-correction3/correction/1-overlapper/blocks/000001.dat -q /project/project1/abodrug/assembly_canu/refQ2-correction3/correction/1-overlapper/queries/000001`

My latest canu command looks like this:
`/software/BIN/canu -correct -p refQ2-raw -d refQ2-correction3 genomeSize=1.45g -pacbio-raw /project/project1/abodrug/pacbio_template_filtered_nopal_size35.fastq useGrid=0 minThreads=22 maxThreads=22 corConcurrency=16 corMemory=900 corThreads=22 cormhapConcurrency=16 cormhapMemory=900 cormhapThreads=22 corovlConcurrency=16 corovlMemory=900 corovlThreads=22 merylThreads=22 merylMemory=900 merylConcurrency=1`

Is there anything else I could do to speed up the precompute and mhap steps of canu on a single machine?

Would using a grid engine be in any way faster if my settings are actually similar to the single machine ones (gridOptionscor, gridOptionscormhap, gridOptionscorovl)?

Thanks, 
Alex

**Comment by rafalwoycicki** [comment]
Hi Alex,

I am not 100% sure, I think the problem is that the Memory/Threads/Concurrency settings you wrote above are trying to take more resources that you have - mostly memory. Have you seen any swapping? (cause the algorithm wants to use 900 GB* 4 (Concurrency) or 900GB * 16 (Concurrency) and it can not get it ).
The memory parameter should be Available Memory / Concurrency and Threads should be No. of threads Available / Concurrency. So for example for 5 Concurrency, Memory would be set to 180 GB and Threads to 4.
It is working on my single machine like that, can someone check if I am right?

Hope it helped.
Rafal

**Comment by brianwalenz** [comment]
The defaults -- leaving out all memory/threads/concurrency options -- should configure to max out the machine.  We've tried to limit job sizes based on genome size, and it's possible a 1.5 Gbp genome is being limited too much.

Agree with Rafal.  The way it's set up, it is trying to run 16 jobs, each wanting 900 GB.

Kill what's running, remove the 1-overlapper directory (nothing can be salvaged, unfortunately) and restart with defaults.  Post back with the canu configuration used if problems persist.

Finally, depending on grid size, YES!  Much faster.  The assembly portion, bogart module, will benefit from large memory; everything else should be comfortable on grid size machines.  Canu will auto configure for the grid, too.

**Comment by albodrug** [comment]
@ Rafal: I do not have memory issues however when setting concurrency and memory so high. Maybe it doesn't reach the step where it should be problematic, but I've had no warning so far. Thanks a lot for the precision! 

@brianwalenz Restarting with default gives me 366 mhap jobs to be executed in the /1-overlapper/partitioning.log. I have such a correction running since the 18th of February and it reached the mhap.2130947_313th overlapping today. Knowing that overlapInCore is to follow...

Before canu, PBcR was used for the 3Gb human genome, so twice what I'm trying to assemble, with similar coverage. But it was on a grid engine, so that might explain the differences in correction time for me.

**Comment by rafalwoycicki** [comment]
Hi Alex, so yes, its probably not reaching the limit - thats good :-) 
I actually had to play yestarday a bit with cormhap settings for my 24 cores and 64GB single machine (tomorrow 96GB it will be), and finally the setting with allowing 20GB per one concurrency when using 6 concurrent jobs gave me usage of 90% of memory (normally would be would be 200% of memory), cause setting 10GB per one job was ending in utilizing just 45% of memory instead of about 90% - 60GB, so not to efficient. I guess it depends on the overlaps parameters also.

**Comment by skoren** [comment]
@albodrug which version of MHAP/Canu are you using? The latest tip has mhap 2.0 which is faster. It's not surprising that the first step (precompute) is much faster than the mhap step, the precompute step just builds the index. The latest version also has a corMhapSensitivity=fast option which will speed up the correction faster. 

However, the main issue is your machine only has 22 cores which isn't sufficient for large genomes. For context, the fastest human overlapping with MHAP is on the order of 3-5k cpu hours (using the fast option, depending on hardware/IO) which would be 6-10 days on your machine and the default would likely be 10-20 days. That seems to match up with your times above since you finished 313/366 correction overlap jobs in about that time.

**Comment by albodrug** [comment]
@skoren Would using a 32 core machine with half the memory be better? 
Thanks for providing some context with the human overlapping. Somehow I understood from the mhap paper that it would be much faster.

I'm using mhap-1.5b1, installed along with the Canu v1.0.  I'll get the 2.0 and give corMhapSensitivity=fast a try then!

**Comment by albodrug** [comment]
@skoren I can't find the mhap 2.0 release, I can only find up to 1.6 in https://github.com/marbl/MHAP/releases/ . Is it somewhere else?

**Comment by skoren** [comment]
It has not been officially released since we're testing it but is included in the Canu repository if you get the latest from master rather than the 1.0 release. Both the next version of Canu (1.1) and MHAP (2.0) should be released soon.
