### ISSUE TITLE
Help with corOutCoverage parameter

### ISSUE THREAD

**Issue by jhtrujillo** [marbl/canu#561]
Hello, I am trying to assemble a polyploid genome/aneoploid, but the assembly results have not been good. The monoploid genome has an approximate size of 1 G and we have 100 Gbp of PacBio. The problem is in the part of the correction that generates very few corrected data. I think the problem is with this parameter: corOutCoverage. Could you see a pipeline explaining how this parameter works?

Thanks!

**Comment by brianwalenz** [comment]
corOutCoverage is controlling how many reads are corrected.  By default, we only correct the longest reads, up to 40x of coverage.  We've observed that correcting and assembling more than this doesn't improve the assembly because these are generally short reads.

How much data is being generated in corrected reads?  If it's around 30x, you can just increase corOutCoverage (and remove the 2-correction directory and correctedReads.fasta.gz and correctedReads.length files, then restart canu) to make some more.

What's your cull canu command?

What's the read length histogram reported?  (just paste in the *.report file, which has some other info about the correction process).

Read through the FAQ http://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads.  As mentioned there (but buried) `corMhapSensitivity=normal` could help, but you need to recompute overlaps.



`corMhapSensitivity=normal` might help, but you need to rerun overlaps.

**Comment by skoren** [comment]
Closing, inactivity. If you have any more questions or encounter an issue with your run, please open a new issue.
