### ISSUE TITLE
What is the best compromise between high coverage and long sequences?

### ISSUE THREAD

**Issue by uceleste** [marbl/canu#567]
Dear All

I know that Canu by default filters the sequences according to their length, discarding the sequences shorter than 1000 bases. Additionally, it allows filtering the sequences based on user-defined length.

Consider a high-coverage PacBio or Nanopore dataset, e.g. 100x, consisting of sequences with a length higher than 1000 bases. Could it be useful to sacrifice some coverage removing a greater number of short sequences? For example, discard the sequences shorter than 5000 bases or more. Would the assembly have a significant qualitative improvement or not?

I know that there are too many factors for a precise answer (e.g. genome size, complexity and percentage of repeated sequences, heterozygosity, etc.), but I would like to know yours opinion!

**Comment by skoren** [comment]
The correction will already choose the longest 40x of data to run the downstream assembly. The issue with just selecting reads longer than some length is you may be including more chimeric/noise reads and losing overall coverage (since a long read isn't necessarily a correct reads). Using the overlaps during correction Canu estimates the post-correction/trimming read length and uses that to inform the selection. Increasing this from the default of 40 makes sense in a heterozygous genome so you don't end up with <20x in some heterozygous regions (assuming diploid).

**Comment by uceleste** [comment]
Clear! Thanks for the explanation, Sergey.

**Comment by johnomics** [comment]
Sorry to reopen this, but I have a follow-up question. We have been quality filtering our nanopore reads before running canu, assuming that this would prevent the low quality, high GC long noise reads from being part of the 40x coverage. But is this filtering not necessary? Can we trust the correction step to filter them out based on lack of overlaps?

**Comment by aphillippy** [comment]
Hey John,
Yes, the correction step uses all-pairs overlaps to estimate the longest 40x of "correctable" reads. So junk reads should be excluded from this calculation. I'd just give it everything.

**Comment by johnomics** [comment]
Excellent, thank you very much!
