### ISSUE TITLE
The step of gfa for unitigging is very very long time!

### ISSUE THREAD

**Issue by RobertoRun** [marbl/canu#568]
Canu is a very nice assembler. I have used it to de novo assemble four genomes. But, when i go to the fifth genome, the step of gfa for unitigging (unitigging/4-unitigger) is very very long time (more than 4 days)!  But, it's still not finished, there file is also no any update (St.unitigs.aligned.bed.err).  Do you think it's regular or not? What i can do in the next if it's failure? Thanks!

-- Reading BED './St.unitigs.bed'.
bed:  Loaded 770 records.
-- Loading sequences from tigStore '../St.utgStore' version 2.
-- Loading sequences from tigStore '../St.ctgStore' version 2.
-- Aligning 770 records using 4 threads.

**Comment by brianwalenz** [comment]
This was fixed in the past week or so.

For this assembly, copy `unitigging/4-unitigger/St.unitigs.bed` to `unitigging/4-unitigger/St.unitigs.aligned.bed` and restart.  The positions in the bed file won't be quite correct.  While you're there, create an empty file `St.unitigs.aligned.bed.gfa` which I keep forgetting to remove.  The restart will go immediately to writing outputs and then you're done.

For later assemblies, update to the 'unstable' version, then v1.6 when it comes out.

**Comment by RobertoRun** [comment]
Thank you so much! I have fixed it and got the results! After failed many times with v1.5, I have updated to the version of July 20th, 2017. 

I will try the latest version (July 28th, 2017) to do assemble in the future!
