### ISSUE TITLE
Corrected reads are missing parts of the genome 

### ISSUE THREAD

**Issue by chklopp** [marbl/canu#569]
Hi,

I'm assembling a fungal genome with CANU 1.5.
I've both PacBio (30x) and ONT(80x) reads and performed both assemblies independently. 
The ONT assembly lacks 20% of the PacBio assembly.
But the corresponding ONT raw reads (covering the missing parts) are present.
The missing parts seem to be partially related to repeats

Here is a plot made by aligning the raw and corrected reads on the PacBio reference genome. The plot presents also the repeat content of the genome produced by RepeatModeler and RepeatMasker (50 = 100% of repeats in the area).

![image](https://user-images.githubusercontent.com/4004727/28705419-f54a2948-736f-11e7-99f0-7f27136c9942.png)

Which parameter should I tweack not to lose these reads?

**Comment by skoren** [comment]
I don't think this is due to the repeats but due to a difference in the read qualities. There is probably some motif causing base calling issues and increasing the local error rate in the nanopore data. You can try increasing the mhap sensitivity (```corMhapSensitivity=normal``` or ```corMhapSensitivity=high```). Additionally, you could try ```corMinCoverage=0``` but I'd start with the sensitivity first and see how it works.

**Comment by chklopp** [comment]
I've launched both corMhapSensitivity tests.


Thank you.


Christophe KLOPP
MIAT   INRA Toulouse
CS 52627
31326 Castanet-Tolosan
Tel: 33 5 61 28 50 36
Email: christophe.klopp@toulouse.inra.fr
http://www.sigenae.org/
http://bioinfo.genotoul.fr/
________________________________
De : Sergey Koren <notifications@github.com>
Envoyé : vendredi 28 juillet 2017 16:00
À : marbl/canu
Cc : Christophe Klopp; Author
Objet : Re: [marbl/canu] Corrected reads are missing parts of the genome (#569)


I don't think this is due to the repeats but due to a difference in the read qualities. There is probably some motif causing base calling issues and increasing the local error rate in the nanopore data. You can try increasing the mhap sensitivity (corMhapSensitivity=normal or corMhapSensitivity=high). Additionally, you could try corMinCoverage=0 but I'd start with the sensitivity first and see how it works.

-

**Comment by chklopp** [comment]
The total assembly length is a bit worse (21% missing) with the corMhapSensitivity=normal option and has not changed with the corMhapSensitivity=high option.

**Comment by skoren** [comment]
Then I suggest trying the corMinCoverage option as well.

Besides the repeat count, have you checked the k-mer content/difference between the PacBio and Nanopre reads in these regions? The nanopore assemblies are always shorter than the PacBio assemblies due to the systematic deletion bias in the platform. This was especially pronounced if you are using an older base caller (pre Albacore 1.1) which did not attempt to call homopolymers over 5bp.

**Comment by chklopp** [comment]
The genome size is the same with the corMinCoverage=0 option.

**Comment by chklopp** [comment]
I've also tried with both parameters corMhapSensitivity=high and corMinCoverage=0 and still get a genome lacking ~20% of the PacBio assembly size.
The reads have been generated using : ONT Albacore Sequencing Pipeline Software (version 1.1.0)

**Comment by skoren** [comment]
Have you checked the identity of the nanopore read if you align it to the missing regions? Does it align? The last couple of things you could try is multiple rounds of correction (see FAQ) using the corMinCoverage=high and corMhapSensitivity=high parameters and potentially increasing the correctedErrorRate to 0.15 or 0.20 (note this will significantly slow down trimming/unitigging).

**Comment by chklopp** [comment]
The Nanopore raw reads align on the missing parts as shown in the graph here-over.

**Comment by skoren** [comment]
I meant the identity of the nanopore reads, I don't see that in the graph. Canu is able to assemble those regions using PacBio reads so I suspect an issue with the Nanopore base calling there.  It's possible my suggestions above will help recover more of the genome or signal-processing with the raw data (using Nanopolish) can recover parts of it as well. 

If you can share your reads (pacbio + nanopore) we can include them in regression testing since we are planning some changes in read correction in the near future to see if they are improved.

**Comment by chklopp** [comment]
Using the raw read alignments, I've compared the identity of the reads for two regions (GOOD : 600-700 and BAD 150-250) of the graph.

![image](https://user-images.githubusercontent.com/4004727/29872138-99dfe3f2-8d8e-11e7-9905-8dd29006920e.png)

The Nanopore reads (average count = 300 per area and technology) show a 5 points lower identity for the BAD area compared to the GOOD one. Which is not the case for the PacBio reads.
I've also checked the GC content along the contig and do not see significant differences between the regions.

**Comment by skoren** [comment]
Right, that is what I suspected. I expect if you look at the ```corMhapSensitivity=high corMinCoverage=0```, the corrected reads will contain the bad region at lower identity. It is probably being removed by trimming. So doing multiple rounds of correction as I suggested above or increasing the error rate for trimming (you could estimate the error rate for the corMinCoverage=0 reads to inform the setting) should help.

**Comment by skoren** [comment]
Closing, inactive and seems like nothing to change within Canu. Higher error rates within the target region from the sequencing are causing some of the drop which will probably be fixed by improved base calling and/or multiple rounds of correction.
