### ISSUE TITLE
Use minimap2 instead of minimap

### ISSUE THREAD

**Issue by gringer** [marbl/canu#595]
The Canu documentation is ambiguous as to whether minimap is currently implemented as an overlapper.

> Two overlap algorithms are in use. One, mhap, is typically applied to raw uncorrected reads and returns alignment-free overlaps with imprecise extents. The other, the original overlapper algorithm ‘ovl’, returns alignments but is much more expensive.

And yet there are plenty of places where _minimap_ is also mentioned, like in the very next paragraph:

> There are three sets of parameters, one for the ‘mhap’ algorithm, one for the ‘ovl’ algorithm, and one for the ‘minimap’ algorithm.

Now that Heng Li has created [minimap2](https://github.com/lh3/minimap2), and it's _really fast_, is there any chance of replacing the minimap implementation in Canu with minimap2?

And if minimap isn't used currently, I'd recommend removing references to it that exist [in the documentation](http://canu.readthedocs.io/en/latest/parameter-reference.html#overlapper-configuration).

**Comment by aphillippy** [comment]
Hi David,
Canu currently runs three rounds of overlapping: (1) for rough correction/trimming, (2) for a more precise correction/trimming, and (3) for unitigging. It is possible to select a different overlapper for each step. Currently, the default is to run 'mhap' for step 1 and 'ovl' for steps 2 & 3, because this gave the best combination of assembly quality and speed in our tests. 'minimap' was integrated and tested, but is off by default.

Currently, the speed bottleneck (especially for nanopore reads) is the old 'ovl' overlapper used for steps 2 and 3. We have left it enabled by default because it produces the best quality assemblies. Generally, we prefer quality over speed and will swap out an algorithm only if the replacement is better by all metrics. We hope to replace the 'ovl' overlapper in future release v1.8 (https://github.com/marbl/canu/projects/2). The plan was to adapt 'mhap' for this task, but we will also test minimap2 and take whichever produces the better assemblies.

The documentation is forever playing catch-up to the code. Sorry if it was unclear.

**Comment by skoren** [comment]
I'll just add that minimap has been replaced with minimap2 throughout but it didn't show significant assembly improvement over minimap. We're still comparing minimap2 vs mhap as Adam said but right now both are available as options until we converge on one.
