### ISSUE TITLE
 mhap jobs failed because of invalid overlap

### ISSUE THREAD

**Issue by chenyufanxin** [marbl/canu#598]
Hello , I just run canu v1.5 on a slurm grid. After  mhap precompute jobs were finished,  it started to run mhap.jobSubmit.sh. However it failed at this step !  Here is my canu command:
```
canu -p ren -d ~/storage/assemble_canu 
genomeSize=2.93g correctedErrorRate=0.040 corMhapSensitivity="low" 
gnuplotTested=true merylMemory=60  batMemory=60 cnsMemory=60  
-pacbio-raw ~/storage/sandai.fastq.gz
```
Part of my canu.out:
```
-- Run under grid control using   60 GB and  16 CPUs for stage 'meryl'.
-- Run under grid control using   48 GB and  16 CPUs for stage 'mhap (cor)'.
-- Run under grid control using   16 GB and   8 CPUs for stage 'overlapper (obt)'.
-- Run under grid control using   16 GB and   8 CPUs for stage 'overlapper (utg)'.
-- Run under grid control using   15 GB and   4 CPUs for stage 'falcon_sense'.
-- Run under grid control using    3 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run under grid control using   32 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run under grid control using   16 GB and   8 CPUs for stage 'read error detection'.
-- Run under grid control using    4 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run under grid control using   60 GB and  16 CPUs for stage 'bogart'.
-- Run under grid control using   16 GB and  16 CPUs for stage 'GFA alignment and processing'.
-- Run under grid control using   60 GB and   8 CPUs for stage 'consensus'.
--
-- Generating assembly 'ren' in '/home/slurm/storage/assemble_canu'
--
-- Parameters:
--
--  genomeSize        2930000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0400 (  4.00%)
--    utgOvlErrorRate 0.0400 (  4.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0400 (  4.00%)
--    utgErrorRate    0.0400 (  4.00%)
--    cnsErrorRate    0.0400 (  4.00%)
--
--
-- BEGIN CORRECTION
--
--
-- 379 mhap jobs failed:
--   job 1-overlapper/results/000001.ovb FAILED.
--   job 1-overlapper/results/000002.ovb FAILED.
--   job 1-overlapper/results/000003.ovb FAILED.
--   job 1-overlapper/results/000004.ovb FAILED.
--   job 1-overlapper/results/000005.ovb FAILED.
--   job 1-overlapper/results/000006.ovb FAILED.
...
```
And I also check the output of mhap.*.out,  here is the tail of one  of them:
```
Time (s) to score, hash to-file, and output: 646.5215702200001
Total scoring time (s): 8351.297409567
Total time (s): 8370.081958668
MinHash search time (s): 2365.018103751
Total matches found: 15401803
Average number of matches per lookup: 3.308018428230847
Average number of table elements processed per lookup: 1191.846467922421
Average number of table elements processed per match: 360.29015369174635
Average % of hashed sequences hit per lookup: 2.374467060247139
Average % of hashed sequences hit that are matches: 0.298737532790561
Average % of hashed sequences fully compared that are matches: 41.46454305472943
INVALID OVERLAP 15719365 (len   4328) 10085788 (len   7952) hangs   1590   4817 -   2126   5656 flip 0
```
It shows that INVALID OVERLAP resulted in canu's failure  , but I can't figure out why this happened. Can you help me ? I'll appreciate it!

**Comment by skoren** [comment]
It looks like all your mhap jobs are failing. Are all the error messages in ```mhap.*.out``` the same complaining about invalid overlap? In that case  it is most likely the precompute did not finish successfully. Are there any error messages in ```precompute.*.out```? Is it possible you hit a disk quota which would truncate the precompute output?

**Comment by chenyufanxin** [comment]
There are four mhap jobs succeed, with the rest failed. And all failed jobs are complaining about invalid overlap.  As for precompute jobs, about half of them succeed the first time I run canu. Then I rerun canu command and the other half were finished, which can be proved by that every precompute job yielded a .dat file in blocks directory. 
I found that the hangs  greater than the read length resulted in invalid overlap, but I dont't understand why this happed. Is my original data wrong?

**Comment by chenyufanxin** [comment]
In addition, I didn't set disk quota , so I don't think precompute outputs are truncated.

**Comment by chenyufanxin** [comment]
Failed precompute jobs I mentioned above complained about I/O exception,  just a problem of file system.  So I rerun canu and those failed jobs were finished finally.  Is it right for me to do so ?

**Comment by skoren** [comment]
The out of bounds hangs is the reason for the bad overlap message. A dat file can be valid but be missing a subset of reads (if the input fasta file is not correct). If the fasta is truncated, the reads will not match so the wrong read will get assigned an overlap, leading to the invalid hangs. 

It should be safe to resume the precompute jobs after I/O errors because Canu only writes a file after it is completed. However, given the errors you are seeing in the mhap step, it is most likely the precompute step did not run correctly. Do you have the precompute output files and could you upload them here? Can you try removing the 1-overlapper folder and re-running Canu but increase the size of the precompute jobs (by setting corMhapMemory or corMhapThreads to double whatever they were in the default run) to reduce the # of jobs and the I/O load to see if that runs without errors.

**Comment by chenyufanxin** [comment]
This is  the output files of  those failed precompute jobs. 
[errorlog.zip](https://github.com/marbl/canu/files/1238436/errorlog.zip)

**Comment by skoren** [comment]
Based on the error logs, the majority of precompute jobs did not succeed, all due to I/O errors. It seems that your cluster FS cannot keep up with the demand. There are errors like:
```
safeRead()-- Read failure on gkStore::gkStore_loadDataFromFile::blob: Bad file descriptor.
safeRead()-- Wanted to read 3988 objects (size=1), read 3968.
gatekeeperDumpFASTQ: AS_UTL/AS_UTL_fileIO.C:152: size_t AS_UTL_safeRead(FILE*, void*, const char*, size_t, size_t): Assertion `(*__errno_location ()) == 0' failed.
```
and
```
Exception in thread "main" java.io.IOException: Input/output error
```
Both of these are complaining essentially about non-existing files when the files clearly exist since other jobs are using them. This is almost identical to issue #586. Is this a new assembly with @brianwalenz suggestion to reduce the job concurrency or is this a different cluster? It seems the number of precompute jobs is the same as before. Essentially, what is changed in this run from the previously failing one.

The unexpected behavior is Canu allowing you to continue while the previous step did not complete. It should be catching these errors and aborting the run. Can you give details on how you ran Canu the first time. Presumably, it tried to re-run the jobs and when they were not successful it stopped. How did you manually run the failing jobs before resuming Canu? What command did you use to resume Canu and did it re-run any precompute jobs when you restarted it?

**Comment by chenyufanxin** [comment]
Following your advice , I removed 1-overlapper directory just now. Also I set corMhapMemory=60 (which is the biggest memory the nodes have) and reduced the number of nodes in grid from 20 to 10. Good news is that Canu finished all precompute jobs in a one-time success. Bad news is that in the next stage  Canu finished most of the mhap jobs successfully but still some of mhap jobs failed due to the same problem,invalid overlap. This is confusing.

**Comment by skoren** [comment]
Can you post the precompute and mhap output jobs? I suspect there is still some disk issue here.

**Comment by chenyufanxin** [comment]
I checked the log file of ervery precompute job and found the reason. As you said, there is one .dat file truncated .It should process 360000 sequences, but only 359986 sequences were processed in fact.And canu didn't detect this error before running mhap jobs.
 Here is the head and the tail of precompute.2019_28.out:
```
Running job 28 based on SLURM_ARRAY_TASK_ID=28 and offset=0.
Dumping reads from 4860001 to 5040000 (inclusive).

Starting mhap precompute.

Running with these settings:
--filter-threshold = 5.0E-6
--help = false
--max-shift = 0.2
--min-olap-length = 116
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 256
--num-min-matches = 3
...
```
```
...
Current # sequences loaded and processed from file: 315000...
Current # sequences loaded and processed from file: 320000...
Current # sequences loaded and processed from file: 325000...
Current # sequences loaded and processed from file: 330000...
Current # sequences loaded and processed from file: 335000...
Current # sequences loaded and processed from file: 340000...
Current # sequences loaded and processed from file: 345000...
Current # sequences loaded and processed from file: 350000...
Current # sequences loaded and processed from file: 355000...
Processed 359986 sequences (fwd and rev).
Read, hashed, and stored file ./000028.input.fasta to ./000028.input.dat.
Time (s): 2280.102935383
Total time (s): 2280.104066877

```
Attached precompute.2019_28.out
[precompute.2019_28.out.zip](https://github.com/marbl/canu/files/1251484/precompute.2019_28.out.zip)

**Comment by skoren** [comment]
I don't see any error in the log file so I see why Canu wouldn't stop. The dump did request 18,000 reads (4860001 to 5040000) (the 36,000 is both fwd and reverse which is why it's double) but it seems the OS silently returned a short read that linux didn't detect and let the program keep running. Perhaps this also explains why the previous run you had was continuing. The gatekeeper job is returning success even though it's calling system read functions which are failing to return reads. We can check the dumped count matches the expected counts as well but your OS/FS is not behaving properly here. 

I guess re-run this dat by hand and make sure all are at the expected sequence counts and mhap should run OK. You definitely also want to use ovsMethod=sequential otherwise your FS will get overloaded again. Perhaps you can define a QOS to limit Canu jobs further or specify gres requests to limit the machines it can run on.

**Comment by chenyufanxin** [comment]
Thank you very much , I will try that!
