### ISSUE TITLE
Some files written to top level directory rather than run folder

### ISSUE THREAD

**Issue by skoren** [marbl/canu#6]
When running locally, the best.* files from unitigging are written to the folder where Canu was launched not to the unitigging/4-unitigger folder, as they should be. This does not happen for grid runs.

**Comment by brianwalenz** [comment]
Interesting.  bogart is apparently the only thing that doesn't use absolute paths (cgw did too, iirc).

When run under grid control, we tell SGE (etc) to chdir to the proper place, then launch the job from there.  When not under grid control, there isn't a chdir, and the job is run rooted wherever canu was launched from.

Before this was converted to grid execution, the runCommand() function would really run "cd $path && $cmd" to run a job.  In the local parallel execution code, there was no 'cd'; all jobs ran from the directory the assembler was launched from.

Fixed in 30f27c01ef7e6e58185c93c8140aa3fcd65d320c
