### ISSUE TITLE
cormhap Memory settings

### ISSUE THREAD

**Issue by rafalwoycicki** [marbl/canu#61]
Dear All,

I have a problem with using more efficiently the Memory for the mhap correction.

On the single machine with 64gb with 6/4 concurrency/threads settings I had to set memory to 20GB per 1 job so that 1 job finally was able to utilize 15% of memory *6 jobs do 90%. When the setting was 10GB, as would be expected from 64/6 so the utilisation was just 6%, not to efficient.

Then I upgraded my workstation to 96GB and so I thought to set memory to 30GB , so 1/2 more , proportionally to the additional amount of RAM, but what I got was 6% utilisation just per job.

How should I set the values? so that the utilisation will be more efficient?
After changing OvlHashBlockLength to 26 th eutilisation went up to 8% max per job, still not good enough.

My other question is about controlling length of fragments and overlaps. At each step of the pipeline separetely. Is it possible somehow?

Thank you in advance for your help.

Rafal

**Comment by brianwalenz** [comment]
We nearly always run with the default settings, for microbes to humans, on laptops, grids and large memory machines.

For mhap, you can try doubling mhapBlockSize to load more reads into each mhap process.  I wouldn't mess with the memory settings - canu is picking the memory so that N jobs will fit on the machine.  If those jobs aren't filling their memory allotment -- that's the block size.

For the ovl overlapper, it doesn't matter at all.  Regardless of memory usage, it takes (almost) constant time.  4gb and 8gb are recommended.  Smaller than that, and you get "too many" output files.  Larger than that and building the hash table (a single thread) takes too long.

You can run each of the three stages independently; see 'canu -h' (-correct, -trim, -assemble).

If you need more advice, paste in the initial output of canu, where it describes how it set up the compute.  Lines like:

```
-- Allowed to run under grid control, and use up to   4 compute threads and   15 GB memory for stage 'bogart (unitigger)'.
```

(and three back-ticks before and after the block will format it nicely)

**Comment by rafalwoycicki** [comment]
Thank you Brian, I will try.
