### ISSUE TITLE
Question. Combining PacBio and Nanopore 1D and 1D^2 reads

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [marbl/canu#612]
Hi there,
I was wondering if you had any recommendations for combing PacBio P6 and Nanopore R9 1D and 1D^2 reads? Or if you were to suggest to only one datatype as polishing afterwards might be tricky.

I could not find anything about mix and match in the documentation.

Thanks!

**Comment by skoren** [comment]
Typically, for assembly continuity you want to maximize read length rather than identity so I'd guess the 1D would be better than the 1D^2. That said, it is probably fine to throw in all the data together and let the assembler pick the best/longest reads to correct and assemble. For polishing, I'd suggest using the PacBio data with arrow (as long as you have sufficient coverage) as that ends up with higher identity than just nanopore data for now.
