### ISSUE TITLE
Clarification about correctedErrorRate settings for nanopore data

### ISSUE THREAD

**Issue by johnomics** [marbl/canu#625]
The correctedErrorRate recommendations changed just after v1.6 was released (https://github.com/marbl/canu/commit/9e1af2e141fd6bd090341904abf365e901ddba5d); the default is up to 14.4% from 4%, and the recommendation for R9 1D data is now 22.5%, up from 7.5%. Please could you clarify this?

1. What prompted the large increase here? Why aren't these values decreasing as the raw read quality increases?
2. I had been assuming that we should be using the R9 1D values for recent R9.4/R9.5 data, as they are 'R9' flow cells, but now I realise that's probably dumb, as surely the newest data is what the defaults are for. But please could you confirm this? IE you recommend correctedErrorRate of 14.4% for R9.4/R9.5 data (give or take 1% for coverage)?

Thanks.

**Comment by skoren** [comment]
The increase is due to a change in how parameters were handled and doesn't actually increase the error rate used. The old method specified the error in a single read vs the reference, not in the overlap so Canu implicitly tripled it. Specifying 4.5 would give you about 13.5%. The new method is specifying the overlap error rate. The default should be fine for R9 1d and R7 2d data, it shouldn't be necessary to increase it to 22%.

**Comment by brianwalenz** [comment]
I'll add that this was out of date documentation; the code has been using 14.4% since the 1.5 release.

**Comment by johnomics** [comment]
Thanks Sergey, Brian - OK, I will go back to using the defaults - and thanks for updating the documentation to remove the 22%. All is clear!
