### ISSUE TITLE
Some cases where 'guessed X coverage' in asm/unitigging/0-mercounts/asm.ms22.estMerThresh.err is far off the mark

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#63]
I just wanted to mention that I've observed a few times, only when nanopore data is included, that guessed X coverage is estimated to be 4-6x higher than it should be. 

I am curious about what effects this would have on the subsequent unitigging steps. Does it result in fewer reads being used for overlapping/unitig construction?

I can say when this happens, it is correlated with smaller (sometimes much smaller) contig size stats.

**Comment by JohnUrban** [comment]
I just also noticed that this "guessed X coverage" issue is present in the trimming directory's http://0-mercounts/asm.ms22.estMerThresh.err as well.

For the particular cases this time around, it seems to be happening when I set:
 corMhapSensitivity=high \
 corMinCoverage=2 \

Interestingly, when these are set, although there are more read lengths in trimming/asm.gkpStore/readlengths.txt (i.e. more lines) than when default settings are used, they sum to a smaller number.
For example:
Default settings 
1,154,942 reads
summed lengths = 7,280,570,825
mean length = 6303.84

When corMhapSensitivity=high, corMinCoverage=2 
1,186,788 reads
summed lengths = 5,382,611,399
mean length = 4535.44

**Comment by skoren** [comment]
The coverage estimate shouldn't have much effect on unitigging, it will only affect the breaking parameters. As for shorter unitigs, you can try increasing the minimum overlap size to about half your average trimmed read length. Bogart can over-split some repeats and increasing the overlap size would avoid it splitting.

I'm not sure why you have less data from the sensitive parameters, especially since dropping the corMinCoverage should give you more bases. What happens if you run with just corMinCoverage=2 or even 0?

**Comment by JohnUrban** [comment]
I haven't been able to get to your suggestions yet because I had 8 assemblies running for the past week or so. But I can update you…

Of those 8, 4 used the more sensitive parameters:
 corMhapSensitivity=high \
 corMinCoverage=2 \

For the 4 that didn't, the guessed coverage at both the trimming and unitigging steps was between 20-30 in agreement with summing the read lengths.

For the for that had those sensitive parameters, the guessed coverage at both steps was between 90-130 -- 5-6 times higher than summing the read lengths and dividing by expected genome size.

>Some more specific information -- all info is from unitigging stage except 1 that is from the trimming stage:
**Runs without sensitive parameters**
g250-default-corcov/unitigging/g250-default-corcov.gkpStore/readlengths.txt
nreads	1594828
sum_reads	8726734086
sum_length/G	29.08911362000000000000
mean_length	5471.9
Guessed X coverage is 31

g250-default/unitigging/g250-default.gkpStore/readlengths.txt
nreads	874212
sum_reads	6235195203
sum_length/G	20.78398401000000000000
mean_length	7132.36
Guessed X coverage is 21

g310-default-corcov/unitigging/g310-default-corcov.gkpStore/readlengths.txt
nreads	1594828
sum_reads	8726734086
sum_length/G	29.08911362000000000000
mean_length	5471.9
Guessed X coverage is 31

g310-default/unitigging/g310-default.gkpStore/readlengths.txt
nreads	1198192
sum_reads	7433226336
sum_length/G	24.77742112000000000000
mean_length	6203.7
Guessed X coverage is 26


**Runs with sensitive parameters:**
g250-lowcovish-corcov/unitigging/g250-lowcovish-corcov.gkpStore/readlengths.txt
nreads	1708027
sum_reads	7664770860
sum_length/G	25.54923620000000000000
mean_length	4487.5
Guessed X coverage is 129

g250-lowcovish/unitigging/g250-lowcovish.gkpStore/readlengths.txt
nreads	922069
sum_reads	4859291834
sum_length/G	16.19763944666666666666
mean_length	5269.99
Guessed X coverage is 95

g310-lowcovish-corcov/trimming/g310-lowcovish-corcov.gkpStore/readlengths.txt
**NOTE: from trimming dir**
nreads	1734781
sum_reads	7739417734
sum_length/G	25.79805911333333333333
mean_length	4461.32
Guessed X coverage is 127

g310-lowcovish/unitigging/g310-lowcovish.gkpStore/readlengths.txt
nreads	1234284
sum_reads	5562988379
sum_length/G	18.54329459666666666666
mean_length	4507.06
Guessed X coverage is 116





To make sure I understand, you'd be interested in finding out what happens if I remove "corMhapSensitivity=high" leaving only "corMinCoverage=2" or "corMinCoverage=0" - correct?

**Comment by JohnUrban** [comment]
It looks like using the more sensitive parameters is strictly leading to fewer reads, lower coverage, etc….
This wasn't always the behavior… and I'm not sure what has changed.

**Comment by skoren** [comment]
I've seen cases on some repetitive genomes that the sensitive parameters are too sensitive and generate more repeat-induced overlaps which end up hurting the corrected read lengths/count because they are made to look like a collapsed version of the repeat. I'm testing if we can increase thresholds for the overlaps without hurting assembly quality and so far the answer is yes. We've usually always tried to find more overlaps with MHAP and then filter them downstream but that filter isn't perfect, though this isn't generally noticeable unless the genome is very repetitive. 

The parameters I'd be curious about testing would be default sensitivity (so no corMhapSensitivity=high) and corMinCoverage=0 to see if you get sufficient corrected reads for a good assembly. The second would be corMhapSensitivity=high and corMaxEvidenceErate=0.7 which would increase the stringency of the downstream filter to keep higher identity overlaps.

**Comment by JohnUrban** [comment]
Alright - these jobs still have not finished yet, and one has crashed, which I will explain why later -- it may be of interest. However, I can tell you the relevant info from trimming/g310-asm.gkpStore/

job1 --> corMinCoverage=0 
job2 --> corMhapSensitivity=high corMaxEvidenceErate=0.7 

>job1
nreads 1363664
sumreads 12030937323
sumreads/G 38.80947523548387096774
Guessed X coverage is 28

>job2
nreads 979766
sumreads 3568246890
sumreads/G 11.51047383870967741935
Guessed X coverage is 102

>As a point of reference, default looked like this:
nreads 1198192
sum_reads 7433226336
sum_length/G 24.77742112000000000000
mean_length 6203.7
Guessed X coverage is 26


Alright, job2 ( corMhapSensitivity=high corMaxEvidenceErate=0.7 ) failed at the asm.ovlStore.BUILDING stage (trimming dir).

It looks like in trimming/asm.ovlStore.BUILDING/scripts/, there are 3 steps/scripts.
The contents:
1-bucketize.jobSubmit.sh  1-bucketize.sh  2-sort.jobSubmit.sh  2-sort.sh  3-index.sh

It appears to be failing on the 2-sort step.

In trimming/asm.ovlStore.BUILDING/logs/2-sort*.out, the failure message seems to be:
ERROR:  Overlaps need 3.00 GB memory, but process limited (via -M) to 3 GB.
Failure.

It appears I can probably manually change 2-sort.sh (perhaps -M 3 --> -M 4) and run it before resuming the Canu pipeline:
$bin/ovStoreSorter \
  -deletelate \
  -M 3 \  
  -O /asm/trimming/asm.ovlStore.BUILDING \
  -G /asm/trimmingasm.gkpStore \
  -F 4 \
  -job $jobid 36

I thought this error might be of interest to you in general. 
Any thoughts welcome.
