### ISSUE TITLE
unexpected stop and how to resume

### ISSUE THREAD

**Issue by bioteksampath** [marbl/canu#632]
HI

I try to assemble 600mb genome using 30Gb data on a linux server (grid engine GE), My test run with 5Gb data was went well and produced desired results. However, when I run with 30 Gb data the canu program was stopped unexpectedly (at     ./overlap.sh 99 > ./overlap.000099.out 2>&1) after two weeks of run during the trimming step and without leaving any error message. I don't think we have a memory issue. 

Following is the comment used to run the job on GE (40 cores used)

#!/bin/bash
#$ -S /bin/bash
#$ -N ox_Bn6
#$ -j y
#$ -cwd
#$ -R y
#$ -pe smp 40

/mnt/HNAS_NLSAS/home/AGR.GC.CA/perumals/bin/javaNcanu/canu-1.5/Linux-amd64/bin/canu -java=/mnt/HNAS_NLSAS/home/AGR.GC.CA/perumals/bin/javaNcanu/jre1.8.0_131/bin/java -p Bn6 -d Bn6  genomeSize=600m -nanopore-raw Bn6_QC30x.fasta useGrid=false

The complete report can be found here
[canu_30x_report.txt](https://github.com/marbl/canu/files/1307150/canu_30x_report.txt)

what might be the reason for this? and how to resume the job?
In addition, how to increase the speed of the assembly process?

Thanks in advance
sam

**Comment by skoren** [comment]
It looks from the log like the Canu job was killed/stopped by the system, perhaps due to a time limit? Is there any output in overlap.000099.out indicating an error? If you re-run the same Canu command, it will automatically resume where it left off.

As for speeding it up, you're running on single machine on a large genome so it will take time. It looks like you have a grid. Canu can submit itself to most grids so running the overlap jobs in parallel on the grid would speed it up (right now you have 178 jobs but are running only 12 concurrently). Alternatively, you could try the fast parameters from the release notes (```overlapper=mhap utgReAlign=true```) and run canu with ```-nanopore-corrected Bn6/Bn6.correctedReads.fasta.gz```). This will be faster but may give a less contiguous assembly than the default.

**Comment by bioteksampath** [comment]
Hi Koren,
Thanks for your prompt response, 
The results of overlap.000099.out and some other jobs seem partially completed.
[overlap.000099.out.txt](https://github.com/marbl/canu/files/1307245/overlap.000099.out.txt)

Below the screenshot of the overlap.xxxxxx.out

![image](https://user-images.githubusercontent.com/8802351/30496500-cc1cb7ac-9a0c-11e7-840b-031bb80a1c37.png)

This shows that the overlapping job stopped while working

![image](https://user-images.githubusercontent.com/8802351/30496293-2cffac06-9a0c-11e7-9332-898ee4cd9550.png)

Just for the clarity, I can input the above parameters (overlapper=mhap utgReAlign=true) to resume the same job to speed up the process, or  I should have to use my old comment itself if I want to resume the same job?

Thanks again
sam

**Comment by skoren** [comment]
Is there any error in the in-process out files (like 99 or 86). If there isn't then I expect your reached some sort of time limit for jobs on your grid.

If you want to try the fast parameters, you have to run again in a different folder starting from the corrected reads. You cannot mix the two. To resume this run, you can use the exact same command as before and it will skip all the jobs that have output and start running the jobs which did not complete.

**Comment by bioteksampath** [comment]
Thanks ... I will give it a shot.

**Comment by skoren** [comment]
Closing, idle.
