### ISSUE TITLE
Canu for metagenomics

### ISSUE THREAD

**Issue by Cbdinh** [marbl/canu#634]
Using canu1.6 on MacOSX 10.10.5

canu -d foldername -p name genomesize=100m gnuplotTested=true -nanopore -raw "metagenomeReads.fastq"

Hi all. 

I have been attempting to run canu on metagenomic sequences from microbial communities and would love to see if anyone else was doing this as well. I had some questions about the appropriate parameters.

Primarily, I am interested in the genomesize parameter. I have attempted several genome sizes from 4-100Mnts (largest bacterial, fungal, or aggregate genome size). I have been trying to search in the issues and documentation about how this might affect Canu when it is attempting to assemble genomes from a more complex environment. I see that it might affect sensitivity, but I am unsure how to think about this from a metagenomic point of view.  Should we choose the genome size based on the largest or smallest individual genome size, or the summed aggregate expected genome size? Does this affect assembly time? Each run seems to take about 2 weeks on lab computers. 

2 minor problems: gnuplot is not being found. I have tried rebuilding from source. Further, Canu does not seem to be fully utilizing the resources available (only using one thread out of 8 available, though it can identify all 8; only running one process at a time during trimming). I have just added in minThreads or specified the number of threads/concurrent processes for the trimming stages. 

Thank you for any advice about these issues or the proper place to send my questions.

**Comment by skoren** [comment]
The genome size affects how many reads are corrected (in combination with the corOutCoverage parameter) and how sensitive the overlapping is. It is also the denominator for the genome size reports output during the run. Typically for metagenomes we set it to the average genome in the sample and instead increase the corOutCoverage and sensitivity parameters. Here are some common parameters we've used for recent assemblies:
```corMinCoverage=0' corOutCoverage=all corMhapSensitivity=high 'correctedErrorRate=0.105' 'genomeSize=5m' 'corMaxEvidenceCoverageLocal=10 corMaxEvidenceCoverageGlobal=10 oeaMemory=32' 'redMemory=32' batMemory=200```

The first set of parameters increases the sensitivity and keeps as much data as possible. The next set limits how many other reads any given read can correct to try to avoid mixing strains and finally, some default memory is increased but this is not strictly necessary.

As for the multi-threading question, Canu doesn't always use all cores. Some steps are single-thread (like estimating corrected read length and overlap store building on a single machine) so it's expected that parts of the time it will take 1 core but other times all available.

**Comment by Cbdinh** [comment]
Thank you for the help. I will try the new settings. I was worried about the sensitivity and am not sure how changing the genome size would affect sensitivity. Is it true that if we input a larger genome size that the sensitivity would decrease as shorter contigs would be less contributory to the whole? With the decreased sensitivity, would the short reads or reads with shallow sequence depth be lost, possibly along with the identity of that species? This seems like it would preclude the accurate taxonomic id of the minor species.

Your parameters seem to take these into account. I will read more of the canu documentation about how these parameters affect the assembly as it runs.

Again, thank you.

**Comment by skoren** [comment]
Metagenomic settings added to FAQ.

**Comment by skoren** [comment]
1. The ```corMaxEvidenceCoverageLocal=10 corMaxEvidenceCoverageGlobal=10``` are meant to try to limit what reads are used as evidence in cases when strains are similar but we don't have good evidence they help very much so that's why they're not on the FAQ. 

2. The genome size is used to set the sensitivity, the amount of reads to correct (with a caveat in 1.7 that automatically rescues reads), and resources to use. When the sensitivity and coverage are set, then the genome size is only relevant to select resources. Setting to to something smaller keeps Canu from trying to use large memory instances since they're not really necessary in this case. I'd expect an assembly with a large genome size to be comparable to one with a small one but using larger compute nodes. 

3. Having all the data will slow down the computation but the tf-idf does compensate for repeats already. The unitigging will also prefer longer overlaps so it will use the best overlaps out of all the available data. Generally, it can deal with mixes of coverage between different contigs too since coverage isn't used to identify repeats/etc. So you could probably make the assembly faster with normalization but I've never tried that on long reads and don't know how well it would work. Given that 1.7 has a read rescue where it will add reads to the correction that don't have good representation in the longest set selected (e.g. it will rescue a 3kb plasmid in a high coverage long-read dataset), it's possible you don't need to set corOutCoverage as high as the FAQ either. If you set it to 40 or 80, it should limit the coverage of the abundant genomes and then should rescue all the low-abundance ones. We haven't tested that so you could give it a shot and see how it compares to correcting all reads.

**Comment by jtremblay** [comment]
Somehow related to this I am trying to perform a MG co-assembly of 4 nanopore libraries. I used the options mentionned above:
```
canu -useGrid=false maxMemory=128 maxThreads=32 \
  -p shotgun_MG -d ./assembly  \
  corMinCoverage=0 \
  corOutCoverage=all \
  corMhapSensitivity=high \
  correctedErrorRate=0.105 \
  genomeSize=5m \
  corMaxEvidenceCoverageLocal=10 \
  corMaxEvidenceCoverageGlobal=10 \
  -nanopore-raw ./my_nanopore_fastq.gz
```

And got to this stage of the pipeline:

```
ABORT:   ==> LOADING AND FILTERING OVERLAPS.
ABORT:   
ABORT:   ReadInfo()-- Using 906817 reads, no minimum read length used.
ABORT:   
ABORT:   OverlapCache()-- limited to 16384MB memory (user supplied).
ABORT:   
ABORT:   OverlapCache()--       6MB for read data.
ABORT:   OverlapCache()--      34MB for best edges.
ABORT:   OverlapCache()--      89MB for tigs.
ABORT:   OverlapCache()--      24MB for tigs - read layouts.
ABORT:   OverlapCache()--      34MB for tigs - error profiles.
ABORT:   OverlapCache()--    4096MB for tigs - error profile overlaps.
ABORT:   OverlapCache()--       0MB for other processes.
ABORT:   OverlapCache()-- ---------
ABORT:   OverlapCache()--    4303MB for data structures (sum of above).
ABORT:   OverlapCache()-- ---------
ABORT:   OverlapCache()--      17MB for overlap store structure.
ABORT:   OverlapCache()--   12063MB for overlap data.
ABORT:   OverlapCache()-- ---------
ABORT:   OverlapCache()--   16384MB allowed.
ABORT:   OverlapCache()--
ABORT:   OverlapCache()-- Retain at least 1061 overlaps/read, based on 530.58x coverage.
ABORT:   OverlapCache()-- Initial guess at 871 overlaps/read.
ABORT:   OverlapCache()--
ABORT:   OverlapCache()-- Not enough memory to load the minimum number of overlaps; increase -M.
ABORT:
```
Since there is very unlikely that I will be getting such a high coverage value, is there a way to limit the number of overlaps per read? My fastq file contains only 906,817 reads representing 4,108,699,793 bases.
Cheers,
