### ISSUE TITLE
No mitochondrial genome in assemblies

### ISSUE THREAD

**Issue by situssog** [marbl/canu#635]
Dear Canu Team,

I've been running Canu 1.5 to assembly some small genomes (~14Mb).
It has works great but for some reason in some samples it does not assembly the MT scaffold. I guess It is because of the high coverage (at least 1:15 relative to nuclear genome) and the circular feature. 

Normally I guess something like this (figure) but no in all samples:

![temporal_mt](https://user-images.githubusercontent.com/22887707/30511234-8248bdba-9ad4-11e7-8324-4a03cf3a08f4.JPG)

After that I just trim the sequence. But in some samples I don't get any thing for MT.

Is there any advise on how can I assemble the MT genome? I tried extracting the MT reads by mapping with the reference genome and using those for the assembly. It didn't give me any thing tho. 

also, Is there a way to run Canu with a subset of data, without running all steps again? for instance sub-sampling the corrected or trimmed reads. and using those.

Thanks a lot,

Best,

/Sergio

**Comment by skoren** [comment]
Coverage or circularity doesn't matter to Canu, it would still assemble the mitochondria genome. There are a couple of possibilities, if the mitochondria is very short it may not get enough corrected reads from the longest set to be assembled. In that case you can increase the corOutCoverage parameter. In Canu 1.5 and earlier it may also be getting flagged as unassembled if it is largely spanned by a single read (this is fixed in Canu 1.6) so you could check the asm.unassembled.fasta to see if that has the mitochondria.

You said you tried to map and select reads from just the mitochondria and it did not assemble. How much coverage did you end up with? Did you have any contigs from that assembly, anything in the asm.unassembled.fasta?

**Comment by situssog** [comment]
Hello @skoren,

Thanks a lot for your reply. Yes, the mitochondria was in one of the unassembled contigs. 

Best,
/S

**Comment by skoren** [comment]
OK, if you get a chance to re-run this assembly in 1.6 let us know if it still ends up in the unassembled contigs because that should no longer happen.
