### ISSUE TITLE
Canu splitting a single region into two contigs

### ISSUE THREAD

**Issue by skyungyong** [marbl/canu#654]
Hi, 

I am assembling a small region of a mammalian chromosome ( ~ 3.5Mb ) using PacBio CCS reads (3 passes + 0.900 accuracy) with Canu. I had a very high coverage ( > 100X for CCS reads) and the result from Canu was quite satisfying. 

While annotating the chromosome, I observed a single gene was split into two in two different contigs. The contigs had a very clear overlap with 100% of ID at a significant region ( > 500 bp while contig is ~ 6000 bp). 

```
contigA        >.......................[Overlapping region]

contigB                                [Overlapping region]..............>
```

I have found some others, but they had a few gaps or mismatches. However, mapping these contigs to the reference suggested these contigs were supposed be joined. Would there be a way to improve the continuity?

**Comment by skoren** [comment]
Canu contigs always break at a read end so in cases where there is a split due to a repeat, there will be an overhang into the repeat on both ends of the split. This means you can find overlaps which won't necessarily be correct if joined. In this case, there was probably some conflicting evidence indicating an alternate path existed that cause the contigs to be split. You can decrease the sensitivity to these breaks in Canu by adjusting the unitigging parameters (see the bat options on the FAQ: http://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it), specifically the ```-ca 500 -cp 50``` part but this comes at an increased risk of mis-assembly.

**Comment by kevfengler227** [comment]
I have examined this issue quite a bit in plant genome assemblies through the lens of bionano hybrid scaffolding, which detects but does not resolve overlapping contigs. For one assembly, ~70% of the scaffold "gaps" were actually overlapping contigs, with an average overlap of ~12 kb. So this issue of overlapping contigs definitely needs to be addressed in the process of creating a reference genome assembly.

KF

**Comment by skoren** [comment]
Right but the fact that there is an overlap doesn't mean the assembler should have merged it since there is always an overlap because of the way Canu builds the graph. Contigs will extend into a repeat by a read length so a 12kb overlap is possible. However, there could be multiple other contigs which have said overlap leading Canu to break the assembly because the repeat couldn't be confidently resolved. 

Since BioNano has longer molecules, it can uniquely resolve the correct join. As far as I know It should have an accurate hap size estimate of the distance between contigs and merges contigs when appropriate so if it left a gap it is possible you have a large repeated unit (say 12kb) that has more than 1 copy but by merging the overlap of the contigs you'll collapse it to one.

**Comment by kevfengler227** [comment]
so unfortunately, bionano hybrid scaffolding does not (yet) merge contigs that overlap in map space, it inserts a generic 499 bp gap in this case. However, with this info in hand, you can interrogate the overlap between two contig ends with Mummer and trim back one contig to resolve the overlap. But as you mention above, sometimes one contig end will begin to walk into a different copy of the repeat elsewhere, thus there is not a perfect overlap between contig ends that overlap in map space. Again, the bionano map can give clues as to which contig needs to be trimmed. Anyway, the extent of overlapping contigs is not widely appreciated yet, but it will be. But I agree it is not an issue that can easily be addressed at the assembly level, but after scaffolding it can.

**Comment by skyungyong** [comment]
This is probably a late follow-up. The overlapping region was not a repeat but a part of a single-exon gene. This region shouldn't be confusing like a repeat. 

```
                                 |---------single-exon gene--------------->
contigA        >.......................[Overlapping region]
                                       ||||||||||||||||||||
contigB                                [Overlapping region].........................................>


```
At the annotation level, these contigs were clearly one region. The genes located before the single-exon gene in contigA and after it in contigB were also perfectly matching the reference genome, suggesting the contigs should be merged. 

I moved on to some other plant species that do not have any reference sequences. I am seeing these fragmented genes quite more often. But I am sure when Canu was splitting these regions into different contigs, Canu had a clear reason why. I wonder what are the possible reasons. 
```

**Comment by skoren** [comment]
See my previous comment for an explanation. Conflicting evidence can also come from variation in the sample (heterozygosity) which can also look like a repeat. It could have also never been joined in the first place if the overlaps had a higher error rate than Canu used. You can use my suggestion above to decrease the breaking and see if the region is joined or you can increase the error rate used for the assembly. However, if you have evidence for contigs to be joined you can always use that information for scaffolding the contigs as well.

**Comment by skyungyong** [comment]
Thank you. We are now thinking this is due to the heterozygosity of the chromosomes. I will try your suggestions and see how the contigs improve!
