### ISSUE TITLE
Limiting the number of jobs launched?

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#681]
Hi,

Quick question regarding limiting the number of jobs launched by canu.  I'm using a secondary storage system that is getting overwhelmed by the I/O generated from the numerous jobs generated by canu on our HPC SLURM system.  Is there an option that will limit the number of jobs that are launched at anyone time?

Thanks,

Jeff Maughan
BYU

**Comment by skoren** [comment]
Not something that can be easily controlled within Canu because schedulers vary widely in how they support this and because Canu doesn't request the same number of cores for all array jobs and they don't all have the same load characteristics.

I'd argue this should be up to the scheduler/system configuration. Depending on your system, you could submit to a partition with more limits on concurrent jobs or create a new partition. As a workaround, you could set ```gridEngineArrayOption="-a ARRAY_JOBS%25" which would limit all array jobs to 25 at most on a slurm system but that won't give you the same number of cores all the time since jobs will vary in how many cores they use.

**Comment by pjm43** [comment]
Thanks for the quick reply.  I will give that a try.
