### ISSUE TITLE
Insatallation issue.

### ISSUE THREAD

**Issue by PradipVCU** [marbl/canu#685]
Trying to install canu-1.6 into windows 10, Cygwin 

`but, it showed Error`
``AS_global.C:101:24: error: ‘omp_set_num_threads’ was not declared in this scope``
``omp_set_num_threads(1);``

I went into "src" folder and the give command.
$ make
Building for 'CYGWIN_NT-10.0' '2.9.0(0.318/5/3)' as 'amd64' into '/cygdrive/d/assembl/CYGWIN_NT-10.0-amd64/{bin,obj}'
CC  cc 6.4.0
CXX g++ 6.4.0
Building release v1.6

g++ -o /cygdrive/d/assembler/canu-1.6/CYGWIN_NT-10.0-amd64/obj/libcanu.a/AS_global.o enmp -pthread -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-e -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomitter -DNOBACKTRACE -I/cygdrive/d/assembler/canu-1.6/src -IAS_UTL -Istores -Istores/libignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalconibboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/libalcon_sense/libfalcon AS_global.C
AS_global.C: In function ‘int AS_configure(int, char**)’:
AS_global.C:101:24: error: ‘omp_set_num_threads’ was not declared in this scope
   omp_set_num_threads(1);
                        ^
make: *** [Makefile:655: /cygdrive/d/assembler/canu-1.6/CYGWIN_NT-10.0-amd64/obj/libcobal.o] Error 1

**Comment by skoren** [comment]
Canu has had limited testing on Windows and we don't recommend it because cygwin has other quirks which may break your assembly (like spaces in paths). 

It looks like the flags from the makefile are somehow getting truncated (it should be ``` -fopenmp -pthread``` but your command shows only ```enmp -pthread```). No idea how/why that would happen and without access to a cygwin environment there isn't a way for us to debug. I'd suggest making sure you have the latest version of make available for cygwin and try setting CXXFLAGS manually in the environment to be ```-fopenmp -pthread```.

**Comment by PradipVCU** [comment]
Hi Koren,

Thanks for your reply and explaining it to me.
Someone advocating to use UBUNTU in windows to use canu. Is it doable? If yes, then I have UBUNTU in windows as bash please help me in installing it there and using it.

Thanks

With Regards

Pradip

**Comment by skoren** [comment]
We don't have access to a test Windows platform for cygwin or bash tests but previous users have compiled Canu for windows bash so it should be possible. Try it and see what happens.

**Comment by PradipVCU** [comment]
Thanks,,,

Tell me one more thing, if I can use Mac system, it will be pretty easy to install and use.

With regards

Pradip

**Comment by skoren** [comment]
Linux and OS X are the officially supported so yes you can download and build on a mac.

**Comment by PradipVCU** [comment]
Thanks,,

With regards

Pradip

**Comment by skoren** [comment]
I committed a fix based on another cygwin users's build errors (issue #689). That compilation was correctly processing the compile flags so that seems like a machine-specific issue which might be fixed by updating cygwin and make system components.

I'm going to close this since the build on cygwin should be OK now and you've switched to OSX.
