### ISSUE TITLE
about the version of canu

### ISSUE THREAD

**Issue by milkcookie** [marbl/canu#693]
Dear all:
I have use a new version "Canu snapshot v1.6 +61 changes (r8473 86f53cff1401ce4229d2a579ed093afe68751e0a)" to assemble a genome, the same spe.txt ,and same input fastq, with the same linux server, but my result have a lower N50 and larger numbers of contigs than use "Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available", please tell me why?
what I can do to improve my genome with the new version of canu?
milk
FAFU

**Comment by skoren** [comment]
It sounds like your previous version is before 1.5 since subsequent releases would report a version without a repository which is quite old. The 1.6+changes version you have was checked out in the middle of large-scale changes and there are no guarantees that the tip is stable at a particular point in time so it is possible it had bugs which affected your assembly. 

I suggest switching to a release version (1.6 is the latest) rather than tip unless you are encountering a specific error in the released fixed in the time. Number of contigs is expected to increase in the tip because Canu captures short sequences (like plasmids) better and keeps more low-coverage sequence but that shouldn't affect the NG50 very much. I'll also add that NG50 is not the only metric for assembly quality, if the new assembly is more correct it can have a lower NG50 but may still be preferable.

**Comment by milkcookie** [comment]
Thanks for your reply, but my new genome is a little smaller than before, so I want to know why. larger numbers of contig, and smaller genome size...

**Comment by skoren** [comment]
It could be due to a bug in tip, I'd still recommend using and comparing with a release version.

**Comment by skoren** [comment]
Tip is currently unstable, see #704.
