### ISSUE TITLE
How are default values for corMinCoverage chosen

### ISSUE THREAD

**Issue by yeban** [marbl/canu#696]
I want to test the impact `corMinCoverage` on corrected reads, and in turn on my assembly. The documentation suggests setting this to 0 or 4 depending on the coverage. But what happens if `corMinCoverage` is set to 1/2/3. 0 & 1 seem to be the same. I think, Canu would need at least three reads to make a consensus, so 2 should be the same as 0 & 1. So 3 would be the lowest value to use for only consensus reads to be reported. Anything higher (4, 5, 6) should result in corrected reads of higher quality (and lower quantity). I am guessing 4 is the suggested value because in practice 3 & 4 don't make too much difference if one has sufficient coverage?

Thanks.

**Comment by skoren** [comment]
Think of it as number of other reads supporting a base. There is no minimum to make a consensus, the base form of consensus is just reporting back the raw read. So 0 means keep all bases in the original input read even if it has no support from anywhere else. The idea is to correct as much of a read as you can, especially the ends, to avoid losing coverage when you don't have much input. You can definitely use other values between 1 and 4 and they will give slightly different results. 

In practice the difference is a few bases which is why it's set to 4 because given a random error model, the chance of 4 reads having the same mistake is quite low and increasing it doesn't drop the error that much.

**Comment by yeban** [comment]
Thank you.
