### ISSUE TITLE
Canu v1.6: ovlStore Building and Sorting hanging with large filesystem footprint

### ISSUE THREAD

**Issue by halfwayBraindead** [marbl/canu#705]
This issue concerns use of the v1.6 release of Canu on a Slurm-configured cluster, with a cluster-wide operating system of CentOS 6.9.

Command used was:

```
canu \
        -p someFish -d someFish_v16 \
        genomeSize=2.4g useGrid=1 gnuplotTested=true \
        gridOptions="--partition=batch,256g" \
        -pacbio-raw someFish_raw.fastq
```

We've been trying to assemble the large genome of a certain fish, with an estimated genome size of 2.4g. The assembly appeared to exhibit hanging behavior on the main "correction" phase, specifically within the ovlStore building and sorting stages. Complete generation of the "1-overlapper" directory via mhap took approximately 3 days, with an output filesystem footprint of 6.8 TB.

When we began ovlStore building, the RAID upon which the assembly was progressing ran out of space overnight, halting Canu. We then transferred the existing assembly progress onto a larger RAID and attempted to resume, at which point ovlStore building progressed at a speed that appeared to be very slow, with anywhere from 200-400 cores being reserved from our cluster (while each core was barely being utilized), with the larger RAID writing several hundred MB/sec and continued to grow in total filesystem footprint size until it exceeded 21 TB.

Time elapsed from 1-bucketize to 2-sort in ovlStore: approximately 5.25 days. By this point, the many cores appeared to be thrashing the larger RAID, and we began to experience compute node outages, at which point the assembler was halted entirely.

We've assembled another large fish genome previously (1.2g estimated genome size), with both Canu major versions 1.5 and 1.6, and we did not observe this sort of behavior from the correction stage of Canu. gkpStore output described the previous assembly's raw coverage near 60X, with peak insert lengths between 8k and 10k. For this current errant assembly, the raw coverage was initially estimated to be around 33x, but gkpStore found it to be closer to 23x. Many insert subreads are distributed between 1k and 7-8k in length, with the largest peaks occurring at or below 2k. (8% of raw data was discarded entirely by Canu for being <1k in length.)

Several questions:

1) Would the halting of the assembly due to a RAID fill-up event permanently "degrade" the ovlStore building process, such that re-running ovlStore after purging its contents would feasibly work?

2) Is there any way in which the ovlStore processes can be instructed to use local disks on compute nodes before syncing this data to RAIDs later?

Thanks!

**Comment by outpaddling** [comment]
Additional info:

Our file servers use NFS over 54 mbit FDR Infiniband.  iftop on the RAID server showed up to 600 megabytes/sec both read and write at times.  There were 5 ovStoreSorter processes running on a typical node using 10.7 GB virtual memory each.  ( 10 GB resident )  

Is there a way to reduce the amount of file I/O by using different job parameters, i.e. memory, number of processes, etc?  I know we could alleviate the NFS load by simply using fewer processes, but how does this stage of analysis generally scale assuming the I/O bandwidth exists?  Can it utilize 600 cores effectively where a parallel filesystem exists, for example?

Does it make extensive use of any files (maybe temporary files) that could be stored on the local disk in order to reduce NFS traffic?

Thanks much...

**Comment by skoren** [comment]
This step is essentially a large distributed merge sort so it will use as much I/O as your FS can provide. Each 1-bucketize.sh step opens many files (however many 2-sort.sh jobs you have) so if your FS doesn't like having so many simultaneously open files, it could be slow even if it has bandwidth remaining. You could increase the ovsMemory parameter to decrease the 2-sort.sh jobs and thus the number of open files. Other than that, there isn't anything you can do to reduce I/O rather than limit job concurrency. Moving files around won't matter and it will the same speed to re-run a build.

1. We've run hundreds on commercial HPC filesystems mounted over NFS and thousands on a GPFS system without issue. It definitely gives the storage a workout though.

2. There is no support in the code but you could potentially modify the shell scripts to read/write local disk but there would still be I/O contention moving files to/from scratch space which on our systems is no better than just writing directly to shared disk. Each 1-bucketize.sh job reads a single output from 1-overlapper/results/*.ovb (job 1 reads 000001.ovb). You could move this to scratch first and then update the path given to -O to be the scratch space. You'd have to move the created bucketXXXX directory back to shared disk at the end of the job. To do the same with 2-sort.sh you need to find subsets of files from most buckets (e.g. 2-sort.sh job 1 will take files named slice0001 from all bucketXXX folders and all the sliceSizes files in all buckets) so you'll be shuffling a lot of files to scratch.

3. You can save space by removing some intermediate outputs early. The ```correction/1-overlapper/blocks/*``` files can be removed. The ```correction/1-overlapper/results/*``` can be removed once the 1-bucketize.sh step completes. However, this is more risky as if there is an issue with your FS and one of the 1-bucketize steps gets corrupted, you wouldn't be able to re-create it without these files. You'd have to go back and re-run part of the overlapping. Canu automatically cleans up these files once a store is built.

**Comment by outpaddling** [comment]
Thanks for the detailed info!  Increasing ovsMemory might be a good option for us in the short term.  Is there any advantage to running more jobs/node with less memory for each?  If not, we could increase our ovsMemory to the point of limiting each node to 1 job.

**Comment by halfwayBraindead** [comment]
Many thanks for the input and insight, Sergey!

For reference, the gkpStore histogram we've seen from the main "assembly.report" file:

```
-- In gatekeeper store 'correction/someFish.gkpStore':
--   Found 7959427 reads.
--   Found 54790276089 bases (22.82 times coverage).
--
--   Read length histogram (one '*' equals 13149.27 reads):
--        0    999      0
--     1000   1999 920449 **********************************************************************
--     2000   2999 758413 *********************************************************
--     3000   3999 709456 *****************************************************
--     4000   4999 685246 ****************************************************
--     5000   5999 643614 ************************************************
--     6000   6999 622054 ***********************************************
--     7000   7999 779949 ***********************************************************
--     8000   8999 712431 ******************************************************
--     9000   9999 518163 ***************************************
--    10000  10999 393881 *****************************
--    11000  11999 326387 ************************
--    12000  12999 245409 ******************
--    13000  13999 173186 *************
--    14000  14999 122905 *********
--    15000  15999  88564 ******
--    16000  16999  64350 ****
--    17000  17999  46842 ***
--    18000  18999  34568 **
--    19000  19999  25387 *
--    20000  20999  19333 *
--    21000  21999  14813 *
```

Would a dataset of this non-ideal quality and fairly low coverage (23x) present difficulties during correction and subsequent assembly?

**Comment by skoren** [comment]
Certainly the low coverage compounds the size and I/O load because we have to care about all overlaps not just the largest ones, with higher coverage Canu uses stricter overlap parameters which can reduce noise. The sort job is single-core so you'll lose a lot of parallelism if you restrict the jobs to one per machine (I assume your machines have at least 16 cores each).

**Comment by halfwayBraindead** [comment]
Thanks, Sergey!

Very good to know that low-coverage datasets compound difficulties during correction. Worse yet, from discussion with our collaborators who provided the raw data for this assembly, this genome suffers from extremely long repetitive elements, in addition to oscillating ploidy between chromosomes. We're in for a real ride here!

We've since completed the 1-bucketizer phase within ovlStore and are currently on 2-sorting. This is currently being run on 96 cores across 4 nodes with access to a non-parallelized filesystem (not sure if increasing core count would help any further, as the filesystem appears unable to keep up with this many cores as-is), so this will take us a while.

**Comment by outpaddling** [comment]
Do you know the basic specs on the NFS-mounted Isilon appliance?  I'd be interested in knowing about the RAID throughput capability and the interconnect for comparison.  Right now we're using an "embarrassingly parallel" filesystem, an array of independent NFS servers.  Works beautifully for 99% of our jobs.  Each one is capable of over 800 MB/sec sustained in both directions over our IB fabric.  This is the first time one of these servers has been challenged as far as I know.  We're pondering a parallel filesystem down the road, but too short-staffed to even explore it right now.

**Comment by halfwayBraindead** [comment]
Hi Sergey,

Wanted to provide an update that the ovlStore sorting stage has begun to hang at least one of our allocated compute nodes. What might cause this? Can sorting complete if a compute node hangs? If not, can the sort be resumed?

**Comment by skoren** [comment]
@outpaddling we have an array of X410s (https://store.emc.com/en-us/ISILON-PRODUCTS/Dell-EMC-Isilon-X410-Storage/p/EMC-Isilon-X410), I don't know the performance off the top of my head but I do know it improves with the # of shelves you buy and we have about 6. 

@halfwayBraindead i would guess it's all I/O or networking so it's probably not hanging but just unresponsive to ping. If it really does down, Canu will retry failed sort jobs when the next job in the line runs.

**Comment by halfwayBraindead** [comment]
An update on our situation: the ovlStore sorting jobs failed. Multiple attempts to re-run the assembler to complete construction of the ovlStore were all met with failure. Upon inspection of the log files, it appeared that the ovlStore sorter was not being triggered to forcibly run by Canu, and so it would verify faulty ovlStore sorting output as "valid" and then quit.

Deleting the offending ovlStore outputs and re-running the assembler with ovsMemory=20 (20 GB memory allocation) has resolved the issue. We are now proceeding with correction scoring in the 2-correction stage.

Will update further as we aim for completion.

**Comment by halfwayBraindead** [comment]
Assembly of our dataset has completed; thanks very much for the advice and insight in this thread, Sergey! We'll continue experimenting with ovlStore bucketizer and sorting parameters on our cluster in the near-future to better understand ovlStore requirements for large, repetitive, and complex genomes.
