### ISSUE TITLE
misassembly -- recovers a single conglomerate contig (should be 3) (Canu v1.6 -- Linux)

### ISSUE THREAD

**Issue by Josh-Lefler** [marbl/canu#709]
Hello! 

I ran canu on default settings on some PacBio reads with a reported coverage of about (x192). The algorithm returned a single contig without any trouble. However this contig seems to be a combination of the three contigs I was expecting from this assembly.

My Assembly:
1 contig : ~ 4.6 Mbp

Expected Assembly:
contig 1 : ~ 4.2 Mbp
contig 2 : ~ 350 Kbp
contig 3: ~ 70 Kbp

Looking at the unitigs seems to reinforce this: It shows a 4.2 Mbp unitig overlapping with a unitig that I assume is a merging of contigs 2 and 3 (~396 Kbp) including a few smaller unitig bits.

I've used Canu before to assemble small microbial genomes and this is first time I've had any sort of minor difficulties.

Any suggestions on what parameters I should toy with? 

Thanks!

parameters set:
genomeSize=4.8m
-pacbio-raw

^^ that's all I explicitly set.

**Comment by skoren** [comment]
I guess the first question is how certain you are there should be three contigs and not one. The unitigs are meant to be more conservative than the contigs but also they often over-split due to variation in the sample or large repeats. So, just because it is split in a unitig does not mean the contig is incorrect.

Some potential things to check: Is the single contig circular? Have you tried mapping the reads back to the assembly to see if there is any discrepancy in read coverage at the unitig breakpoint in the contig? You can also increase the stringency of the repeat splitting (see the heterozygous parameters: http://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak) rather than decreasing the ca/cp parameters increase them, something like ```"batOptions=-ca 5000 -cp 500"``` (the default is 2000/200).

**Comment by Josh-Lefler** [comment]
Thanks for the feedback!

I'm assembling a strain of a Leptospira species for which I've assembled many previous strains, so I have an idea of what to expect in terms of number of structures and their sizes (hence the rather specific sizes I provide), so I'm not basing this off the unitig break points but what I've recovered from my previous assemblies (the size of the unitigs seems to imply that the 3 contigs typically found for this species have been merged!). Yes, the resulting contig is circular. 

I'm currently fooling around with aligning the original reads to the contig and other things to see what's going on. I'll let you know what happens!

**Comment by Josh-Lefler** [comment]
Just a little update:

My suspicions were confirmed with a whole genome alignment b/t the genome in question and another genome I assembled of same species but different strain -- the single contig was a merging of two chromosomes. 

Toying with the canu parameters I've only been able to resolve two contigs that are equivalent to the sizes of the two chromosomes, however both ends of each contig overlap with one another. I've decided to just proceed and circularize the two contigs individually and things should be fine.

Thanks again for your help!

**Comment by skoren** [comment]
Thanks for the update, sounds like this is resolved? Do you mind posting what parameters you changed for other users?

When you say the ends of the contigs overlap with one another, the two different contigs overlap to each other or the contig ends from the same contigs overlap? The latter is expected for circular chromosomes, there is a redundant bit of sequence due to the assembly going around the circle more than once so that needs to be aligned and trimmed. If it's the former, that is probably a repeat which caused the mis-assembly you originally saw.

**Comment by Josh-Lefler** [comment]
Here:

Based on my previous assemblies, I would expect something like this:

![graph](https://user-images.githubusercontent.com/22378652/33676392-7a1eac1e-da6a-11e7-95fb-5656e5982835.png)

What I got was this:

![graph](https://user-images.githubusercontent.com/22378652/33676593-fb9feb54-da6a-11e7-936b-f824823a0204.png)

So yeah, I thought it was some shared repeat across the structures which merged them together.  

I played around with batOptions and increasing the default corOutCoverage to see if I could recover a (if any) plasmid. I found that your recommendation `"batOptions=-ca 5000 -cp 500"` was enough to resolve chromosome I and chromosome II (though they're still connected by overlap edges as per below). Never managed to get full separation so I extracted the two large contigs for manual circularization.

![graph](https://user-images.githubusercontent.com/22378652/33676976-1f2695c2-da6c-11e7-8a79-21674a37cad7.png)
