### ISSUE TITLE
too few reads getting into the error correction step

### ISSUE THREAD

**Issue by aswathyseb** [marbl/canu#71]
Hi all,
I am starting the assembly pipeline with ~500 reads and the program finishes successfully without any errors.But nothing gets assembled. I noticed that only very few reads (~35) gets into the correction step and hence after correcting, I have too few reads to assemble.Could someone help me to figure it out?

What I noticed is that --min-store-length parameter in the overlapper algorithm is to ~3700 and I suspect this is removing most of my reads from entering the correction step. If this is the problem, How can I change this parameter while running canu?

Thanks you very much in advance for your inputs.

**Comment by skoren** [comment]
The default is to only try to correct the longest 40X. You can control this with the corOutCoverage=XXX parameter. For example, setting corOutCoverage=100 would try to correct the longest 100X. You can set it to larger than your input coverage if you want to correct all data. 

If you have a very small genome with a few long reads accounting for the majority of it (like lambda with a 30K read for a 50K contig) it may get flagged as unassembled by Canu because it doesn't expect a single read to span your genome. I would suggest checking your asm.unassembled.fasta file if this is the case for your genome.

**Comment by aswathyseb** [comment]
Thank you very much for the quick response. So does that mean, if we have a small genome and we have many reads covering the entire region, canu won't try to put them together and give a single sequence?  
Mine is a small region from lambda phage and I have many reads covering the region. Like you said, I have my corrected reads in the  asm.unassembled.fasta file and since they are all long reads covering the region, it seemed to me that they could have been easily put together.

**Comment by skoren** [comment]
The unassembled set includes single reads that could not be assembled as well as contigs failing some complexity criteria but which may be composed of multiple reads. The default rules are if a contig is over 75% covered by a single read it's considered unassembled since, in general use cases, you wouldn't expect your reads to be equal in size to your genome. I would suggest taking the largest unassembled contig which is comprised of more than a single read, the asm.layout file will tell you how many reads each contig has.

**Comment by aswathyseb** [comment]
Thank you very much. That helped a lot!
