### ISSUE TITLE
Threads not being used in MHAP?

### ISSUE THREAD

**Issue by pbfrandsen** [marbl/canu#715]
Hello all,

Thank you for the great tool. I'm running canu 1.6 on a Linux server with 2TB of RAM and 96 CPUs with the following command:

```
canu -p first_test -d test_all_pacbio useGrid=false gnuplotTested=true genomesize=3.912g ovsMethod=sequential corMhapSensitivity=normal corOutCoverage=40 -pacbio-raw `cat reads.txt`
```

Canu does a fantastic job of finding available resources:

```
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_45' (from '/share/apps/java/jdk1.8.0_45/bin/java').
-- Detected 96 CPUs and 2020 gigabytes of memory.
-- Detected Sun Grid Engine in '/opt/gridengine/default'.
-- Grid engine disabled per useGrid=false option.
--
-- Reset concurrency from --
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl    256 GB   32 CPUs x   3 jobs  (k-mer counting)
-- Local: cormhap   48 GB   16 CPUs x   6 jobs  (overlap detection with mhap)
-- Local: obtovl    16 GB    8 CPUs x  12 jobs  (overlap detection)
-- Local: utgovl    16 GB    8 CPUs x  12 jobs  (overlap detection)
-- Local: cor       32 GB    4 CPUs x  24 jobs  (read correction)
-- Local: ovb        4 GB    1 CPU  x  96 jobs  (overlap store bucketizer)
-- Local: ovs       32 GB    1 CPU  x  96 jobs  (overlap store sorting)
-- Local: red       16 GB    8 CPUs x  12 jobs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  96 jobs  (overlap error adjustment)
-- Local: bat      512 GB   32 CPUs x   3 jobs  (contig construction)
-- Local: cns      128 GB    8 CPUs x  12 jobs  (consensus)
-- Local: gfa       32 GB   32 CPUs x   3 jobs  (GFA alignment and processing)
```

However, it has been on the corMhap stage for 5 days and it is still on the first batch of 6 jobs (out of 523). When I look at the resource use with `top`, it shows 6 processes, but every time that I've examined it, 5 processes are using only 100% of a CPU and one fluctuates between 100% and ~1100%. Is this normal behavior? I am wondering if I have done something wrong with the configuration of the threading.

Would it be better if I raised the concurrency and lowered the threading?

Thank you,

Paul

**Comment by skoren** [comment]
The first step dumps the fasta sequences of the reads in a single thread. It's ilkely you're seeing that step. It's possible lowering cpus/increasing concurrency will help in that case but we typically run with 16 threads and see 1600 cpu utilization. You could also make each job use more memory since you have a large amount available (say 128gb and 12 cores letting you run 8 jobs). 

Given a 4gb genome, your assembly is going to take a while on a single machine, maybe a month (a human genome takes about 25k cpu hours so 25k / 96 = 11 days but there are steps which utilize only one core which will inflate the wall-time. A grid would be better for this size of genome.

**Comment by skoren** [comment]
Idle, closing.
