### ISSUE TITLE
Add support for module environment

### ISSUE THREAD

**Issue by Phhere** [marbl/canu#717]
On many HPC-Systems most of the software is not directly installed onto the servers but available by using lmod or module environment.
This requires that when run in grid-mode canu should also load these modules.

It would be create when there would be an option to run commands before the canu call in submitted jobs.

**Comment by skoren** [comment]
Any reason this can't be handled by environment inheritance for the canu job? Typically SLURM automatically does this and you can do it with -V on SGE (and similar on others).

**Comment by Phhere** [comment]
It is possible to use environment inheritance but this causes to use the wrong binaries. We are using different binaries for our login nodes and our different islands inside of our cluster. So it would be good to load these modules inside the job

**Comment by brianwalenz** [comment]
Every job canu runs is wrapped in a shell script.  I wanted to propose adding a 'precondition' command to each shell script canu runs.  But this won't help 'module' because the 'module' run in the precondition script would change the environment only for the precondition script, and not the canu script.

So, we'd need to support adding an arbitrary block of script to the canu scripts.  If this can be done on one line, the 'precondition' command would still work.  Something like:
```
canu ... precondition="module load canu" ...
```
would result in canu scripts like:
```
#!/bin/sh

module load canu

syst=`uname -s`
arch=`uname -m`
name=`uname -n`

if [ "$arch" = "x86_64" ] ; then
  arch="amd64"
fi
if [ "$arch" = "Power Macintosh" ] ; then
  arch="ppc"
fi

bin="/work/canu/$syst-$arch/bin"
...
```
What kind of stuff do you need to do to setup the various environments?  Does it fit nicely on one line?

**Comment by Phhere** [comment]
Yes, i think this would be a good solution

**Comment by brianwalenz** [comment]
Implemented.  Use something like preExec="module load canu".
