### ISSUE TITLE
Canu correct on restriction-generated genome subsets

### ISSUE THREAD

**Issue by claumer** [marbl/canu#719]
Hello,

I've been attempting to use canu to assemble a relatively small invertebrate genome, circa 150 mb size, using ONT 1D reads. The critter is extremely small, such that it's not possible to get more than a few hundred picograms of DNA from a single individual. Therefore, I've had to resort to some clever long-range amplification strategies. To produce relatively long fragments from such small quantities of DNA, I chose to split a DNA extraction into 8 parts, and digested each with some 6-cutter restriction enzymes. I then do end repair, ligation, and PCR amplification, and long story short, get libraries with reads between 0.5-10 kb, typically N50 3-3.5 kb. I've then pooled each library into a flowcell, giving each subset its own barcoding index, getting about 2.8 million reads and almost 5 Gb of data. 

I have one canu run which has been going for a long time, using all reads pooled together. But, my intuition is that I should be able to run the "correct" step on each barcode separately -- because of the nature of restriction fragmentation, every time two reads sample a base, they should sample all bases falling between two restriction sites, so the correction step should be efficient even on relatively low read coverage. So, I've set 8 canu jobs up to run the correct step on each barcode set...

And have been finding that they've been failing, with an error that is not particularly meaningful to me. I attach the stdout from an example run, which might help diagnose what's going wrong here.

Do you have any ideas? Is this restriction-fragmented type of library just so unusual that it breaks some of the assumptions going under the hood in canu's correct step? Or is there perhaps something simple I can change to get the correct step to finish on a per-barcode level?

Thanks muchly,
Chris L

[canu_singleRE_failure_log.txt](https://github.com/marbl/canu/files/1523983/canu_singleRE_failure_log.txt)

**Comment by skoren** [comment]
Amplified input is not very good for assembly. It introduces biases in the coverage and might not represent the full genome. That combined with the short read lengths is probably not going to assemble very well. We typically end up sequencing siblings or populations in the case when one sample is insufficient rather than doing amplification.

First, I'd suggest switch to the release rather than tip as it is more stable. From the logs, there is only 3x of input coverage that is not going to work. There isn't enough redundancy to make an accurate corrected read. I'd stick with using the full dataset simultaneously as it will use data from all digestions to correct each other which will work better. You can try the faster run options documented on the 1.6 release notes if you want to decrease runtime (```overlapper=mhap utgReAlign=true```).

**Comment by skoren** [comment]
Idle, closing.
