### ISSUE TITLE
What does this error mean and what's a general solution?

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#734]
Dear developers,

I run canu starting with a corrected reads and from the step 'trimming'. But it reports this problem. Is there any good suggestion for me to solve this problem? Around 324 jobs failed with the same error.

version: canu 1.6
step: trimming

ERROR: short read on './bucket0066/sliceSizes'.
ERROR: read 0 sizes insteadof 231.
ovStoreSorter: stores/ovStoreWriter.C:291: uint64 ovStoreWriter::loadBucketSizes(uint64*): Assertion `nr == _fileLimit + 1' failed.
/tmp/slurmd/job14446231/slurm_script: line 77:  8812 Aborted                 (core dumped) $bin/ovStoreSorter -deletelate -M 4 -O . -G ../lucidus.gkpStore -F 230 -job $jobid 439

**Comment by skoren** [comment]
Generally this is a filesystem issue. The filesystem is failing to return a valid block from the file. Either the file is corrupt or the read failed due to networking/connectivity issues. The easiest way is to remove the ```asm.ovlStore.BUILDING``` folder and run with ```ovsMethod=sequential```. This will run a single job to build the overlap store rather than parallelizing it. It's slower but safer if your filesystem can't keep up with the I/O.

**Comment by nottwy** [comment]
Thank u for your help.
The parameter 'ovsMethod=sequential‘ solves my problem.
