### ISSUE TITLE
I have a doubt about the covstat in the final assembly genome

### ISSUE THREAD

**Issue by fanr123** [marbl/canu#74]
Hi,all
I have a doubt about the covstat in the final assembly genome. For example,
>tig00000001 len=26963 reads=34 covStat=22.51 
>tig00000002 len=14617581 reads=48278 covStat=2194.64 
>tig00000006 len=2359688 reads=3417 covStat=3357.18 
>tig00000102 len=624275 reads=2191 covStat=-14.18 

How is the covstat calculated and what does the negative value mean?

**Comment by brianwalenz** [comment]
It's the log of the ratio of the contig being unique vs it being two-copy, based on the number of reads used to form it.  http://wgs-assembler.sourceforge.net/wiki/index.php/Celera_Assembler_Theory#Coverage-based_repeat_discrimination

Positive means more likely to be unique, negative means more likely to be repetitive.  It is flagging tig102 as having too many reads to be unique, based on the rest of the contigs.  Given how large the contig is, this could be caused by a pile up of reads in a few repeats, or it could be indicating that this is a contaminant sequenced at higher coverage than the primary target.

**Comment by fanr123** [comment]
Thanks a lot.
