### ISSUE TITLE
Shared libs

### ISSUE THREAD

**Issue by outpaddling** [marbl/canu#741]
Good morning,

Are libcanu and libleaff meant to be used by other programs, or just within canu?

If they're meant for public consumption, could you also build them as shared libs by default?

Thanks,

   Jason

**Comment by skoren** [comment]
We haven't documented the APIs which have changed a few times since Canu 1.0 so we weren't planning on making them public but if they're useful we could build them as shared libs as well.

**Comment by outpaddling** [comment]
If you're not planning to make them public, I would probably just omit them from the install in our package managers for now.  If someone else decides that they're useful outside canu, I would encourage building shared libs at that time, as that's preferred by package managers like Debian packages, FreeBSD ports, etc.

I just committed the FreeBSD port, so in a couple days (whenever the package build farm gets around to it), FreeBSD users will be able to install canu by simply typing

pkg install canu

I will do the same for pkgsrc after the freeze for the next quarterly release is over (early January).  Binary packages will then be generated for RHEL/CentOS 6 & 7, Mac OS X, NetBSD, and SmartOS.

Details for anyone who's interested:

http://uwm.edu/hpc/software-management/

**Comment by brianwalenz** [comment]
Given this is over a year old and still no action from me....I'm closing.  I had left it open in the hope that I'd get motivation and/or figure out how to easily make shared libraries.  It's unlikely anyone will find the shared libraries useful, so, yup, just install the binaries.

I'm honored to have a port.  Canu is actually developed on FreeBSD -- I've been using it since 2.2.5, installed via floppies.

Your pull request for limiting the number of jobs is, sadly, still open; I like the idea, but not the implementation.  I want to overload the various 'Concurrency' options to do this but haven't had the time.
