### ISSUE TITLE
change mhap parameters and do not know if they work

### ISSUE THREAD

**Issue by bzvew** [marbl/canu#742]
I set corMhapOptions, and below is the the content in mhap.sh in 1-overlap folder when running:

```
if [ ! -e "results/$qry.mhap" ] ; then
  /usr/bin//java -d64 -server -Xmx13312m \
    -jar  $bin/mhap-2.1.2.jar  \
    --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 \
    --num-hashes 768 \
    --num-min-matches 2 \
    --threshold 0.73 \
    --filter-threshold 0.000005 \
    --ordered-sketch-size 1536 \
    --ordered-kmer-size 12 \
    --num-threads 16 \
 --repeat-idf-scale 2.0 --repeat-weight 0.9 \
    -f  ../0-mercounts/step1.ms16.frequentMers.ignore.gz  \
    -s  ./blocks/$blk.dat $slf  \
    -q  queries/$qry  \
 > results/$qry.mhap.WORKING \
```

I see there is a default value:--repeat-weight 0.9 --repeat-idf-scale 10
And later that is changed to --repeat-idf-scale 2.0 --repeat-weight 0.9

I do not know if that changed the default value, and I test a number of parameters for --repeat-idf-scale and --repeat-weight, but the running time is nearly the same for the task until the end of overlap.

**Comment by skoren** [comment]
Yes, the later values will overwrite the earlier values. All the parameters used are logged in the output files so you can look at ```1-overlapper/precompute.*.out``` or ```1-overlapper/mhap.*.out``` to confirm the parameters change. Adjusting the repeat scale will affect the precompute but will have pretty much no effect on the mhap runtime, which is what you're running above, since it just loads prepared sketches from disk.
