### ISSUE TITLE
Add FASTQ output to indicate assembly reliability

### ISSUE THREAD

**Issue by gringer** [marbl/canu#744]
See original question (and answers) from Bioinformatics Stack Exchange here:

https://bioinformatics.stackexchange.com/questions/3167/can-the-canu-assembler-output-a-fastq-file-of-the-final-assembly-just-like-hgap4

> The HGAP4 assembler outputs a fastq file of the final assembly such that I can see how reliable the sequence is along the genome. On the other hand, canu does no such thing, which means I do not know how much I can trust each nucleotide in the assembly? Is there a way canu can output the fastq file as well or at least some depth information at each base?

I assume that at least the error correction phase of assembly has an indication of the reliability of bases in corrected sequences. Could a similar procedure mapping reads to the genome be used to produce estimates of sequence reliability and/or coverage?

**Comment by skoren** [comment]
HGAP4 is based on Falcon, which does not output fastq from the assembly. The fastq is generated by the signal-polishing from Arrow and reflects the consensus accuracy not necessarily the assembly correctness. You can reproduce the same fastq output by running Arrow on Canu outputs.

That said, canu outputs layout files which tells you all corrected reads which were used to build a contig. You can get coverage and similar information using ```tgStoreDump```, they're not output by default because the files can end up quite large. We do have quality values for the corrected bases as well but those are currently not saved. Future releases will let you get that information as well.

**Comment by skoren** [comment]
Closing, inactive. Equivalent output to HGAP can be produced by running Arrow on Canu results.
