### ISSUE TITLE
Assemble step uses correction output instead of trimming output

### ISSUE THREAD

**Issue by eldariont** [marbl/canu#747]
Hi,

I use canu 1.6 (Linux, single machine) to assemble a mammalian genome. I perform each of the three steps individually and noticed that the 3rd step (assemble) uses the corrected reads although I asked it to use the trimmed reads.

These are my commands:
`canu -correct -p assembly -d assembly_dir genomeSize=2g maxMemory=280g maxThreads=60 -pacbio-raw raw/*.fa.gz`
`canu -trim -p assembly -d assembly_dir genomeSize=2g maxMemory=280g maxThreads=60 -pacbio-corrected assembly_dir/assembly.correctedReads.fasta.gz`
`canu -assemble -p assembly -d assembly_dir genomeSize=2g maxMemory=280g maxThreads=60 -pacbio-corrected assembly_dir/assembly.trimmedReads.fasta.gz`

This is the beginning of the log of the 3rd step:
```
-- Canu 1.6
--
-- CITATIONS
--...
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_141' (from 'java').
-- Detected gnuplot version '5.0 patchlevel 5' (from 'gnuplot') and image format 'png'.
-- Detected 80 CPUs and 1007 gigabytes of memory.
-- Limited to 280g gigabytes from maxMemory option.
-- Limited to 60 CPUs from maxThreads option.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl    140 GB   30 CPUs x   2 jobs  (k-mer counting)
-- Local: cormhap   48 GB   15 CPUs x   4 jobs  (overlap detection with mhap)
-- Local: obtovl    16 GB    6 CPUs x  10 jobs  (overlap detection)
-- Local: utgovl    16 GB    6 CPUs x  10 jobs  (overlap detection)
-- Local: cor       18 GB    4 CPUs x  15 jobs  (read correction)
-- Local: ovb        4 GB    1 CPU  x  60 jobs  (overlap store bucketizer)
-- Local: ovs       32 GB    1 CPU  x  60 jobs  (overlap store sorting)
-- Local: red       16 GB    6 CPUs x  10 jobs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  60 jobs  (overlap error adjustment)
-- Local: bat      140 GB   30 CPUs x   2 jobs  (contig construction)
-- Local: cns       70 GB    8 CPUs x   7 jobs  (consensus)
-- Local: gfa       32 GB   30 CPUs x   2 jobs  (GFA alignment and processing)
--
-- Found PacBio corrected reads in 'assembly.correctedReads.fasta.gz'.
--
-- Generating assembly 'assembly' in 'assembly_dir'
--
-- Parameters:
--
--  genomeSize        2000000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
```

I do not understand why it found corrected reads in assembly.correctedReads.fasta.gz and not in assembly.trimmedReads.fasta.gz.

When I execute the 3rd step in a separate directory (by giving "-d other_dir") it works alright and prints `-- Found PacBio corrected reads in the input files.` instead of `-- Found PacBio corrected reads in 'assembly.correctedReads.fasta.gz'.`.

Do you have any idea? :)

**Comment by brianwalenz** [comment]
This part has been mostly rewritten since 1.6 came out.  I've got some changes to make before it supports this style of execution, and I'll probably get those committed tomorrow.

The bug appears limited to running each stage individually.  There's some complicated logic in there to figure out if the input reads should come from an existing gkpStore, or from a previous intermediate result, or from the input files on the command line.  When the assembly stage is run manually, it's detecting the correctedReads first, then (incorrectly) ignores the existing trimmedReads.  Further, since it found an intermediate result, it completely ignores the file given on the command line.

If the three stages are run automatically, the detection step is skipped - it just knows to use correctedReads or trimmedReads as appropriate.

So, a bunch of workarounds:

1)  Swap the two lines in canu.pl at lines 367/368, and that _should_ fix the problem (I haven't tested).  It'll still ignore the file given on the command line, but will detect the correct intermediate result.

2)  Run in a new directory for each step, using the output from the last step as input:
```
canu -p asm -d step1 ....
canu -p asm -d step2 ... -pacbio-corrected step1/*correctedReads.fasta.gz
canu -p asm -d step3 ... -pacbio-corrected step2/*trimmedReads.fasta.gz
```

3)  Use the latest unreleased code.  Note that I still need to commit a few changes.  I'd appreciate any testing done, but this version isn't quite ready for production yet.  In particular, there is a problem in the corrected reads that slightly degrade large and/or complex assemblies.

**Comment by eldariont** [comment]
Thank you for looking into this! :)
For the meantime I used workaround 2 as I already discovered that separate directories solve the issue.
Cheers, David

**Comment by brianwalenz** [comment]
I just made sure (and updated) tip for this style of execution.
