### ISSUE TITLE
canu failed with 'failed to create the overlap store' but no zeros in overlap

### ISSUE THREAD

**Issue by marcelauliano** [marbl/canu#769]
Hey guys, 
I'm running canu for a 3.5Gb mammal genome, I have about 24x coverage of sequel reads.

Canu is failing in the /canu-1.6/Linux-amd64/bin/ovStoreBuild part of the pipeline, but all logs seem to be pretty sane, no failure messages anywhere, so it's been hard for me to find out what the issue is.

My canu command line is: 

'/canu-1.6/Linux-amd64/bin/./canu -p cdida-canu1 -d canu genomeSize=3.5g -pacbio-raw Track*.subreads.fa.gz useGrid=false ovsMethod=sequential maxMemory=512G maxThreads=40

The main log is attached. The final of it is:

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to create the overlap store.
ABORT:
ABORT: Disk space available:  67108.789 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/cdida-canu1.ovlStore.err):
ABORT:
ABORT:

But when I look at ovlStore.err (log attached), there are no zeros or anything. It seems sane. Also files inside the 1-overlapper folder seem sane. It's just not being able to finalize to build the canu1.ovlStore.BUILDING folder.

Some more information: mhap job took 13 days to run (in a previous configuration of 64 cores, 252Gb RAM) but it finished without problems. 1-overlapper folder has 2,4T of tmp data, and canu1.ovlStore.BUILDING folder right now has 4,1T of data. 
I already tried to erase canu1.ovlStore.BUILDING folder and run canu again (then I changed to a node that has 40 cores and 512 Gb RAM) but after 24 hours it stopped again in building it.

I'm a little lost, since the logs don't seem to indicate exactly what is the problem. Any inputs will help a lot! 
Thank you so much!
[canu1.ovlStore.err.txt](https://github.com/marbl/canu/files/1677069/canu1.ovlStore.err.txt)

[mainlog.txt](https://github.com/marbl/canu/files/1677124/mainlog.txt)

**Comment by brianwalenz** [comment]
Yes, the logs show nothing amiss.  Were there more than 188 mhap jobs?  There should be one "bucketizing" message per mhap output file.

I suspect it's hitting some limit on the number of open files.  If so, increasing the allowed memory for store building (parameter ovsMemory) will help.  It's currently allowed to use 4GB memory; doubling will halve the number of open files.  Other than that, there's no gain to using more memory here.

In your mainlog.txt, you can run the same ovStoreBuild command by hand, instead of restarting canu.  The -M parameter there controls memory usage.  "-M 4-32" lets ovStoreBuild pick a reasonable size from between 4GB and 32GB.  I'd try just 16 or 32 first.  If it finishes successfully, rename the *.ovlStore.BUILDING directory to just *.ovlStore and restart canu.

Adding saveOverlaps=true will prevent canu from deleting the mhap outputs.  It normally does this after the store is created, but since they took quite a while to compute, and you're having trouble building the store, better to waste a little disk space and be safe.  Once the correction process gets under way you can manually delete the mhap outputs.

**Comment by marcelauliano** [comment]
Dear Brian,
Your advice worked. I've run it with -M 30 and it has finished. Now I've just restarted canu.

Thanks a lot for your fast answer! The cluster I use here had a few system problems, but now canu is back again running. The ovlStore took something like 2 days!

Let's hope it will finish without further errors now. I send news soon!
Cheers,

**Comment by brianwalenz** [comment]
Glad to hear.  I'm closing, but feel free to update with N50 and etc.
