### ISSUE TITLE
Restarting Canu after error

### ISSUE THREAD

**Issue by aviantask** [marbl/canu#77]
Canu pipeline has failed with following error -- 
```
----------------------------------------
Warning: multiple IDs for job cor_asm got 6 and should have been 1.
----------------------------------------
-- Starting command on Thu Mar 24 04:18:28 2016 with 81541.3 GB free disk space

    qsub \
      -l mem=4g \
      -l nodes=1:ppn=1 \
      -l walltime=300:00:00 \
      -q cegs  \
      -W depend=afteranyarray:14449024[].hpc-pbs.hpcc.usc.edu:14449046[].hpc-pbs.hpcc.usc.edu:14449047[].hpc-pbs.hpcc.usc.edu:14449048[].hpc-pbs.hpcc.usc.edu:14449049[].hpc-pbs.hpcc.usc.edu:14449050[].hpc-pbs.hpcc.usc.edu \
      -d `pwd` \
      -N "canu_asm" \
      -j oe \
      -o /staging/Canu_assemblyTrial/CDCFrontier_canu1.1/canu-scripts/canu.08.out /staging/Canu_assemblyTrial/CDCFrontier_canu1.1/canu-scripts/canu.08.sh
qsub: submit error (Invalid Job Dependency)

-- Finished on Thu Mar 24 04:18:29 2016 (1 second) with 81541.3 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 208.
ERROR:
================================================================================
```
I am unsure how to restart the pipeline after this error. What checks/steps should I take to handle this error before restarting the pipeline?

**Comment by skoren** [comment]
This is a PBS race condition that can't be fixed. A subset of your jobs from the previous task failed (6 it looks like) and Canu re-ran them. Since PBS doesn't support holding on the job name, but needs an ID, Canu checked the IDs to hold for and submitted the next command. By the time this happened, one of the jobs had finished and PBS complained. There is no way to avoid this in the case where a subset of jobs fail on the initial run.

To restart Canu, wait for the jobs listed in the depend=afterany list to finish and re-run your original command.
