### ISSUE TITLE
Invalid bases

### ISSUE THREAD

**Issue by dandepledge** [marbl/canu#776]
I'm exploring the possibility of using CANU to correct direct RNA nanopore sequencing data. However, Gatekeeper is kicking up a fuss over the presence of invalid bases 

read '@2cb75810-8628-4311-a6f1-77cbd151dfde runid=b73494dadc1605823b4718931b68e35f28fcf872 read=101 ch=286 start_time=2018-01-23T21:03:01Z' has 818 invalid bases.  Converted to 'N'.

I am pretty sure this is due to the presence of U rather than T in the sequence reads.

Is this something which could be fixed in the next update?

Dan

**Comment by brianwalenz** [comment]
I could add a translation of U to T, but supporting U directly would be a big task -- everything that deals with sequence data assumes a four letter alphabet.

If you're fine getting outputs with T instead of U, I can probably get that in the next release -- we're hoping to launch final tests tonight or tomorrow, but that seems like a trivial change to make.

Later, I can probably convert T's back to U's for contigs and unitigs.  Reads, I'm not so sure I can do that automagically.  Both aren't trivial, so I'd rather you be satisfied getting T's in your output.

**Comment by dandepledge** [comment]
Hi Brian,

Translation of U to T definitely sounds the simplest solution. It won't
impact on downstream analyses. As you say, it's simple enough with FASTA
files outside of canu but is a little more awkward with FASTQ.

The other question in all this is how will canu do with splicing? I
understand it aligns similar reads but if one contains a gap (say 100
bases, resulting from alternate splicing), will this be retained in the
final reads?

**Comment by skoren** [comment]
Canu only uses the best matches to correct a sequence so large differences will likely mean the isoform will be correctly assigned/corrected. Similar isoforms will definitely get mixed up in the correction. 

Users have reported that DNA transcripts work reasonably well. In either case, I would only use the correction not the assembly, the assembly will definitely break with transcript data.
