### ISSUE TITLE
Array jobs not supported in our HPC

### ISSUE THREAD

**Issue by patelhardip** [marbl/canu#802]
Hi
I have installed Canu (v1.7) on our [supercomputing facility](http://nci.org.au/systems-services/peak-system/raijin/) with few modifications. Our facility doesn't support running of array jobs. You can see details [here](https://opus.nci.org.au/display/Help/How+to+submit+array+jobs+on+Raijin). I was wondering if there is a way to switch of array jobs altogether in Canu. Most ideal solution would be to modify the code base so that it Canu can capitalize on supercomputing facility with >50000 cores without using Job Arrays. I am happy to contribute to the code base modification if I can get some help in terms of where to make modifications if at all possible.
Anyways, your help in turning off array jobs at this stage is greatly appreciated.
Kind regards
Hardip

**Comment by skoren** [comment]
Not having arrays will make job dependency management a bit difficult. Can you grid support a hold on a list of 3000 jobs? That would be required since Canu submits itself to wait for the completion of array jobs (which can be thousands of jobs on a large genome) but with an array it only has one ID to wait for. I don't see us supporting array-less grids because that isn't very common or efficient. I don't see a good reason against arrays in the page you linked to (in fact the explanation makes a good argument for why array jobs are better than individual jobs) and PBS does support arrays, it just seems the admins don't feel like enabling them.

You could make this work without code modifications, when Canu tries to submit an array it will write a submission shell script. You could then modify this shell script to submit the array as individual jobs, wait for those jobs to complete, and re-run Canu which will resume from that point. ```useGrid=remote``` should make Canu write the script and quit automatically. This of course requires manual intervention on your part to restart the assembly. If you want to modify the code, take a look at ```buildGridJob``` in ```scr/pipelines/canu/Execution.pm``` but you'll likely encounter issues when you try to make a dependency on thousands of jobs.

**Comment by patelhardip** [comment]
Hi Sergey
Thank you so much for your detailed response and options to tackle our problem.
Kind regards
Hardip
