### ISSUE TITLE
running canu "by hand" on LSF grid

### ISSUE THREAD

**Issue by TinaH10** [marbl/canu#812]
Hello, 

I am still having issues with running canu efficiently on our LSF computing grid. The issue arises because the software uses more memory (and being shut down by the sys admins) than allowed when not restricted in the following way:

gridOptions="-W 24:00" gridEngineThreadsOption="-R span[hosts=1] -n THREADS -x"

With the above option, the software sits for some of the steps in the waiting queue for over 3 days, which is just not very practical. A run can take weeks in this way.  So I am wondering if I can run the individual commands "by hand". 

So ideally, I would have a list of commands, and how much memory they would need. Then I would run them by hand one by one and reserve the correct amount of memory. 

Thanks or any help!

Tina

**Comment by skoren** [comment]
You can run with ```useGrid=remote``` which will print the command to submit but will not submit it. 

None of the grid options above request memory. All of them are also correct, as you want all your cores to be on a single machine. The only part of that request I can see slowing down scheduling is -x which means exclusive use of the node. Canu will request memory through the ```gridEngineMemoryOption``` which defaults to ```-M memory```. Do you have a specific step and the requested memory vs used memory which had to be killed?

**Comment by TinaH10** [comment]
Thank you. I will try this.

But we also have made some progress with this now. The sysadmin suggested to rerun with

gridEngineThreadsOption="-R span[hosts=1] -n 16,24 -x"

instead of -n THREADS. The 16,24 indicates the maximum number of threads for the smallest and the 24 the maximum number of threads for the largest node. 

I don't know why this would shorten the waiting period with, but a test run I just started right now worked. The run started right away and was not stuck for 3 days waiting. 



This is what happens when I start the software like this:

gridEngineThreadsOption="-R span[hosts=1]"

which gets it killed by the sys admins. 

JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
8344594 bharr   RUN   mpi        gwdc101     gwdc101     *teTEST[1] Mar 11 16:50

gwdc101:0 16:55:55 ~ # top
top - 16:55:56 up 46 days,  7:53,  1 user,  load average: 45.23, 45.57, 42.59
Tasks: 881 total,  11 running, 870 sleeping,   0 stopped,   0 zombie
%Cpu(s): 68.9 us,  2.2 sy,  0.0 ni, 28.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65943212 total, 35342368 free, 25511780 used,  5089064 buff/cache
KiB Swap: 12582908 total, 12397520 free,   185388 used. 38202080 avail Mem

 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
21429 bharr     20   0 16.525g 0.013t    980 R 329.6 20.5  23:35.98 meryl



Maybe I could try and run with:

gridEngineThreadsOption="-R span[hosts=1] -n 16,24"

i.e. just set the -n but not the -x? Have not tried that yet.

**Comment by skoren** [comment]
I'd guess the 16,24 is just picking a larger machine with more memory which is why it is not being killed. Can you post the preamble from Canu where it reports available resources and what resources it configured itself to use? It looks like the job is failing in meryl, can you post the shell scripts in ```*/0-mercounts/```, there should be a ```meryl.sh``` and a ```meryl.jobSubmit-01.sh``` that will have more info.

**Comment by TinaH10** [comment]
We have solved this problem now internally with the help of the admins. At least I think so. It seems like the solution is very specific to the configuration of our cluster, which in detail I am not familiar enough with to describe. It somehow has something to do with this:
https://listserv.gwdg.de/pipermail/hpc-announce/2016/000235.html
https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.2/lsf_admin/exclusive_scheduling_lsf.html

Which can cause excessive wait times for these exclusive jobs. But without the -x option, the software will always interfere with other user's running jobs.

We are now resorting to specify the grid options for each step, specific for our cluster, so that the least amount of waiting is anticipated. In my case this would be:

gridOptions="-W 24:00"
gridEngineThreadsOption="-R span[hosts=1]"
gridOptionsMERYL="-q fat -n 64 -x"
gridOptionsCORMHAP="-q mpi -n 8"
gridOptionsOBTMHAP="-q mpi -n 8"
gridOptionsUTGMHAP="-q mpi -n 8"
gridOptionsOVB="-q mpi -n 1"
gridOptionsOVS="-q mpi -n 10"
gridOptionsRED="-q mpi -n 4"
gridOptionsOEA="-q mpi -n 2"
gridOptionsBAT="-q fat -n 64 -x"
gridOptionsGFA="-q mpi -n 16"

I have not tried it yet, but will tomorrow, once the runs that are running right now finish.

**Comment by skoren** [comment]
The size of the jobs will also vary with genome size so it's possible your parameter will work on one genome but not another. To make sure it doesn't you need to set both the corresponding threads and memory options (e.g. ```batThreads``` and ```batMemory```).

I'd still be curious to see what meryl was requesting/using because we routinely run it on nodes shared with other jobs without interference (just not on LSF). I don't see any memory requested in any of the grid options, is memory automatically reserved based on cores on your cluster? That could be an issue in which case your approach to reserve a corresponding number of threads would be correct.

**Comment by TinaH10** [comment]
sorry, I forgot to answer that question: 

meryl tried to run with the -n 1 -x option. This leads to excessive wait times. And if I don't specify -x, it will still run with -n 1 but use much more memory, than is allocated to one thread and then interferes with other users. 

Yes, you are exactly right, the way it works on our cluster is that memory is reserved based on the number of cores requested. For example, 20 cores share 64 Gb. Therefore, I have to set -n 20 to get 64 Gb, even if my software runs only on 1 core.

**Comment by skoren** [comment]
Meryl should be running with -n 32 unless your gridEngineThreadsOption specified -n 1 (not -n THREADS) as well as the -x. I could see that being a problem if the large machine has a total of 256 gb and 64 cores so to reserve 256 gb you need to reserve 64 cores not 32. I think the lack of memory request explains the issue. Is there any reason your cluster doesn't support memory requests? That would be the easiest solution, Canu will use -m by default to request memory (you should see it in the ```meryl.jobSubmit-01.sh```) or you can overwrite it using ```gridEngineMemoryOption```.

If you don't have support for memory reservation, I would suggest setting the memory and threads for each Canu component (```canu -options |grep memory``` and ```canu -options |grep threads```) rather than the individual grid options because those will vary by genome. You can leave the queue and -x options for the individual tasks but let Canu fill in the threads (leave the -n THREADS in your gridEngineThreadsOption options.

Either way, it doesn't seem like there is anything here for us to fix in the code.

**Comment by skoren** [comment]
Inactive, I assume resolved? Re-open if not fixed.
