### ISSUE TITLE
optimizing I/O during correction

### ISSUE THREAD

**Issue by kevfengler227** [marbl/canu#816]
I have started using staging on the scratch space on the cluster nodes to mitigate potential file system I/O issues. However, I am trying to figure out if I am creating I/O issue by running too many of the jobs at once. Is the entire gkpStore copied to each node? With access to 1000 cores I can get 250 correction jobs running at once. So the same file is being access and copied by 250 machines at once, right? If so, would it be better to throttle back the number of concurrent jobs and create less jobs? What is the best way to do this?

Thanks,
KF

**Comment by skoren** [comment]
The entire gkpStore is copied yes, multiple times if multiple nodes land on the same node. However, this type of streaming I/O is typically handled OK by the parallel file systems (we do this on our GPFS system with thousands of concurrent jobs). The file gets cached and since the access is all read-only and sequential it is not that I/O intensive. The expensive part is doing random seeks on the same file which only happens on the local disk.

**Comment by kevfengler227** [comment]
OK, thanks. I am getting complaints that I am killing our cluster with Canu somehow during this step or the next. Could increasing the --hashbits to 25 be problematic? I did this to overcome error during trimming/1-overlapper.

KF

**Comment by skoren** [comment]
No, if anything the hash bits will decrease I/O because there will be fewer jobs. The staging within Canu is only done in the correction step so neither trimming or unitigging will do anything with it. You can always modify the grid options for the Canu steps to limit the parallel number of jobs (-tc on SGE for example).

**Comment by skoren** [comment]
Some recent commits (https://github.com/marbl/canu/commit/26a8fb47e85ec12d0ca069cc3ff30817545d5c99) will reduce the gkpStore size further which should fix this issue and will be part of the next release.
