### ISSUE TITLE
Assembling Phage/Cosmid Genomes

### ISSUE THREAD

**Issue by zachcp** [marbl/canu#818]
Hi Team Canu,

I have a question that is related to  #552. I have cosmid sequences that I am assembling but in many cases I have ~40x coverage of the same sequence.  My output `asm.unasssembled.fasta` file looks like a perfect multiple sequence alignment (with a few errors here and there), yet no single assembly/consensus is chosen as the contig in `asm.contigs.fasta`.

In #552 you recommended using the following settings: `contigFilter="2 1000 1.0 1.0 2"` and I am wondering if this advice has changed. I am using Canu 1.7 on linux on a local machine and there are no compute-related issues.

I am wondering if I am missing something obvious and would appreciate any feedback.

Thanks,
zach cp

```
# run options
canu \
  -fast \
  -p test \
  -d test \
  genomeSize=40k \
  corMhapSensitivity=high \
  contigFilter="2 10000 1.0 1.0 0" \
  -nanopore-raw input.fasta

#  I've also tried the variations below the results (no contigs/unitigs file) are the same
# contigFilter="2 0 1.0 0.5 0" \
# contigFilter="2 0 1.0 0.5 0" \
# contigFilter="2 1000  1.0 0.5 2" \
```

**Comment by brianwalenz** [comment]
The contigFilter parameters changed a while back.  I'm sad Canu didn't complain about the old format.  See:

http://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why
http://canu.readthedocs.io/en/latest/parameter-reference.html#contigfilter

I'd be happy to run them over here and look through the intermediate files (if small enough, email the reads to me, otherwise, upload the the FTP listed in the FAQ).  At least, I'd like to see the *.report in the root assembly directory.

One easy thing to try is to _increase_ the genome size parameter to 4m.  Canu uses this for correction and trimming decisions; the actual assembly doesn't use it at all.  Effectively, all the reads become unique (nothing is a repeat) and precious (everything is low coverage).

**Comment by zachcp** [comment]
thank you so much for your quick response, @brianwalenz

I am trying your `4m` suggestion now and will also send you some reads shortly.

zach cp

**Comment by zachcp** [comment]
@brianwalenz you are a wizard. The `4m` trick does rescue one of the cosmids in my test set, but not all.  I've just emailed you a few sequences. Thanks again.

**Comment by brianwalenz** [comment]
I'll look at it tonight or tomorrow.  If not, you know how to bug me.  ;-)
