### ISSUE TITLE
Large part of the genome in unassembled.fasta?

### ISSUE THREAD

**Issue by jonbra** [marbl/canu#827]
Hi,
I have assembled Nanopore reads using Canu v1.6 (I first error corrected the reads with Illumina data using Lordec). I notice that the unassembled.fasta file was much larger (100394 sequences) than the contigs file (5069 sequences). And when I mapped a set of genomic Illumina reads to each of the files, almost the same number of reads mapped to each. The only difference was that a lot of reads mapped multiple times to the unassembled file, and much more unique alignments to the contigs file. What could be the reason that almost the same portion of genomic reads map to the two files?

Thanks

Mapped to contigs.fasta:

```
79854061 reads; of these:
  79854061 (100.00%) were unpaired; of these:
    11962095 (14.98%) aligned 0 times
    33645483 (42.13%) aligned exactly 1 time
    34246483 (42.89%) aligned >1 times
85.02% overall alignment rate
```

Mapped to unassembled.fasta:

```
79854061 reads; of these:
  79854061 (100.00%) were unpaired; of these:
    9561239 (11.97%) aligned 0 times
    4879456 (6.11%) aligned exactly 1 time
    65413366 (81.92%) aligned >1 times
88.03% overall alignment rate
```

Canu command: `~/canu-1.6/Linux-amd64/bin/canu -assemble -p hydrurus -d canu_correct_9_500_lordec-erate-0.144 correctedErrorRate=0.144 genomeSize=300m -maxThreads=16 -maxMemory=60 useGrid=false ovsMethod=sequential -nanopore-corrected canu_correct_9_500_lordec/hydrurus.trimmedReads.fasta.gz`

**Comment by skoren** [comment]
The unassembled fasta is mostly singleton sequences that had some issue (chimera, bad ends, etc) and so is larger in bases because it contains more than 1x coverage of your genome. Typically it is 3-5x more bases than the assembly. It can also contain collapsed repeats that couldn't be incorporated into the assembly. 

That is why your Illumina reads map to both but if you map the unassembled to the contigs most will map as well so they are redundant. So it should be safe to ignore the unassembled. If you want to make sure you're not excluding any collapsed repeats, you could keep any unassembled sequence with more than 1 read (the fasta header will tell you how many reads are in it).

**Comment by jonbra** [comment]
I see. Thanks for taking the time to answer 😄
