### ISSUE TITLE
run on Hadoop?

### ISSUE THREAD

**Issue by robmaz** [marbl/canu#835]
Canu already has support for a number of grid computing systems, and the documentation seems to suggest that it would not be impossible to add another.  While Hadoop clusters are a bit different from the class of currently supported grid computing systems, I wonder how difficult it would be to get canu to run its tasks on such a cluster, using mapreduce streaming jobs. I guess the question is mostly if the canu dataflow can fit the [mapreduce paradigm](https://en.wikipedia.org/wiki/MapReduce).

**Comment by skoren** [comment]
We're planning to support DNAnexus which uses AWS compute and requires staging and pulling data back and forth from compute nodes. This would probably be close enough to map reduce that it should be possible to port to hadoop (by modifying how data is fetched/saved).

**Comment by robmaz** [comment]
Great! Do you think this can be done as "yet another grid engine", or will this require some change to the internal logic?

**Comment by skoren** [comment]
The DNA nexus would be supported as another grid engine with some hooks to retrieve the necessary data for a given step. That would need to change for Hadoop to retrieve data in its own way but the rest should be similar.

**Comment by skoren** [comment]
We've added "cloud" mode support and DNA nexus as a grid engine in the latest in the repo. It's been lightly tested. I don't have much experience with Hadoop so can't give much detail on how you'd implement it. 

The cloud mode lets canu read/write files remotely so it removes the assumption of a global FS, not sure if that's needed for Hadoop. Overall, Canu workflow is to submit a large array job and a master job at the end to collate the results. This should fit well with map/reduce. Take a look at the Grid_Cloud.pm and Grid_Dnanexus.pm files as a start. There's also some code related to grids in Execution.pm. The code is reused for pretty much all the commands so if you get at least one submit/collate step working, they should pretty much all work.

I'm going to close this issue because we're not planning to add the Hadoop support (and don't have access to a cluster to test) but feel free to open issues if you start implementing it and have specific questions about a specific step/modification.
