### ISSUE TITLE
the comparison between triocanu and falcon-unzip

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#838]
Dear koren,

We notice that you use falcon-unzip to assemble F1 cross. And we also use falcon-unzip to assemble another genome with large size (3G).
We found that unzip module try to read all .las files into memory and we had around 20T .las files. It's hard to find a machine with so large memories. Do you have any suggestion to avoid loading all data into memories?

3ku~

**Comment by skoren** [comment]
Are you asking how we ran Falcon-unzip in the paper? It was run by PacBio using the configuration file provided in the supplement. 

From my understanding of the code, the unzip module should not be reading all the las files into memory, we've run it locally on smaller genomes where the las files were larger than the memory of the machine. A 20tb set wouldn't fit in any realistic machine. It does have a lot of I/O to randomly seek the files. You should ask the question on the falcon-unzip GitHub page or alternatively you could run falcon-unzip on dnanexus.

**Comment by nottwy** [comment]
OK, I'll seek help from pacbio/falcon-unzip.
And could you please spend some minutes helping me verify whether all las files are loaded into memory?
----------------------------------------------------------------------------------------------------
https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/mains/rr_ctg_track.py
----------------------------------------------------------------------------------------------------
file_list = glob.glob(os.path.join(rawread_dir, "m*/raw_reads.*.las"))
for fn in file_list:
inputs.append((run_tr_stage1, db_fn, fn, min_len, bestn, rid_to_ctg))

    bread_to_areads = {}
    for fn, res in exe_pool.imap(io.run_func, inputs):
        for k in res:
            bread_to_areads.setdefault(k, [])
            for item in res[k]:
                if len(bread_to_areads[k]) < bestn:
                    heappush(bread_to_areads[k], item)
                else:
                    heappushpop(bread_to_areads[k], item)

----------------------------------------------------------------------
Are all records loaded into the variable 'bread_to_areads'?
If so, all las files are loaded into memory.

**Comment by skoren** [comment]
No I don't think they are. LAS files contain lots of information including read ids/read match positions, and breadcrumbs to reconstruct the alignment. 

As background, here is my understanding of what this code is doing. It is trying to identify all reads which belong to a contig to use them to identify variants and create haplotypes. Since not all reads are corrected (only the longest), the corrected reads used to make the contig are an incomplete list. You also need to find the reads which went into making the corrected read which went into making the contig. So, the code takes all reads which have been placed in a contig and, for each of those, finds the best overlaps to it to also include in the contig. If you look at the loading function (tr_stage1), it's only storing the ID and length and only storing those over a minimum length and a max of 40 (by default) ids per read. So at most it would load # reads * bestn identifiers which should be much smaller than the full las size.

**Comment by pb-cdunn** [comment]
@nottwy, skoren's analysis is correct. I'll suggest a solution at PB GitHub.
