### ISSUE TITLE
Output contigs file has a contig made up of one read

### ISSUE THREAD

**Issue by SamanthaNicole** [marbl/canu#842]
Hello,

I am assembling some pacbio reads using Canu version 1.6 on a Mac (High Sierra) using the default settings:

`canu -p n_gon_FA1090 -d n_gon_FA1090-pacbio genomeSize=2.15m -pacbio-raw K05_subreads_fastq/*.fastq`

My question comes from the output contigs.fasta file.  One contig is the estimated genome size and is made up of 4460 reads (reads=4460), while the other is 27684bp and is comprised of 1 read.  According to the report file my coverage started at 842.25x coverage and at start of trimming was 36.43x:

```[CORRECTION/READS]
-- In gatekeeper store 'correction/n_gon_FA1090.gkpStore':
--   Found 153074 reads.
--   Found 1810858404 bases (842.25 times coverage).

[TRIMMING/READS]
-- In gatekeeper store 'trimming/n_gon_FA1090.gkpStore':
--   Found 4534 reads.
--   Found 78332258 bases (36.43 times coverage).
```

This single read contig is suspicious to me (I expected the contigs to have a minimum coverage before being finalized) and I was wondering if I am correct to be suspicious.  If so, I was hoping you had a recommendation for a parameter to change to get this down to one contig.  When I BLAST the read my hit is the genome that we sequenced with high identity so I'm confident it's not a contamination issue. I did read in the FAQ page to add the `correctedErrorRate=0.04` and `corMhapSensitivity=normal` flags to high coverage data, but when I did so I got the same results, though the sizes were slightly different (26kb instead of 27kb for the small guy, still one read). I've also tried increasing the minOverlapLength to 800 (in conjunction with the other two flags) to see if I could bridge whatever gap is being created, but that just split things into three contigs.

Any help/clarification would be greatly appreciated!
Thanks!
Samantha

**Comment by skoren** [comment]
First question would be, is the larger contig circular and have self-similarity at the ends? If so it is likely to be complete already. The small contig is being kept because it is connected in the graph, most likely it's a less frequent variant in the colony (e.g. the sample isn't perfectly clonal).

**Comment by SamanthaNicole** [comment]
Thanks for the quick response!  Yes, the large contig is considered circular via Canu prediction and when I tried the MUMmer example from the FAQ I get a huge list of alignment regions but I think this hit means that region 1-17898 aligns with 2155346-2173237 (beginning and end):

1	17898	2155346	2173237	17898	17892	99.89	2173237	21732370.82	0.82	tig00000073	tig00000073

Can I use the circularization status as a general rule to apply to other assemblies? I've been working on 4 assemblies that didn't assemble into one contig with default parameters. All of them gave me one suggestCircular=yes contig of the right genome size and one or two small ones that aren't.  These small contigs are made up of more than 1 read, but not usually more than 15 reads.  Can I make the same conclusion that it might be a less frequent variant in the colony?

Thanks,
Samantha

**Comment by skoren** [comment]
Generally, yes if the contig is predicted to be circular it should be complete. You can try mapping the shorter contig to the primary assembly to confirm it maps. 

The GFA file (contigs.gfa and unitigs.gfa) should also give you an idea how the smaller sequence potentially fits into the genome. Are you able to share one of these assemblies (fasta +gfa)?

**Comment by SamanthaNicole** [comment]
Yes, here is one. tig00000001 is the one that matches the genome, tig00000003 is the small contig, and I determined tig00000021 to be a small linear plasmid that belongs to that genome.

[b_cereus-ATCC-contigs-gfa.zip](https://github.com/marbl/canu/files/1856741/b_cereus-ATCC-contigs-gfa.zip)

**Comment by skoren** [comment]
I looked at this and forgot to post the response. The contig gfa does show the main chromosome to be circular. 
![contigs](https://user-images.githubusercontent.com/923478/38366866-1b5d234c-38af-11e8-9e94-2b5743a77fa6.png)


It looks from the unitig gfa file like the shorter contig can be integrated into the main genome as an alternate to a large chunk of sequence (the selected blue node) which is why Canu is incorporating it in the output. This could be a low-frequency variant in the sequenced colony.
![unitigs](https://user-images.githubusercontent.com/923478/38366876-1ee2e498-38af-11e8-97ab-dd704c7d769d.png)

It should be OK to take the primary circular chromosome though and trim it to remove the circular self-overlap.
