### ISSUE TITLE
Smashing haplotypes FAQ

### ISSUE THREAD

**Issue by yeban** [marbl/canu#845]
Hello,

[FAQ](http://canu.readthedocs.io/en/latest/faq.html) suggests using `ovlErrorRate` option to smash haplotypes together. But what should be the prefix? Is it `corOvlErrorRate`?

**Comment by skoren** [comment]
We typically do not. It's already set to 30% but we do lots of filtering to select best reads to correct each read and avoid collapsing repeats. I think you want to leave that alone so that you have the option of either smashing or separating haplotypes downstream rather than mixing your corrected reads which will also mis-correct repeats.

**Comment by yeban** [comment]
Thanks.
