### ISSUE TITLE
Too short contigs on Mammalian genome 

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#86]
Hi guys,

We have 27x coverage on a 3G genome. We checked out the code on March 11th. After a "successful" run, we have the following stat:

lenSuggestRepeat sum  143095587 (genomeSize 3000000000)
lenSuggestRepeat num      13251
lenSuggestRepeat ave      10798
lenUnassembled ng10       20121 bp   lg10   11332   sum  300018389 bp
lenUnassembled ng20       14384 bp   lg20   29229   sum  600009371 bp
lenUnassembled ng30       10814 bp   lg30   53370   sum  900009499 bp
lenUnassembled ng40        7899 bp   lg40   85832   sum 1200000703 bp
lenUnassembled ng50        5332 bp   lg50  131871   sum 1500001919 bp
lenUnassembled ng60        2867 bp   lg60  207314   sum 1800001024 bp
lenUnassembled sum 1982227478 (genomeSize 3000000000)
lenUnassembled num     305026
lenUnassembled ave       6498
lenBubble sum     338717 (genomeSize 3000000000)
lenBubble num         11
lenBubble ave      30792
lenContig ng10      338590 bp   lg10     620   sum  300247411 bp
lenContig ng20      207252 bp   lg20    1782   sum  600180436 bp
lenContig ng30      143429 bp   lg30    3538   sum  900110808 bp
lenContig ng40      101073 bp   lg40    6049   sum 1200008181 bp
lenContig ng50       69059 bp   lg50    9645   sum 1500009220 bp
lenContig ng60       43577 bp   lg60   15062   sum 1800022620 bp
lenContig sum 2025416508 (genomeSize 3000000000)
lenContig num      22727
lenContig ave      89119 

It seems ng50 is too low. As we have talked, this may suggest the pipeline did not finish correctly. I have checked the logs, everything looks like fine; the only problem is that we had around 7T data sitting under correction/genome.ovlStore directory.

So I will check out new code and rerun it.

**Comment by skoren** [comment]
The main factors influencing assembly quality is read length and genome complexity. An NG50 in the 70-100kb range is not unreasonable for a more complex genome with low coverage. What is the mean read length of your input dataset? What is the coverage/mean length of the corrected reads? How heterozygous is this sample? That will help guide what you can expect from the assembly.

We're also always working on improving the performance on low coverage, when you re-run, I would try the parameters:
```
corMhapSensitivity=high corMinCoverage=0 errorRate=0.035  minOverlapLength=499
```

As for the ovlStore directory, Canu leaves behind the binary stores in case you want to re-run parts of the pipeline. Since you'll be starting a new assembly from scratch, you can erase any ovlStore or gkpStore folders to save space.

**Comment by woodoo46** [comment]
We had reads with average length 13K. Since our cluster is not fully compatible with your pipeline, some steps we ran manually. Meaning the pipeline was interrupted, and we submitted jobs by hand. Although did not find any errors, it is still possible something went wrong by our manual work. We will rerun it any way.

Last, I just want to confirm that we **do not use corMaxEvidenceErate=0.3**.  

Thanks.

**Comment by skoren** [comment]
Yes, do not use it, it's auto set if you're using v1.2

**Comment by skoren** [comment]
@woodoo46 is this resolved, I saw in another issue you mentioned your latest asm was about a 400Kbp N50.

**Comment by woodoo46** [comment]
Ya, ya. Sorry. I forgot to reply. This can be closed, I think.
