### ISSUE TITLE
Error: Failed with exit code 136 (rc=34816)

### ISSUE THREAD

**Issue by codingcondemned** [marbl/canu#882]
I am gettting the following error message:
![image](https://user-images.githubusercontent.com/38774409/39342689-3b52dce8-4a2d-11e8-8412-b212c997cbec.png)

The command I used was: 
canu -p lambda -d lambda_oxford genomeSize=48.5k -nanopore-raw /the/path/to/my/workspace/pass/*.fastq

The version is: Canu1.7 and I'm running it on an Ubuntu virtual server.

Help would be appreciated 😃

**Comment by brianwalenz** [comment]
I need a bit more logging, like the command that just finished running, and any *.out or *.err that it created.  The *.report in the assembly directory can help too; at least, it'll tell if your assembly is failing due to data issues.

If you're running this in a VirtualBox shared folder, that's a known failure.  See issue #811 for discussion.

**Comment by duspriya** [comment]
I am getting the following error message 
![capture1](https://user-images.githubusercontent.com/38563652/39397093-0a19527a-4b17-11e8-8abf-a54755a7857e.PNG)

The command I used was:
canu -p ecoli  -d ecoli-mix genomeSize=4.8m -reads.fastq  -nanopore-raw  oxford.fastq

The version is: Canu1.7 and I'm running it on an Ubuntu 16.04

**Comment by duspriya** [comment]
version is canu

**Comment by skoren** [comment]
1. Don't submit an issue and email directly less than an hour later. Github is the appropriate channel for questions so wait to get a reply.

2. The error is coming from your OS not Canu because the canu command is not in your path. Google is your friend, the first hit for "command not found" explains how to fix the error. Provide the full path to wherever you installed/downloaded canu. Typically something like canu-1.7/*/bin (described on release notes page). 

3. VirtualBox has issues with FS support so make sure you read @brianwalenz comment above and don't use a VirtualBox shared folder for the assembly.

**Comment by skoren** [comment]
Idle, nothing to fix on our end. Incomplete VirtualBox FS support + PATH settings.
