### ISSUE TITLE
Question about CANU haplotyping

### ISSUE THREAD

**Issue by Lcornet** [marbl/canu#884]
Hello,

This is not an issue but a question about CANU/FALCON assembly.

I work on cassava genome with pacbio. We are interested on a specific and highly repeated region. For the region we are interested in the difference between the two haplotypes. We already try Falcon unzip assembly but for some reason, we are not satisfied. Does CANU will give us the haplotigs like Falcon do ? We don't have the possibility for CANU trio (no parents).

Thanks you,
Luc

**Comment by skoren** [comment]
So first to clarify, the falcon unzip primary contigs are not haplotigs, they are locally phased but can switch between haplotypes due to homozygous regions. The alternate haplotigs should be phased.

The answer depends on how diverged the region is and why you're not happy with the current falcon results. Canu does not have an explicit phasing step but will separate regions that are more than about 1.5-2% diverged. Regions less diverse than this might still get separated because of structural variation. 

Trio Canu doesn't necessarily need parents but frequent markers (e.g. the parental k-mers are the markers by default) but if you have phasing information from some other datasets which tells you kmers specific to each haplotype within the region (but not the full structure) you could bin the reads and assemble them separately using the trio approach.

**Comment by skoren** [comment]
Idle, closing.
