### ISSUE TITLE
Usage of Object Stores

### ISSUE THREAD

**Issue by hdzierz** [marbl/canu#900]
We are envisaging using object stores and have found your perl module "Grid_Cloud.pm". Is there any documentation how to use it? 

Thanks

**Comment by brianwalenz** [comment]
It's not a general purpose module, but an interface between our application and the DNA Nexus platform.  Most of the module is to emit shell code from perl; there's really not much magic in there.

**Comment by hdzierz** [comment]
Yes, but how do you make canu use this instead of your local file system?

Cheers

Helge

**Comment by brianwalenz** [comment]
Sorry, the original question was phrased such that it sounded like you wanted to use it independently.

It depends on having a command line utility to handle file access to the object storage, needing methods to: upload a file, download a file, delete a file, rename a file and test if a file exists.  It'd be handy if upload and download can use stdin/stdout instead of needing an actual file.  The store must be able to handle storing a hierarchy of files, or at least be able to store files with names that look like relative paths.  It should be straightforward to add support for any store that handles those operations.  That part works (mostly).

If you aren't using Slurm or SGE or PBS, then support for whatever scheduler is being used needs to be added, and that isn't always trivial to do.

I'm purposely not including specifics because I don't really want others using it quite yet.  We're not 100% happy with some pieces yet.
