### ISSUE TITLE
Heterozygosity

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#908]
Sergey,

I was reading through thread #848 where you suggested using the Genomescope to estimate heterozygosity.  Just a couple of questions.  1) what is considered high heterozygosity?  Genomescope predicts my genome's heterozygosity to be 0.27% (see below for output) - is that high enough to warrant the heterozygosity parameters.  2) An just for clarification, the histogram file we should use in Genomescope is from the trimming/0-mercounts folder (not the corrections/0-mercount folder), correct?

Thanks,

Jeff

GenomeScope version 1.0
k = 22

property                      min               max               
Heterozygosity                0.272828%         0.273887%         
Genome Haploid Length         3,833,302,032 bp  3,833,927,478 bp  
Genome Repeat Length          2,762,242,165 bp  2,762,692,855 bp  
Genome Unique Length          1,071,059,867 bp  1,071,234,622 bp  
Model Fit                     89.3165%          98.0265%          
Read Error Rate               0.329538%         0.329538%

**Comment by skoren** [comment]
Yep, either trimming or unitigging/0-mercounts, not correction. The raw reads have too much noise typically. Your genome is very repetitive though based on that info (>70%). That will likely mean longer runtime, maybe add ```OvlMerThreshold=300```. See issue #855 or #587 for some correction parameters that may speed up correction if you want to run again (since you a trimmed folder you've got corrected reads so that ran OK).

0.27% is pretty low, over 1% is medium and starts to impact assembly contiguity and can benefit from the heterozygous parameters.

**Comment by pjm43** [comment]
Run times have been long - although my bigger problems have been disk space issues (hit 66 Tb during correction).  Thanks for the quick response.
Jeff

**Comment by skoren** [comment]
Both of the parameter suggestions should reduce disk usage too.

**Comment by ersgupta** [comment]
Hi Sergey,

I am also bit concerned about the time and memory usage due to the heterozygosity in my genome. I am also considering adding ```OvlMerThreshold=300``` to sort this. Could you let me know how much does this impact the assembly, (if at all)?

Saurabh
