### ISSUE TITLE
the low coverage data for correction and trim step

### ISSUE THREAD

**Issue by huangziyan11111** [marbl/canu#918]
Hi! I have the two type of long read data (nanopore ~10X;Pacbio ~70X). I managed to run Canu to the correction and trim step, respectively. And then combined these two types trimed reads to assemble. But I am not sure if it is proper to correct the read by Canu for nanopore data, as the coverage is low. I see the the recommendation (20X is the minimum) to assemble. But I just to correct and trim. Could you please give some recommendation?

**Comment by skoren** [comment]
You probably want to correct the data together, otherwise most of the nanopore data will not be corrected. Specify ```corMhapSensitivity=normal corOutCoverage=100``` as well.

**Comment by huangziyan11111** [comment]
Thank you. When I see the previous issue, I found if combining the nanopore and  Pacbio data, the parameter is fited for nanopore. I wonder if it effects the correction of pacbio data.

**Comment by brianwalenz** [comment]
The change in parameters is to accommodate the extra noise in Nanopore reads when finding and filtering alignments.  When the Nanopore parameters are applied to PacBio reads, the correction results are nearly the same, they just take a little longer to compute.  "Nearly" the same, because some alignments that would have been filtered out with the default PacBio parameters could be used for correcting reads when the Nanopore parameters are used.
