### ISSUE TITLE
 replong error : no ovb files

### ISSUE THREAD

**Issue by ankita86** [marbl/canu#924]
Hi,
I am using replong (a canu based software) to find repeats using pacbio reads. After read correction, I got following error. I tried to troubleshoot as suggested on another thread by reinstalling canu1.4 rather than using 1.7version but cannot figure out the reason for this :
########## Error Message #################
-- Purging correctReads output after merging to final output file.
-- Purging disabled by saveReadCorrections=true.

-- Corrected reads saved in '/home/drankitanarang/Desktop/tmp/step1.correctedReads.fasta.gz'.
the folder is /home/drankitanarang/Desktop/tmp
process reads
ls: cannot access correction/1-overlapper/results/*.ovb: No such file or directory

ls: cannot access correction/1-overlapper/results/.ovb: No such file or directory
the number of totalfiles is 0
ls: cannot access correction/1-overlapper/results/.ovb: No such file or directory
no ovb files
merge the bed file
cat: *new.bed: No such file or directory
0
use ovl to find overlap

Please help in this regard.

**Comment by skoren** [comment]
We don't maintain replog so I'm sure what parts of Canu it is using. 

From the error, it looks like it failed to find overlap results, perhaps because they are being purged by Canu by default? Try adding saveOverlaps=true to whatever Canu command it is running and see if that helps. If not, try contacting the replong authors.
