### ISSUE TITLE
Canu + WTDBG

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#934]
Sergey,

Just read your post on GIS  entitled "Human genome assemblies with nanopore, an update, May 23, 2018" - great post!  In it you suggest that Canu + WTDBG is good compromise between speed and accuracy.  A couple of follow up questions - in the post you suggest using Canu's corrected reads as input for WTDBG contigging- is that the "corrected only" or the "corrected plus trimmed" reads?  Also, is your suggestion solely for Nanopore reads for would you also suggest this strategy for Pacbio Sequel reads as well?

Thanks,

Jeff

**Comment by skoren** [comment]
We only use the corrected reads, not corrected+trimmed. This saves time since you don't need to run the trimming step. WTDBG works on the corrected reads from both nanopore and PacBio (we've used this to sanity-check and validate some Canu assemblies) but the time saving is more significant for nanopore data.

**Comment by skoren** [comment]
We've been running with the parameters ``` -I reads.fa.gz -fo dbg -S 2 --edge-min 2 --rescue-low-cov-edges``` leaving the rest as default with good results but it's possible you could adjust them more.
