### ISSUE TITLE
Correction step and no more space

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#937]
Hi,

I have trouble with my assembly because I am running out of space.

I am at this step:

```
-- Starting command on Thu May 31 10:19:55 2018 with 3974.775 GB free disk space

    cd correction
    /scratch/beegfs/monthly/ptranvan/Software/canu/1.7/Linux-amd64/bin/ovStoreBuild \
     -O ./fsel_P.ovlStore.BUILDING \
     -G ./fsel_P.gkpStore \
     -M 4-16 \
     -L ./1-overlapper/ovljob.files \
     > ./fsel_P.ovlStore.err 2>&1

```
Is it possible to move the repository 1-overlapper/ somewhere else and resume the job ? 

Edit:

Apparently this directory fsel_P.ovlStore.BUILDING/ take a lot of space, is there a way to deal with this issue ?
And there are only `tmp.sort.*` files ..

**Comment by skoren** [comment]
How big is the 1-overlapper/results folder? That will give an idea of how big the store will be. 

You can't make the construction take less space but you can remove some intermediate files early, like the 1-overlapper/blocks folder. You can't remove the 1-overlapper/results folder since it is being used to generate the store but you can move it to another drive/folder and symlink it in place to continue the build.

**Comment by ptranvan** [comment]
the 1-overlapper/results has a size of 2.6T.

So I move the 1-overlapper/results  and symlink it, and run the same command ? this one:

`canu -correct -p fsel_P -d fsel_P_cor_opt genomeSize=300m maxThreads=90 maxMemory=450 useGrid=false gfaThreads=90 corMhapSensitivity=normal corOutCoverage=100 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" -pacbio-raw reads`

**Comment by brianwalenz** [comment]
What files exist in fsel_P.ovlStore.BUILDING?  To resume, you'll need to start loading overlaps from scratch: rename (or delete) fsel_P.ovlStore.BUILDING and then restart.  If any of the files in 1-overlapper were removed, those would need to be recomputed.

**Comment by skoren** [comment]
Idle, closing.
