### ISSUE TITLE
trioCanu works for short reads?

### ISSUE THREAD

**Issue by ke-shi** [marbl/canu#944]
Hi Skoren,

I have Illumina data (150-bp length, paired-end) for 50 F1s (100x in total) and their parents (6x for each), which genome size is 13 Gb. I really wanted to divide the F1 reads into two by trioCanu (v1.7) on Linux, so I picked a F1 (2x) for a trial with the following command:

`trioCanu \`
`-p asm -d out \`
`genomeSize=13G \`
`minReadLength=100 \`
`minOverlapLength=50 \`
`-haplotypemyP1 myP1_R?.fastq.gz \`
`-haplotypemyP2 myP2_R?.fastq.gz \`
`-pacbio-raw myF1_R?.fasta`

The 108,805,322 F1 reads could be divieded into three classes, P1 with 280,927 reads (0.2%), P2 with 22,861 reads (0.02%), and tons of unknown with 108,501,534 reads (99.7%). 

My question is: Is it possible for trioCanu to divide short reads (instead of long like PacBio and Nanopore) correctly? If works, do you have any recommendations for the command options?

Thanks,
Kenta

**Comment by skoren** [comment]
The algorithm is the same whether reads are short or long. Read classification is affected by your genome heterozygosity, read length, and read error rate (see figure in the preprint).  I suspect your diversity is too low to allow classification of short reads. I'd suggest looking at the F1 histogram to check the diversity/genome size estimate using something like genomescope.

Having only 6x coverage is not ideal. I'd expect most of your k-mers are noise, certainly the heterozygous kmers are (e.g. the het k-mers in each parent are at 3x). We typically recommend 30x for the parents. Have you looked at the histogram distributions for the parents to see if there is a peak other than the one at low-copy noise k-mers? Canu should have generated the histograms as part of the classification so you can use those in genomescope. Having multiple F1s will also confound the analysis since since the breakpoints between the parental chromosomes will be different between different F1s so even your binned reads will have haplotype variation.

**Comment by ke-shi** [comment]
Thanks for the suggestion. Here are the histograms not converged from jellyfish, I did not find histogram files from canu. I may need more reads.

P1 + P2 + 50 F1s
http://qb.cshl.edu/genomescope/analysis.php?code=pbvhNmYZDtAcBe0bJKiv

P1 + P2
http://qb.cshl.edu/genomescope/analysis.php?code=nzuSVQwwJtSi2DBrxwQC

P1
http://qb.cshl.edu/genomescope/analysis.php?code=f5bGi0O76W1D2EQBG4hZ

P2
http://qb.cshl.edu/genomescope/analysis.php?code=pcNPYsS8ejqZmrdO5vF9

An F1
http://qb.cshl.edu/genomescope/analysis.php?code=YvX0XyEKCayVJz8K6ivn

**Comment by skoren** [comment]
Yes, I think there is not enough coverage of either parent here based on genome scope. Either way, there isn't any parameters to change for short vs long reads, it's a function of heterozygosity and read length.
