### ISSUE TITLE
trioCanu for long contigs?

### ISSUE THREAD

**Issue by ke-shi** [marbl/canu#950]
Hi Skoren,

I have Flacon-Unzip contigs (total = 700Mb , N50 = 3Mb) for an interspecific hybrid derived from a cross between two diploids. Because the genome size of each diploid is 350 Mb, I assume the contigs are mixture of two genome sequences. I tried trioCanu with >30x Illumina short-reads for each diploid to classify the contigs into two diploids:
`trioCanu \`
`-p asm -d out \`
`genomeSize=700m \`
`-haplotypemyP1 myP1_R?.fastq.gz \`
`-haplotypemyP2 myP2_R?.fastq.gz \`
`-pacbio-corrected myHybrid.fasta`

; but failed with the message saying:
`ABORT:`
`ABORT: Canu 1.7`
`ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.`
`ABORT: Try restarting.  If that doesn't work, ask for help.`
`ABORT:`
`ABORT:   didn't find any reads in store 'haplotype/asm.gkpStore'?.`
`ABORT:`

Do I need to run trioCanu on PacBio raw reads instead of the assembled sequences, and to work on assembly again? 

Thanks,
Kenta

**Comment by skoren** [comment]
Falcon-unzip contigs are not going to be binnable because they will already mix haplotypes (each contig contains switching). So, it doesn't really make sense to bin an assembly.

I'd instead suggest making a new assembly with the raw data and binning that with your parent species. You should use the haploid genome size and make sure you read the release notes regarding higher memory requirements for the current release of trio binning, that could have caused your error here.

**Comment by ke-shi** [comment]
Thanks for quick response. I shall work on the raw reads.
