### ISSUE TITLE
moleculo support

### ISSUE THREAD

**Issue by igordot** [marbl/canu#96]
Celera Assembler used to support Moleculo (now Illumina TruSeq Synthetic Long-Reads). Are there plans to bring that over to Canu? Has anyone attempted to use those reads with the current version of Canu?

**Comment by albodrug** [comment]
Hello, 
I used moleculo data with canu by pretenting the data is pacbio corrected reads, like this: 
`canu -assemble -d directory -p prefix -pacbio-corrected moleculoa_data.fasta`
The assembly had a decent n50, but not much higher that what was achieved with newbler short illumina reads.

**Comment by skoren** [comment]
Canu has the same support for moleculo data that Celera Assembler had. Using moleculo data with the -pacbio-corrected option should be fine, you can also specify the -assemble option to not trim the data since it should already be correct. In my experience, moleculo data isn't ideal for assembly, it is generally shorter on average than either PacBio or Nanopore sequencing so fewer repeats can be spanned. When we assembled D. melanogaster with PacBio data, it was significantly more contiguous than the same genome with moleculo sequencing.

**Comment by igordot** [comment]
Thanks for the input. I've had some limited experience with Moleculo and that is similar to what I saw. Since CA is the recommended tool, but is no longer supported, I just wanted to see what the status with Canu was.
