### ISSUE TITLE
check whether data is being staged to compute nodes

### ISSUE THREAD

**Issue by Phylloxera** [marbl/canu#964]
Here is my command:
```
~/canu-1.7/Linux-amd64/bin/canu -correct \
-p gaurt1 -d /Jake/home/aaron.dickey/data/Smith/gaur/test \
stageDirectory=/local/\$SLRUM_JOBID gridEngineStageOption=lscratch:60 \
-merylMemory=60 -batMemory=60 -gnuplotTested=true genomesize=2.8g \
-pacbio-raw /Jake/home/aaron.dickey/data/Smith/gaur/gaur.fasta.gz \
stopAfter=overlap
```

Here is my setup
Linux; canu-1.7;SLURM grid

I'm trying to ascertain whether I get any benefit from staging my data to each compute node during the overlap stage... but no additional storage space appears to be consumed on /local. Did I set up my stageDirectory parameter correctly with escaping? Or has canu not reached the step that benefits from staging? (it is running 108 jobs of cormhap right now... should be done with that tonight running 15-at-a-time) Is there a way to check if canu is staging the data as desired?

Thanks, Aaron

**Comment by skoren** [comment]
I think you have a typo in your stage directory path (SLRUM_JOBID not SLURM_JOBID), otherwise the command looks correct. 

That said, the data is only staged for consensus calling for the corrected reads, not overlapping. So you won't see it in cormhap jobs at all. Since you told it to stop after overlapping, it will never stage the data here. The other steps don't do random seek on the file so the parallel FS should be able to handle it efficiently.

**Comment by Phylloxera** [comment]
That was an easy fix, thanks! I noticed that when I ran overlap before it took about 4.5 days (on fifteen 16-core nodes) and I estimated from AVERSS that ~1/2 this time the MhapConvert was only using 1 out of the 16 cores. Is this one of the single cpu bottlenecks to which some previous issues have referred?

**Comment by skoren** [comment]
MhapConvert should only use 1 thread but it's just reading/writing a file stream. The single thread bottleneck from previous issues is removed in 1.7 because it's computed in parallel in an earlier step.
