### ISSUE TITLE
is canu correction step influenced by genome size?

### ISSUE THREAD

**Issue by JifengTang** [marbl/canu#973]
we have one genome assembly project. We think the haplogenome size is about 1g, input PacBio reads about 106x.
Using genomescope, it indicates the genome size is about 480Mbp. genomescope can underestimate the genome size. The genome size can be slightly biger, such as 600m.
However the canu1.7.1 assembly using genome size =1g "genomeSize=1g corMhapSensitivity=high corMinCoverage=0 corOutCoverage=200 correctedErrorRate=0.013 ovlErrorRate=0.15" has been running for  five days. The corrected reads has been generated and currently it is running at trimming step (meryl).

I am wondering what i should do. 
1) is it worth let the assembly to be completed?
2) Stop the assembly, restart from the beginning using "genomesize=600m corMhapSensitivity=high corMinCoverage=4  corOutCoverage=all correctedErrorRate=0.013 ovlErrorRate=0.15" 
3) stop the assembly, restart from the corrected reads using "genomesize=600m corMhapSensitivity=high corMinCoverage=4  corOutCoverage=all correctedErrorRate=0.013 ovlErrorRate=0.15" 

I appreciate any suggestions from you.

**Comment by brianwalenz** [comment]
The genome size is used only to decide how many bases to output from correction.  By using corOutCoverage=200 with a 1g genome size, it'll try to output 1g * 200 bp in reads, which I think will end up being all your reads.  Otherwise, it'll discard the shortest reads.

corMinCoverage=0 leaves a lot of work for trimming to do, but I don't think it'll add significantly to the time required.  I wouldn't have picked it for the depth of coverage you have, but oh well.  I also wouldn't restart correction just to fix that parameter.

Not much more I can suggest without seeing the `*.report` (with hints about the correction quality) and `trimming/0-mercounts/*.estMerThresh.err` (with hints about the run time needed for overlaps) files.

**Comment by JifengTang** [comment]
Thank you for the reply.

Where can I find *.report for correction?
I stopped the process after corrected reads were generated. trimming step was not performed yet. 

If the genomesize setting only resulted in more reads in the correction, can I use "smaller genomesize " ( "genomesize=600m corMhapSensitivity=high corMinCoverage=4 corOutCoverage=all correctedErrorRate=0.013 ovlErrorRate=0.15") for trimming and assembly?  will the assembly results be similar to using "smaller genomesize for all steps (correction,trimming and assembly?

Thank you very much.

**Comment by skoren** [comment]
There is only a single report file that contains information on all steps, it's in the folder you provided via the -d option.

The genome size won't be used for anything after correction except the genome size to report assembly statistics so you will get different NG50 values with different genome sizes but that doesn't mean the assembly is any different. You can use the smaller genome size and the explicit request for more coverage, it will be the same as the larger genome size, yes. Option 3 won't change anything from option 1 since the parameter changes will affect correction but you're not regenerating corrected reads. Option 2 is likely to give similar corrected reads though shorter since you're enforcing a minimum coverage. If correction took a very long time then you can stick with option 1 modulo the changes I recommend below for correctedErrorRate/ovlErrorRate. Otherwise you can run option 2 but again fix correctedErrorRate/ovlErrorRate.

Your other parameters will cause issues. A corrected error rate of 0.013 is too low, this is the pairwise error rate in the overlap not the individual read error rate. The default for PacBio data is 0.045 and we recommend higher for Sequel data and Nanopore data. The ovlErrorRate of 0.15 is also quite high and will overwrite your correctedErrorRate setting since it comes later in the command. That's why your trimming was taking so long. Unless you have a specific reason for setting those explicitly, I'd only change correctedErrorRate and leave it at the defaults or at most 0.075.
